# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit scripts/templates/system_metrics.py and then run the following command:
#     hatch run data:generate

# https://clickhouse.com/docs/operations/system-tables/metrics
SystemMetrics = {
    'name': 'system.metrics',
    'query': 'SELECT value, metric FROM system.metrics',
    'columns': [
        {'name': 'value', 'type': 'source'},
        {
            'name': 'metric',
            'type': 'match',
            'source': 'value',
            'items': {
                'ActiveTimersInQueryProfiler': {
                    'name': 'ClickHouseMetrics_ActiveTimersInQueryProfiler',
                    'type': 'gauge',
                },
                'AddressesActive': {'name': 'ClickHouseMetrics_AddressesActive', 'type': 'gauge'},
                'AddressesBanned': {'name': 'ClickHouseMetrics_AddressesBanned', 'type': 'gauge'},
                'AggregatorThreads': {'name': 'ClickHouseMetrics_AggregatorThreads', 'type': 'gauge'},
                'AggregatorThreadsActive': {'name': 'ClickHouseMetrics_AggregatorThreadsActive', 'type': 'gauge'},
                'AggregatorThreadsScheduled': {'name': 'ClickHouseMetrics_AggregatorThreadsScheduled', 'type': 'gauge'},
                'AsyncInsertCacheSize': {'name': 'ClickHouseMetrics_AsyncInsertCacheSize', 'type': 'gauge'},
                'AsynchronousInsertQueueBytes': {
                    'name': 'ClickHouseMetrics_AsynchronousInsertQueueBytes',
                    'type': 'gauge',
                },
                'AsynchronousInsertQueueSize': {
                    'name': 'ClickHouseMetrics_AsynchronousInsertQueueSize',
                    'type': 'gauge',
                },
                'AsynchronousInsertThreads': {'name': 'ClickHouseMetrics_AsynchronousInsertThreads', 'type': 'gauge'},
                'AsynchronousInsertThreadsActive': {
                    'name': 'ClickHouseMetrics_AsynchronousInsertThreadsActive',
                    'type': 'gauge',
                },
                'AsynchronousInsertThreadsScheduled': {
                    'name': 'ClickHouseMetrics_AsynchronousInsertThreadsScheduled',
                    'type': 'gauge',
                },
                'AsynchronousReadWait': {'name': 'ClickHouseMetrics_AsynchronousReadWait', 'type': 'gauge'},
                'AttachedDatabase': {'name': 'ClickHouseMetrics_AttachedDatabase', 'type': 'gauge'},
                'AttachedDictionary': {'name': 'ClickHouseMetrics_AttachedDictionary', 'type': 'gauge'},
                'AttachedReplicatedTable': {'name': 'ClickHouseMetrics_AttachedReplicatedTable', 'type': 'gauge'},
                'AttachedTable': {'name': 'ClickHouseMetrics_AttachedTable', 'type': 'gauge'},
                'AttachedView': {'name': 'ClickHouseMetrics_AttachedView', 'type': 'gauge'},
                'AvroSchemaCacheBytes': {'name': 'ClickHouseMetrics_AvroSchemaCacheBytes', 'type': 'gauge'},
                'AvroSchemaCacheCells': {'name': 'ClickHouseMetrics_AvroSchemaCacheCells', 'type': 'gauge'},
                'AvroSchemaRegistryCacheBytes': {
                    'name': 'ClickHouseMetrics_AvroSchemaRegistryCacheBytes',
                    'type': 'gauge',
                },
                'AvroSchemaRegistryCacheCells': {
                    'name': 'ClickHouseMetrics_AvroSchemaRegistryCacheCells',
                    'type': 'gauge',
                },
                'AzureRequests': {'name': 'ClickHouseMetrics_AzureRequests', 'type': 'gauge'},
                'BackgroundBufferFlushSchedulePoolSize': {
                    'name': 'ClickHouseMetrics_BackgroundBufferFlushSchedulePoolSize',
                    'type': 'gauge',
                },
                'BackgroundBufferFlushSchedulePoolTask': {
                    'name': 'ClickHouseMetrics_BackgroundBufferFlushSchedulePoolTask',
                    'type': 'gauge',
                },
                'BackgroundCommonPoolSize': {'name': 'ClickHouseMetrics_BackgroundCommonPoolSize', 'type': 'gauge'},
                'BackgroundCommonPoolTask': {'name': 'ClickHouseMetrics_BackgroundCommonPoolTask', 'type': 'gauge'},
                'BackgroundDistributedSchedulePoolSize': {
                    'name': 'ClickHouseMetrics_BackgroundDistributedSchedulePoolSize',
                    'type': 'gauge',
                },
                'BackgroundDistributedSchedulePoolTask': {
                    'name': 'ClickHouseMetrics_BackgroundDistributedSchedulePoolTask',
                    'type': 'gauge',
                },
                'BackgroundFetchesPoolSize': {'name': 'ClickHouseMetrics_BackgroundFetchesPoolSize', 'type': 'gauge'},
                'BackgroundFetchesPoolTask': {'name': 'ClickHouseMetrics_BackgroundFetchesPoolTask', 'type': 'gauge'},
                'BackgroundMergesAndMutationsPoolSize': {
                    'name': 'ClickHouseMetrics_BackgroundMergesAndMutationsPoolSize',
                    'type': 'gauge',
                },
                'BackgroundMergesAndMutationsPoolTask': {
                    'name': 'ClickHouseMetrics_BackgroundMergesAndMutationsPoolTask',
                    'type': 'gauge',
                },
                'BackgroundMessageBrokerSchedulePoolSize': {
                    'name': 'ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolSize',
                    'type': 'gauge',
                },
                'BackgroundMessageBrokerSchedulePoolTask': {
                    'name': 'ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolTask',
                    'type': 'gauge',
                },
                'BackgroundMovePoolSize': {'name': 'ClickHouseMetrics_BackgroundMovePoolSize', 'type': 'gauge'},
                'BackgroundMovePoolTask': {'name': 'ClickHouseMetrics_BackgroundMovePoolTask', 'type': 'gauge'},
                'BackgroundSchedulePoolSize': {'name': 'ClickHouseMetrics_BackgroundSchedulePoolSize', 'type': 'gauge'},
                'BackgroundSchedulePoolTask': {'name': 'ClickHouseMetrics_BackgroundSchedulePoolTask', 'type': 'gauge'},
                'BackupsIOThreads': {'name': 'ClickHouseMetrics_BackupsIOThreads', 'type': 'gauge'},
                'BackupsIOThreadsActive': {'name': 'ClickHouseMetrics_BackupsIOThreadsActive', 'type': 'gauge'},
                'BackupsIOThreadsScheduled': {'name': 'ClickHouseMetrics_BackupsIOThreadsScheduled', 'type': 'gauge'},
                'BackupsThreads': {'name': 'ClickHouseMetrics_BackupsThreads', 'type': 'gauge'},
                'BackupsThreadsActive': {'name': 'ClickHouseMetrics_BackupsThreadsActive', 'type': 'gauge'},
                'BackupsThreadsScheduled': {'name': 'ClickHouseMetrics_BackupsThreadsScheduled', 'type': 'gauge'},
                'BrokenDisks': {'name': 'ClickHouseMetrics_BrokenDisks', 'type': 'gauge'},
                'BrokenDistributedBytesToInsert': {
                    'name': 'ClickHouseMetrics_BrokenDistributedBytesToInsert',
                    'type': 'gauge',
                },
                'BrokenDistributedFilesToInsert': {
                    'name': 'ClickHouseMetrics_BrokenDistributedFilesToInsert',
                    'type': 'gauge',
                },
                'BuildVectorSimilarityIndexThreads': {
                    'name': 'ClickHouseMetrics_BuildVectorSimilarityIndexThreads',
                    'type': 'gauge',
                },
                'BuildVectorSimilarityIndexThreadsActive': {
                    'name': 'ClickHouseMetrics_BuildVectorSimilarityIndexThreadsActive',
                    'type': 'gauge',
                },
                'BuildVectorSimilarityIndexThreadsScheduled': {
                    'name': 'ClickHouseMetrics_BuildVectorSimilarityIndexThreadsScheduled',
                    'type': 'gauge',
                },
                'CacheDetachedFileSegments': {'name': 'ClickHouseMetrics_CacheDetachedFileSegments', 'type': 'gauge'},
                'CacheDictionaryThreads': {'name': 'ClickHouseMetrics_CacheDictionaryThreads', 'type': 'gauge'},
                'CacheDictionaryThreadsActive': {
                    'name': 'ClickHouseMetrics_CacheDictionaryThreadsActive',
                    'type': 'gauge',
                },
                'CacheDictionaryThreadsScheduled': {
                    'name': 'ClickHouseMetrics_CacheDictionaryThreadsScheduled',
                    'type': 'gauge',
                },
                'CacheDictionaryUpdateQueueBatches': {
                    'name': 'ClickHouseMetrics_CacheDictionaryUpdateQueueBatches',
                    'type': 'gauge',
                },
                'CacheDictionaryUpdateQueueKeys': {
                    'name': 'ClickHouseMetrics_CacheDictionaryUpdateQueueKeys',
                    'type': 'gauge',
                },
                'CacheFileSegments': {'name': 'ClickHouseMetrics_CacheFileSegments', 'type': 'gauge'},
                'CacheWarmerBytesInProgress': {'name': 'ClickHouseMetrics_CacheWarmerBytesInProgress', 'type': 'gauge'},
                'CompiledExpressionCacheBytes': {
                    'name': 'ClickHouseMetrics_CompiledExpressionCacheBytes',
                    'type': 'gauge',
                },
                'CompiledExpressionCacheCount': {
                    'name': 'ClickHouseMetrics_CompiledExpressionCacheCount',
                    'type': 'gauge',
                },
                'Compressing': {'name': 'ClickHouseMetrics_Compressing', 'type': 'gauge'},
                'CompressionThread': {'name': 'ClickHouseMetrics_CompressionThread', 'type': 'gauge'},
                'CompressionThreadActive': {'name': 'ClickHouseMetrics_CompressionThreadActive', 'type': 'gauge'},
                'CompressionThreadScheduled': {'name': 'ClickHouseMetrics_CompressionThreadScheduled', 'type': 'gauge'},
                'ConcurrencyControlAcquired': {'name': 'ClickHouseMetrics_ConcurrencyControlAcquired', 'type': 'gauge'},
                'ConcurrencyControlAcquiredNonCompeting': {
                    'name': 'ClickHouseMetrics_ConcurrencyControlAcquiredNonCompeting',
                    'type': 'gauge',
                },
                'ConcurrencyControlPreempted': {
                    'name': 'ClickHouseMetrics_ConcurrencyControlPreempted',
                    'type': 'gauge',
                },
                'ConcurrencyControlScheduled': {
                    'name': 'ClickHouseMetrics_ConcurrencyControlScheduled',
                    'type': 'gauge',
                },
                'ConcurrencyControlSoftLimit': {
                    'name': 'ClickHouseMetrics_ConcurrencyControlSoftLimit',
                    'type': 'gauge',
                },
                'ConcurrentHashJoinPoolThreads': {
                    'name': 'ClickHouseMetrics_ConcurrentHashJoinPoolThreads',
                    'type': 'gauge',
                },
                'ConcurrentHashJoinPoolThreadsActive': {
                    'name': 'ClickHouseMetrics_ConcurrentHashJoinPoolThreadsActive',
                    'type': 'gauge',
                },
                'ConcurrentHashJoinPoolThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ConcurrentHashJoinPoolThreadsScheduled',
                    'type': 'gauge',
                },
                'ConcurrentQueryAcquired': {'name': 'ClickHouseMetrics_ConcurrentQueryAcquired', 'type': 'gauge'},
                'ConcurrentQueryScheduled': {'name': 'ClickHouseMetrics_ConcurrentQueryScheduled', 'type': 'gauge'},
                'ContextLockWait': {'name': 'ClickHouseMetrics_ContextLockWait', 'type': 'gauge'},
                'CoordinatedMergesCoordinatorAssignedMerges': {
                    'name': 'ClickHouseMetrics_CoordinatedMergesCoordinatorAssignedMerges',
                    'type': 'gauge',
                },
                'CoordinatedMergesCoordinatorRunningMerges': {
                    'name': 'ClickHouseMetrics_CoordinatedMergesCoordinatorRunningMerges',
                    'type': 'gauge',
                },
                'CoordinatedMergesWorkerAssignedMerges': {
                    'name': 'ClickHouseMetrics_CoordinatedMergesWorkerAssignedMerges',
                    'type': 'gauge',
                },
                'CreatedTimersInQueryProfiler': {
                    'name': 'ClickHouseMetrics_CreatedTimersInQueryProfiler',
                    'type': 'gauge',
                },
                'DDLWorkerThreads': {'name': 'ClickHouseMetrics_DDLWorkerThreads', 'type': 'gauge'},
                'DDLWorkerThreadsActive': {'name': 'ClickHouseMetrics_DDLWorkerThreadsActive', 'type': 'gauge'},
                'DDLWorkerThreadsScheduled': {'name': 'ClickHouseMetrics_DDLWorkerThreadsScheduled', 'type': 'gauge'},
                'DNSAddressesCacheBytes': {'name': 'ClickHouseMetrics_DNSAddressesCacheBytes', 'type': 'gauge'},
                'DNSAddressesCacheSize': {'name': 'ClickHouseMetrics_DNSAddressesCacheSize', 'type': 'gauge'},
                'DNSHostsCacheBytes': {'name': 'ClickHouseMetrics_DNSHostsCacheBytes', 'type': 'gauge'},
                'DNSHostsCacheSize': {'name': 'ClickHouseMetrics_DNSHostsCacheSize', 'type': 'gauge'},
                'DWARFReaderThreads': {'name': 'ClickHouseMetrics_DWARFReaderThreads', 'type': 'gauge'},
                'DWARFReaderThreadsActive': {'name': 'ClickHouseMetrics_DWARFReaderThreadsActive', 'type': 'gauge'},
                'DWARFReaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DWARFReaderThreadsScheduled',
                    'type': 'gauge',
                },
                'DatabaseBackupThreads': {'name': 'ClickHouseMetrics_DatabaseBackupThreads', 'type': 'gauge'},
                'DatabaseBackupThreadsActive': {
                    'name': 'ClickHouseMetrics_DatabaseBackupThreadsActive',
                    'type': 'gauge',
                },
                'DatabaseBackupThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DatabaseBackupThreadsScheduled',
                    'type': 'gauge',
                },
                'DatabaseCatalogThreads': {'name': 'ClickHouseMetrics_DatabaseCatalogThreads', 'type': 'gauge'},
                'DatabaseCatalogThreadsActive': {
                    'name': 'ClickHouseMetrics_DatabaseCatalogThreadsActive',
                    'type': 'gauge',
                },
                'DatabaseCatalogThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DatabaseCatalogThreadsScheduled',
                    'type': 'gauge',
                },
                'DatabaseOnDiskThreads': {'name': 'ClickHouseMetrics_DatabaseOnDiskThreads', 'type': 'gauge'},
                'DatabaseOnDiskThreadsActive': {
                    'name': 'ClickHouseMetrics_DatabaseOnDiskThreadsActive',
                    'type': 'gauge',
                },
                'DatabaseOnDiskThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DatabaseOnDiskThreadsScheduled',
                    'type': 'gauge',
                },
                'DatabaseReplicatedCreateTablesThreads': {
                    'name': 'ClickHouseMetrics_DatabaseReplicatedCreateTablesThreads',
                    'type': 'gauge',
                },
                'DatabaseReplicatedCreateTablesThreadsActive': {
                    'name': 'ClickHouseMetrics_DatabaseReplicatedCreateTablesThreadsActive',
                    'type': 'gauge',
                },
                'DatabaseReplicatedCreateTablesThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DatabaseReplicatedCreateTablesThreadsScheduled',
                    'type': 'gauge',
                },
                'Decompressing': {'name': 'ClickHouseMetrics_Decompressing', 'type': 'gauge'},
                'DelayedInserts': {'name': 'ClickHouseMetrics_DelayedInserts', 'type': 'gauge'},
                'DestroyAggregatesThreads': {'name': 'ClickHouseMetrics_DestroyAggregatesThreads', 'type': 'gauge'},
                'DestroyAggregatesThreadsActive': {
                    'name': 'ClickHouseMetrics_DestroyAggregatesThreadsActive',
                    'type': 'gauge',
                },
                'DestroyAggregatesThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DestroyAggregatesThreadsScheduled',
                    'type': 'gauge',
                },
                'DictCacheRequests': {'name': 'ClickHouseMetrics_DictCacheRequests', 'type': 'gauge'},
                'DiskConnectionsStored': {'name': 'ClickHouseMetrics_DiskConnectionsStored', 'type': 'gauge'},
                'DiskConnectionsTotal': {'name': 'ClickHouseMetrics_DiskConnectionsTotal', 'type': 'gauge'},
                'DiskObjectStorageAsyncThreads': {
                    'name': 'ClickHouseMetrics_DiskObjectStorageAsyncThreads',
                    'type': 'gauge',
                },
                'DiskObjectStorageAsyncThreadsActive': {
                    'name': 'ClickHouseMetrics_DiskObjectStorageAsyncThreadsActive',
                    'type': 'gauge',
                },
                'DiskPlainRewritableAzureDirectoryMapSize': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableAzureDirectoryMapSize',
                    'type': 'gauge',
                },
                'DiskPlainRewritableAzureFileCount': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableAzureFileCount',
                    'type': 'gauge',
                },
                'DiskPlainRewritableAzureUniqueFileNamesCount': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableAzureUniqueFileNamesCount',
                    'type': 'gauge',
                },
                'DiskPlainRewritableLocalDirectoryMapSize': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableLocalDirectoryMapSize',
                    'type': 'gauge',
                },
                'DiskPlainRewritableLocalFileCount': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableLocalFileCount',
                    'type': 'gauge',
                },
                'DiskPlainRewritableLocalUniqueFileNamesCount': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableLocalUniqueFileNamesCount',
                    'type': 'gauge',
                },
                'DiskPlainRewritableS3DirectoryMapSize': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableS3DirectoryMapSize',
                    'type': 'gauge',
                },
                'DiskPlainRewritableS3FileCount': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableS3FileCount',
                    'type': 'gauge',
                },
                'DiskPlainRewritableS3UniqueFileNamesCount': {
                    'name': 'ClickHouseMetrics_DiskPlainRewritableS3UniqueFileNamesCount',
                    'type': 'gauge',
                },
                'DiskS3NoSuchKeyErrors': {'name': 'ClickHouseMetrics_DiskS3NoSuchKeyErrors', 'type': 'gauge'},
                'DiskSpaceReservedForMerge': {'name': 'ClickHouseMetrics_DiskSpaceReservedForMerge', 'type': 'gauge'},
                'DistrCacheAllocatedConnections': {
                    'name': 'ClickHouseMetrics_DistrCacheAllocatedConnections',
                    'type': 'gauge',
                },
                'DistrCacheBorrowedConnections': {
                    'name': 'ClickHouseMetrics_DistrCacheBorrowedConnections',
                    'type': 'gauge',
                },
                'DistrCacheOpenedConnections': {
                    'name': 'ClickHouseMetrics_DistrCacheOpenedConnections',
                    'type': 'gauge',
                },
                'DistrCacheReadRequests': {'name': 'ClickHouseMetrics_DistrCacheReadRequests', 'type': 'gauge'},
                'DistrCacheRegisteredServers': {
                    'name': 'ClickHouseMetrics_DistrCacheRegisteredServers',
                    'type': 'gauge',
                },
                'DistrCacheRegisteredServersCurrentAZ': {
                    'name': 'ClickHouseMetrics_DistrCacheRegisteredServersCurrentAZ',
                    'type': 'gauge',
                },
                'DistrCacheServerConnections': {
                    'name': 'ClickHouseMetrics_DistrCacheServerConnections',
                    'type': 'gauge',
                },
                'DistrCacheServerRegistryConnections': {
                    'name': 'ClickHouseMetrics_DistrCacheServerRegistryConnections',
                    'type': 'gauge',
                },
                'DistrCacheServerS3CachedClients': {
                    'name': 'ClickHouseMetrics_DistrCacheServerS3CachedClients',
                    'type': 'gauge',
                },
                'DistrCacheUsedConnections': {'name': 'ClickHouseMetrics_DistrCacheUsedConnections', 'type': 'gauge'},
                'DistrCacheWriteRequests': {'name': 'ClickHouseMetrics_DistrCacheWriteRequests', 'type': 'gauge'},
                'DistributedBytesToInsert': {'name': 'ClickHouseMetrics_DistributedBytesToInsert', 'type': 'gauge'},
                'DistributedFilesToInsert': {'name': 'ClickHouseMetrics_DistributedFilesToInsert', 'type': 'gauge'},
                'DistributedInsertThreads': {'name': 'ClickHouseMetrics_DistributedInsertThreads', 'type': 'gauge'},
                'DistributedInsertThreadsActive': {
                    'name': 'ClickHouseMetrics_DistributedInsertThreadsActive',
                    'type': 'gauge',
                },
                'DistributedInsertThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DistributedInsertThreadsScheduled',
                    'type': 'gauge',
                },
                'DistributedSend': {'name': 'ClickHouseMetrics_DistributedSend', 'type': 'gauge'},
                'DropDistributedCacheThreads': {
                    'name': 'ClickHouseMetrics_DropDistributedCacheThreads',
                    'type': 'gauge',
                },
                'DropDistributedCacheThreadsActive': {
                    'name': 'ClickHouseMetrics_DropDistributedCacheThreadsActive',
                    'type': 'gauge',
                },
                'DropDistributedCacheThreadsScheduled': {
                    'name': 'ClickHouseMetrics_DropDistributedCacheThreadsScheduled',
                    'type': 'gauge',
                },
                'EphemeralNode': {'name': 'ClickHouseMetrics_EphemeralNode', 'type': 'gauge'},
                'FilesystemCacheDelayedCleanupElements': {
                    'name': 'ClickHouseMetrics_FilesystemCacheDelayedCleanupElements',
                    'type': 'gauge',
                },
                'FilesystemCacheDownloadQueueElements': {
                    'name': 'ClickHouseMetrics_FilesystemCacheDownloadQueueElements',
                    'type': 'gauge',
                },
                'FilesystemCacheElements': {'name': 'ClickHouseMetrics_FilesystemCacheElements', 'type': 'gauge'},
                'FilesystemCacheHoldFileSegments': {
                    'name': 'ClickHouseMetrics_FilesystemCacheHoldFileSegments',
                    'type': 'gauge',
                },
                'FilesystemCacheKeys': {'name': 'ClickHouseMetrics_FilesystemCacheKeys', 'type': 'gauge'},
                'FilesystemCacheReadBuffers': {'name': 'ClickHouseMetrics_FilesystemCacheReadBuffers', 'type': 'gauge'},
                'FilesystemCacheSize': {'name': 'ClickHouseMetrics_FilesystemCacheSize', 'type': 'gauge'},
                'FilesystemCacheSizeLimit': {'name': 'ClickHouseMetrics_FilesystemCacheSizeLimit', 'type': 'gauge'},
                'FilteringMarksWithPrimaryKey': {
                    'name': 'ClickHouseMetrics_FilteringMarksWithPrimaryKey',
                    'type': 'gauge',
                },
                'FilteringMarksWithSecondaryKeys': {
                    'name': 'ClickHouseMetrics_FilteringMarksWithSecondaryKeys',
                    'type': 'gauge',
                },
                'FormatParsingThreads': {'name': 'ClickHouseMetrics_FormatParsingThreads', 'type': 'gauge'},
                'FormatParsingThreadsActive': {'name': 'ClickHouseMetrics_FormatParsingThreadsActive', 'type': 'gauge'},
                'FormatParsingThreadsScheduled': {
                    'name': 'ClickHouseMetrics_FormatParsingThreadsScheduled',
                    'type': 'gauge',
                },
                'GlobalThread': {'name': 'ClickHouseMetrics_GlobalThread', 'type': 'gauge'},
                'GlobalThreadActive': {'name': 'ClickHouseMetrics_GlobalThreadActive', 'type': 'gauge'},
                'GlobalThreadScheduled': {'name': 'ClickHouseMetrics_GlobalThreadScheduled', 'type': 'gauge'},
                'HTTPConnection': {'name': 'ClickHouseMetrics_HTTPConnection', 'type': 'gauge'},
                'HTTPConnectionsStored': {'name': 'ClickHouseMetrics_HTTPConnectionsStored', 'type': 'gauge'},
                'HTTPConnectionsTotal': {'name': 'ClickHouseMetrics_HTTPConnectionsTotal', 'type': 'gauge'},
                'HashedDictionaryThreads': {'name': 'ClickHouseMetrics_HashedDictionaryThreads', 'type': 'gauge'},
                'HashedDictionaryThreadsActive': {
                    'name': 'ClickHouseMetrics_HashedDictionaryThreadsActive',
                    'type': 'gauge',
                },
                'HashedDictionaryThreadsScheduled': {
                    'name': 'ClickHouseMetrics_HashedDictionaryThreadsScheduled',
                    'type': 'gauge',
                },
                'HiveFilesCacheBytes': {'name': 'ClickHouseMetrics_HiveFilesCacheBytes', 'type': 'gauge'},
                'HiveFilesCacheFiles': {'name': 'ClickHouseMetrics_HiveFilesCacheFiles', 'type': 'gauge'},
                'HiveMetadataFilesCacheBytes': {
                    'name': 'ClickHouseMetrics_HiveMetadataFilesCacheBytes',
                    'type': 'gauge',
                },
                'HiveMetadataFilesCacheFiles': {
                    'name': 'ClickHouseMetrics_HiveMetadataFilesCacheFiles',
                    'type': 'gauge',
                },
                'IDiskCopierThreads': {'name': 'ClickHouseMetrics_IDiskCopierThreads', 'type': 'gauge'},
                'IDiskCopierThreadsActive': {'name': 'ClickHouseMetrics_IDiskCopierThreadsActive', 'type': 'gauge'},
                'IDiskCopierThreadsScheduled': {
                    'name': 'ClickHouseMetrics_IDiskCopierThreadsScheduled',
                    'type': 'gauge',
                },
                'IOPrefetchThreads': {'name': 'ClickHouseMetrics_IOPrefetchThreads', 'type': 'gauge'},
                'IOPrefetchThreadsActive': {'name': 'ClickHouseMetrics_IOPrefetchThreadsActive', 'type': 'gauge'},
                'IOPrefetchThreadsScheduled': {'name': 'ClickHouseMetrics_IOPrefetchThreadsScheduled', 'type': 'gauge'},
                'IOThreads': {'name': 'ClickHouseMetrics_IOThreads', 'type': 'gauge'},
                'IOThreadsActive': {'name': 'ClickHouseMetrics_IOThreadsActive', 'type': 'gauge'},
                'IOThreadsScheduled': {'name': 'ClickHouseMetrics_IOThreadsScheduled', 'type': 'gauge'},
                'IOUringInFlightEvents': {'name': 'ClickHouseMetrics_IOUringInFlightEvents', 'type': 'gauge'},
                'IOUringPendingEvents': {'name': 'ClickHouseMetrics_IOUringPendingEvents', 'type': 'gauge'},
                'IOWriterThreads': {'name': 'ClickHouseMetrics_IOWriterThreads', 'type': 'gauge'},
                'IOWriterThreadsActive': {'name': 'ClickHouseMetrics_IOWriterThreadsActive', 'type': 'gauge'},
                'IOWriterThreadsScheduled': {'name': 'ClickHouseMetrics_IOWriterThreadsScheduled', 'type': 'gauge'},
                'IcebergCatalogThreads': {'name': 'ClickHouseMetrics_IcebergCatalogThreads', 'type': 'gauge'},
                'IcebergCatalogThreadsActive': {
                    'name': 'ClickHouseMetrics_IcebergCatalogThreadsActive',
                    'type': 'gauge',
                },
                'IcebergCatalogThreadsScheduled': {
                    'name': 'ClickHouseMetrics_IcebergCatalogThreadsScheduled',
                    'type': 'gauge',
                },
                'IcebergMetadataFilesCacheBytes': {
                    'name': 'ClickHouseMetrics_IcebergMetadataFilesCacheBytes',
                    'type': 'gauge',
                },
                'IcebergMetadataFilesCacheFiles': {
                    'name': 'ClickHouseMetrics_IcebergMetadataFilesCacheFiles',
                    'type': 'gauge',
                },
                'IndexMarkCacheBytes': {'name': 'ClickHouseMetrics_IndexMarkCacheBytes', 'type': 'gauge'},
                'IndexMarkCacheFiles': {'name': 'ClickHouseMetrics_IndexMarkCacheFiles', 'type': 'gauge'},
                'IndexUncompressedCacheBytes': {
                    'name': 'ClickHouseMetrics_IndexUncompressedCacheBytes',
                    'type': 'gauge',
                },
                'IndexUncompressedCacheCells': {
                    'name': 'ClickHouseMetrics_IndexUncompressedCacheCells',
                    'type': 'gauge',
                },
                'InterserverConnection': {'name': 'ClickHouseMetrics_InterserverConnection', 'type': 'gauge'},
                'IsServerShuttingDown': {'name': 'ClickHouseMetrics_IsServerShuttingDown', 'type': 'gauge'},
                'KafkaAssignedPartitions': {'name': 'ClickHouseMetrics_KafkaAssignedPartitions', 'type': 'gauge'},
                'KafkaBackgroundReads': {'name': 'ClickHouseMetrics_KafkaBackgroundReads', 'type': 'gauge'},
                'KafkaConsumers': {'name': 'ClickHouseMetrics_KafkaConsumers', 'type': 'gauge'},
                'KafkaConsumersInUse': {'name': 'ClickHouseMetrics_KafkaConsumersInUse', 'type': 'gauge'},
                'KafkaConsumersWithAssignment': {
                    'name': 'ClickHouseMetrics_KafkaConsumersWithAssignment',
                    'type': 'gauge',
                },
                'KafkaLibrdkafkaThreads': {'name': 'ClickHouseMetrics_KafkaLibrdkafkaThreads', 'type': 'gauge'},
                'KafkaProducers': {'name': 'ClickHouseMetrics_KafkaProducers', 'type': 'gauge'},
                'KafkaWrites': {'name': 'ClickHouseMetrics_KafkaWrites', 'type': 'gauge'},
                'KeeperAliveConnections': {'name': 'ClickHouseMetrics_KeeperAliveConnections', 'type': 'gauge'},
                'KeeperOutstandingRequests': {'name': 'ClickHouseMetrics_KeeperOutstandingRequests', 'type': 'gauge'},
                'LicenseRemainingSeconds': {'name': 'ClickHouseMetrics_LicenseRemainingSeconds', 'type': 'gauge'},
                'LocalThread': {'name': 'ClickHouseMetrics_LocalThread', 'type': 'gauge'},
                'LocalThreadActive': {'name': 'ClickHouseMetrics_LocalThreadActive', 'type': 'gauge'},
                'LocalThreadScheduled': {'name': 'ClickHouseMetrics_LocalThreadScheduled', 'type': 'gauge'},
                'MMapCacheCells': {'name': 'ClickHouseMetrics_MMapCacheCells', 'type': 'gauge'},
                'MMappedFileBytes': {'name': 'ClickHouseMetrics_MMappedFileBytes', 'type': 'gauge'},
                'MMappedFiles': {'name': 'ClickHouseMetrics_MMappedFiles', 'type': 'gauge'},
                'MarkCacheBytes': {'name': 'ClickHouseMetrics_MarkCacheBytes', 'type': 'gauge'},
                'MarkCacheFiles': {'name': 'ClickHouseMetrics_MarkCacheFiles', 'type': 'gauge'},
                'MarksLoaderThreads': {'name': 'ClickHouseMetrics_MarksLoaderThreads', 'type': 'gauge'},
                'MarksLoaderThreadsActive': {'name': 'ClickHouseMetrics_MarksLoaderThreadsActive', 'type': 'gauge'},
                'MarksLoaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MarksLoaderThreadsScheduled',
                    'type': 'gauge',
                },
                'MaxDDLEntryID': {'name': 'ClickHouseMetrics_MaxDDLEntryID', 'type': 'gauge'},
                'MaxPushedDDLEntryID': {'name': 'ClickHouseMetrics_MaxPushedDDLEntryID', 'type': 'gauge'},
                'MemoryTracking': {'name': 'ClickHouseMetrics_MemoryTracking', 'type': 'gauge'},
                'MemoryTrackingUncorrected': {'name': 'ClickHouseMetrics_MemoryTrackingUncorrected', 'type': 'gauge'},
                'Merge': {'name': 'ClickHouseMetrics_Merge', 'type': 'gauge'},
                'MergeJoinBlocksCacheBytes': {'name': 'ClickHouseMetrics_MergeJoinBlocksCacheBytes', 'type': 'gauge'},
                'MergeJoinBlocksCacheCount': {'name': 'ClickHouseMetrics_MergeJoinBlocksCacheCount', 'type': 'gauge'},
                'MergeParts': {'name': 'ClickHouseMetrics_MergeParts', 'type': 'gauge'},
                'MergeTreeAllRangesAnnouncementsSent': {
                    'name': 'ClickHouseMetrics_MergeTreeAllRangesAnnouncementsSent',
                    'type': 'gauge',
                },
                'MergeTreeBackgroundExecutorThreads': {
                    'name': 'ClickHouseMetrics_MergeTreeBackgroundExecutorThreads',
                    'type': 'gauge',
                },
                'MergeTreeBackgroundExecutorThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreeBackgroundExecutorThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreeBackgroundExecutorThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreeBackgroundExecutorThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreeDataSelectExecutorThreads': {
                    'name': 'ClickHouseMetrics_MergeTreeDataSelectExecutorThreads',
                    'type': 'gauge',
                },
                'MergeTreeDataSelectExecutorThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreeDataSelectExecutorThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreeDataSelectExecutorThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreeDataSelectExecutorThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreeFetchPartitionThreads': {
                    'name': 'ClickHouseMetrics_MergeTreeFetchPartitionThreads',
                    'type': 'gauge',
                },
                'MergeTreeFetchPartitionThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreeFetchPartitionThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreeFetchPartitionThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreeFetchPartitionThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreeOutdatedPartsLoaderThreads': {
                    'name': 'ClickHouseMetrics_MergeTreeOutdatedPartsLoaderThreads',
                    'type': 'gauge',
                },
                'MergeTreeOutdatedPartsLoaderThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreeOutdatedPartsLoaderThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreeOutdatedPartsLoaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreeOutdatedPartsLoaderThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreePartsCleanerThreads': {
                    'name': 'ClickHouseMetrics_MergeTreePartsCleanerThreads',
                    'type': 'gauge',
                },
                'MergeTreePartsCleanerThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreePartsCleanerThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreePartsCleanerThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreePartsCleanerThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreePartsLoaderThreads': {
                    'name': 'ClickHouseMetrics_MergeTreePartsLoaderThreads',
                    'type': 'gauge',
                },
                'MergeTreePartsLoaderThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreePartsLoaderThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreePartsLoaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreePartsLoaderThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreeReadTaskRequestsSent': {
                    'name': 'ClickHouseMetrics_MergeTreeReadTaskRequestsSent',
                    'type': 'gauge',
                },
                'MergeTreeSubcolumnsReaderThreads': {
                    'name': 'ClickHouseMetrics_MergeTreeSubcolumnsReaderThreads',
                    'type': 'gauge',
                },
                'MergeTreeSubcolumnsReaderThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreeSubcolumnsReaderThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreeSubcolumnsReaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreeSubcolumnsReaderThreadsScheduled',
                    'type': 'gauge',
                },
                'MergeTreeUnexpectedPartsLoaderThreads': {
                    'name': 'ClickHouseMetrics_MergeTreeUnexpectedPartsLoaderThreads',
                    'type': 'gauge',
                },
                'MergeTreeUnexpectedPartsLoaderThreadsActive': {
                    'name': 'ClickHouseMetrics_MergeTreeUnexpectedPartsLoaderThreadsActive',
                    'type': 'gauge',
                },
                'MergeTreeUnexpectedPartsLoaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_MergeTreeUnexpectedPartsLoaderThreadsScheduled',
                    'type': 'gauge',
                },
                'MergesMutationsMemoryTracking': {
                    'name': 'ClickHouseMetrics_MergesMutationsMemoryTracking',
                    'type': 'gauge',
                },
                'MetadataFromKeeperCacheObjects': {
                    'name': 'ClickHouseMetrics_MetadataFromKeeperCacheObjects',
                    'type': 'gauge',
                },
                'Move': {'name': 'ClickHouseMetrics_Move', 'type': 'gauge'},
                'MySQLConnection': {'name': 'ClickHouseMetrics_MySQLConnection', 'type': 'gauge'},
                'NetworkReceive': {'name': 'ClickHouseMetrics_NetworkReceive', 'type': 'gauge'},
                'NetworkSend': {'name': 'ClickHouseMetrics_NetworkSend', 'type': 'gauge'},
                'NonAbortedMergeFailures': {'name': 'ClickHouseMetrics_NonAbortedMergeFailures', 'type': 'gauge'},
                'ObjectStorageAzureThreads': {'name': 'ClickHouseMetrics_ObjectStorageAzureThreads', 'type': 'gauge'},
                'ObjectStorageAzureThreadsActive': {
                    'name': 'ClickHouseMetrics_ObjectStorageAzureThreadsActive',
                    'type': 'gauge',
                },
                'ObjectStorageAzureThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ObjectStorageAzureThreadsScheduled',
                    'type': 'gauge',
                },
                'ObjectStorageQueueRegisteredServers': {
                    'name': 'ClickHouseMetrics_ObjectStorageQueueRegisteredServers',
                    'type': 'gauge',
                },
                'ObjectStorageQueueShutdownThreads': {
                    'name': 'ClickHouseMetrics_ObjectStorageQueueShutdownThreads',
                    'type': 'gauge',
                },
                'ObjectStorageQueueShutdownThreadsActive': {
                    'name': 'ClickHouseMetrics_ObjectStorageQueueShutdownThreadsActive',
                    'type': 'gauge',
                },
                'ObjectStorageQueueShutdownThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ObjectStorageQueueShutdownThreadsScheduled',
                    'type': 'gauge',
                },
                'ObjectStorageS3Threads': {'name': 'ClickHouseMetrics_ObjectStorageS3Threads', 'type': 'gauge'},
                'ObjectStorageS3ThreadsActive': {
                    'name': 'ClickHouseMetrics_ObjectStorageS3ThreadsActive',
                    'type': 'gauge',
                },
                'ObjectStorageS3ThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ObjectStorageS3ThreadsScheduled',
                    'type': 'gauge',
                },
                'OpenFileForRead': {'name': 'ClickHouseMetrics_OpenFileForRead', 'type': 'gauge'},
                'OpenFileForWrite': {'name': 'ClickHouseMetrics_OpenFileForWrite', 'type': 'gauge'},
                'OutdatedPartsLoadingThreads': {
                    'name': 'ClickHouseMetrics_OutdatedPartsLoadingThreads',
                    'type': 'gauge',
                },
                'OutdatedPartsLoadingThreadsActive': {
                    'name': 'ClickHouseMetrics_OutdatedPartsLoadingThreadsActive',
                    'type': 'gauge',
                },
                'OutdatedPartsLoadingThreadsScheduled': {
                    'name': 'ClickHouseMetrics_OutdatedPartsLoadingThreadsScheduled',
                    'type': 'gauge',
                },
                'PageCacheBytes': {'name': 'ClickHouseMetrics_PageCacheBytes', 'type': 'gauge'},
                'PageCacheCells': {'name': 'ClickHouseMetrics_PageCacheCells', 'type': 'gauge'},
                'ParallelCompressedWriteBufferThreads': {
                    'name': 'ClickHouseMetrics_ParallelCompressedWriteBufferThreads',
                    'type': 'gauge',
                },
                'ParallelCompressedWriteBufferWait': {
                    'name': 'ClickHouseMetrics_ParallelCompressedWriteBufferWait',
                    'type': 'gauge',
                },
                'ParallelFormattingOutputFormatThreads': {
                    'name': 'ClickHouseMetrics_ParallelFormattingOutputFormatThreads',
                    'type': 'gauge',
                },
                'ParallelFormattingOutputFormatThreadsActive': {
                    'name': 'ClickHouseMetrics_ParallelFormattingOutputFormatThreadsActive',
                    'type': 'gauge',
                },
                'ParallelFormattingOutputFormatThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ParallelFormattingOutputFormatThreadsScheduled',
                    'type': 'gauge',
                },
                'ParallelParsingInputFormatThreads': {
                    'name': 'ClickHouseMetrics_ParallelParsingInputFormatThreads',
                    'type': 'gauge',
                },
                'ParallelParsingInputFormatThreadsActive': {
                    'name': 'ClickHouseMetrics_ParallelParsingInputFormatThreadsActive',
                    'type': 'gauge',
                },
                'ParallelParsingInputFormatThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ParallelParsingInputFormatThreadsScheduled',
                    'type': 'gauge',
                },
                'ParallelWithQueryActiveThreads': {
                    'name': 'ClickHouseMetrics_ParallelWithQueryActiveThreads',
                    'type': 'gauge',
                },
                'ParallelWithQueryScheduledThreads': {
                    'name': 'ClickHouseMetrics_ParallelWithQueryScheduledThreads',
                    'type': 'gauge',
                },
                'ParallelWithQueryThreads': {'name': 'ClickHouseMetrics_ParallelWithQueryThreads', 'type': 'gauge'},
                'ParquetDecoderIOThreads': {'name': 'ClickHouseMetrics_ParquetDecoderIOThreads', 'type': 'gauge'},
                'ParquetDecoderIOThreadsActive': {
                    'name': 'ClickHouseMetrics_ParquetDecoderIOThreadsActive',
                    'type': 'gauge',
                },
                'ParquetDecoderIOThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ParquetDecoderIOThreadsScheduled',
                    'type': 'gauge',
                },
                'ParquetDecoderThreads': {'name': 'ClickHouseMetrics_ParquetDecoderThreads', 'type': 'gauge'},
                'ParquetDecoderThreadsActive': {
                    'name': 'ClickHouseMetrics_ParquetDecoderThreadsActive',
                    'type': 'gauge',
                },
                'ParquetDecoderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ParquetDecoderThreadsScheduled',
                    'type': 'gauge',
                },
                'ParquetEncoderThreads': {'name': 'ClickHouseMetrics_ParquetEncoderThreads', 'type': 'gauge'},
                'ParquetEncoderThreadsActive': {
                    'name': 'ClickHouseMetrics_ParquetEncoderThreadsActive',
                    'type': 'gauge',
                },
                'ParquetEncoderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ParquetEncoderThreadsScheduled',
                    'type': 'gauge',
                },
                'PartMutation': {'name': 'ClickHouseMetrics_PartMutation', 'type': 'gauge'},
                'PartsActive': {'name': 'ClickHouseMetrics_PartsActive', 'type': 'gauge'},
                'PartsCommitted': {'name': 'ClickHouseMetrics_PartsCommitted', 'type': 'gauge'},
                'PartsCompact': {'name': 'ClickHouseMetrics_PartsCompact', 'type': 'gauge'},
                'PartsDeleteOnDestroy': {'name': 'ClickHouseMetrics_PartsDeleteOnDestroy', 'type': 'gauge'},
                'PartsDeleting': {'name': 'ClickHouseMetrics_PartsDeleting', 'type': 'gauge'},
                'PartsOutdated': {'name': 'ClickHouseMetrics_PartsOutdated', 'type': 'gauge'},
                'PartsPreActive': {'name': 'ClickHouseMetrics_PartsPreActive', 'type': 'gauge'},
                'PartsPreCommitted': {'name': 'ClickHouseMetrics_PartsPreCommitted', 'type': 'gauge'},
                'PartsTemporary': {'name': 'ClickHouseMetrics_PartsTemporary', 'type': 'gauge'},
                'PartsWide': {'name': 'ClickHouseMetrics_PartsWide', 'type': 'gauge'},
                'PendingAsyncInsert': {'name': 'ClickHouseMetrics_PendingAsyncInsert', 'type': 'gauge'},
                'PolygonDictionaryThreads': {'name': 'ClickHouseMetrics_PolygonDictionaryThreads', 'type': 'gauge'},
                'PolygonDictionaryThreadsActive': {
                    'name': 'ClickHouseMetrics_PolygonDictionaryThreadsActive',
                    'type': 'gauge',
                },
                'PolygonDictionaryThreadsScheduled': {
                    'name': 'ClickHouseMetrics_PolygonDictionaryThreadsScheduled',
                    'type': 'gauge',
                },
                'PostgreSQLConnection': {'name': 'ClickHouseMetrics_PostgreSQLConnection', 'type': 'gauge'},
                'PrimaryIndexCacheBytes': {'name': 'ClickHouseMetrics_PrimaryIndexCacheBytes', 'type': 'gauge'},
                'PrimaryIndexCacheFiles': {'name': 'ClickHouseMetrics_PrimaryIndexCacheFiles', 'type': 'gauge'},
                'Query': {'name': 'ClickHouseMetrics_Query', 'type': 'gauge'},
                'QueryCacheBytes': {'name': 'ClickHouseMetrics_QueryCacheBytes', 'type': 'gauge'},
                'QueryCacheEntries': {'name': 'ClickHouseMetrics_QueryCacheEntries', 'type': 'gauge'},
                'QueryConditionCacheBytes': {'name': 'ClickHouseMetrics_QueryConditionCacheBytes', 'type': 'gauge'},
                'QueryConditionCacheEntries': {'name': 'ClickHouseMetrics_QueryConditionCacheEntries', 'type': 'gauge'},
                'QueryPipelineExecutorThreads': {
                    'name': 'ClickHouseMetrics_QueryPipelineExecutorThreads',
                    'type': 'gauge',
                },
                'QueryPipelineExecutorThreadsActive': {
                    'name': 'ClickHouseMetrics_QueryPipelineExecutorThreadsActive',
                    'type': 'gauge',
                },
                'QueryPipelineExecutorThreadsScheduled': {
                    'name': 'ClickHouseMetrics_QueryPipelineExecutorThreadsScheduled',
                    'type': 'gauge',
                },
                'QueryPreempted': {'name': 'ClickHouseMetrics_QueryPreempted', 'type': 'gauge'},
                'QueryThread': {'name': 'ClickHouseMetrics_QueryThread', 'type': 'gauge'},
                'RWLockActiveReaders': {'name': 'ClickHouseMetrics_RWLockActiveReaders', 'type': 'gauge'},
                'RWLockActiveWriters': {'name': 'ClickHouseMetrics_RWLockActiveWriters', 'type': 'gauge'},
                'RWLockWaitingReaders': {'name': 'ClickHouseMetrics_RWLockWaitingReaders', 'type': 'gauge'},
                'RWLockWaitingWriters': {'name': 'ClickHouseMetrics_RWLockWaitingWriters', 'type': 'gauge'},
                'Read': {'name': 'ClickHouseMetrics_Read', 'type': 'gauge'},
                'ReadTaskRequestsSent': {'name': 'ClickHouseMetrics_ReadTaskRequestsSent', 'type': 'gauge'},
                'ReadonlyDisks': {'name': 'ClickHouseMetrics_ReadonlyDisks', 'type': 'gauge'},
                'ReadonlyReplica': {'name': 'ClickHouseMetrics_ReadonlyReplica', 'type': 'gauge'},
                'RefreshableViews': {'name': 'ClickHouseMetrics_RefreshableViews', 'type': 'gauge'},
                'RefreshingViews': {'name': 'ClickHouseMetrics_RefreshingViews', 'type': 'gauge'},
                'RemoteRead': {'name': 'ClickHouseMetrics_RemoteRead', 'type': 'gauge'},
                'ReplicatedChecks': {'name': 'ClickHouseMetrics_ReplicatedChecks', 'type': 'gauge'},
                'ReplicatedFetch': {'name': 'ClickHouseMetrics_ReplicatedFetch', 'type': 'gauge'},
                'ReplicatedSend': {'name': 'ClickHouseMetrics_ReplicatedSend', 'type': 'gauge'},
                'RestartReplicaThreads': {'name': 'ClickHouseMetrics_RestartReplicaThreads', 'type': 'gauge'},
                'RestartReplicaThreadsActive': {
                    'name': 'ClickHouseMetrics_RestartReplicaThreadsActive',
                    'type': 'gauge',
                },
                'RestartReplicaThreadsScheduled': {
                    'name': 'ClickHouseMetrics_RestartReplicaThreadsScheduled',
                    'type': 'gauge',
                },
                'RestoreThreads': {'name': 'ClickHouseMetrics_RestoreThreads', 'type': 'gauge'},
                'RestoreThreadsActive': {'name': 'ClickHouseMetrics_RestoreThreadsActive', 'type': 'gauge'},
                'RestoreThreadsScheduled': {'name': 'ClickHouseMetrics_RestoreThreadsScheduled', 'type': 'gauge'},
                'Revision': {'name': 'ClickHouseMetrics_Revision', 'type': 'gauge'},
                'S3Requests': {'name': 'ClickHouseMetrics_S3Requests', 'type': 'gauge'},
                'SchedulerIOReadScheduled': {'name': 'ClickHouseMetrics_SchedulerIOReadScheduled', 'type': 'gauge'},
                'SchedulerIOWriteScheduled': {'name': 'ClickHouseMetrics_SchedulerIOWriteScheduled', 'type': 'gauge'},
                'SendExternalTables': {'name': 'ClickHouseMetrics_SendExternalTables', 'type': 'gauge'},
                'SendScalars': {'name': 'ClickHouseMetrics_SendScalars', 'type': 'gauge'},
                'SharedCatalogDropDetachLocalTablesErrors': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropDetachLocalTablesErrors',
                    'type': 'gauge',
                },
                'SharedCatalogDropLocalThreads': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropLocalThreads',
                    'type': 'gauge',
                },
                'SharedCatalogDropLocalThreadsActive': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropLocalThreadsActive',
                    'type': 'gauge',
                },
                'SharedCatalogDropLocalThreadsScheduled': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropLocalThreadsScheduled',
                    'type': 'gauge',
                },
                'SharedCatalogDropZooKeeperThreads': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropZooKeeperThreads',
                    'type': 'gauge',
                },
                'SharedCatalogDropZooKeeperThreadsActive': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropZooKeeperThreadsActive',
                    'type': 'gauge',
                },
                'SharedCatalogDropZooKeeperThreadsScheduled': {
                    'name': 'ClickHouseMetrics_SharedCatalogDropZooKeeperThreadsScheduled',
                    'type': 'gauge',
                },
                'SharedCatalogNumberOfObjectsInState': {
                    'name': 'ClickHouseMetrics_SharedCatalogNumberOfObjectsInState',
                    'type': 'gauge',
                },
                'SharedCatalogStateApplicationThreads': {
                    'name': 'ClickHouseMetrics_SharedCatalogStateApplicationThreads',
                    'type': 'gauge',
                },
                'SharedCatalogStateApplicationThreadsActive': {
                    'name': 'ClickHouseMetrics_SharedCatalogStateApplicationThreadsActive',
                    'type': 'gauge',
                },
                'SharedCatalogStateApplicationThreadsScheduled': {
                    'name': 'ClickHouseMetrics_SharedCatalogStateApplicationThreadsScheduled',
                    'type': 'gauge',
                },
                'SharedDatabaseCatalogTablesInLocalDropDetachQueue': {
                    'name': 'ClickHouseMetrics_SharedDatabaseCatalogTablesInLocalDropDetachQueue',
                    'type': 'gauge',
                },
                'SharedMergeTreeAssignedCurrentParts': {
                    'name': 'ClickHouseMetrics_SharedMergeTreeAssignedCurrentParts',
                    'type': 'gauge',
                },
                'SharedMergeTreeCondemnedPartsInKeeper': {
                    'name': 'ClickHouseMetrics_SharedMergeTreeCondemnedPartsInKeeper',
                    'type': 'gauge',
                },
                'SharedMergeTreeFetch': {'name': 'ClickHouseMetrics_SharedMergeTreeFetch', 'type': 'gauge'},
                'SharedMergeTreeOutdatedPartsInKeeper': {
                    'name': 'ClickHouseMetrics_SharedMergeTreeOutdatedPartsInKeeper',
                    'type': 'gauge',
                },
                'SharedMergeTreeThreads': {'name': 'ClickHouseMetrics_SharedMergeTreeThreads', 'type': 'gauge'},
                'SharedMergeTreeThreadsActive': {
                    'name': 'ClickHouseMetrics_SharedMergeTreeThreadsActive',
                    'type': 'gauge',
                },
                'SharedMergeTreeThreadsScheduled': {
                    'name': 'ClickHouseMetrics_SharedMergeTreeThreadsScheduled',
                    'type': 'gauge',
                },
                'StartupScriptsExecutionState': {
                    'name': 'ClickHouseMetrics_StartupScriptsExecutionState',
                    'type': 'gauge',
                },
                'StartupSystemTablesThreads': {'name': 'ClickHouseMetrics_StartupSystemTablesThreads', 'type': 'gauge'},
                'StartupSystemTablesThreadsActive': {
                    'name': 'ClickHouseMetrics_StartupSystemTablesThreadsActive',
                    'type': 'gauge',
                },
                'StartupSystemTablesThreadsScheduled': {
                    'name': 'ClickHouseMetrics_StartupSystemTablesThreadsScheduled',
                    'type': 'gauge',
                },
                'StatelessWorkerThreads': {'name': 'ClickHouseMetrics_StatelessWorkerThreads', 'type': 'gauge'},
                'StatelessWorkerThreadsActive': {
                    'name': 'ClickHouseMetrics_StatelessWorkerThreadsActive',
                    'type': 'gauge',
                },
                'StatelessWorkerThreadsScheduled': {
                    'name': 'ClickHouseMetrics_StatelessWorkerThreadsScheduled',
                    'type': 'gauge',
                },
                'StorageBufferBytes': {'name': 'ClickHouseMetrics_StorageBufferBytes', 'type': 'gauge'},
                'StorageBufferFlushThreads': {'name': 'ClickHouseMetrics_StorageBufferFlushThreads', 'type': 'gauge'},
                'StorageBufferFlushThreadsActive': {
                    'name': 'ClickHouseMetrics_StorageBufferFlushThreadsActive',
                    'type': 'gauge',
                },
                'StorageBufferFlushThreadsScheduled': {
                    'name': 'ClickHouseMetrics_StorageBufferFlushThreadsScheduled',
                    'type': 'gauge',
                },
                'StorageBufferRows': {'name': 'ClickHouseMetrics_StorageBufferRows', 'type': 'gauge'},
                'StorageConnectionsStored': {'name': 'ClickHouseMetrics_StorageConnectionsStored', 'type': 'gauge'},
                'StorageConnectionsTotal': {'name': 'ClickHouseMetrics_StorageConnectionsTotal', 'type': 'gauge'},
                'StorageDistributedThreads': {'name': 'ClickHouseMetrics_StorageDistributedThreads', 'type': 'gauge'},
                'StorageDistributedThreadsActive': {
                    'name': 'ClickHouseMetrics_StorageDistributedThreadsActive',
                    'type': 'gauge',
                },
                'StorageDistributedThreadsScheduled': {
                    'name': 'ClickHouseMetrics_StorageDistributedThreadsScheduled',
                    'type': 'gauge',
                },
                'StorageHiveThreads': {'name': 'ClickHouseMetrics_StorageHiveThreads', 'type': 'gauge'},
                'StorageHiveThreadsActive': {'name': 'ClickHouseMetrics_StorageHiveThreadsActive', 'type': 'gauge'},
                'StorageHiveThreadsScheduled': {
                    'name': 'ClickHouseMetrics_StorageHiveThreadsScheduled',
                    'type': 'gauge',
                },
                'StorageObjectStorageThreads': {
                    'name': 'ClickHouseMetrics_StorageObjectStorageThreads',
                    'type': 'gauge',
                },
                'StorageObjectStorageThreadsActive': {
                    'name': 'ClickHouseMetrics_StorageObjectStorageThreadsActive',
                    'type': 'gauge',
                },
                'StorageObjectStorageThreadsScheduled': {
                    'name': 'ClickHouseMetrics_StorageObjectStorageThreadsScheduled',
                    'type': 'gauge',
                },
                'StorageS3Threads': {'name': 'ClickHouseMetrics_StorageS3Threads', 'type': 'gauge'},
                'StorageS3ThreadsActive': {'name': 'ClickHouseMetrics_StorageS3ThreadsActive', 'type': 'gauge'},
                'StorageS3ThreadsScheduled': {'name': 'ClickHouseMetrics_StorageS3ThreadsScheduled', 'type': 'gauge'},
                'SystemReplicasThreads': {'name': 'ClickHouseMetrics_SystemReplicasThreads', 'type': 'gauge'},
                'SystemReplicasThreadsActive': {
                    'name': 'ClickHouseMetrics_SystemReplicasThreadsActive',
                    'type': 'gauge',
                },
                'SystemReplicasThreadsScheduled': {
                    'name': 'ClickHouseMetrics_SystemReplicasThreadsScheduled',
                    'type': 'gauge',
                },
                'TCPConnection': {'name': 'ClickHouseMetrics_TCPConnection', 'type': 'gauge'},
                'TablesLoaderBackgroundThreads': {
                    'name': 'ClickHouseMetrics_TablesLoaderBackgroundThreads',
                    'type': 'gauge',
                },
                'TablesLoaderBackgroundThreadsActive': {
                    'name': 'ClickHouseMetrics_TablesLoaderBackgroundThreadsActive',
                    'type': 'gauge',
                },
                'TablesLoaderBackgroundThreadsScheduled': {
                    'name': 'ClickHouseMetrics_TablesLoaderBackgroundThreadsScheduled',
                    'type': 'gauge',
                },
                'TablesLoaderForegroundThreads': {
                    'name': 'ClickHouseMetrics_TablesLoaderForegroundThreads',
                    'type': 'gauge',
                },
                'TablesLoaderForegroundThreadsActive': {
                    'name': 'ClickHouseMetrics_TablesLoaderForegroundThreadsActive',
                    'type': 'gauge',
                },
                'TablesLoaderForegroundThreadsScheduled': {
                    'name': 'ClickHouseMetrics_TablesLoaderForegroundThreadsScheduled',
                    'type': 'gauge',
                },
                'TablesToDropQueueSize': {'name': 'ClickHouseMetrics_TablesToDropQueueSize', 'type': 'gauge'},
                'TaskTrackerThreads': {'name': 'ClickHouseMetrics_TaskTrackerThreads', 'type': 'gauge'},
                'TaskTrackerThreadsActive': {'name': 'ClickHouseMetrics_TaskTrackerThreadsActive', 'type': 'gauge'},
                'TaskTrackerThreadsScheduled': {
                    'name': 'ClickHouseMetrics_TaskTrackerThreadsScheduled',
                    'type': 'gauge',
                },
                'TemporaryFilesForAggregation': {
                    'name': 'ClickHouseMetrics_TemporaryFilesForAggregation',
                    'type': 'gauge',
                },
                'TemporaryFilesForJoin': {'name': 'ClickHouseMetrics_TemporaryFilesForJoin', 'type': 'gauge'},
                'TemporaryFilesForMerge': {'name': 'ClickHouseMetrics_TemporaryFilesForMerge', 'type': 'gauge'},
                'TemporaryFilesForSort': {'name': 'ClickHouseMetrics_TemporaryFilesForSort', 'type': 'gauge'},
                'TemporaryFilesUnknown': {'name': 'ClickHouseMetrics_TemporaryFilesUnknown', 'type': 'gauge'},
                'ThreadPoolFSReaderThreads': {'name': 'ClickHouseMetrics_ThreadPoolFSReaderThreads', 'type': 'gauge'},
                'ThreadPoolFSReaderThreadsActive': {
                    'name': 'ClickHouseMetrics_ThreadPoolFSReaderThreadsActive',
                    'type': 'gauge',
                },
                'ThreadPoolFSReaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ThreadPoolFSReaderThreadsScheduled',
                    'type': 'gauge',
                },
                'ThreadPoolRemoteFSReaderThreads': {
                    'name': 'ClickHouseMetrics_ThreadPoolRemoteFSReaderThreads',
                    'type': 'gauge',
                },
                'ThreadPoolRemoteFSReaderThreadsActive': {
                    'name': 'ClickHouseMetrics_ThreadPoolRemoteFSReaderThreadsActive',
                    'type': 'gauge',
                },
                'ThreadPoolRemoteFSReaderThreadsScheduled': {
                    'name': 'ClickHouseMetrics_ThreadPoolRemoteFSReaderThreadsScheduled',
                    'type': 'gauge',
                },
                'ThreadsInOvercommitTracker': {'name': 'ClickHouseMetrics_ThreadsInOvercommitTracker', 'type': 'gauge'},
                'TotalMergeFailures': {'name': 'ClickHouseMetrics_TotalMergeFailures', 'type': 'gauge'},
                'TotalTemporaryFiles': {'name': 'ClickHouseMetrics_TotalTemporaryFiles', 'type': 'gauge'},
                'UncompressedCacheBytes': {'name': 'ClickHouseMetrics_UncompressedCacheBytes', 'type': 'gauge'},
                'UncompressedCacheCells': {'name': 'ClickHouseMetrics_UncompressedCacheCells', 'type': 'gauge'},
                'VectorSimilarityIndexCacheBytes': {
                    'name': 'ClickHouseMetrics_VectorSimilarityIndexCacheBytes',
                    'type': 'gauge',
                },
                'VectorSimilarityIndexCacheCells': {
                    'name': 'ClickHouseMetrics_VectorSimilarityIndexCacheCells',
                    'type': 'gauge',
                },
                'VersionInteger': {'name': 'ClickHouseMetrics_VersionInteger', 'type': 'gauge'},
                'Write': {'name': 'ClickHouseMetrics_Write', 'type': 'gauge'},
                'ZooKeeperRequest': {'name': 'ClickHouseMetrics_ZooKeeperRequest', 'type': 'gauge'},
                'ZooKeeperSession': {'name': 'ClickHouseMetrics_ZooKeeperSession', 'type': 'gauge'},
                'ZooKeeperWatch': {'name': 'ClickHouseMetrics_ZooKeeperWatch', 'type': 'gauge'},
            },
        },
    ],
}
