# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit scripts/templates/system_metrics.py and then run the following command:
#     hatch run data:generate

# https://clickhouse.com/docs/operations/system-tables/errors
SystemErrors = {
    'name': 'system_errors',
    'query': 'SELECT value, name FROM system.errors',
    'columns': [
        {'name': 'metric_value', 'type': 'source'},
        {
            'name': 'metric_name',
            'type': 'match',
            'source': 'metric_value',
            'items': {
                'ABORTED': {'name': 'ClickHouseErrors_ABORTED', 'type': 'monotonic_gauge'},
                'ACCESS_DENIED': {'name': 'ClickHouseErrors_ACCESS_DENIED', 'type': 'monotonic_gauge'},
                'ACCESS_ENTITY_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_ACCESS_ENTITY_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'ACCESS_ENTITY_NOT_FOUND': {
                    'name': 'ClickHouseErrors_ACCESS_ENTITY_NOT_FOUND',
                    'type': 'monotonic_gauge',
                },
                'ACCESS_STORAGE_DOESNT_ALLOW_BACKUP': {
                    'name': 'ClickHouseErrors_ACCESS_STORAGE_DOESNT_ALLOW_BACKUP',
                    'type': 'monotonic_gauge',
                },
                'ACCESS_STORAGE_FOR_INSERTION_NOT_FOUND': {
                    'name': 'ClickHouseErrors_ACCESS_STORAGE_FOR_INSERTION_NOT_FOUND',
                    'type': 'monotonic_gauge',
                },
                'ACCESS_STORAGE_READONLY': {
                    'name': 'ClickHouseErrors_ACCESS_STORAGE_READONLY',
                    'type': 'monotonic_gauge',
                },
                'AGGREGATE_FUNCTION_DOESNT_ALLOW_PARAMETERS': {
                    'name': 'ClickHouseErrors_AGGREGATE_FUNCTION_DOESNT_ALLOW_PARAMETERS',
                    'type': 'monotonic_gauge',
                },
                'AGGREGATE_FUNCTION_THROW': {
                    'name': 'ClickHouseErrors_AGGREGATE_FUNCTION_THROW',
                    'type': 'monotonic_gauge',
                },
                'AIO_READ_ERROR': {'name': 'ClickHouseErrors_AIO_READ_ERROR', 'type': 'monotonic_gauge'},
                'AIO_WRITE_ERROR': {'name': 'ClickHouseErrors_AIO_WRITE_ERROR', 'type': 'monotonic_gauge'},
                'ALIAS_REQUIRED': {'name': 'ClickHouseErrors_ALIAS_REQUIRED', 'type': 'monotonic_gauge'},
                'ALL_CONNECTION_TRIES_FAILED': {
                    'name': 'ClickHouseErrors_ALL_CONNECTION_TRIES_FAILED',
                    'type': 'monotonic_gauge',
                },
                'ALL_REPLICAS_ARE_STALE': {
                    'name': 'ClickHouseErrors_ALL_REPLICAS_ARE_STALE',
                    'type': 'monotonic_gauge',
                },
                'ALL_REPLICAS_LOST': {'name': 'ClickHouseErrors_ALL_REPLICAS_LOST', 'type': 'monotonic_gauge'},
                'ALTER_OF_COLUMN_IS_FORBIDDEN': {
                    'name': 'ClickHouseErrors_ALTER_OF_COLUMN_IS_FORBIDDEN',
                    'type': 'monotonic_gauge',
                },
                'AMBIGUOUS_COLUMN_NAME': {'name': 'ClickHouseErrors_AMBIGUOUS_COLUMN_NAME', 'type': 'monotonic_gauge'},
                'AMBIGUOUS_IDENTIFIER': {'name': 'ClickHouseErrors_AMBIGUOUS_IDENTIFIER', 'type': 'monotonic_gauge'},
                'ARGUMENT_OUT_OF_BOUND': {'name': 'ClickHouseErrors_ARGUMENT_OUT_OF_BOUND', 'type': 'monotonic_gauge'},
                'ARROWFLIGHT_CONNECTION_FAILURE': {
                    'name': 'ClickHouseErrors_ARROWFLIGHT_CONNECTION_FAILURE',
                    'type': 'monotonic_gauge',
                },
                'ARROWFLIGHT_FETCH_SCHEMA_ERROR': {
                    'name': 'ClickHouseErrors_ARROWFLIGHT_FETCH_SCHEMA_ERROR',
                    'type': 'monotonic_gauge',
                },
                'ARROWFLIGHT_INTERNAL_ERROR': {
                    'name': 'ClickHouseErrors_ARROWFLIGHT_INTERNAL_ERROR',
                    'type': 'monotonic_gauge',
                },
                'ARROWFLIGHT_WRITE_ERROR': {
                    'name': 'ClickHouseErrors_ARROWFLIGHT_WRITE_ERROR',
                    'type': 'monotonic_gauge',
                },
                'ASYNC_LOAD_CANCELED': {'name': 'ClickHouseErrors_ASYNC_LOAD_CANCELED', 'type': 'monotonic_gauge'},
                'ASYNC_LOAD_CYCLE': {'name': 'ClickHouseErrors_ASYNC_LOAD_CYCLE', 'type': 'monotonic_gauge'},
                'ASYNC_LOAD_FAILED': {'name': 'ClickHouseErrors_ASYNC_LOAD_FAILED', 'type': 'monotonic_gauge'},
                'ASYNC_LOAD_WAIT_FAILED': {
                    'name': 'ClickHouseErrors_ASYNC_LOAD_WAIT_FAILED',
                    'type': 'monotonic_gauge',
                },
                'ATOMIC_RENAME_FAIL': {'name': 'ClickHouseErrors_ATOMIC_RENAME_FAIL', 'type': 'monotonic_gauge'},
                'ATTEMPT_TO_READ_AFTER_EOF': {
                    'name': 'ClickHouseErrors_ATTEMPT_TO_READ_AFTER_EOF',
                    'type': 'monotonic_gauge',
                },
                'AUTHENTICATION_FAILED': {'name': 'ClickHouseErrors_AUTHENTICATION_FAILED', 'type': 'monotonic_gauge'},
                'AVRO_EXCEPTION': {'name': 'ClickHouseErrors_AVRO_EXCEPTION', 'type': 'monotonic_gauge'},
                'AWS_ERROR': {'name': 'ClickHouseErrors_AWS_ERROR', 'type': 'monotonic_gauge'},
                'AZURE_BLOB_STORAGE_ERROR': {
                    'name': 'ClickHouseErrors_AZURE_BLOB_STORAGE_ERROR',
                    'type': 'monotonic_gauge',
                },
                'BACKUP_ALREADY_EXISTS': {'name': 'ClickHouseErrors_BACKUP_ALREADY_EXISTS', 'type': 'monotonic_gauge'},
                'BACKUP_DAMAGED': {'name': 'ClickHouseErrors_BACKUP_DAMAGED', 'type': 'monotonic_gauge'},
                'BACKUP_ENGINE_NOT_FOUND': {
                    'name': 'ClickHouseErrors_BACKUP_ENGINE_NOT_FOUND',
                    'type': 'monotonic_gauge',
                },
                'BACKUP_ENTRY_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_BACKUP_ENTRY_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'BACKUP_ENTRY_NOT_FOUND': {
                    'name': 'ClickHouseErrors_BACKUP_ENTRY_NOT_FOUND',
                    'type': 'monotonic_gauge',
                },
                'BACKUP_IS_EMPTY': {'name': 'ClickHouseErrors_BACKUP_IS_EMPTY', 'type': 'monotonic_gauge'},
                'BACKUP_NOT_FOUND': {'name': 'ClickHouseErrors_BACKUP_NOT_FOUND', 'type': 'monotonic_gauge'},
                'BACKUP_VERSION_NOT_SUPPORTED': {
                    'name': 'ClickHouseErrors_BACKUP_VERSION_NOT_SUPPORTED',
                    'type': 'monotonic_gauge',
                },
                'BAD_ARGUMENTS': {'name': 'ClickHouseErrors_BAD_ARGUMENTS', 'type': 'monotonic_gauge'},
                'BAD_COLLATION': {'name': 'ClickHouseErrors_BAD_COLLATION', 'type': 'monotonic_gauge'},
                'BAD_DATABASE_FOR_TEMPORARY_TABLE': {
                    'name': 'ClickHouseErrors_BAD_DATABASE_FOR_TEMPORARY_TABLE',
                    'type': 'monotonic_gauge',
                },
                'BAD_DATA_PART_NAME': {'name': 'ClickHouseErrors_BAD_DATA_PART_NAME', 'type': 'monotonic_gauge'},
                'BAD_FILE_TYPE': {'name': 'ClickHouseErrors_BAD_FILE_TYPE', 'type': 'monotonic_gauge'},
                'BAD_GET': {'name': 'ClickHouseErrors_BAD_GET', 'type': 'monotonic_gauge'},
                'BAD_ODBC_CONNECTION_STRING': {
                    'name': 'ClickHouseErrors_BAD_ODBC_CONNECTION_STRING',
                    'type': 'monotonic_gauge',
                },
                'BAD_QUERY_PARAMETER': {'name': 'ClickHouseErrors_BAD_QUERY_PARAMETER', 'type': 'monotonic_gauge'},
                'BAD_REQUEST_PARAMETER': {'name': 'ClickHouseErrors_BAD_REQUEST_PARAMETER', 'type': 'monotonic_gauge'},
                'BAD_SIZE_OF_FILE_IN_DATA_PART': {
                    'name': 'ClickHouseErrors_BAD_SIZE_OF_FILE_IN_DATA_PART',
                    'type': 'monotonic_gauge',
                },
                'BAD_TTL_EXPRESSION': {'name': 'ClickHouseErrors_BAD_TTL_EXPRESSION', 'type': 'monotonic_gauge'},
                'BAD_TTL_FILE': {'name': 'ClickHouseErrors_BAD_TTL_FILE', 'type': 'monotonic_gauge'},
                'BAD_TYPE_OF_FIELD': {'name': 'ClickHouseErrors_BAD_TYPE_OF_FIELD', 'type': 'monotonic_gauge'},
                'BROKEN_PROJECTION': {'name': 'ClickHouseErrors_BROKEN_PROJECTION', 'type': 'monotonic_gauge'},
                'BROTLI_READ_FAILED': {'name': 'ClickHouseErrors_BROTLI_READ_FAILED', 'type': 'monotonic_gauge'},
                'BROTLI_WRITE_FAILED': {'name': 'ClickHouseErrors_BROTLI_WRITE_FAILED', 'type': 'monotonic_gauge'},
                'BUZZHOUSE': {'name': 'ClickHouseErrors_BUZZHOUSE', 'type': 'monotonic_gauge'},
                'BZIP2_STREAM_DECODER_FAILED': {
                    'name': 'ClickHouseErrors_BZIP2_STREAM_DECODER_FAILED',
                    'type': 'monotonic_gauge',
                },
                'BZIP2_STREAM_ENCODER_FAILED': {
                    'name': 'ClickHouseErrors_BZIP2_STREAM_ENCODER_FAILED',
                    'type': 'monotonic_gauge',
                },
                'CACHE_DICTIONARY_UPDATE_FAIL': {
                    'name': 'ClickHouseErrors_CACHE_DICTIONARY_UPDATE_FAIL',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_ADD_DIFFERENT_AGGREGATE_STATES': {
                    'name': 'ClickHouseErrors_CANNOT_ADD_DIFFERENT_AGGREGATE_STATES',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_ADVISE': {'name': 'ClickHouseErrors_CANNOT_ADVISE', 'type': 'monotonic_gauge'},
                'CANNOT_ALLOCATE_MEMORY': {
                    'name': 'ClickHouseErrors_CANNOT_ALLOCATE_MEMORY',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_APPEND_TO_FILE': {'name': 'ClickHouseErrors_CANNOT_APPEND_TO_FILE', 'type': 'monotonic_gauge'},
                'CANNOT_APPLY_CATBOOST_MODEL': {
                    'name': 'ClickHouseErrors_CANNOT_APPLY_CATBOOST_MODEL',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_ASSIGN_ALTER': {'name': 'ClickHouseErrors_CANNOT_ASSIGN_ALTER', 'type': 'monotonic_gauge'},
                'CANNOT_ASSIGN_OPTIMIZE': {
                    'name': 'ClickHouseErrors_CANNOT_ASSIGN_OPTIMIZE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_BACKUP_TABLE': {'name': 'ClickHouseErrors_CANNOT_BACKUP_TABLE', 'type': 'monotonic_gauge'},
                'CANNOT_BIND_RABBITMQ_EXCHANGE': {
                    'name': 'ClickHouseErrors_CANNOT_BIND_RABBITMQ_EXCHANGE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_BLOCK_SIGNAL': {'name': 'ClickHouseErrors_CANNOT_BLOCK_SIGNAL', 'type': 'monotonic_gauge'},
                'CANNOT_CLOCK_GETTIME': {'name': 'ClickHouseErrors_CANNOT_CLOCK_GETTIME', 'type': 'monotonic_gauge'},
                'CANNOT_CLOSE_FILE': {'name': 'ClickHouseErrors_CANNOT_CLOSE_FILE', 'type': 'monotonic_gauge'},
                'CANNOT_COMMIT_OFFSET': {'name': 'ClickHouseErrors_CANNOT_COMMIT_OFFSET', 'type': 'monotonic_gauge'},
                'CANNOT_COMPILE_CODE': {'name': 'ClickHouseErrors_CANNOT_COMPILE_CODE', 'type': 'monotonic_gauge'},
                'CANNOT_COMPILE_REGEXP': {'name': 'ClickHouseErrors_CANNOT_COMPILE_REGEXP', 'type': 'monotonic_gauge'},
                'CANNOT_COMPRESS': {'name': 'ClickHouseErrors_CANNOT_COMPRESS', 'type': 'monotonic_gauge'},
                'CANNOT_CONNECT_NATS': {'name': 'ClickHouseErrors_CANNOT_CONNECT_NATS', 'type': 'monotonic_gauge'},
                'CANNOT_CONNECT_RABBITMQ': {
                    'name': 'ClickHouseErrors_CANNOT_CONNECT_RABBITMQ',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CONVERT_CHARSET': {
                    'name': 'ClickHouseErrors_CANNOT_CONVERT_CHARSET',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CONVERT_TYPE': {'name': 'ClickHouseErrors_CANNOT_CONVERT_TYPE', 'type': 'monotonic_gauge'},
                'CANNOT_CREATE_CHARSET_CONVERTER': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_CHARSET_CONVERTER',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_CHILD_PROCESS': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_CHILD_PROCESS',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_DATABASE': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_DATABASE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_DIRECTORY': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_DIRECTORY',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_FILE': {'name': 'ClickHouseErrors_CANNOT_CREATE_FILE', 'type': 'monotonic_gauge'},
                'CANNOT_CREATE_IO_BUFFER': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_IO_BUFFER',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_RABBITMQ_QUEUE_BINDING': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_RABBITMQ_QUEUE_BINDING',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_RECURSIVE_FUNCTION': {
                    'name': 'ClickHouseErrors_CANNOT_CREATE_RECURSIVE_FUNCTION',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_CREATE_TIMER': {'name': 'ClickHouseErrors_CANNOT_CREATE_TIMER', 'type': 'monotonic_gauge'},
                'CANNOT_DECLARE_RABBITMQ_EXCHANGE': {
                    'name': 'ClickHouseErrors_CANNOT_DECLARE_RABBITMQ_EXCHANGE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_DECOMPRESS': {'name': 'ClickHouseErrors_CANNOT_DECOMPRESS', 'type': 'monotonic_gauge'},
                'CANNOT_DETACH_DICTIONARY_AS_TABLE': {
                    'name': 'ClickHouseErrors_CANNOT_DETACH_DICTIONARY_AS_TABLE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_DETECT_FORMAT': {'name': 'ClickHouseErrors_CANNOT_DETECT_FORMAT', 'type': 'monotonic_gauge'},
                'CANNOT_DLOPEN': {'name': 'ClickHouseErrors_CANNOT_DLOPEN', 'type': 'monotonic_gauge'},
                'CANNOT_DLSYM': {'name': 'ClickHouseErrors_CANNOT_DLSYM', 'type': 'monotonic_gauge'},
                'CANNOT_DROP_FUNCTION': {'name': 'ClickHouseErrors_CANNOT_DROP_FUNCTION', 'type': 'monotonic_gauge'},
                'CANNOT_EXTRACT_TABLE_STRUCTURE': {
                    'name': 'ClickHouseErrors_CANNOT_EXTRACT_TABLE_STRUCTURE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_FCNTL': {'name': 'ClickHouseErrors_CANNOT_FCNTL', 'type': 'monotonic_gauge'},
                'CANNOT_FORGET_PARTITION': {
                    'name': 'ClickHouseErrors_CANNOT_FORGET_PARTITION',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_FORK': {'name': 'ClickHouseErrors_CANNOT_FORK', 'type': 'monotonic_gauge'},
                'CANNOT_FORMAT_DATETIME': {
                    'name': 'ClickHouseErrors_CANNOT_FORMAT_DATETIME',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_FSTAT': {'name': 'ClickHouseErrors_CANNOT_FSTAT', 'type': 'monotonic_gauge'},
                'CANNOT_FSYNC': {'name': 'ClickHouseErrors_CANNOT_FSYNC', 'type': 'monotonic_gauge'},
                'CANNOT_GETTIMEOFDAY': {'name': 'ClickHouseErrors_CANNOT_GETTIMEOFDAY', 'type': 'monotonic_gauge'},
                'CANNOT_GET_CREATE_DICTIONARY_QUERY': {
                    'name': 'ClickHouseErrors_CANNOT_GET_CREATE_DICTIONARY_QUERY',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_GET_CREATE_TABLE_QUERY': {
                    'name': 'ClickHouseErrors_CANNOT_GET_CREATE_TABLE_QUERY',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_GET_REPLICATED_DATABASE_SNAPSHOT': {
                    'name': 'ClickHouseErrors_CANNOT_GET_REPLICATED_DATABASE_SNAPSHOT',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_GET_SIZE_OF_FIELD': {
                    'name': 'ClickHouseErrors_CANNOT_GET_SIZE_OF_FIELD',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN': {
                    'name': 'ClickHouseErrors_CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_INSERT_VALUE_OF_DIFFERENT_SIZE_INTO_TUPLE': {
                    'name': 'ClickHouseErrors_CANNOT_INSERT_VALUE_OF_DIFFERENT_SIZE_INTO_TUPLE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_IOSETUP': {'name': 'ClickHouseErrors_CANNOT_IOSETUP', 'type': 'monotonic_gauge'},
                'CANNOT_IO_GETEVENTS': {'name': 'ClickHouseErrors_CANNOT_IO_GETEVENTS', 'type': 'monotonic_gauge'},
                'CANNOT_IO_SUBMIT': {'name': 'ClickHouseErrors_CANNOT_IO_SUBMIT', 'type': 'monotonic_gauge'},
                'CANNOT_KILL': {'name': 'ClickHouseErrors_CANNOT_KILL', 'type': 'monotonic_gauge'},
                'CANNOT_LINK': {'name': 'ClickHouseErrors_CANNOT_LINK', 'type': 'monotonic_gauge'},
                'CANNOT_LOAD_CATBOOST_MODEL': {
                    'name': 'ClickHouseErrors_CANNOT_LOAD_CATBOOST_MODEL',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_LOAD_CONFIG': {'name': 'ClickHouseErrors_CANNOT_LOAD_CONFIG', 'type': 'monotonic_gauge'},
                'CANNOT_MANIPULATE_SIGSET': {
                    'name': 'ClickHouseErrors_CANNOT_MANIPULATE_SIGSET',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_MERGE_DIFFERENT_AGGREGATED_DATA_VARIANTS': {
                    'name': 'ClickHouseErrors_CANNOT_MERGE_DIFFERENT_AGGREGATED_DATA_VARIANTS',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_MPROTECT': {'name': 'ClickHouseErrors_CANNOT_MPROTECT', 'type': 'monotonic_gauge'},
                'CANNOT_MREMAP': {'name': 'ClickHouseErrors_CANNOT_MREMAP', 'type': 'monotonic_gauge'},
                'CANNOT_MUNMAP': {'name': 'ClickHouseErrors_CANNOT_MUNMAP', 'type': 'monotonic_gauge'},
                'CANNOT_NORMALIZE_STRING': {
                    'name': 'ClickHouseErrors_CANNOT_NORMALIZE_STRING',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_OPEN_FILE': {'name': 'ClickHouseErrors_CANNOT_OPEN_FILE', 'type': 'monotonic_gauge'},
                'CANNOT_PACK_ARCHIVE': {'name': 'ClickHouseErrors_CANNOT_PACK_ARCHIVE', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_BACKUP_SETTINGS': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_BACKUP_SETTINGS',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_BOOL': {'name': 'ClickHouseErrors_CANNOT_PARSE_BOOL', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_CAPN_PROTO_SCHEMA': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_CAPN_PROTO_SCHEMA',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_DATE': {'name': 'ClickHouseErrors_CANNOT_PARSE_DATE', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_DATETIME': {'name': 'ClickHouseErrors_CANNOT_PARSE_DATETIME', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_DWARF': {'name': 'ClickHouseErrors_CANNOT_PARSE_DWARF', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_ELF': {'name': 'ClickHouseErrors_CANNOT_PARSE_ELF', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_ESCAPE_SEQUENCE': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_ESCAPE_SEQUENCE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_INPUT_ASSERTION_FAILED': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_INPUT_ASSERTION_FAILED',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_IPV4': {'name': 'ClickHouseErrors_CANNOT_PARSE_IPV4', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_IPV6': {'name': 'ClickHouseErrors_CANNOT_PARSE_IPV6', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_NUMBER': {'name': 'ClickHouseErrors_CANNOT_PARSE_NUMBER', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_PROMQL_QUERY': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_PROMQL_QUERY',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_PROTOBUF_SCHEMA': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_PROTOBUF_SCHEMA',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_QUOTED_STRING': {
                    'name': 'ClickHouseErrors_CANNOT_PARSE_QUOTED_STRING',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PARSE_TEXT': {'name': 'ClickHouseErrors_CANNOT_PARSE_TEXT', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_UUID': {'name': 'ClickHouseErrors_CANNOT_PARSE_UUID', 'type': 'monotonic_gauge'},
                'CANNOT_PARSE_YAML': {'name': 'ClickHouseErrors_CANNOT_PARSE_YAML', 'type': 'monotonic_gauge'},
                'CANNOT_PIPE': {'name': 'ClickHouseErrors_CANNOT_PIPE', 'type': 'monotonic_gauge'},
                'CANNOT_POLL': {'name': 'ClickHouseErrors_CANNOT_POLL', 'type': 'monotonic_gauge'},
                'CANNOT_PRINT_FLOAT_OR_DOUBLE_NUMBER': {
                    'name': 'ClickHouseErrors_CANNOT_PRINT_FLOAT_OR_DOUBLE_NUMBER',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_PTHREAD_ATTR': {'name': 'ClickHouseErrors_CANNOT_PTHREAD_ATTR', 'type': 'monotonic_gauge'},
                'CANNOT_READ_ALL_DATA': {'name': 'ClickHouseErrors_CANNOT_READ_ALL_DATA', 'type': 'monotonic_gauge'},
                'CANNOT_READ_ARRAY_FROM_TEXT': {
                    'name': 'ClickHouseErrors_CANNOT_READ_ARRAY_FROM_TEXT',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_READ_FROM_FILE_DESCRIPTOR': {
                    'name': 'ClickHouseErrors_CANNOT_READ_FROM_FILE_DESCRIPTOR',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_READ_FROM_ISTREAM': {
                    'name': 'ClickHouseErrors_CANNOT_READ_FROM_ISTREAM',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_READ_FROM_SOCKET': {
                    'name': 'ClickHouseErrors_CANNOT_READ_FROM_SOCKET',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_READ_MAP_FROM_TEXT': {
                    'name': 'ClickHouseErrors_CANNOT_READ_MAP_FROM_TEXT',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_REMOVE_RABBITMQ_EXCHANGE': {
                    'name': 'ClickHouseErrors_CANNOT_REMOVE_RABBITMQ_EXCHANGE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_RESTORE_DATABASE': {
                    'name': 'ClickHouseErrors_CANNOT_RESTORE_DATABASE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_RESTORE_FROM_FIELD_DUMP': {
                    'name': 'ClickHouseErrors_CANNOT_RESTORE_FROM_FIELD_DUMP',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_RESTORE_TABLE': {'name': 'ClickHouseErrors_CANNOT_RESTORE_TABLE', 'type': 'monotonic_gauge'},
                'CANNOT_RESTORE_TO_NONENCRYPTED_DISK': {
                    'name': 'ClickHouseErrors_CANNOT_RESTORE_TO_NONENCRYPTED_DISK',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_RMDIR': {'name': 'ClickHouseErrors_CANNOT_RMDIR', 'type': 'monotonic_gauge'},
                'CANNOT_SCHEDULE_TASK': {'name': 'ClickHouseErrors_CANNOT_SCHEDULE_TASK', 'type': 'monotonic_gauge'},
                'CANNOT_SEEK_THROUGH_FILE': {
                    'name': 'ClickHouseErrors_CANNOT_SEEK_THROUGH_FILE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_SELECT': {'name': 'ClickHouseErrors_CANNOT_SELECT', 'type': 'monotonic_gauge'},
                'CANNOT_SEND_SIGNAL': {'name': 'ClickHouseErrors_CANNOT_SEND_SIGNAL', 'type': 'monotonic_gauge'},
                'CANNOT_SET_ROUNDING_MODE': {
                    'name': 'ClickHouseErrors_CANNOT_SET_ROUNDING_MODE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_SET_SIGNAL_HANDLER': {
                    'name': 'ClickHouseErrors_CANNOT_SET_SIGNAL_HANDLER',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_SET_THREAD_PRIORITY': {
                    'name': 'ClickHouseErrors_CANNOT_SET_THREAD_PRIORITY',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_SET_TIMER_PERIOD': {
                    'name': 'ClickHouseErrors_CANNOT_SET_TIMER_PERIOD',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_SIGQUEUE': {'name': 'ClickHouseErrors_CANNOT_SIGQUEUE', 'type': 'monotonic_gauge'},
                'CANNOT_SKIP_UNKNOWN_FIELD': {
                    'name': 'ClickHouseErrors_CANNOT_SKIP_UNKNOWN_FIELD',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_STAT': {'name': 'ClickHouseErrors_CANNOT_STAT', 'type': 'monotonic_gauge'},
                'CANNOT_STATVFS': {'name': 'ClickHouseErrors_CANNOT_STATVFS', 'type': 'monotonic_gauge'},
                'CANNOT_SYSCONF': {'name': 'ClickHouseErrors_CANNOT_SYSCONF', 'type': 'monotonic_gauge'},
                'CANNOT_TRUNCATE_FILE': {'name': 'ClickHouseErrors_CANNOT_TRUNCATE_FILE', 'type': 'monotonic_gauge'},
                'CANNOT_UNBLOCK_SIGNAL': {'name': 'ClickHouseErrors_CANNOT_UNBLOCK_SIGNAL', 'type': 'monotonic_gauge'},
                'CANNOT_UNLINK': {'name': 'ClickHouseErrors_CANNOT_UNLINK', 'type': 'monotonic_gauge'},
                'CANNOT_UNPACK_ARCHIVE': {'name': 'ClickHouseErrors_CANNOT_UNPACK_ARCHIVE', 'type': 'monotonic_gauge'},
                'CANNOT_UPDATE_COLUMN': {'name': 'ClickHouseErrors_CANNOT_UPDATE_COLUMN', 'type': 'monotonic_gauge'},
                'CANNOT_USE_DISTRIBUTED_CACHE': {
                    'name': 'ClickHouseErrors_CANNOT_USE_DISTRIBUTED_CACHE',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_WAITPID': {'name': 'ClickHouseErrors_CANNOT_WAITPID', 'type': 'monotonic_gauge'},
                'CANNOT_WAIT_FOR_SIGNAL': {
                    'name': 'ClickHouseErrors_CANNOT_WAIT_FOR_SIGNAL',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_WRITE_AFTER_BUFFER_CANCELED': {
                    'name': 'ClickHouseErrors_CANNOT_WRITE_AFTER_BUFFER_CANCELED',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_WRITE_AFTER_END_OF_BUFFER': {
                    'name': 'ClickHouseErrors_CANNOT_WRITE_AFTER_END_OF_BUFFER',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_WRITE_TO_FILE': {'name': 'ClickHouseErrors_CANNOT_WRITE_TO_FILE', 'type': 'monotonic_gauge'},
                'CANNOT_WRITE_TO_FILE_DESCRIPTOR': {
                    'name': 'ClickHouseErrors_CANNOT_WRITE_TO_FILE_DESCRIPTOR',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_WRITE_TO_OSTREAM': {
                    'name': 'ClickHouseErrors_CANNOT_WRITE_TO_OSTREAM',
                    'type': 'monotonic_gauge',
                },
                'CANNOT_WRITE_TO_SOCKET': {
                    'name': 'ClickHouseErrors_CANNOT_WRITE_TO_SOCKET',
                    'type': 'monotonic_gauge',
                },
                'CAPN_PROTO_BAD_CAST': {'name': 'ClickHouseErrors_CAPN_PROTO_BAD_CAST', 'type': 'monotonic_gauge'},
                'CAPN_PROTO_BAD_TYPE': {'name': 'ClickHouseErrors_CAPN_PROTO_BAD_TYPE', 'type': 'monotonic_gauge'},
                'CASSANDRA_INTERNAL_ERROR': {
                    'name': 'ClickHouseErrors_CASSANDRA_INTERNAL_ERROR',
                    'type': 'monotonic_gauge',
                },
                'CHECKSUM_DOESNT_MATCH': {'name': 'ClickHouseErrors_CHECKSUM_DOESNT_MATCH', 'type': 'monotonic_gauge'},
                'CHILD_WAS_NOT_EXITED_NORMALLY': {
                    'name': 'ClickHouseErrors_CHILD_WAS_NOT_EXITED_NORMALLY',
                    'type': 'monotonic_gauge',
                },
                'CLIENT_HAS_CONNECTED_TO_WRONG_PORT': {
                    'name': 'ClickHouseErrors_CLIENT_HAS_CONNECTED_TO_WRONG_PORT',
                    'type': 'monotonic_gauge',
                },
                'CLIENT_INFO_DOES_NOT_MATCH': {
                    'name': 'ClickHouseErrors_CLIENT_INFO_DOES_NOT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'CLIENT_OUTPUT_FORMAT_SPECIFIED': {
                    'name': 'ClickHouseErrors_CLIENT_OUTPUT_FORMAT_SPECIFIED',
                    'type': 'monotonic_gauge',
                },
                'CLUSTER_DOESNT_EXIST': {'name': 'ClickHouseErrors_CLUSTER_DOESNT_EXIST', 'type': 'monotonic_gauge'},
                'COLLATION_COMPARISON_FAILED': {
                    'name': 'ClickHouseErrors_COLLATION_COMPARISON_FAILED',
                    'type': 'monotonic_gauge',
                },
                'COLUMN_QUERIED_MORE_THAN_ONCE': {
                    'name': 'ClickHouseErrors_COLUMN_QUERIED_MORE_THAN_ONCE',
                    'type': 'monotonic_gauge',
                },
                'CONCURRENT_ACCESS_NOT_SUPPORTED': {
                    'name': 'ClickHouseErrors_CONCURRENT_ACCESS_NOT_SUPPORTED',
                    'type': 'monotonic_gauge',
                },
                'CORRUPTED_DATA': {'name': 'ClickHouseErrors_CORRUPTED_DATA', 'type': 'monotonic_gauge'},
                'CURRENT_WRITE_BUFFER_IS_EXHAUSTED': {
                    'name': 'ClickHouseErrors_CURRENT_WRITE_BUFFER_IS_EXHAUSTED',
                    'type': 'monotonic_gauge',
                },
                'CYCLIC_ALIASES': {'name': 'ClickHouseErrors_CYCLIC_ALIASES', 'type': 'monotonic_gauge'},
                'DATABASE_ACCESS_DENIED': {
                    'name': 'ClickHouseErrors_DATABASE_ACCESS_DENIED',
                    'type': 'monotonic_gauge',
                },
                'DATABASE_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_DATABASE_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'DATABASE_NOT_EMPTY': {'name': 'ClickHouseErrors_DATABASE_NOT_EMPTY', 'type': 'monotonic_gauge'},
                'DATABASE_REPLICATION_FAILED': {
                    'name': 'ClickHouseErrors_DATABASE_REPLICATION_FAILED',
                    'type': 'monotonic_gauge',
                },
                'DATALAKE_DATABASE_ERROR': {
                    'name': 'ClickHouseErrors_DATALAKE_DATABASE_ERROR',
                    'type': 'monotonic_gauge',
                },
                'DATA_ENCRYPTION_ERROR': {'name': 'ClickHouseErrors_DATA_ENCRYPTION_ERROR', 'type': 'monotonic_gauge'},
                'DATA_TYPE_CANNOT_BE_PROMOTED': {
                    'name': 'ClickHouseErrors_DATA_TYPE_CANNOT_BE_PROMOTED',
                    'type': 'monotonic_gauge',
                },
                'DATA_TYPE_CANNOT_BE_USED_IN_KEY': {
                    'name': 'ClickHouseErrors_DATA_TYPE_CANNOT_BE_USED_IN_KEY',
                    'type': 'monotonic_gauge',
                },
                'DATA_TYPE_CANNOT_BE_USED_IN_TABLES': {
                    'name': 'ClickHouseErrors_DATA_TYPE_CANNOT_BE_USED_IN_TABLES',
                    'type': 'monotonic_gauge',
                },
                'DATA_TYPE_CANNOT_HAVE_ARGUMENTS': {
                    'name': 'ClickHouseErrors_DATA_TYPE_CANNOT_HAVE_ARGUMENTS',
                    'type': 'monotonic_gauge',
                },
                'DATA_TYPE_INCOMPATIBLE_WITH_PROTOBUF_FIELD': {
                    'name': 'ClickHouseErrors_DATA_TYPE_INCOMPATIBLE_WITH_PROTOBUF_FIELD',
                    'type': 'monotonic_gauge',
                },
                'DEADLOCK_AVOIDED': {'name': 'ClickHouseErrors_DEADLOCK_AVOIDED', 'type': 'monotonic_gauge'},
                'DECIMAL_OVERFLOW': {'name': 'ClickHouseErrors_DECIMAL_OVERFLOW', 'type': 'monotonic_gauge'},
                'DELTA_KERNEL_ERROR': {'name': 'ClickHouseErrors_DELTA_KERNEL_ERROR', 'type': 'monotonic_gauge'},
                'DEPENDENCIES_NOT_FOUND': {
                    'name': 'ClickHouseErrors_DEPENDENCIES_NOT_FOUND',
                    'type': 'monotonic_gauge',
                },
                'DEPRECATED_FUNCTION': {'name': 'ClickHouseErrors_DEPRECATED_FUNCTION', 'type': 'monotonic_gauge'},
                'DICTIONARIES_WAS_NOT_LOADED': {
                    'name': 'ClickHouseErrors_DICTIONARIES_WAS_NOT_LOADED',
                    'type': 'monotonic_gauge',
                },
                'DICTIONARY_ACCESS_DENIED': {
                    'name': 'ClickHouseErrors_DICTIONARY_ACCESS_DENIED',
                    'type': 'monotonic_gauge',
                },
                'DICTIONARY_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_DICTIONARY_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'DICTIONARY_IS_EMPTY': {'name': 'ClickHouseErrors_DICTIONARY_IS_EMPTY', 'type': 'monotonic_gauge'},
                'DIRECTORY_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_DIRECTORY_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'DIRECTORY_DOESNT_EXIST': {
                    'name': 'ClickHouseErrors_DIRECTORY_DOESNT_EXIST',
                    'type': 'monotonic_gauge',
                },
                'DISTRIBUTED_BROKEN_BATCH_FILES': {
                    'name': 'ClickHouseErrors_DISTRIBUTED_BROKEN_BATCH_FILES',
                    'type': 'monotonic_gauge',
                },
                'DISTRIBUTED_BROKEN_BATCH_INFO': {
                    'name': 'ClickHouseErrors_DISTRIBUTED_BROKEN_BATCH_INFO',
                    'type': 'monotonic_gauge',
                },
                'DISTRIBUTED_CACHE_ERROR': {
                    'name': 'ClickHouseErrors_DISTRIBUTED_CACHE_ERROR',
                    'type': 'monotonic_gauge',
                },
                'DISTRIBUTED_IN_JOIN_SUBQUERY_DENIED': {
                    'name': 'ClickHouseErrors_DISTRIBUTED_IN_JOIN_SUBQUERY_DENIED',
                    'type': 'monotonic_gauge',
                },
                'DISTRIBUTED_TOO_MANY_PENDING_BYTES': {
                    'name': 'ClickHouseErrors_DISTRIBUTED_TOO_MANY_PENDING_BYTES',
                    'type': 'monotonic_gauge',
                },
                'DNS_ERROR': {'name': 'ClickHouseErrors_DNS_ERROR', 'type': 'monotonic_gauge'},
                'DUPLICATED_PART_UUIDS': {'name': 'ClickHouseErrors_DUPLICATED_PART_UUIDS', 'type': 'monotonic_gauge'},
                'DUPLICATE_COLUMN': {'name': 'ClickHouseErrors_DUPLICATE_COLUMN', 'type': 'monotonic_gauge'},
                'DUPLICATE_DATA_PART': {'name': 'ClickHouseErrors_DUPLICATE_DATA_PART', 'type': 'monotonic_gauge'},
                'DUPLICATE_INTERSERVER_IO_ENDPOINT': {
                    'name': 'ClickHouseErrors_DUPLICATE_INTERSERVER_IO_ENDPOINT',
                    'type': 'monotonic_gauge',
                },
                'EMPTY_DATA_PASSED': {'name': 'ClickHouseErrors_EMPTY_DATA_PASSED', 'type': 'monotonic_gauge'},
                'EMPTY_LIST_OF_COLUMNS_PASSED': {
                    'name': 'ClickHouseErrors_EMPTY_LIST_OF_COLUMNS_PASSED',
                    'type': 'monotonic_gauge',
                },
                'EMPTY_LIST_OF_COLUMNS_QUERIED': {
                    'name': 'ClickHouseErrors_EMPTY_LIST_OF_COLUMNS_QUERIED',
                    'type': 'monotonic_gauge',
                },
                'EMPTY_NESTED_TABLE': {'name': 'ClickHouseErrors_EMPTY_NESTED_TABLE', 'type': 'monotonic_gauge'},
                'EMPTY_QUERY': {'name': 'ClickHouseErrors_EMPTY_QUERY', 'type': 'monotonic_gauge'},
                'ENGINE_REQUIRED': {'name': 'ClickHouseErrors_ENGINE_REQUIRED', 'type': 'monotonic_gauge'},
                'EPOLL_ERROR': {'name': 'ClickHouseErrors_EPOLL_ERROR', 'type': 'monotonic_gauge'},
                'EXCESSIVE_ELEMENT_IN_CONFIG': {
                    'name': 'ClickHouseErrors_EXCESSIVE_ELEMENT_IN_CONFIG',
                    'type': 'monotonic_gauge',
                },
                'EXPECTED_ALL_OR_ANY': {'name': 'ClickHouseErrors_EXPECTED_ALL_OR_ANY', 'type': 'monotonic_gauge'},
                'EXPECTED_ALL_OR_DISTINCT': {
                    'name': 'ClickHouseErrors_EXPECTED_ALL_OR_DISTINCT',
                    'type': 'monotonic_gauge',
                },
                'EXPECTED_END_OF_FILE': {'name': 'ClickHouseErrors_EXPECTED_END_OF_FILE', 'type': 'monotonic_gauge'},
                'EXPERIMENTAL_FEATURE_ERROR': {
                    'name': 'ClickHouseErrors_EXPERIMENTAL_FEATURE_ERROR',
                    'type': 'monotonic_gauge',
                },
                'EXTERNAL_LIBRARY_ERROR': {
                    'name': 'ClickHouseErrors_EXTERNAL_LIBRARY_ERROR',
                    'type': 'monotonic_gauge',
                },
                'EXTERNAL_SERVER_IS_NOT_RESPONDING': {
                    'name': 'ClickHouseErrors_EXTERNAL_SERVER_IS_NOT_RESPONDING',
                    'type': 'monotonic_gauge',
                },
                'FAILED_TO_GETPWUID': {'name': 'ClickHouseErrors_FAILED_TO_GETPWUID', 'type': 'monotonic_gauge'},
                'FAILED_TO_SYNC_BACKUP_OR_RESTORE': {
                    'name': 'ClickHouseErrors_FAILED_TO_SYNC_BACKUP_OR_RESTORE',
                    'type': 'monotonic_gauge',
                },
                'FAULT_INJECTED': {'name': 'ClickHouseErrors_FAULT_INJECTED', 'type': 'monotonic_gauge'},
                'FEATURE_IS_NOT_ENABLED_AT_BUILD_TIME': {
                    'name': 'ClickHouseErrors_FEATURE_IS_NOT_ENABLED_AT_BUILD_TIME',
                    'type': 'monotonic_gauge',
                },
                'FILECACHE_ACCESS_DENIED': {
                    'name': 'ClickHouseErrors_FILECACHE_ACCESS_DENIED',
                    'type': 'monotonic_gauge',
                },
                'FILECACHE_CANNOT_WRITE_THROUGH_CACHE_WITH_CONCURRENT_READS': {
                    'name': 'ClickHouseErrors_FILECACHE_CANNOT_WRITE_THROUGH_CACHE_WITH_CONCURRENT_READS',
                    'type': 'monotonic_gauge',
                },
                'FILE_ALREADY_EXISTS': {'name': 'ClickHouseErrors_FILE_ALREADY_EXISTS', 'type': 'monotonic_gauge'},
                'FILE_DOESNT_EXIST': {'name': 'ClickHouseErrors_FILE_DOESNT_EXIST', 'type': 'monotonic_gauge'},
                'FIRST_AND_NEXT_TOGETHER': {
                    'name': 'ClickHouseErrors_FIRST_AND_NEXT_TOGETHER',
                    'type': 'monotonic_gauge',
                },
                'FORMAT_IS_NOT_SUITABLE_FOR_INPUT': {
                    'name': 'ClickHouseErrors_FORMAT_IS_NOT_SUITABLE_FOR_INPUT',
                    'type': 'monotonic_gauge',
                },
                'FORMAT_IS_NOT_SUITABLE_FOR_OUTPUT': {
                    'name': 'ClickHouseErrors_FORMAT_IS_NOT_SUITABLE_FOR_OUTPUT',
                    'type': 'monotonic_gauge',
                },
                'FORMAT_VERSION_TOO_OLD': {
                    'name': 'ClickHouseErrors_FORMAT_VERSION_TOO_OLD',
                    'type': 'monotonic_gauge',
                },
                'FS_METADATA_ERROR': {'name': 'ClickHouseErrors_FS_METADATA_ERROR', 'type': 'monotonic_gauge'},
                'FUNCTION_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_FUNCTION_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'FUNCTION_CANNOT_HAVE_PARAMETERS': {
                    'name': 'ClickHouseErrors_FUNCTION_CANNOT_HAVE_PARAMETERS',
                    'type': 'monotonic_gauge',
                },
                'FUNCTION_IS_SPECIAL': {'name': 'ClickHouseErrors_FUNCTION_IS_SPECIAL', 'type': 'monotonic_gauge'},
                'FUNCTION_NOT_ALLOWED': {'name': 'ClickHouseErrors_FUNCTION_NOT_ALLOWED', 'type': 'monotonic_gauge'},
                'FUNCTION_THROW_IF_VALUE_IS_NON_ZERO': {
                    'name': 'ClickHouseErrors_FUNCTION_THROW_IF_VALUE_IS_NON_ZERO',
                    'type': 'monotonic_gauge',
                },
                'GCP_ERROR': {'name': 'ClickHouseErrors_GCP_ERROR', 'type': 'monotonic_gauge'},
                'GOOGLE_CLOUD_ERROR': {'name': 'ClickHouseErrors_GOOGLE_CLOUD_ERROR', 'type': 'monotonic_gauge'},
                'HAVE_DEPENDENT_OBJECTS': {
                    'name': 'ClickHouseErrors_HAVE_DEPENDENT_OBJECTS',
                    'type': 'monotonic_gauge',
                },
                'HDFS_ERROR': {'name': 'ClickHouseErrors_HDFS_ERROR', 'type': 'monotonic_gauge'},
                'HTTP_LENGTH_REQUIRED': {'name': 'ClickHouseErrors_HTTP_LENGTH_REQUIRED', 'type': 'monotonic_gauge'},
                'HTTP_RANGE_NOT_SATISFIABLE': {
                    'name': 'ClickHouseErrors_HTTP_RANGE_NOT_SATISFIABLE',
                    'type': 'monotonic_gauge',
                },
                'HYPERSCAN_CANNOT_SCAN_TEXT': {
                    'name': 'ClickHouseErrors_HYPERSCAN_CANNOT_SCAN_TEXT',
                    'type': 'monotonic_gauge',
                },
                'ICEBERG_SPECIFICATION_VIOLATION': {
                    'name': 'ClickHouseErrors_ICEBERG_SPECIFICATION_VIOLATION',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_AGGREGATION': {'name': 'ClickHouseErrors_ILLEGAL_AGGREGATION', 'type': 'monotonic_gauge'},
                'ILLEGAL_CODEC_PARAMETER': {
                    'name': 'ClickHouseErrors_ILLEGAL_CODEC_PARAMETER',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_COLUMN': {'name': 'ClickHouseErrors_ILLEGAL_COLUMN', 'type': 'monotonic_gauge'},
                'ILLEGAL_DIVISION': {'name': 'ClickHouseErrors_ILLEGAL_DIVISION', 'type': 'monotonic_gauge'},
                'ILLEGAL_FINAL': {'name': 'ClickHouseErrors_ILLEGAL_FINAL', 'type': 'monotonic_gauge'},
                'ILLEGAL_INDEX': {'name': 'ClickHouseErrors_ILLEGAL_INDEX', 'type': 'monotonic_gauge'},
                'ILLEGAL_MYSQL_VARIABLE': {
                    'name': 'ClickHouseErrors_ILLEGAL_MYSQL_VARIABLE',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_PREWHERE': {'name': 'ClickHouseErrors_ILLEGAL_PREWHERE', 'type': 'monotonic_gauge'},
                'ILLEGAL_PROJECTION': {'name': 'ClickHouseErrors_ILLEGAL_PROJECTION', 'type': 'monotonic_gauge'},
                'ILLEGAL_STATISTICS': {'name': 'ClickHouseErrors_ILLEGAL_STATISTICS', 'type': 'monotonic_gauge'},
                'ILLEGAL_SYNTAX_FOR_CODEC_TYPE': {
                    'name': 'ClickHouseErrors_ILLEGAL_SYNTAX_FOR_CODEC_TYPE',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_SYNTAX_FOR_DATA_TYPE': {
                    'name': 'ClickHouseErrors_ILLEGAL_SYNTAX_FOR_DATA_TYPE',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_TIME_SERIES_TAGS': {
                    'name': 'ClickHouseErrors_ILLEGAL_TIME_SERIES_TAGS',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_TYPE_OF_ARGUMENT': {
                    'name': 'ClickHouseErrors_ILLEGAL_TYPE_OF_ARGUMENT',
                    'type': 'monotonic_gauge',
                },
                'ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER': {
                    'name': 'ClickHouseErrors_ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER',
                    'type': 'monotonic_gauge',
                },
                'INCOMPATIBLE_COLUMNS': {'name': 'ClickHouseErrors_INCOMPATIBLE_COLUMNS', 'type': 'monotonic_gauge'},
                'INCOMPATIBLE_TYPE_OF_JOIN': {
                    'name': 'ClickHouseErrors_INCOMPATIBLE_TYPE_OF_JOIN',
                    'type': 'monotonic_gauge',
                },
                'INCONSISTENT_CLUSTER_DEFINITION': {
                    'name': 'ClickHouseErrors_INCONSISTENT_CLUSTER_DEFINITION',
                    'type': 'monotonic_gauge',
                },
                'INCONSISTENT_METADATA_FOR_BACKUP': {
                    'name': 'ClickHouseErrors_INCONSISTENT_METADATA_FOR_BACKUP',
                    'type': 'monotonic_gauge',
                },
                'INCORRECT_ACCESS_ENTITY_DEFINITION': {
                    'name': 'ClickHouseErrors_INCORRECT_ACCESS_ENTITY_DEFINITION',
                    'type': 'monotonic_gauge',
                },
                'INCORRECT_DATA': {'name': 'ClickHouseErrors_INCORRECT_DATA', 'type': 'monotonic_gauge'},
                'INCORRECT_DICTIONARY_DEFINITION': {
                    'name': 'ClickHouseErrors_INCORRECT_DICTIONARY_DEFINITION',
                    'type': 'monotonic_gauge',
                },
                'INCORRECT_DISK_INDEX': {'name': 'ClickHouseErrors_INCORRECT_DISK_INDEX', 'type': 'monotonic_gauge'},
                'INCORRECT_ELEMENT_OF_SET': {
                    'name': 'ClickHouseErrors_INCORRECT_ELEMENT_OF_SET',
                    'type': 'monotonic_gauge',
                },
                'INCORRECT_FILE_NAME': {'name': 'ClickHouseErrors_INCORRECT_FILE_NAME', 'type': 'monotonic_gauge'},
                'INCORRECT_INDEX': {'name': 'ClickHouseErrors_INCORRECT_INDEX', 'type': 'monotonic_gauge'},
                'INCORRECT_NUMBER_OF_COLUMNS': {
                    'name': 'ClickHouseErrors_INCORRECT_NUMBER_OF_COLUMNS',
                    'type': 'monotonic_gauge',
                },
                'INCORRECT_PART_TYPE': {'name': 'ClickHouseErrors_INCORRECT_PART_TYPE', 'type': 'monotonic_gauge'},
                'INCORRECT_QUERY': {'name': 'ClickHouseErrors_INCORRECT_QUERY', 'type': 'monotonic_gauge'},
                'INCORRECT_RESULT_OF_SCALAR_SUBQUERY': {
                    'name': 'ClickHouseErrors_INCORRECT_RESULT_OF_SCALAR_SUBQUERY',
                    'type': 'monotonic_gauge',
                },
                'INDEX_NOT_USED': {'name': 'ClickHouseErrors_INDEX_NOT_USED', 'type': 'monotonic_gauge'},
                'INDEX_OF_POSITIONAL_ARGUMENT_IS_OUT_OF_RANGE': {
                    'name': 'ClickHouseErrors_INDEX_OF_POSITIONAL_ARGUMENT_IS_OUT_OF_RANGE',
                    'type': 'monotonic_gauge',
                },
                'INFINITE_LOOP': {'name': 'ClickHouseErrors_INFINITE_LOOP', 'type': 'monotonic_gauge'},
                'INSECURE_PATH': {'name': 'ClickHouseErrors_INSECURE_PATH', 'type': 'monotonic_gauge'},
                'INSERT_WAS_DEDUPLICATED': {
                    'name': 'ClickHouseErrors_INSERT_WAS_DEDUPLICATED',
                    'type': 'monotonic_gauge',
                },
                'INTERNAL_REDIS_ERROR': {'name': 'ClickHouseErrors_INTERNAL_REDIS_ERROR', 'type': 'monotonic_gauge'},
                'INTERSECT_OR_EXCEPT_RESULT_STRUCTURES_MISMATCH': {
                    'name': 'ClickHouseErrors_INTERSECT_OR_EXCEPT_RESULT_STRUCTURES_MISMATCH',
                    'type': 'monotonic_gauge',
                },
                'INTERSERVER_SCHEME_DOESNT_MATCH': {
                    'name': 'ClickHouseErrors_INTERSERVER_SCHEME_DOESNT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'INTO_OUTFILE_NOT_ALLOWED': {
                    'name': 'ClickHouseErrors_INTO_OUTFILE_NOT_ALLOWED',
                    'type': 'monotonic_gauge',
                },
                'INVALID_CONFIG_PARAMETER': {
                    'name': 'ClickHouseErrors_INVALID_CONFIG_PARAMETER',
                    'type': 'monotonic_gauge',
                },
                'INVALID_FORMAT_INSERT_QUERY_WITH_DATA': {
                    'name': 'ClickHouseErrors_INVALID_FORMAT_INSERT_QUERY_WITH_DATA',
                    'type': 'monotonic_gauge',
                },
                'INVALID_GRANT': {'name': 'ClickHouseErrors_INVALID_GRANT', 'type': 'monotonic_gauge'},
                'INVALID_GRPC_QUERY_INFO': {
                    'name': 'ClickHouseErrors_INVALID_GRPC_QUERY_INFO',
                    'type': 'monotonic_gauge',
                },
                'INVALID_IDENTIFIER': {'name': 'ClickHouseErrors_INVALID_IDENTIFIER', 'type': 'monotonic_gauge'},
                'INVALID_JOIN_ON_EXPRESSION': {
                    'name': 'ClickHouseErrors_INVALID_JOIN_ON_EXPRESSION',
                    'type': 'monotonic_gauge',
                },
                'INVALID_LIMIT_EXPRESSION': {
                    'name': 'ClickHouseErrors_INVALID_LIMIT_EXPRESSION',
                    'type': 'monotonic_gauge',
                },
                'INVALID_PARTITION_VALUE': {
                    'name': 'ClickHouseErrors_INVALID_PARTITION_VALUE',
                    'type': 'monotonic_gauge',
                },
                'INVALID_RAID_TYPE': {'name': 'ClickHouseErrors_INVALID_RAID_TYPE', 'type': 'monotonic_gauge'},
                'INVALID_REDIS_STORAGE_TYPE': {
                    'name': 'ClickHouseErrors_INVALID_REDIS_STORAGE_TYPE',
                    'type': 'monotonic_gauge',
                },
                'INVALID_REDIS_TABLE_STRUCTURE': {
                    'name': 'ClickHouseErrors_INVALID_REDIS_TABLE_STRUCTURE',
                    'type': 'monotonic_gauge',
                },
                'INVALID_SCHEDULER_NODE': {
                    'name': 'ClickHouseErrors_INVALID_SCHEDULER_NODE',
                    'type': 'monotonic_gauge',
                },
                'INVALID_SESSION_TIMEOUT': {
                    'name': 'ClickHouseErrors_INVALID_SESSION_TIMEOUT',
                    'type': 'monotonic_gauge',
                },
                'INVALID_SETTING_VALUE': {'name': 'ClickHouseErrors_INVALID_SETTING_VALUE', 'type': 'monotonic_gauge'},
                'INVALID_SHARD_ID': {'name': 'ClickHouseErrors_INVALID_SHARD_ID', 'type': 'monotonic_gauge'},
                'INVALID_STATE': {'name': 'ClickHouseErrors_INVALID_STATE', 'type': 'monotonic_gauge'},
                'INVALID_TABLE_OVERRIDE': {
                    'name': 'ClickHouseErrors_INVALID_TABLE_OVERRIDE',
                    'type': 'monotonic_gauge',
                },
                'INVALID_TEMPLATE_FORMAT': {
                    'name': 'ClickHouseErrors_INVALID_TEMPLATE_FORMAT',
                    'type': 'monotonic_gauge',
                },
                'INVALID_TRANSACTION': {'name': 'ClickHouseErrors_INVALID_TRANSACTION', 'type': 'monotonic_gauge'},
                'INVALID_USAGE_OF_INPUT': {
                    'name': 'ClickHouseErrors_INVALID_USAGE_OF_INPUT',
                    'type': 'monotonic_gauge',
                },
                'INVALID_WITH_FILL_EXPRESSION': {
                    'name': 'ClickHouseErrors_INVALID_WITH_FILL_EXPRESSION',
                    'type': 'monotonic_gauge',
                },
                'IO_SETUP_ERROR': {'name': 'ClickHouseErrors_IO_SETUP_ERROR', 'type': 'monotonic_gauge'},
                'IO_URING_INIT_FAILED': {'name': 'ClickHouseErrors_IO_URING_INIT_FAILED', 'type': 'monotonic_gauge'},
                'IO_URING_SUBMIT_ERROR': {'name': 'ClickHouseErrors_IO_URING_SUBMIT_ERROR', 'type': 'monotonic_gauge'},
                'IP_ADDRESS_NOT_ALLOWED': {
                    'name': 'ClickHouseErrors_IP_ADDRESS_NOT_ALLOWED',
                    'type': 'monotonic_gauge',
                },
                'KEEPER_EXCEPTION': {'name': 'ClickHouseErrors_KEEPER_EXCEPTION', 'type': 'monotonic_gauge'},
                'KERBEROS_ERROR': {'name': 'ClickHouseErrors_KERBEROS_ERROR', 'type': 'monotonic_gauge'},
                'LDAP_ERROR': {'name': 'ClickHouseErrors_LDAP_ERROR', 'type': 'monotonic_gauge'},
                'LIBSSH_ERROR': {'name': 'ClickHouseErrors_LIBSSH_ERROR', 'type': 'monotonic_gauge'},
                'LICENSE_EXPIRED': {'name': 'ClickHouseErrors_LICENSE_EXPIRED', 'type': 'monotonic_gauge'},
                'LIMIT_BY_WITH_TIES_IS_NOT_SUPPORTED': {
                    'name': 'ClickHouseErrors_LIMIT_BY_WITH_TIES_IS_NOT_SUPPORTED',
                    'type': 'monotonic_gauge',
                },
                'LIMIT_EXCEEDED': {'name': 'ClickHouseErrors_LIMIT_EXCEEDED', 'type': 'monotonic_gauge'},
                'LOGICAL_ERROR': {'name': 'ClickHouseErrors_LOGICAL_ERROR', 'type': 'monotonic_gauge'},
                'LZ4_DECODER_FAILED': {'name': 'ClickHouseErrors_LZ4_DECODER_FAILED', 'type': 'monotonic_gauge'},
                'LZ4_ENCODER_FAILED': {'name': 'ClickHouseErrors_LZ4_ENCODER_FAILED', 'type': 'monotonic_gauge'},
                'LZMA_STREAM_DECODER_FAILED': {
                    'name': 'ClickHouseErrors_LZMA_STREAM_DECODER_FAILED',
                    'type': 'monotonic_gauge',
                },
                'LZMA_STREAM_ENCODER_FAILED': {
                    'name': 'ClickHouseErrors_LZMA_STREAM_ENCODER_FAILED',
                    'type': 'monotonic_gauge',
                },
                'MEMORY_LIMIT_EXCEEDED': {'name': 'ClickHouseErrors_MEMORY_LIMIT_EXCEEDED', 'type': 'monotonic_gauge'},
                'METADATA_MISMATCH': {'name': 'ClickHouseErrors_METADATA_MISMATCH', 'type': 'monotonic_gauge'},
                'MISMATCHING_USERS_FOR_PROCESS_AND_DATA': {
                    'name': 'ClickHouseErrors_MISMATCHING_USERS_FOR_PROCESS_AND_DATA',
                    'type': 'monotonic_gauge',
                },
                'MISMATCH_REPLICAS_DATA_SOURCES': {
                    'name': 'ClickHouseErrors_MISMATCH_REPLICAS_DATA_SOURCES',
                    'type': 'monotonic_gauge',
                },
                'MIXED_ACCESS_PARAMETER_TYPES': {
                    'name': 'ClickHouseErrors_MIXED_ACCESS_PARAMETER_TYPES',
                    'type': 'monotonic_gauge',
                },
                'MONGODB_CANNOT_AUTHENTICATE': {
                    'name': 'ClickHouseErrors_MONGODB_CANNOT_AUTHENTICATE',
                    'type': 'monotonic_gauge',
                },
                'MONGODB_ERROR': {'name': 'ClickHouseErrors_MONGODB_ERROR', 'type': 'monotonic_gauge'},
                'MULTIPLE_ASSIGNMENTS_TO_COLUMN': {
                    'name': 'ClickHouseErrors_MULTIPLE_ASSIGNMENTS_TO_COLUMN',
                    'type': 'monotonic_gauge',
                },
                'MULTIPLE_COLUMNS_SERIALIZED_TO_SAME_PROTOBUF_FIELD': {
                    'name': 'ClickHouseErrors_MULTIPLE_COLUMNS_SERIALIZED_TO_SAME_PROTOBUF_FIELD',
                    'type': 'monotonic_gauge',
                },
                'MULTIPLE_EXPRESSIONS_FOR_ALIAS': {
                    'name': 'ClickHouseErrors_MULTIPLE_EXPRESSIONS_FOR_ALIAS',
                    'type': 'monotonic_gauge',
                },
                'MULTIPLE_STREAMS_REQUIRED': {
                    'name': 'ClickHouseErrors_MULTIPLE_STREAMS_REQUIRED',
                    'type': 'monotonic_gauge',
                },
                'MYSQL_CLIENT_INSUFFICIENT_CAPABILITIES': {
                    'name': 'ClickHouseErrors_MYSQL_CLIENT_INSUFFICIENT_CAPABILITIES',
                    'type': 'monotonic_gauge',
                },
                'MYSQL_SYNTAX_ERROR': {'name': 'ClickHouseErrors_MYSQL_SYNTAX_ERROR', 'type': 'monotonic_gauge'},
                'NAMED_COLLECTION_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_NAMED_COLLECTION_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'NAMED_COLLECTION_DOESNT_EXIST': {
                    'name': 'ClickHouseErrors_NAMED_COLLECTION_DOESNT_EXIST',
                    'type': 'monotonic_gauge',
                },
                'NAMED_COLLECTION_IS_IMMUTABLE': {
                    'name': 'ClickHouseErrors_NAMED_COLLECTION_IS_IMMUTABLE',
                    'type': 'monotonic_gauge',
                },
                'NETLINK_ERROR': {'name': 'ClickHouseErrors_NETLINK_ERROR', 'type': 'monotonic_gauge'},
                'NETWORK_ERROR': {'name': 'ClickHouseErrors_NETWORK_ERROR', 'type': 'monotonic_gauge'},
                'NOT_AN_AGGREGATE': {'name': 'ClickHouseErrors_NOT_AN_AGGREGATE', 'type': 'monotonic_gauge'},
                'NOT_A_LEADER': {'name': 'ClickHouseErrors_NOT_A_LEADER', 'type': 'monotonic_gauge'},
                'NOT_ENOUGH_SPACE': {'name': 'ClickHouseErrors_NOT_ENOUGH_SPACE', 'type': 'monotonic_gauge'},
                'NOT_FOUND_COLUMN_IN_BLOCK': {
                    'name': 'ClickHouseErrors_NOT_FOUND_COLUMN_IN_BLOCK',
                    'type': 'monotonic_gauge',
                },
                'NOT_FOUND_EXPECTED_DATA_PART': {
                    'name': 'ClickHouseErrors_NOT_FOUND_EXPECTED_DATA_PART',
                    'type': 'monotonic_gauge',
                },
                'NOT_FOUND_NODE': {'name': 'ClickHouseErrors_NOT_FOUND_NODE', 'type': 'monotonic_gauge'},
                'NOT_IMPLEMENTED': {'name': 'ClickHouseErrors_NOT_IMPLEMENTED', 'type': 'monotonic_gauge'},
                'NOT_INITIALIZED': {'name': 'ClickHouseErrors_NOT_INITIALIZED', 'type': 'monotonic_gauge'},
                'NO_ACTIVE_REPLICAS': {'name': 'ClickHouseErrors_NO_ACTIVE_REPLICAS', 'type': 'monotonic_gauge'},
                'NO_AVAILABLE_DATA': {'name': 'ClickHouseErrors_NO_AVAILABLE_DATA', 'type': 'monotonic_gauge'},
                'NO_AVAILABLE_REPLICA': {'name': 'ClickHouseErrors_NO_AVAILABLE_REPLICA', 'type': 'monotonic_gauge'},
                'NO_BASE_BACKUP': {'name': 'ClickHouseErrors_NO_BASE_BACKUP', 'type': 'monotonic_gauge'},
                'NO_COLUMNS_SERIALIZED_TO_PROTOBUF_FIELDS': {
                    'name': 'ClickHouseErrors_NO_COLUMNS_SERIALIZED_TO_PROTOBUF_FIELDS',
                    'type': 'monotonic_gauge',
                },
                'NO_COLUMN_SERIALIZED_TO_REQUIRED_PROTOBUF_FIELD': {
                    'name': 'ClickHouseErrors_NO_COLUMN_SERIALIZED_TO_REQUIRED_PROTOBUF_FIELD',
                    'type': 'monotonic_gauge',
                },
                'NO_COMMON_TYPE': {'name': 'ClickHouseErrors_NO_COMMON_TYPE', 'type': 'monotonic_gauge'},
                'NO_DATA_TO_INSERT': {'name': 'ClickHouseErrors_NO_DATA_TO_INSERT', 'type': 'monotonic_gauge'},
                'NO_ELEMENTS_IN_CONFIG': {'name': 'ClickHouseErrors_NO_ELEMENTS_IN_CONFIG', 'type': 'monotonic_gauge'},
                'NO_FILE_IN_DATA_PART': {'name': 'ClickHouseErrors_NO_FILE_IN_DATA_PART', 'type': 'monotonic_gauge'},
                'NO_FREE_CONNECTION': {'name': 'ClickHouseErrors_NO_FREE_CONNECTION', 'type': 'monotonic_gauge'},
                'NO_HIVEMETASTORE': {'name': 'ClickHouseErrors_NO_HIVEMETASTORE', 'type': 'monotonic_gauge'},
                'NO_REMOTE_SHARD_AVAILABLE': {
                    'name': 'ClickHouseErrors_NO_REMOTE_SHARD_AVAILABLE',
                    'type': 'monotonic_gauge',
                },
                'NO_REPLICA_HAS_PART': {'name': 'ClickHouseErrors_NO_REPLICA_HAS_PART', 'type': 'monotonic_gauge'},
                'NO_REPLICA_NAME_GIVEN': {'name': 'ClickHouseErrors_NO_REPLICA_NAME_GIVEN', 'type': 'monotonic_gauge'},
                'NO_ROW_DELIMITER': {'name': 'ClickHouseErrors_NO_ROW_DELIMITER', 'type': 'monotonic_gauge'},
                'NO_SUCH_COLUMN_IN_TABLE': {
                    'name': 'ClickHouseErrors_NO_SUCH_COLUMN_IN_TABLE',
                    'type': 'monotonic_gauge',
                },
                'NO_SUCH_DATA_PART': {'name': 'ClickHouseErrors_NO_SUCH_DATA_PART', 'type': 'monotonic_gauge'},
                'NO_SUCH_ERROR_CODE': {'name': 'ClickHouseErrors_NO_SUCH_ERROR_CODE', 'type': 'monotonic_gauge'},
                'NO_SUCH_INTERSERVER_IO_ENDPOINT': {
                    'name': 'ClickHouseErrors_NO_SUCH_INTERSERVER_IO_ENDPOINT',
                    'type': 'monotonic_gauge',
                },
                'NO_SUCH_PROJECTION_IN_TABLE': {
                    'name': 'ClickHouseErrors_NO_SUCH_PROJECTION_IN_TABLE',
                    'type': 'monotonic_gauge',
                },
                'NO_SUCH_REPLICA': {'name': 'ClickHouseErrors_NO_SUCH_REPLICA', 'type': 'monotonic_gauge'},
                'NO_SUITABLE_FUNCTION_IMPLEMENTATION': {
                    'name': 'ClickHouseErrors_NO_SUITABLE_FUNCTION_IMPLEMENTATION',
                    'type': 'monotonic_gauge',
                },
                'NO_ZOOKEEPER': {'name': 'ClickHouseErrors_NO_ZOOKEEPER', 'type': 'monotonic_gauge'},
                'NUMBER_OF_ARGUMENTS_DOESNT_MATCH': {
                    'name': 'ClickHouseErrors_NUMBER_OF_ARGUMENTS_DOESNT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'NUMBER_OF_COLUMNS_DOESNT_MATCH': {
                    'name': 'ClickHouseErrors_NUMBER_OF_COLUMNS_DOESNT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'NUMBER_OF_DIMENSIONS_MISMATCHED': {
                    'name': 'ClickHouseErrors_NUMBER_OF_DIMENSIONS_MISMATCHED',
                    'type': 'monotonic_gauge',
                },
                'OFFSET_FETCH_WITHOUT_ORDER_BY': {
                    'name': 'ClickHouseErrors_OFFSET_FETCH_WITHOUT_ORDER_BY',
                    'type': 'monotonic_gauge',
                },
                'OK': {'name': 'ClickHouseErrors_OK', 'type': 'monotonic_gauge'},
                'ONLY_NULLS_WHILE_READING_SCHEMA': {
                    'name': 'ClickHouseErrors_ONLY_NULLS_WHILE_READING_SCHEMA',
                    'type': 'monotonic_gauge',
                },
                'OPENSSL_ERROR': {'name': 'ClickHouseErrors_OPENSSL_ERROR', 'type': 'monotonic_gauge'},
                'PARAMETERS_TO_AGGREGATE_FUNCTIONS_MUST_BE_LITERALS': {
                    'name': 'ClickHouseErrors_PARAMETERS_TO_AGGREGATE_FUNCTIONS_MUST_BE_LITERALS',
                    'type': 'monotonic_gauge',
                },
                'PARAMETER_OUT_OF_BOUND': {
                    'name': 'ClickHouseErrors_PARAMETER_OUT_OF_BOUND',
                    'type': 'monotonic_gauge',
                },
                'PARQUET_EXCEPTION': {'name': 'ClickHouseErrors_PARQUET_EXCEPTION', 'type': 'monotonic_gauge'},
                'PARTITION_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_PARTITION_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'PARTITION_DOESNT_EXIST': {
                    'name': 'ClickHouseErrors_PARTITION_DOESNT_EXIST',
                    'type': 'monotonic_gauge',
                },
                'PART_IS_LOCKED': {'name': 'ClickHouseErrors_PART_IS_LOCKED', 'type': 'monotonic_gauge'},
                'PART_IS_TEMPORARILY_LOCKED': {
                    'name': 'ClickHouseErrors_PART_IS_TEMPORARILY_LOCKED',
                    'type': 'monotonic_gauge',
                },
                'PATH_ACCESS_DENIED': {'name': 'ClickHouseErrors_PATH_ACCESS_DENIED', 'type': 'monotonic_gauge'},
                'POCO_EXCEPTION': {'name': 'ClickHouseErrors_POCO_EXCEPTION', 'type': 'monotonic_gauge'},
                'POSITION_OUT_OF_BOUND': {'name': 'ClickHouseErrors_POSITION_OUT_OF_BOUND', 'type': 'monotonic_gauge'},
                'POSTGRESQL_CONNECTION_FAILURE': {
                    'name': 'ClickHouseErrors_POSTGRESQL_CONNECTION_FAILURE',
                    'type': 'monotonic_gauge',
                },
                'POSTGRESQL_REPLICATION_INTERNAL_ERROR': {
                    'name': 'ClickHouseErrors_POSTGRESQL_REPLICATION_INTERNAL_ERROR',
                    'type': 'monotonic_gauge',
                },
                'POTENTIALLY_BROKEN_DATA_PART': {
                    'name': 'ClickHouseErrors_POTENTIALLY_BROKEN_DATA_PART',
                    'type': 'monotonic_gauge',
                },
                'PROJECTION_NOT_USED': {'name': 'ClickHouseErrors_PROJECTION_NOT_USED', 'type': 'monotonic_gauge'},
                'PROTOBUF_BAD_CAST': {'name': 'ClickHouseErrors_PROTOBUF_BAD_CAST', 'type': 'monotonic_gauge'},
                'PROTOBUF_FIELD_NOT_REPEATED': {
                    'name': 'ClickHouseErrors_PROTOBUF_FIELD_NOT_REPEATED',
                    'type': 'monotonic_gauge',
                },
                'PROTOCOL_VERSION_MISMATCH': {
                    'name': 'ClickHouseErrors_PROTOCOL_VERSION_MISMATCH',
                    'type': 'monotonic_gauge',
                },
                'PTHREAD_ERROR': {'name': 'ClickHouseErrors_PTHREAD_ERROR', 'type': 'monotonic_gauge'},
                'QUERY_CACHE_USED_WITH_NONDETERMINISTIC_FUNCTIONS': {
                    'name': 'ClickHouseErrors_QUERY_CACHE_USED_WITH_NONDETERMINISTIC_FUNCTIONS',
                    'type': 'monotonic_gauge',
                },
                'QUERY_CACHE_USED_WITH_NON_THROW_OVERFLOW_MODE': {
                    'name': 'ClickHouseErrors_QUERY_CACHE_USED_WITH_NON_THROW_OVERFLOW_MODE',
                    'type': 'monotonic_gauge',
                },
                'QUERY_CACHE_USED_WITH_SYSTEM_TABLE': {
                    'name': 'ClickHouseErrors_QUERY_CACHE_USED_WITH_SYSTEM_TABLE',
                    'type': 'monotonic_gauge',
                },
                'QUERY_IS_NOT_SUPPORTED_IN_MATERIALIZED_VIEW': {
                    'name': 'ClickHouseErrors_QUERY_IS_NOT_SUPPORTED_IN_MATERIALIZED_VIEW',
                    'type': 'monotonic_gauge',
                },
                'QUERY_IS_NOT_SUPPORTED_IN_WINDOW_VIEW': {
                    'name': 'ClickHouseErrors_QUERY_IS_NOT_SUPPORTED_IN_WINDOW_VIEW',
                    'type': 'monotonic_gauge',
                },
                'QUERY_IS_PROHIBITED': {'name': 'ClickHouseErrors_QUERY_IS_PROHIBITED', 'type': 'monotonic_gauge'},
                'QUERY_IS_TOO_LARGE': {'name': 'ClickHouseErrors_QUERY_IS_TOO_LARGE', 'type': 'monotonic_gauge'},
                'QUERY_NOT_ALLOWED': {'name': 'ClickHouseErrors_QUERY_NOT_ALLOWED', 'type': 'monotonic_gauge'},
                'QUERY_WAS_CANCELLED': {'name': 'ClickHouseErrors_QUERY_WAS_CANCELLED', 'type': 'monotonic_gauge'},
                'QUERY_WAS_CANCELLED_BY_CLIENT': {
                    'name': 'ClickHouseErrors_QUERY_WAS_CANCELLED_BY_CLIENT',
                    'type': 'monotonic_gauge',
                },
                'QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING': {
                    'name': 'ClickHouseErrors_QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING',
                    'type': 'monotonic_gauge',
                },
                'QUOTA_EXCEEDED': {'name': 'ClickHouseErrors_QUOTA_EXCEEDED', 'type': 'monotonic_gauge'},
                'QUOTA_REQUIRES_CLIENT_KEY': {
                    'name': 'ClickHouseErrors_QUOTA_REQUIRES_CLIENT_KEY',
                    'type': 'monotonic_gauge',
                },
                'RAFT_ERROR': {'name': 'ClickHouseErrors_RAFT_ERROR', 'type': 'monotonic_gauge'},
                'READONLY': {'name': 'ClickHouseErrors_READONLY', 'type': 'monotonic_gauge'},
                'READONLY_SETTING': {'name': 'ClickHouseErrors_READONLY_SETTING', 'type': 'monotonic_gauge'},
                'RECEIVED_EMPTY_DATA': {'name': 'ClickHouseErrors_RECEIVED_EMPTY_DATA', 'type': 'monotonic_gauge'},
                'RECEIVED_ERROR_FROM_REMOTE_IO_SERVER': {
                    'name': 'ClickHouseErrors_RECEIVED_ERROR_FROM_REMOTE_IO_SERVER',
                    'type': 'monotonic_gauge',
                },
                'RECEIVED_ERROR_TOO_MANY_REQUESTS': {
                    'name': 'ClickHouseErrors_RECEIVED_ERROR_TOO_MANY_REQUESTS',
                    'type': 'monotonic_gauge',
                },
                'REFRESH_FAILED': {'name': 'ClickHouseErrors_REFRESH_FAILED', 'type': 'monotonic_gauge'},
                'REPLICA_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_REPLICA_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'REPLICA_IS_ALREADY_ACTIVE': {
                    'name': 'ClickHouseErrors_REPLICA_IS_ALREADY_ACTIVE',
                    'type': 'monotonic_gauge',
                },
                'REPLICA_IS_NOT_IN_QUORUM': {
                    'name': 'ClickHouseErrors_REPLICA_IS_NOT_IN_QUORUM',
                    'type': 'monotonic_gauge',
                },
                'REPLICA_STATUS_CHANGED': {
                    'name': 'ClickHouseErrors_REPLICA_STATUS_CHANGED',
                    'type': 'monotonic_gauge',
                },
                'REQUIRED_PASSWORD': {'name': 'ClickHouseErrors_REQUIRED_PASSWORD', 'type': 'monotonic_gauge'},
                'RESOURCE_ACCESS_DENIED': {
                    'name': 'ClickHouseErrors_RESOURCE_ACCESS_DENIED',
                    'type': 'monotonic_gauge',
                },
                'RESOURCE_NOT_FOUND': {'name': 'ClickHouseErrors_RESOURCE_NOT_FOUND', 'type': 'monotonic_gauge'},
                'ROCKSDB_ERROR': {'name': 'ClickHouseErrors_ROCKSDB_ERROR', 'type': 'monotonic_gauge'},
                'ROW_AND_ROWS_TOGETHER': {'name': 'ClickHouseErrors_ROW_AND_ROWS_TOGETHER', 'type': 'monotonic_gauge'},
                'S3_ERROR': {'name': 'ClickHouseErrors_S3_ERROR', 'type': 'monotonic_gauge'},
                'SAMPLING_NOT_SUPPORTED': {
                    'name': 'ClickHouseErrors_SAMPLING_NOT_SUPPORTED',
                    'type': 'monotonic_gauge',
                },
                'SEEK_POSITION_OUT_OF_BOUND': {
                    'name': 'ClickHouseErrors_SEEK_POSITION_OUT_OF_BOUND',
                    'type': 'monotonic_gauge',
                },
                'SERIALIZATION_ERROR': {'name': 'ClickHouseErrors_SERIALIZATION_ERROR', 'type': 'monotonic_gauge'},
                'SERVER_OVERLOADED': {'name': 'ClickHouseErrors_SERVER_OVERLOADED', 'type': 'monotonic_gauge'},
                'SESSION_ID_EMPTY': {'name': 'ClickHouseErrors_SESSION_ID_EMPTY', 'type': 'monotonic_gauge'},
                'SESSION_IS_LOCKED': {'name': 'ClickHouseErrors_SESSION_IS_LOCKED', 'type': 'monotonic_gauge'},
                'SESSION_NOT_FOUND': {'name': 'ClickHouseErrors_SESSION_NOT_FOUND', 'type': 'monotonic_gauge'},
                'SETTING_CONSTRAINT_VIOLATION': {
                    'name': 'ClickHouseErrors_SETTING_CONSTRAINT_VIOLATION',
                    'type': 'monotonic_gauge',
                },
                'SET_NON_GRANTED_ROLE': {'name': 'ClickHouseErrors_SET_NON_GRANTED_ROLE', 'type': 'monotonic_gauge'},
                'SET_SIZE_LIMIT_EXCEEDED': {
                    'name': 'ClickHouseErrors_SET_SIZE_LIMIT_EXCEEDED',
                    'type': 'monotonic_gauge',
                },
                'SHARD_HAS_NO_CONNECTIONS': {
                    'name': 'ClickHouseErrors_SHARD_HAS_NO_CONNECTIONS',
                    'type': 'monotonic_gauge',
                },
                'SIZES_OF_ARRAYS_DONT_MATCH': {
                    'name': 'ClickHouseErrors_SIZES_OF_ARRAYS_DONT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'SIZES_OF_COLUMNS_DOESNT_MATCH': {
                    'name': 'ClickHouseErrors_SIZES_OF_COLUMNS_DOESNT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'SIZES_OF_COLUMNS_IN_TUPLE_DOESNT_MATCH': {
                    'name': 'ClickHouseErrors_SIZES_OF_COLUMNS_IN_TUPLE_DOESNT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'SIZES_OF_MARKS_FILES_ARE_INCONSISTENT': {
                    'name': 'ClickHouseErrors_SIZES_OF_MARKS_FILES_ARE_INCONSISTENT',
                    'type': 'monotonic_gauge',
                },
                'SIZES_OF_NESTED_COLUMNS_ARE_INCONSISTENT': {
                    'name': 'ClickHouseErrors_SIZES_OF_NESTED_COLUMNS_ARE_INCONSISTENT',
                    'type': 'monotonic_gauge',
                },
                'SIZE_OF_FIXED_STRING_DOESNT_MATCH': {
                    'name': 'ClickHouseErrors_SIZE_OF_FIXED_STRING_DOESNT_MATCH',
                    'type': 'monotonic_gauge',
                },
                'SNAPPY_COMPRESS_FAILED': {
                    'name': 'ClickHouseErrors_SNAPPY_COMPRESS_FAILED',
                    'type': 'monotonic_gauge',
                },
                'SNAPPY_UNCOMPRESS_FAILED': {
                    'name': 'ClickHouseErrors_SNAPPY_UNCOMPRESS_FAILED',
                    'type': 'monotonic_gauge',
                },
                'SOCKET_TIMEOUT': {'name': 'ClickHouseErrors_SOCKET_TIMEOUT', 'type': 'monotonic_gauge'},
                'SQLITE_ENGINE_ERROR': {'name': 'ClickHouseErrors_SQLITE_ENGINE_ERROR', 'type': 'monotonic_gauge'},
                'SSH_EXCEPTION': {'name': 'ClickHouseErrors_SSH_EXCEPTION', 'type': 'monotonic_gauge'},
                'STARTUP_SCRIPTS_ERROR': {'name': 'ClickHouseErrors_STARTUP_SCRIPTS_ERROR', 'type': 'monotonic_gauge'},
                'STD_EXCEPTION': {'name': 'ClickHouseErrors_STD_EXCEPTION', 'type': 'monotonic_gauge'},
                'STORAGE_REQUIRES_PARAMETER': {
                    'name': 'ClickHouseErrors_STORAGE_REQUIRES_PARAMETER',
                    'type': 'monotonic_gauge',
                },
                'SUPPORT_IS_DISABLED': {'name': 'ClickHouseErrors_SUPPORT_IS_DISABLED', 'type': 'monotonic_gauge'},
                'SUSPICIOUS_TYPE_FOR_LOW_CARDINALITY': {
                    'name': 'ClickHouseErrors_SUSPICIOUS_TYPE_FOR_LOW_CARDINALITY',
                    'type': 'monotonic_gauge',
                },
                'SYNC_MYSQL_USER_ACCESS_ERROR': {
                    'name': 'ClickHouseErrors_SYNC_MYSQL_USER_ACCESS_ERROR',
                    'type': 'monotonic_gauge',
                },
                'SYNTAX_ERROR': {'name': 'ClickHouseErrors_SYNTAX_ERROR', 'type': 'monotonic_gauge'},
                'SYSTEM_ERROR': {'name': 'ClickHouseErrors_SYSTEM_ERROR', 'type': 'monotonic_gauge'},
                'TABLE_ALREADY_EXISTS': {'name': 'ClickHouseErrors_TABLE_ALREADY_EXISTS', 'type': 'monotonic_gauge'},
                'TABLE_DIFFERS_TOO_MUCH': {
                    'name': 'ClickHouseErrors_TABLE_DIFFERS_TOO_MUCH',
                    'type': 'monotonic_gauge',
                },
                'TABLE_IS_BEING_RESTARTED': {
                    'name': 'ClickHouseErrors_TABLE_IS_BEING_RESTARTED',
                    'type': 'monotonic_gauge',
                },
                'TABLE_IS_DROPPED': {'name': 'ClickHouseErrors_TABLE_IS_DROPPED', 'type': 'monotonic_gauge'},
                'TABLE_IS_READ_ONLY': {'name': 'ClickHouseErrors_TABLE_IS_READ_ONLY', 'type': 'monotonic_gauge'},
                'TABLE_METADATA_ALREADY_EXISTS': {
                    'name': 'ClickHouseErrors_TABLE_METADATA_ALREADY_EXISTS',
                    'type': 'monotonic_gauge',
                },
                'TABLE_NOT_EMPTY': {'name': 'ClickHouseErrors_TABLE_NOT_EMPTY', 'type': 'monotonic_gauge'},
                'TABLE_SIZE_EXCEEDS_MAX_DROP_SIZE_LIMIT': {
                    'name': 'ClickHouseErrors_TABLE_SIZE_EXCEEDS_MAX_DROP_SIZE_LIMIT',
                    'type': 'monotonic_gauge',
                },
                'TABLE_UUID_MISMATCH': {'name': 'ClickHouseErrors_TABLE_UUID_MISMATCH', 'type': 'monotonic_gauge'},
                'TABLE_WAS_NOT_DROPPED': {'name': 'ClickHouseErrors_TABLE_WAS_NOT_DROPPED', 'type': 'monotonic_gauge'},
                'TCP_CONNECTION_LIMIT_REACHED': {
                    'name': 'ClickHouseErrors_TCP_CONNECTION_LIMIT_REACHED',
                    'type': 'monotonic_gauge',
                },
                'THERE_IS_NO_COLUMN': {'name': 'ClickHouseErrors_THERE_IS_NO_COLUMN', 'type': 'monotonic_gauge'},
                'THERE_IS_NO_DEFAULT_VALUE': {
                    'name': 'ClickHouseErrors_THERE_IS_NO_DEFAULT_VALUE',
                    'type': 'monotonic_gauge',
                },
                'THERE_IS_NO_PROFILE': {'name': 'ClickHouseErrors_THERE_IS_NO_PROFILE', 'type': 'monotonic_gauge'},
                'THERE_IS_NO_QUERY': {'name': 'ClickHouseErrors_THERE_IS_NO_QUERY', 'type': 'monotonic_gauge'},
                'THERE_IS_NO_SESSION': {'name': 'ClickHouseErrors_THERE_IS_NO_SESSION', 'type': 'monotonic_gauge'},
                'THREAD_WAS_CANCELED': {'name': 'ClickHouseErrors_THREAD_WAS_CANCELED', 'type': 'monotonic_gauge'},
                'TIMEOUT_EXCEEDED': {'name': 'ClickHouseErrors_TIMEOUT_EXCEEDED', 'type': 'monotonic_gauge'},
                'TLD_LIST_NOT_FOUND': {'name': 'ClickHouseErrors_TLD_LIST_NOT_FOUND', 'type': 'monotonic_gauge'},
                'TOO_BIG_AST': {'name': 'ClickHouseErrors_TOO_BIG_AST', 'type': 'monotonic_gauge'},
                'TOO_DEEP_AST': {'name': 'ClickHouseErrors_TOO_DEEP_AST', 'type': 'monotonic_gauge'},
                'TOO_DEEP_RECURSION': {'name': 'ClickHouseErrors_TOO_DEEP_RECURSION', 'type': 'monotonic_gauge'},
                'TOO_DEEP_SUBQUERIES': {'name': 'ClickHouseErrors_TOO_DEEP_SUBQUERIES', 'type': 'monotonic_gauge'},
                'TOO_FEW_ARGUMENTS_FOR_FUNCTION': {
                    'name': 'ClickHouseErrors_TOO_FEW_ARGUMENTS_FOR_FUNCTION',
                    'type': 'monotonic_gauge',
                },
                'TOO_FEW_LIVE_REPLICAS': {'name': 'ClickHouseErrors_TOO_FEW_LIVE_REPLICAS', 'type': 'monotonic_gauge'},
                'TOO_LARGE_ARRAY_SIZE': {'name': 'ClickHouseErrors_TOO_LARGE_ARRAY_SIZE', 'type': 'monotonic_gauge'},
                'TOO_LARGE_DISTRIBUTED_DEPTH': {
                    'name': 'ClickHouseErrors_TOO_LARGE_DISTRIBUTED_DEPTH',
                    'type': 'monotonic_gauge',
                },
                'TOO_LARGE_LIGHTWEIGHT_UPDATES': {
                    'name': 'ClickHouseErrors_TOO_LARGE_LIGHTWEIGHT_UPDATES',
                    'type': 'monotonic_gauge',
                },
                'TOO_LARGE_SIZE_COMPRESSED': {
                    'name': 'ClickHouseErrors_TOO_LARGE_SIZE_COMPRESSED',
                    'type': 'monotonic_gauge',
                },
                'TOO_LARGE_STRING_SIZE': {'name': 'ClickHouseErrors_TOO_LARGE_STRING_SIZE', 'type': 'monotonic_gauge'},
                'TOO_MANY_ARGUMENTS_FOR_FUNCTION': {
                    'name': 'ClickHouseErrors_TOO_MANY_ARGUMENTS_FOR_FUNCTION',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_BYTES': {'name': 'ClickHouseErrors_TOO_MANY_BYTES', 'type': 'monotonic_gauge'},
                'TOO_MANY_COLUMNS': {'name': 'ClickHouseErrors_TOO_MANY_COLUMNS', 'type': 'monotonic_gauge'},
                'TOO_MANY_DATABASES': {'name': 'ClickHouseErrors_TOO_MANY_DATABASES', 'type': 'monotonic_gauge'},
                'TOO_MANY_MATERIALIZED_VIEWS': {
                    'name': 'ClickHouseErrors_TOO_MANY_MATERIALIZED_VIEWS',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_MUTATIONS': {'name': 'ClickHouseErrors_TOO_MANY_MUTATIONS', 'type': 'monotonic_gauge'},
                'TOO_MANY_PARTITIONS': {'name': 'ClickHouseErrors_TOO_MANY_PARTITIONS', 'type': 'monotonic_gauge'},
                'TOO_MANY_PARTS': {'name': 'ClickHouseErrors_TOO_MANY_PARTS', 'type': 'monotonic_gauge'},
                'TOO_MANY_QUERY_PLAN_OPTIMIZATIONS': {
                    'name': 'ClickHouseErrors_TOO_MANY_QUERY_PLAN_OPTIMIZATIONS',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_REDIRECTS': {'name': 'ClickHouseErrors_TOO_MANY_REDIRECTS', 'type': 'monotonic_gauge'},
                'TOO_MANY_RETRIES_TO_FETCH_PARTS': {
                    'name': 'ClickHouseErrors_TOO_MANY_RETRIES_TO_FETCH_PARTS',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_ROWS': {'name': 'ClickHouseErrors_TOO_MANY_ROWS', 'type': 'monotonic_gauge'},
                'TOO_MANY_ROWS_OR_BYTES': {
                    'name': 'ClickHouseErrors_TOO_MANY_ROWS_OR_BYTES',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_SIMULTANEOUS_QUERIES': {
                    'name': 'ClickHouseErrors_TOO_MANY_SIMULTANEOUS_QUERIES',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_TABLES': {'name': 'ClickHouseErrors_TOO_MANY_TABLES', 'type': 'monotonic_gauge'},
                'TOO_MANY_TEMPORARY_COLUMNS': {
                    'name': 'ClickHouseErrors_TOO_MANY_TEMPORARY_COLUMNS',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_TEMPORARY_NON_CONST_COLUMNS': {
                    'name': 'ClickHouseErrors_TOO_MANY_TEMPORARY_NON_CONST_COLUMNS',
                    'type': 'monotonic_gauge',
                },
                'TOO_MANY_UNEXPECTED_DATA_PARTS': {
                    'name': 'ClickHouseErrors_TOO_MANY_UNEXPECTED_DATA_PARTS',
                    'type': 'monotonic_gauge',
                },
                'TOO_SLOW': {'name': 'ClickHouseErrors_TOO_SLOW', 'type': 'monotonic_gauge'},
                'TOO_SLOW_PARSING': {'name': 'ClickHouseErrors_TOO_SLOW_PARSING', 'type': 'monotonic_gauge'},
                'TOO_SMALL_BUFFER_SIZE': {'name': 'ClickHouseErrors_TOO_SMALL_BUFFER_SIZE', 'type': 'monotonic_gauge'},
                'TOP_AND_LIMIT_TOGETHER': {
                    'name': 'ClickHouseErrors_TOP_AND_LIMIT_TOGETHER',
                    'type': 'monotonic_gauge',
                },
                'TYPE_MISMATCH': {'name': 'ClickHouseErrors_TYPE_MISMATCH', 'type': 'monotonic_gauge'},
                'UDF_EXECUTION_FAILED': {'name': 'ClickHouseErrors_UDF_EXECUTION_FAILED', 'type': 'monotonic_gauge'},
                'UNABLE_TO_SKIP_UNUSED_SHARDS': {
                    'name': 'ClickHouseErrors_UNABLE_TO_SKIP_UNUSED_SHARDS',
                    'type': 'monotonic_gauge',
                },
                'UNACCEPTABLE_URL': {'name': 'ClickHouseErrors_UNACCEPTABLE_URL', 'type': 'monotonic_gauge'},
                'UNEXPECTED_AST_STRUCTURE': {
                    'name': 'ClickHouseErrors_UNEXPECTED_AST_STRUCTURE',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_CLUSTER': {'name': 'ClickHouseErrors_UNEXPECTED_CLUSTER', 'type': 'monotonic_gauge'},
                'UNEXPECTED_DATA_AFTER_PARSED_VALUE': {
                    'name': 'ClickHouseErrors_UNEXPECTED_DATA_AFTER_PARSED_VALUE',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_DATA_TYPE': {'name': 'ClickHouseErrors_UNEXPECTED_DATA_TYPE', 'type': 'monotonic_gauge'},
                'UNEXPECTED_END_OF_FILE': {
                    'name': 'ClickHouseErrors_UNEXPECTED_END_OF_FILE',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_EXPRESSION': {'name': 'ClickHouseErrors_UNEXPECTED_EXPRESSION', 'type': 'monotonic_gauge'},
                'UNEXPECTED_FILE_IN_DATA_PART': {
                    'name': 'ClickHouseErrors_UNEXPECTED_FILE_IN_DATA_PART',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_HTTP_HEADERS': {
                    'name': 'ClickHouseErrors_UNEXPECTED_HTTP_HEADERS',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_NODE_IN_ZOOKEEPER': {
                    'name': 'ClickHouseErrors_UNEXPECTED_NODE_IN_ZOOKEEPER',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_PACKET_FROM_CLIENT': {
                    'name': 'ClickHouseErrors_UNEXPECTED_PACKET_FROM_CLIENT',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_PACKET_FROM_SERVER': {
                    'name': 'ClickHouseErrors_UNEXPECTED_PACKET_FROM_SERVER',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_TABLE_ENGINE': {
                    'name': 'ClickHouseErrors_UNEXPECTED_TABLE_ENGINE',
                    'type': 'monotonic_gauge',
                },
                'UNEXPECTED_ZOOKEEPER_ERROR': {
                    'name': 'ClickHouseErrors_UNEXPECTED_ZOOKEEPER_ERROR',
                    'type': 'monotonic_gauge',
                },
                'UNFINISHED': {'name': 'ClickHouseErrors_UNFINISHED', 'type': 'monotonic_gauge'},
                'UNION_ALL_RESULT_STRUCTURES_MISMATCH': {
                    'name': 'ClickHouseErrors_UNION_ALL_RESULT_STRUCTURES_MISMATCH',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_ACCESS_TYPE': {'name': 'ClickHouseErrors_UNKNOWN_ACCESS_TYPE', 'type': 'monotonic_gauge'},
                'UNKNOWN_ADDRESS_PATTERN_TYPE': {
                    'name': 'ClickHouseErrors_UNKNOWN_ADDRESS_PATTERN_TYPE',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_AGGREGATED_DATA_VARIANT': {
                    'name': 'ClickHouseErrors_UNKNOWN_AGGREGATED_DATA_VARIANT',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_AGGREGATE_FUNCTION': {
                    'name': 'ClickHouseErrors_UNKNOWN_AGGREGATE_FUNCTION',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_BLOCK_INFO_FIELD': {
                    'name': 'ClickHouseErrors_UNKNOWN_BLOCK_INFO_FIELD',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_CODEC': {'name': 'ClickHouseErrors_UNKNOWN_CODEC', 'type': 'monotonic_gauge'},
                'UNKNOWN_COMPRESSION_METHOD': {
                    'name': 'ClickHouseErrors_UNKNOWN_COMPRESSION_METHOD',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_DATABASE': {'name': 'ClickHouseErrors_UNKNOWN_DATABASE', 'type': 'monotonic_gauge'},
                'UNKNOWN_DATABASE_ENGINE': {
                    'name': 'ClickHouseErrors_UNKNOWN_DATABASE_ENGINE',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_DIRECTION_OF_SORTING': {
                    'name': 'ClickHouseErrors_UNKNOWN_DIRECTION_OF_SORTING',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_DISK': {'name': 'ClickHouseErrors_UNKNOWN_DISK', 'type': 'monotonic_gauge'},
                'UNKNOWN_DISTRIBUTED_PRODUCT_MODE': {
                    'name': 'ClickHouseErrors_UNKNOWN_DISTRIBUTED_PRODUCT_MODE',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_ELEMENT_IN_AST': {
                    'name': 'ClickHouseErrors_UNKNOWN_ELEMENT_IN_AST',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_ELEMENT_IN_CONFIG': {
                    'name': 'ClickHouseErrors_UNKNOWN_ELEMENT_IN_CONFIG',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_ELEMENT_OF_ENUM': {
                    'name': 'ClickHouseErrors_UNKNOWN_ELEMENT_OF_ENUM',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_EXCEPTION': {'name': 'ClickHouseErrors_UNKNOWN_EXCEPTION', 'type': 'monotonic_gauge'},
                'UNKNOWN_FILE_SIZE': {'name': 'ClickHouseErrors_UNKNOWN_FILE_SIZE', 'type': 'monotonic_gauge'},
                'UNKNOWN_FORMAT': {'name': 'ClickHouseErrors_UNKNOWN_FORMAT', 'type': 'monotonic_gauge'},
                'UNKNOWN_FORMAT_VERSION': {
                    'name': 'ClickHouseErrors_UNKNOWN_FORMAT_VERSION',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_FUNCTION': {'name': 'ClickHouseErrors_UNKNOWN_FUNCTION', 'type': 'monotonic_gauge'},
                'UNKNOWN_IDENTIFIER': {'name': 'ClickHouseErrors_UNKNOWN_IDENTIFIER', 'type': 'monotonic_gauge'},
                'UNKNOWN_JOIN': {'name': 'ClickHouseErrors_UNKNOWN_JOIN', 'type': 'monotonic_gauge'},
                'UNKNOWN_LOAD_BALANCING': {
                    'name': 'ClickHouseErrors_UNKNOWN_LOAD_BALANCING',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_MUTATION_COMMAND': {
                    'name': 'ClickHouseErrors_UNKNOWN_MUTATION_COMMAND',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_MYSQL_DATATYPES_SUPPORT_LEVEL': {
                    'name': 'ClickHouseErrors_UNKNOWN_MYSQL_DATATYPES_SUPPORT_LEVEL',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_OVERFLOW_MODE': {'name': 'ClickHouseErrors_UNKNOWN_OVERFLOW_MODE', 'type': 'monotonic_gauge'},
                'UNKNOWN_PACKET_FROM_CLIENT': {
                    'name': 'ClickHouseErrors_UNKNOWN_PACKET_FROM_CLIENT',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_PACKET_FROM_SERVER': {
                    'name': 'ClickHouseErrors_UNKNOWN_PACKET_FROM_SERVER',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_PART_TYPE': {'name': 'ClickHouseErrors_UNKNOWN_PART_TYPE', 'type': 'monotonic_gauge'},
                'UNKNOWN_POLICY': {'name': 'ClickHouseErrors_UNKNOWN_POLICY', 'type': 'monotonic_gauge'},
                'UNKNOWN_PROTOBUF_FORMAT': {
                    'name': 'ClickHouseErrors_UNKNOWN_PROTOBUF_FORMAT',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_PROTOCOL': {'name': 'ClickHouseErrors_UNKNOWN_PROTOCOL', 'type': 'monotonic_gauge'},
                'UNKNOWN_QUERY_PARAMETER': {
                    'name': 'ClickHouseErrors_UNKNOWN_QUERY_PARAMETER',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_QUOTA': {'name': 'ClickHouseErrors_UNKNOWN_QUOTA', 'type': 'monotonic_gauge'},
                'UNKNOWN_RAID_TYPE': {'name': 'ClickHouseErrors_UNKNOWN_RAID_TYPE', 'type': 'monotonic_gauge'},
                'UNKNOWN_READ_METHOD': {'name': 'ClickHouseErrors_UNKNOWN_READ_METHOD', 'type': 'monotonic_gauge'},
                'UNKNOWN_ROLE': {'name': 'ClickHouseErrors_UNKNOWN_ROLE', 'type': 'monotonic_gauge'},
                'UNKNOWN_ROW_POLICY': {'name': 'ClickHouseErrors_UNKNOWN_ROW_POLICY', 'type': 'monotonic_gauge'},
                'UNKNOWN_SETTING': {'name': 'ClickHouseErrors_UNKNOWN_SETTING', 'type': 'monotonic_gauge'},
                'UNKNOWN_SNAPSHOT': {'name': 'ClickHouseErrors_UNKNOWN_SNAPSHOT', 'type': 'monotonic_gauge'},
                'UNKNOWN_STATUS_OF_INSERT': {
                    'name': 'ClickHouseErrors_UNKNOWN_STATUS_OF_INSERT',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_STATUS_OF_TRANSACTION': {
                    'name': 'ClickHouseErrors_UNKNOWN_STATUS_OF_TRANSACTION',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_STORAGE': {'name': 'ClickHouseErrors_UNKNOWN_STORAGE', 'type': 'monotonic_gauge'},
                'UNKNOWN_TABLE': {'name': 'ClickHouseErrors_UNKNOWN_TABLE', 'type': 'monotonic_gauge'},
                'UNKNOWN_TOTALS_MODE': {'name': 'ClickHouseErrors_UNKNOWN_TOTALS_MODE', 'type': 'monotonic_gauge'},
                'UNKNOWN_TYPE': {'name': 'ClickHouseErrors_UNKNOWN_TYPE', 'type': 'monotonic_gauge'},
                'UNKNOWN_TYPE_OF_AST_NODE': {
                    'name': 'ClickHouseErrors_UNKNOWN_TYPE_OF_AST_NODE',
                    'type': 'monotonic_gauge',
                },
                'UNKNOWN_TYPE_OF_QUERY': {'name': 'ClickHouseErrors_UNKNOWN_TYPE_OF_QUERY', 'type': 'monotonic_gauge'},
                'UNKNOWN_UNION': {'name': 'ClickHouseErrors_UNKNOWN_UNION', 'type': 'monotonic_gauge'},
                'UNKNOWN_USER': {'name': 'ClickHouseErrors_UNKNOWN_USER', 'type': 'monotonic_gauge'},
                'UNKNOWN_VOLUME': {'name': 'ClickHouseErrors_UNKNOWN_VOLUME', 'type': 'monotonic_gauge'},
                'UNRECOGNIZED_ARGUMENTS': {
                    'name': 'ClickHouseErrors_UNRECOGNIZED_ARGUMENTS',
                    'type': 'monotonic_gauge',
                },
                'UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE': {
                    'name': 'ClickHouseErrors_UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE',
                    'type': 'monotonic_gauge',
                },
                'UNSUPPORTED_COLLATION_LOCALE': {
                    'name': 'ClickHouseErrors_UNSUPPORTED_COLLATION_LOCALE',
                    'type': 'monotonic_gauge',
                },
                'UNSUPPORTED_JOIN_KEYS': {'name': 'ClickHouseErrors_UNSUPPORTED_JOIN_KEYS', 'type': 'monotonic_gauge'},
                'UNSUPPORTED_METHOD': {'name': 'ClickHouseErrors_UNSUPPORTED_METHOD', 'type': 'monotonic_gauge'},
                'UNSUPPORTED_PARAMETER': {'name': 'ClickHouseErrors_UNSUPPORTED_PARAMETER', 'type': 'monotonic_gauge'},
                'UNSUPPORTED_URI_SCHEME': {
                    'name': 'ClickHouseErrors_UNSUPPORTED_URI_SCHEME',
                    'type': 'monotonic_gauge',
                },
                'USER_EXPIRED': {'name': 'ClickHouseErrors_USER_EXPIRED', 'type': 'monotonic_gauge'},
                'USER_SESSION_LIMIT_EXCEEDED': {
                    'name': 'ClickHouseErrors_USER_SESSION_LIMIT_EXCEEDED',
                    'type': 'monotonic_gauge',
                },
                'VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE': {
                    'name': 'ClickHouseErrors_VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE',
                    'type': 'monotonic_gauge',
                },
                'VIOLATED_CONSTRAINT': {'name': 'ClickHouseErrors_VIOLATED_CONSTRAINT', 'type': 'monotonic_gauge'},
                'WITH_TIES_WITHOUT_ORDER_BY': {
                    'name': 'ClickHouseErrors_WITH_TIES_WITHOUT_ORDER_BY',
                    'type': 'monotonic_gauge',
                },
                'WRONG_BACKUP_SETTINGS': {'name': 'ClickHouseErrors_WRONG_BACKUP_SETTINGS', 'type': 'monotonic_gauge'},
                'WRONG_BASE_BACKUP': {'name': 'ClickHouseErrors_WRONG_BASE_BACKUP', 'type': 'monotonic_gauge'},
                'WRONG_DDL_RENAMING_SETTINGS': {
                    'name': 'ClickHouseErrors_WRONG_DDL_RENAMING_SETTINGS',
                    'type': 'monotonic_gauge',
                },
                'WRONG_GLOBAL_SUBQUERY': {'name': 'ClickHouseErrors_WRONG_GLOBAL_SUBQUERY', 'type': 'monotonic_gauge'},
                'WRONG_PASSWORD': {'name': 'ClickHouseErrors_WRONG_PASSWORD', 'type': 'monotonic_gauge'},
                'ZERO_ARRAY_OR_TUPLE_INDEX': {
                    'name': 'ClickHouseErrors_ZERO_ARRAY_OR_TUPLE_INDEX',
                    'type': 'monotonic_gauge',
                },
                'ZERO_COPY_REPLICATION_ERROR': {
                    'name': 'ClickHouseErrors_ZERO_COPY_REPLICATION_ERROR',
                    'type': 'monotonic_gauge',
                },
                'ZLIB_DEFLATE_FAILED': {'name': 'ClickHouseErrors_ZLIB_DEFLATE_FAILED', 'type': 'monotonic_gauge'},
                'ZLIB_INFLATE_FAILED': {'name': 'ClickHouseErrors_ZLIB_INFLATE_FAILED', 'type': 'monotonic_gauge'},
                'ZSTD_DECODER_FAILED': {'name': 'ClickHouseErrors_ZSTD_DECODER_FAILED', 'type': 'monotonic_gauge'},
                'ZSTD_ENCODER_FAILED': {'name': 'ClickHouseErrors_ZSTD_ENCODER_FAILED', 'type': 'monotonic_gauge'},
            },
        },
    ],
}
