# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit scripts/templates/system_async_metrics.py and then run the following command:
#     hatch run data:generate

# https://clickhouse.com/docs/operations/system-tables/asynchronous_metrics
SystemAsynchronousMetrics = {
    'name': 'system_asynchronous_metrics',
    'query': 'SELECT value, metric FROM system.asynchronous_metrics',
    'columns': [
        {'name': 'metric_value', 'type': 'source'},
        {
            'name': 'metric_name',
            'type': 'match',
            'source': 'metric_value',
            'items': {
                'AsynchronousHeavyMetricsCalculationTimeSpent': {
                    'name': 'ClickHouseAsyncMetrics_AsynchronousHeavyMetricsCalculationTimeSpent',
                    'type': 'gauge',
                },
                'AsynchronousHeavyMetricsUpdateInterval': {
                    'name': 'ClickHouseAsyncMetrics_AsynchronousHeavyMetricsUpdateInterval',
                    'type': 'gauge',
                },
                'AsynchronousMetricsCalculationTimeSpent': {
                    'name': 'ClickHouseAsyncMetrics_AsynchronousMetricsCalculationTimeSpent',
                    'type': 'gauge',
                },
                'AsynchronousMetricsUpdateInterval': {
                    'name': 'ClickHouseAsyncMetrics_AsynchronousMetricsUpdateInterval',
                    'type': 'gauge',
                },
                'CGroupMaxCPU': {'name': 'ClickHouseAsyncMetrics_CGroupMaxCPU', 'type': 'gauge'},
                'CGroupMemoryTotal': {'name': 'ClickHouseAsyncMetrics_CGroupMemoryTotal', 'type': 'gauge'},
                'CGroupMemoryUsed': {'name': 'ClickHouseAsyncMetrics_CGroupMemoryUsed', 'type': 'gauge'},
                'CGroupSystemTime': {'name': 'ClickHouseAsyncMetrics_CGroupSystemTime', 'type': 'gauge'},
                'CGroupSystemTimeNormalized': {
                    'name': 'ClickHouseAsyncMetrics_CGroupSystemTimeNormalized',
                    'type': 'gauge',
                },
                'CGroupUserTime': {'name': 'ClickHouseAsyncMetrics_CGroupUserTime', 'type': 'gauge'},
                'CGroupUserTimeNormalized': {
                    'name': 'ClickHouseAsyncMetrics_CGroupUserTimeNormalized',
                    'type': 'gauge',
                },
                'CompiledExpressionCacheBytes': {
                    'name': 'ClickHouseAsyncMetrics_CompiledExpressionCacheBytes',
                    'type': 'gauge',
                },
                'CompiledExpressionCacheCount': {
                    'name': 'ClickHouseAsyncMetrics_CompiledExpressionCacheCount',
                    'type': 'gauge',
                },
                'DictionaryTotalFailedUpdates': {
                    'name': 'ClickHouseAsyncMetrics_DictionaryTotalFailedUpdates',
                    'type': 'gauge',
                },
                'FilesystemCacheBytes': {'name': 'ClickHouseAsyncMetrics_FilesystemCacheBytes', 'type': 'gauge'},
                'FilesystemCacheCapacity': {'name': 'ClickHouseAsyncMetrics_FilesystemCacheCapacity', 'type': 'gauge'},
                'FilesystemCacheFiles': {'name': 'ClickHouseAsyncMetrics_FilesystemCacheFiles', 'type': 'gauge'},
                'FilesystemLogsPathAvailableBytes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemLogsPathAvailableBytes',
                    'type': 'gauge',
                },
                'FilesystemLogsPathAvailableINodes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemLogsPathAvailableINodes',
                    'type': 'gauge',
                },
                'FilesystemLogsPathTotalBytes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemLogsPathTotalBytes',
                    'type': 'gauge',
                },
                'FilesystemLogsPathTotalINodes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemLogsPathTotalINodes',
                    'type': 'gauge',
                },
                'FilesystemLogsPathUsedBytes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemLogsPathUsedBytes',
                    'type': 'gauge',
                },
                'FilesystemLogsPathUsedINodes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemLogsPathUsedINodes',
                    'type': 'gauge',
                },
                'FilesystemMainPathAvailableBytes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemMainPathAvailableBytes',
                    'type': 'gauge',
                },
                'FilesystemMainPathAvailableINodes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemMainPathAvailableINodes',
                    'type': 'gauge',
                },
                'FilesystemMainPathTotalBytes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemMainPathTotalBytes',
                    'type': 'gauge',
                },
                'FilesystemMainPathTotalINodes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemMainPathTotalINodes',
                    'type': 'gauge',
                },
                'FilesystemMainPathUsedBytes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemMainPathUsedBytes',
                    'type': 'gauge',
                },
                'FilesystemMainPathUsedINodes': {
                    'name': 'ClickHouseAsyncMetrics_FilesystemMainPathUsedINodes',
                    'type': 'gauge',
                },
                'HashTableStatsCacheEntries': {
                    'name': 'ClickHouseAsyncMetrics_HashTableStatsCacheEntries',
                    'type': 'gauge',
                },
                'HashTableStatsCacheHits': {'name': 'ClickHouseAsyncMetrics_HashTableStatsCacheHits', 'type': 'gauge'},
                'HashTableStatsCacheMisses': {
                    'name': 'ClickHouseAsyncMetrics_HashTableStatsCacheMisses',
                    'type': 'gauge',
                },
                'IndexMarkCacheBytes': {'name': 'ClickHouseAsyncMetrics_IndexMarkCacheBytes', 'type': 'gauge'},
                'IndexMarkCacheFiles': {'name': 'ClickHouseAsyncMetrics_IndexMarkCacheFiles', 'type': 'gauge'},
                'IndexUncompressedCacheBytes': {
                    'name': 'ClickHouseAsyncMetrics_IndexUncompressedCacheBytes',
                    'type': 'gauge',
                },
                'IndexUncompressedCacheCells': {
                    'name': 'ClickHouseAsyncMetrics_IndexUncompressedCacheCells',
                    'type': 'gauge',
                },
                'Jitter': {'name': 'ClickHouseAsyncMetrics_Jitter', 'type': 'gauge'},
                'LoadAverage1': {'name': 'ClickHouseAsyncMetrics_LoadAverage1', 'type': 'gauge'},
                'LoadAverage15': {'name': 'ClickHouseAsyncMetrics_LoadAverage15', 'type': 'gauge'},
                'LoadAverage5': {'name': 'ClickHouseAsyncMetrics_LoadAverage5', 'type': 'gauge'},
                'MMapCacheCells': {'name': 'ClickHouseAsyncMetrics_MMapCacheCells', 'type': 'gauge'},
                'MarkCacheBytes': {'name': 'ClickHouseAsyncMetrics_MarkCacheBytes', 'type': 'gauge'},
                'MarkCacheFiles': {'name': 'ClickHouseAsyncMetrics_MarkCacheFiles', 'type': 'gauge'},
                'MaxPartCountForPartition': {
                    'name': 'ClickHouseAsyncMetrics_MaxPartCountForPartition',
                    'type': 'gauge',
                },
                'MemoryCode': {'name': 'ClickHouseAsyncMetrics_MemoryCode', 'type': 'gauge'},
                'MemoryDataAndStack': {'name': 'ClickHouseAsyncMetrics_MemoryDataAndStack', 'type': 'gauge'},
                'MemoryResident': {'name': 'ClickHouseAsyncMetrics_MemoryResident', 'type': 'gauge'},
                'MemoryResidentMax': {'name': 'ClickHouseAsyncMetrics_MemoryResidentMax', 'type': 'gauge'},
                'MemoryShared': {'name': 'ClickHouseAsyncMetrics_MemoryShared', 'type': 'gauge'},
                'MemoryVirtual': {'name': 'ClickHouseAsyncMetrics_MemoryVirtual', 'type': 'gauge'},
                'NetworkTCPReceiveQueue': {'name': 'ClickHouseAsyncMetrics_NetworkTCPReceiveQueue', 'type': 'gauge'},
                'NetworkTCPSocketRemoteAddresses': {
                    'name': 'ClickHouseAsyncMetrics_NetworkTCPSocketRemoteAddresses',
                    'type': 'gauge',
                },
                'NetworkTCPSockets': {'name': 'ClickHouseAsyncMetrics_NetworkTCPSockets', 'type': 'gauge'},
                'NetworkTCPTransmitQueue': {'name': 'ClickHouseAsyncMetrics_NetworkTCPTransmitQueue', 'type': 'gauge'},
                'NetworkTCPUnrecoveredRetransmits': {
                    'name': 'ClickHouseAsyncMetrics_NetworkTCPUnrecoveredRetransmits',
                    'type': 'gauge',
                },
                'NumberOfDatabases': {'name': 'ClickHouseAsyncMetrics_NumberOfDatabases', 'type': 'gauge'},
                'NumberOfDetachedByUserParts': {
                    'name': 'ClickHouseAsyncMetrics_NumberOfDetachedByUserParts',
                    'type': 'gauge',
                },
                'NumberOfDetachedParts': {'name': 'ClickHouseAsyncMetrics_NumberOfDetachedParts', 'type': 'gauge'},
                'NumberOfPendingMutations': {
                    'name': 'ClickHouseAsyncMetrics_NumberOfPendingMutations',
                    'type': 'gauge',
                },
                'NumberOfPendingMutationsOverExecutionTime': {
                    'name': 'ClickHouseAsyncMetrics_NumberOfPendingMutationsOverExecutionTime',
                    'type': 'gauge',
                },
                'NumberOfStuckMutations': {'name': 'ClickHouseAsyncMetrics_NumberOfStuckMutations', 'type': 'gauge'},
                'NumberOfTables': {'name': 'ClickHouseAsyncMetrics_NumberOfTables', 'type': 'gauge'},
                'NumberOfTablesSystem': {'name': 'ClickHouseAsyncMetrics_NumberOfTablesSystem', 'type': 'gauge'},
                'OSCPUOverload': {'name': 'ClickHouseAsyncMetrics_OSCPUOverload', 'type': 'gauge'},
                'OSContextSwitches': {'name': 'ClickHouseAsyncMetrics_OSContextSwitches', 'type': 'gauge'},
                'OSGuestNiceTimeNormalized': {
                    'name': 'ClickHouseAsyncMetrics_OSGuestNiceTimeNormalized',
                    'type': 'gauge',
                },
                'OSGuestTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSGuestTimeNormalized', 'type': 'gauge'},
                'OSIOWaitTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSIOWaitTimeNormalized', 'type': 'gauge'},
                'OSIdleTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSIdleTimeNormalized', 'type': 'gauge'},
                'OSInterrupts': {'name': 'ClickHouseAsyncMetrics_OSInterrupts', 'type': 'gauge'},
                'OSIrqTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSIrqTimeNormalized', 'type': 'gauge'},
                'OSMemoryAvailable': {'name': 'ClickHouseAsyncMetrics_OSMemoryAvailable', 'type': 'gauge'},
                'OSMemoryBuffers': {'name': 'ClickHouseAsyncMetrics_OSMemoryBuffers', 'type': 'gauge'},
                'OSMemoryCached': {'name': 'ClickHouseAsyncMetrics_OSMemoryCached', 'type': 'gauge'},
                'OSMemoryFreePlusCached': {'name': 'ClickHouseAsyncMetrics_OSMemoryFreePlusCached', 'type': 'gauge'},
                'OSMemoryFreeWithoutCached': {
                    'name': 'ClickHouseAsyncMetrics_OSMemoryFreeWithoutCached',
                    'type': 'gauge',
                },
                'OSMemorySwapCached': {'name': 'ClickHouseAsyncMetrics_OSMemorySwapCached', 'type': 'gauge'},
                'OSMemoryTotal': {'name': 'ClickHouseAsyncMetrics_OSMemoryTotal', 'type': 'gauge'},
                'OSNiceTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSNiceTimeNormalized', 'type': 'gauge'},
                'OSOpenFiles': {'name': 'ClickHouseAsyncMetrics_OSOpenFiles', 'type': 'gauge'},
                'OSProcessesBlocked': {'name': 'ClickHouseAsyncMetrics_OSProcessesBlocked', 'type': 'gauge'},
                'OSProcessesCreated': {'name': 'ClickHouseAsyncMetrics_OSProcessesCreated', 'type': 'gauge'},
                'OSProcessesRunning': {'name': 'ClickHouseAsyncMetrics_OSProcessesRunning', 'type': 'gauge'},
                'OSSoftIrqTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSSoftIrqTimeNormalized', 'type': 'gauge'},
                'OSStealTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSStealTimeNormalized', 'type': 'gauge'},
                'OSSystemTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSSystemTimeNormalized', 'type': 'gauge'},
                'OSThreadsRunnable': {'name': 'ClickHouseAsyncMetrics_OSThreadsRunnable', 'type': 'gauge'},
                'OSThreadsTotal': {'name': 'ClickHouseAsyncMetrics_OSThreadsTotal', 'type': 'gauge'},
                'OSUptime': {'name': 'ClickHouseAsyncMetrics_OSUptime', 'type': 'gauge'},
                'OSUserTimeNormalized': {'name': 'ClickHouseAsyncMetrics_OSUserTimeNormalized', 'type': 'gauge'},
                'PageCacheBytes': {'name': 'ClickHouseAsyncMetrics_PageCacheBytes', 'type': 'gauge'},
                'PageCacheCells': {'name': 'ClickHouseAsyncMetrics_PageCacheCells', 'type': 'gauge'},
                'PageCacheMaxBytes': {'name': 'ClickHouseAsyncMetrics_PageCacheMaxBytes', 'type': 'gauge'},
                'PageCachePinnedBytes': {'name': 'ClickHouseAsyncMetrics_PageCachePinnedBytes', 'type': 'gauge'},
                'PrimaryIndexCacheBytes': {'name': 'ClickHouseAsyncMetrics_PrimaryIndexCacheBytes', 'type': 'gauge'},
                'PrimaryIndexCacheFiles': {'name': 'ClickHouseAsyncMetrics_PrimaryIndexCacheFiles', 'type': 'gauge'},
                'QueryCacheBytes': {'name': 'ClickHouseAsyncMetrics_QueryCacheBytes', 'type': 'gauge'},
                'QueryCacheEntries': {'name': 'ClickHouseAsyncMetrics_QueryCacheEntries', 'type': 'gauge'},
                'ReplicasMaxAbsoluteDelay': {
                    'name': 'ClickHouseAsyncMetrics_ReplicasMaxAbsoluteDelay',
                    'type': 'gauge',
                },
                'ReplicasMaxInsertsInQueue': {
                    'name': 'ClickHouseAsyncMetrics_ReplicasMaxInsertsInQueue',
                    'type': 'gauge',
                },
                'ReplicasMaxMergesInQueue': {
                    'name': 'ClickHouseAsyncMetrics_ReplicasMaxMergesInQueue',
                    'type': 'gauge',
                },
                'ReplicasMaxQueueSize': {'name': 'ClickHouseAsyncMetrics_ReplicasMaxQueueSize', 'type': 'gauge'},
                'ReplicasMaxRelativeDelay': {
                    'name': 'ClickHouseAsyncMetrics_ReplicasMaxRelativeDelay',
                    'type': 'gauge',
                },
                'ReplicasSumInsertsInQueue': {
                    'name': 'ClickHouseAsyncMetrics_ReplicasSumInsertsInQueue',
                    'type': 'gauge',
                },
                'ReplicasSumMergesInQueue': {
                    'name': 'ClickHouseAsyncMetrics_ReplicasSumMergesInQueue',
                    'type': 'gauge',
                },
                'ReplicasSumQueueSize': {'name': 'ClickHouseAsyncMetrics_ReplicasSumQueueSize', 'type': 'gauge'},
                'TotalBytesOfMergeTreeTables': {
                    'name': 'ClickHouseAsyncMetrics_TotalBytesOfMergeTreeTables',
                    'type': 'gauge',
                },
                'TotalBytesOfMergeTreeTablesSystem': {
                    'name': 'ClickHouseAsyncMetrics_TotalBytesOfMergeTreeTablesSystem',
                    'type': 'gauge',
                },
                'TotalIndexGranularityBytesInMemory': {
                    'name': 'ClickHouseAsyncMetrics_TotalIndexGranularityBytesInMemory',
                    'type': 'gauge',
                },
                'TotalIndexGranularityBytesInMemoryAllocated': {
                    'name': 'ClickHouseAsyncMetrics_TotalIndexGranularityBytesInMemoryAllocated',
                    'type': 'gauge',
                },
                'TotalPartsOfMergeTreeTables': {
                    'name': 'ClickHouseAsyncMetrics_TotalPartsOfMergeTreeTables',
                    'type': 'gauge',
                },
                'TotalPartsOfMergeTreeTablesSystem': {
                    'name': 'ClickHouseAsyncMetrics_TotalPartsOfMergeTreeTablesSystem',
                    'type': 'gauge',
                },
                'TotalPrimaryKeyBytesInMemory': {
                    'name': 'ClickHouseAsyncMetrics_TotalPrimaryKeyBytesInMemory',
                    'type': 'gauge',
                },
                'TotalPrimaryKeyBytesInMemoryAllocated': {
                    'name': 'ClickHouseAsyncMetrics_TotalPrimaryKeyBytesInMemoryAllocated',
                    'type': 'gauge',
                },
                'TotalRowsOfMergeTreeTables': {
                    'name': 'ClickHouseAsyncMetrics_TotalRowsOfMergeTreeTables',
                    'type': 'gauge',
                },
                'TotalRowsOfMergeTreeTablesSystem': {
                    'name': 'ClickHouseAsyncMetrics_TotalRowsOfMergeTreeTablesSystem',
                    'type': 'gauge',
                },
                'TrackedMemory': {'name': 'ClickHouseAsyncMetrics_TrackedMemory', 'type': 'gauge'},
                'UncompressedCacheBytes': {'name': 'ClickHouseAsyncMetrics_UncompressedCacheBytes', 'type': 'gauge'},
                'UncompressedCacheCells': {'name': 'ClickHouseAsyncMetrics_UncompressedCacheCells', 'type': 'gauge'},
                'UnreclaimableRSS': {'name': 'ClickHouseAsyncMetrics_UnreclaimableRSS', 'type': 'gauge'},
                'Uptime': {'name': 'ClickHouseAsyncMetrics_Uptime', 'type': 'gauge'},
                'VMMaxMapCount': {'name': 'ClickHouseAsyncMetrics_VMMaxMapCount', 'type': 'gauge'},
                'VMNumMaps': {'name': 'ClickHouseAsyncMetrics_VMNumMaps', 'type': 'gauge'},
                'jemalloc.epoch': {'name': 'ClickHouseAsyncMetrics_jemalloc.epoch', 'type': 'gauge'},
            },
        },
    ],
}
