# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)


METRICS_MAP = {
    "kubevirt_info": "info",
    "kubevirt_vmi_cpu_system_usage_seconds": "vmi.cpu_system_usage_seconds",
    "kubevirt_vmi_cpu_usage_seconds": "vmi.cpu_usage_seconds",
    "kubevirt_vmi_cpu_user_usage_seconds": "vmi.cpu_user_usage_seconds",
    "kubevirt_vmi_memory_actual_balloon_bytes": "vmi.memory_actual_balloon_bytes",
    "kubevirt_vmi_memory_available_bytes": "vmi.memory_available_bytes",
    "kubevirt_vmi_memory_domain_bytes": "vmi.memory_domain_bytes",
    "kubevirt_vmi_memory_pgmajfault": "vmi.memory_pgmajfault",
    "kubevirt_vmi_memory_pgminfault": "vmi.memory_pgminfault",
    "kubevirt_vmi_memory_resident_bytes": "vmi.memory_resident_bytes",
    "kubevirt_vmi_memory_swap_in_traffic_bytes": "vmi.memory_swap_in_traffic_bytes",
    "kubevirt_vmi_memory_swap_out_traffic_bytes": "vmi.memory_swap_out_traffic_bytes",
    "kubevirt_vmi_memory_unused_bytes": "vmi.memory_unused_bytes",
    "kubevirt_vmi_memory_usable_bytes": "vmi.memory_usable_bytes",
    "kubevirt_vmi_network_receive_bytes": "vmi.network_receive_bytes",
    "kubevirt_vmi_network_receive_errors": "vmi.network_receive_errors",
    "kubevirt_vmi_network_receive_packets_dropped": "vmi.network_receive_packets_dropped",
    "kubevirt_vmi_network_receive_packets": "vmi.network_receive_packets",
    "kubevirt_vmi_network_transmit_bytes": "vmi.network_transmit_bytes",
    "kubevirt_vmi_network_transmit_errors": "vmi.network_transmit_errors",
    "kubevirt_vmi_network_transmit_packets_dropped": "vmi.network_transmit_packets_dropped",
    "kubevirt_vmi_network_transmit_packets": "vmi.network_transmit_packets",
    "kubevirt_vmi_node_cpu_affinity": "vmi.node_cpu_affinity",
    "kubevirt_vmi_storage_flush_requests": "vmi.storage_flush_requests",
    "kubevirt_vmi_storage_flush_times_seconds": "vmi.storage_flush_times_seconds",
    "kubevirt_vmi_storage_iops_read": "vmi.storage_iops_read",
    "kubevirt_vmi_storage_iops_write": "vmi.storage_iops_write",
    "kubevirt_vmi_storage_read_times_seconds": "vmi.storage_read_times_seconds",
    "kubevirt_vmi_storage_read_traffic_bytes": "vmi.storage_read_traffic_bytes",
    "kubevirt_vmi_storage_write_times_seconds": "vmi.storage_write_times_seconds",
    "kubevirt_vmi_storage_write_traffic_bytes": "vmi.storage_write_traffic_bytes",
    "kubevirt_vmi_vcpu_delay_seconds": "vmi.vcpu_delay_seconds",
    "kubevirt_vmi_vcpu_seconds": "vmi.vcpu_seconds",
    "kubevirt_vmi_vcpu_wait_seconds": "vmi.vcpu_wait_seconds",
    "kubevirt_workqueue_adds": "workqueue.adds",
    "kubevirt_workqueue_depth": "workqueue.depth",
    "kubevirt_workqueue_longest_running_processor_seconds": "workqueue.longest_running_processor_seconds",
    "kubevirt_workqueue_queue_duration_seconds": "workqueue.queue_duration_seconds",
    "kubevirt_workqueue_retries": "workqueue.retries",
    "kubevirt_workqueue_unfinished_work_seconds": "workqueue.unfinished_work_seconds",
    "kubevirt_workqueue_work_duration_seconds": "workqueue.work_duration_seconds",
}
