# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
import os

from datadog_checks.dev import get_docker_hostname, get_here

HERE = get_here()
HOST = get_docker_hostname()
PRIVELEGED_METRICS_PORT = 8000
STORAGE_API_PORT = 9000


def get_fixture_path(filename):
    return os.path.join(HERE, 'fixtures', filename)


MOCKED_INSTANCE = {
    "privileged_metrics_endpoint": f"http://{HOST}:{PRIVELEGED_METRICS_PORT}/metrics",
    "storage_api_endpoint": f"http://{HOST}:{STORAGE_API_PORT}/metrics",
    "tags": ['test:test'],
}

COMPOSE_FILE = os.path.join(HERE, 'docker', 'docker-compose.yaml')

PRIVILEGED_METRICS_INSTANCE = {
    "privileged_metrics_endpoint": f"http://{HOST}:{PRIVELEGED_METRICS_PORT}/metrics",
    "tags": ['test:test'],
}

STORAGE_API_INSTANCE = {
    "storage_api_endpoint": f"http://{HOST}:{STORAGE_API_PORT}/metrics",
    "tags": ['test:test'],
}

COMPOSE_FILE = os.path.join(HERE, 'docker', 'docker-compose.yaml')

(
    PRIVILEGED_METRICS_NAMESPACE,
    STORAGE_API_METRICS_NAMESPACE,
) = [
    'supabase',
    'supabase.storage_api',
]

PRIVILEGED_METRICS = [
    'supabase.auth_users.user_count',
    'supabase.db.sql.connection_closed_max_idle.count',
    'supabase.db.sql.connection_closed_max_idle_time.count',
    'supabase.db.sql.connection_closed_max_lifetime.count',
    'supabase.db.sql.connection_max_open',
    'supabase.db.sql.connection_open',
    'supabase.db.sql.connection_wait.count',
    'supabase.db.sql.connection_wait_duration.count',
    'supabase.db.transmit_bytes.count',
    'supabase.go.gc.duration.seconds.count',
    'supabase.go.gc.duration.seconds.quantile',
    'supabase.go.gc.duration.seconds.sum',
    'supabase.go.goroutines',
    'supabase.go.memstats.alloc_bytes',
    'supabase.go.memstats.alloc_bytes.count',
    'supabase.go.memstats.buck_hash.sys_bytes',
    'supabase.go.memstats.frees.count',
    'supabase.go.memstats.gc.sys_bytes',
    'supabase.go.memstats.heap.alloc_bytes',
    'supabase.go.memstats.heap.idle_bytes',
    'supabase.go.memstats.heap.inuse_bytes',
    'supabase.go.memstats.heap.objects',
    'supabase.go.memstats.heap.released_bytes',
    'supabase.go.memstats.heap.sys_bytes',
    'supabase.go.memstats.last_gc_time.seconds',
    'supabase.go.memstats.lookups.count',
    'supabase.go.memstats.mallocs.count',
    'supabase.go.memstats.mcache.inuse_bytes',
    'supabase.go.memstats.mcache.sys_bytes',
    'supabase.go.memstats.mspan.inuse_bytes',
    'supabase.go.memstats.mspan.sys_bytes',
    'supabase.go.memstats.next.gc_bytes',
    'supabase.go.memstats.other.sys_bytes',
    'supabase.go.memstats.stack.inuse_bytes',
    'supabase.go.memstats.stack.sys_bytes',
    'supabase.go.memstats.sys_bytes',
    'supabase.go.threads',
    'supabase.http.server.duration.bucket',
    'supabase.http.server.duration.count',
    'supabase.http.server.duration.sum',
    'supabase.http.server.request.size_bytes.count',
    'supabase.http.server.response.size_bytes.count',
    'supabase.http.status_codes.count',
    'supabase.node.cpu.guest_seconds.count',
    'supabase.node.cpu.seconds.count',
    'supabase.node.disk.discard_time_seconds.count',
    'supabase.node.disk.discarded_sectors.count',
    'supabase.node.disk.discards_completed.count',
    'supabase.node.disk.discards_merged.count',
    'supabase.node.disk.flush_requests.count',
    'supabase.node.disk.flush_requests_time_seconds.count',
    'supabase.node.disk.io_now',
    'supabase.node.disk.io_time_seconds.count',
    'supabase.node.disk.io_time_weighted_seconds.count',
    'supabase.node.disk.read_bytes.count',
    'supabase.node.disk.read_time_seconds.count',
    'supabase.node.disk.reads_completed.count',
    'supabase.node.disk.reads_merged.count',
    'supabase.node.disk.write_time_seconds.count',
    'supabase.node.disk.writes_completed.count',
    'supabase.node.disk.writes_merged.count',
    'supabase.node.disk.written_bytes.count',
    'supabase.node.filesystem.available_bytes',
    'supabase.node.filesystem.device_error',
    'supabase.node.filesystem.files',
    'supabase.node.filesystem.files_free',
    'supabase.node.filesystem.free_bytes',
    'supabase.node.filesystem.readonly',
    'supabase.node.filesystem.size_bytes',
    'supabase.node.load1',
    'supabase.node.load15',
    'supabase.node.load5',
    'supabase.node.memory.active_anon_bytes',
    'supabase.node.memory.active_bytes',
    'supabase.node.memory.active_file_bytes',
    'supabase.node.memory.anon_huge_pages_bytes',
    'supabase.node.memory.anon_pages_bytes',
    'supabase.node.memory.bounce_bytes',
    'supabase.node.memory.buffers_bytes',
    'supabase.node.memory.cached_bytes',
    'supabase.node.memory.commit_limit_bytes',
    'supabase.node.memory.committed_as_bytes',
    'supabase.node.memory.dirty_bytes',
    'supabase.node.memory.file_huge_pages_bytes',
    'supabase.node.memory.file_pmd_mapped_bytes',
    'supabase.node.memory.hardware_corrupted_bytes',
    'supabase.node.memory.huge_page_size_bytes',
    'supabase.node.memory.huge_pages_free',
    'supabase.node.memory.huge_pages_reserved',
    'supabase.node.memory.huge_pages_surp',
    'supabase.node.memory.huge_pages_total',
    'supabase.node.memory.hugetlb_bytes',
    'supabase.node.memory.inactive_anon_bytes',
    'supabase.node.memory.inactive_bytes',
    'supabase.node.memory.inactive_file_bytes',
    'supabase.node.memory.kernel_stack_bytes',
    'supabase.node.memory.kreclaimable_bytes',
    'supabase.node.memory.mapped_bytes',
    'supabase.node.memory.mem_available_bytes',
    'supabase.node.memory.mem_free_bytes',
    'supabase.node.memory.mem_total_bytes',
    'supabase.node.memory.mlocked_bytes',
    'supabase.node.memory.nfs_unstable_bytes',
    'supabase.node.memory.page_tables_bytes',
    'supabase.node.memory.percpu_bytes',
    'supabase.node.memory.shmem_bytes',
    'supabase.node.memory.shmem_huge_pages_bytes',
    'supabase.node.memory.shmem_pmd_mapped_bytes',
    'supabase.node.memory.slab_bytes',
    'supabase.node.memory.sreclaimable_bytes',
    'supabase.node.memory.sunreclaim_bytes',
    'supabase.node.memory.swap_cached_bytes',
    'supabase.node.memory.swap_free_bytes',
    'supabase.node.memory.swap_total_bytes',
    'supabase.node.memory.unevictable_bytes',
    'supabase.node.memory.vm_alloc_chunk_bytes',
    'supabase.node.memory.vm_alloc_total_bytes',
    'supabase.node.memory.vm_alloc_used_bytes',
    'supabase.node.memory.writeback_bytes',
    'supabase.node.memory.writeback_tmp_bytes',
    'supabase.node.network.receive_bytes.count',
    'supabase.node.network.receive_compressed.count',
    'supabase.node.network.receive_drop.count',
    'supabase.node.network.receive_errors.count',
    'supabase.node.network.receive_fifo.count',
    'supabase.node.network.receive_frame.count',
    'supabase.node.network.receive_multicast.count',
    'supabase.node.network.receive_packets.count',
    'supabase.node.network.transmit_bytes.count',
    'supabase.node.network.transmit_carrier.count',
    'supabase.node.network.transmit_colls.count',
    'supabase.node.network.transmit_compressed.count',
    'supabase.node.network.transmit_drop.count',
    'supabase.node.network.transmit_errors.count',
    'supabase.node.network.transmit_fifo.count',
    'supabase.node.network.transmit_packets.count',
    'supabase.node.scrape.collector_duration_seconds',
    'supabase.node.scrape.collector_success',
    'supabase.node.vmstat.oom_kill.count',
    'supabase.node.vmstat.pgfault.count',
    'supabase.node.vmstat.pgmajfault.count',
    'supabase.node.vmstat.pgpgin.count',
    'supabase.node.vmstat.pgpgout.count',
    'supabase.node.vmstat.pswpin.count',
    'supabase.node.vmstat.pswpout.count',
    'supabase.pg.up',
    'supabase.pg_database_size.bytes',
    'supabase.pg_database_size',
    'supabase.pg_exporter.last_scrape_duration_seconds',
    'supabase.pg_exporter.last_scrape_error',
    'supabase.pg_exporter.scrapes.count',
    'supabase.pg_exporter.user_queries_load_error',
    'supabase.pg_ls.archive_statusdir_wal_pending.count',
    'supabase.pg_replication_slots.max_lag_bytes',
    'supabase.pg_scrape_collector.duration_seconds',
    'supabase.pg_scrape_collector.success',
    'supabase.pg_settings.default_transaction_read_only',
    'supabase.pg_stat_activity.xact_runtime',
    'supabase.pg_stat_bgwriter.buffers_alloc.count',
    'supabase.pg_stat_bgwriter.buffers_backend.count',
    'supabase.pg_stat_bgwriter.buffers_backend_fsync.count',
    'supabase.pg_stat_bgwriter.buffers_checkpoint.count',
    'supabase.pg_stat_bgwriter.buffers_clean.count',
    'supabase.pg_stat_bgwriter.checkpoint_sync_time.count',
    'supabase.pg_stat_bgwriter.checkpoint_write_time.count',
    'supabase.pg_stat_bgwriter.checkpoints_req.count',
    'supabase.pg_stat_bgwriter.checkpoints_timed.count',
    'supabase.pg_stat_bgwriter.maxwritten_clean.count',
    'supabase.pg_stat_bgwriter.stats_reset.count',
    'supabase.pg_stat_database.blks_hit.count',
    'supabase.pg_stat_database.blks_read.count',
    'supabase.pg_stat_database.conflicts.count',
    'supabase.pg_stat_database.deadlocks.count',
    'supabase.pg_stat_database.num_backends',
    'supabase.pg_stat_database.temp_bytes.count',
    'supabase.pg_stat_database.temp_files.count',
    'supabase.pg_stat_database.tup_deleted.count',
    'supabase.pg_stat_database.tup_fetched.count',
    'supabase.pg_stat_database.tup_inserted.count',
    'supabase.pg_stat_database.tup_returned.count',
    'supabase.pg_stat_database.tup_updated.count',
    'supabase.pg_stat_database.xact_commit.count',
    'supabase.pg_stat_database.xact_rollback.count',
    'supabase.pg_stat_database.conflicts.confl_bufferpin.count',
    'supabase.pg_stat_database.conflicts.confl_deadlock.count',
    'supabase.pg_stat_database.conflicts.confl_lock.count',
    'supabase.pg_stat_database.conflicts.confl_snapshot.count',
    'supabase.pg_stat_database.conflicts.confl_tablespace.count',
    'supabase.pg_stat_statements.total_queries.count',
    'supabase.pg_stat_statements.total_time_seconds.count',
    'supabase.pg_status.in_recovery',
    'supabase.pg_wal.size',
    'supabase.pgrst.db_pool.available_connections',
    'supabase.pgrst.db_pool.connection_timeouts.count',
    'supabase.pgrst.db_pool.max_connections',
    'supabase.pgrst.db_pool.requests_waiting',
    'supabase.pgrst.schema_cache.loads.count',
    'supabase.pgrst.schema_cache.query_time_seconds',
    'supabase.physical_replication_lag.is_connected_to_primary',
    'supabase.physical_replication_lag.is_wal_replay_paused',
    'supabase.physical_replication_lag_seconds',
    'supabase.postgres_exporter.build_info',
    'supabase.postgres_exporter.config_last_reload_successful',
    'supabase.postgresql.restarts.count',
    'supabase.process.cpu.seconds.count',
    'supabase.process.max_fds',
    'supabase.process.open_fds',
    'supabase.process.resident_memory.bytes',
    'supabase.process.runtime.go_mem_live_objects',
    'supabase.process.start_time.seconds',
    'supabase.process.virtual_memory.bytes',
    'supabase.process.virtual_memory.max_bytes',
    'supabase.promhttp_metric_handler.requests.count',
    'supabase.promhttp_metric_handler.requests_in_flight',
    'supabase.realtime_postgres_changes.client_subscriptions',
    'supabase.realtime_postgres_changes.total_subscriptions',
    'supabase.runtime.uptime_milliseconds',
    'supabase.usage_metrics.user_queries.count',
]
STORAGE_API_METRICS = [
    'supabase.storage_api.database_query_performance.bucket',
    'supabase.storage_api.database_query_performance.count',
    'supabase.storage_api.database_query_performance.sum',
    'supabase.storage_api.db_connections',
    'supabase.storage_api.db_pool',
    'supabase.storage_api.http_pool.busy_sockets',
    'supabase.storage_api.http_pool.errors',
    'supabase.storage_api.http_pool.free_sockets',
    'supabase.storage_api.http_pool.requests',
    'supabase.storage_api.http_request.duration_seconds.bucket',
    'supabase.storage_api.http_request.duration_seconds.count',
    'supabase.storage_api.http_request.duration_seconds.sum',
    'supabase.storage_api.http_request.summary_seconds.count',
    'supabase.storage_api.http_request.summary_seconds.quantile',
    'supabase.storage_api.http_request.summary_seconds.sum',
    'supabase.storage_api.nodejs.active_handles',
    'supabase.storage_api.nodejs.active_handles.total',
    'supabase.storage_api.nodejs.active_requests.total',
    'supabase.storage_api.nodejs.active_resources',
    'supabase.storage_api.nodejs.active_resources.total',
    'supabase.storage_api.nodejs.eventloop_lag.max_seconds',
    'supabase.storage_api.nodejs.eventloop_lag.mean_seconds',
    'supabase.storage_api.nodejs.eventloop_lag.p50_seconds',
    'supabase.storage_api.nodejs.eventloop_lag.p90_seconds',
    'supabase.storage_api.nodejs.eventloop_lag.p99_seconds',
    'supabase.storage_api.nodejs.eventloop_lag.seconds',
    'supabase.storage_api.nodejs.eventloop_lag.stddev_seconds',
    'supabase.storage_api.nodejs.external_memory.bytes',
    'supabase.storage_api.nodejs.gc_duration.seconds.bucket',
    'supabase.storage_api.nodejs.gc_duration.seconds.count',
    'supabase.storage_api.nodejs.gc_duration.seconds.sum',
    'supabase.storage_api.nodejs.heap_size.total_bytes',
    'supabase.storage_api.nodejs.heap_size.used_bytes',
    'supabase.storage_api.nodejs.heap_space_size.available_bytes',
    'supabase.storage_api.nodejs.heap_space_size.total_bytes',
    'supabase.storage_api.nodejs.heap_space_size.used_bytes',
    'supabase.storage_api.nodejs.version_info',
    'supabase.storage_api.nodejs_eventloop_lag.min_seconds',
    'supabase.storage_api.process.heap_bytes',
    'supabase.storage_api.process.max_fds',
    'supabase.storage_api.process.open_fds',
    'supabase.storage_api.process.resident_memory.bytes',
    'supabase.storage_api.process.uptime.seconds',
    'supabase.storage_api.process.virtual_memory.bytes',
    'supabase.storage_api.process_cpu.system.seconds.count',
    'supabase.storage_api.process_cpu.user.seconds.count',
    'supabase.storage_api.process_cpu.seconds.count',
]
