# (C) Datadog, Inc. 2020-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
from datadog_checks.dev import get_docker_hostname, get_here

CHECK_NAME = "cassandra"

HERE = get_here()
HOST = get_docker_hostname()

"""
# not all metrics will be available in our E2E environment, specifically:
    "cassandra.net.up_endpoint_count",
    "cassanra.net.down_endpoint_count",
"""

CASSANDRA_E2E_METRICS = [
    "cassandra.currently_blocked_tasks.count",
    "cassandra.db.droppable_tombstone_ratio",
    "cassandra.dropped.one_minute_rate",
    "cassandra.exceptions.count",
    "cassandra.latency.75th_percentile",
    "cassandra.latency.95th_percentile",
    "cassandra.latency.one_minute_rate",
    "cassandra.load.count",
    "cassandra.pending_tasks",
    "cassandra.total_commit_log_size",
    "cassandra.bloom_filter_false_ratio",
    "cassandra.bytes_flushed.count",
    "cassandra.cas_commit_latency.75th_percentile",
    "cassandra.cas_commit_latency.95th_percentile",
    "cassandra.cas_commit_latency.one_minute_rate",
    "cassandra.cas_prepare_latency.75th_percentile",
    "cassandra.cas_prepare_latency.95th_percentile",
    "cassandra.cas_prepare_latency.one_minute_rate",
    "cassandra.cas_propose_latency.75th_percentile",
    "cassandra.cas_propose_latency.95th_percentile",
    "cassandra.cas_propose_latency.one_minute_rate",
    "cassandra.col_update_time_delta_histogram.75th_percentile",
    "cassandra.col_update_time_delta_histogram.95th_percentile",
    "cassandra.col_update_time_delta_histogram.min",
    "cassandra.compaction_bytes_written.count",
    "cassandra.compression_ratio",
    "cassandra.key_cache_hit_rate",
    "cassandra.live_disk_space_used.count",
    "cassandra.live_ss_table_count",
    "cassandra.max_partition_size",
    "cassandra.max_row_size",
    "cassandra.mean_partition_size",
    "cassandra.mean_row_size",
    "cassandra.pending_compactions",
    "cassandra.pending_flushes.count",
    "cassandra.range_latency.75th_percentile",
    "cassandra.range_latency.95th_percentile",
    "cassandra.range_latency.one_minute_rate",
    "cassandra.read_latency.75th_percentile",
    "cassandra.read_latency.95th_percentile",
    "cassandra.read_latency.99th_percentile",
    "cassandra.read_latency.one_minute_rate",
    "cassandra.row_cache_hit.count",
    "cassandra.row_cache_hit_out_of_range.count",
    "cassandra.row_cache_miss.count",
    "cassandra.snapshots_size",
    "cassandra.ss_tables_per_read_histogram.75th_percentile",
    "cassandra.ss_tables_per_read_histogram.95th_percentile",
    "cassandra.tombstone_scanned_histogram.75th_percentile",
    "cassandra.tombstone_scanned_histogram.95th_percentile",
    "cassandra.total_disk_space_used.count",
    "cassandra.view_lock_acquire_time.75th_percentile",
    "cassandra.view_lock_acquire_time.95th_percentile",
    "cassandra.view_lock_acquire_time.one_minute_rate",
    "cassandra.view_read_time.75th_percentile",
    "cassandra.view_read_time.95th_percentile",
    "cassandra.view_read_time.one_minute_rate",
    "cassandra.waiting_on_free_memtable_space.75th_percentile",
    "cassandra.waiting_on_free_memtable_space.95th_percentile",
    "cassandra.write_latency.75th_percentile",
    "cassandra.write_latency.95th_percentile",
    "cassandra.write_latency.99th_percentile",
    "cassandra.write_latency.one_minute_rate",
    # JVM Metrics -- At this time, collecting these default metrics cannot be excluded from this test
    "jvm.buffer_pool.direct.capacity",
    "jvm.buffer_pool.direct.count",
    "jvm.buffer_pool.direct.used",
    "jvm.buffer_pool.mapped.capacity",
    "jvm.buffer_pool.mapped.count",
    "jvm.buffer_pool.mapped.used",
    "jvm.cpu_load.process",
    "jvm.cpu_load.system",
    "jvm.gc.eden_size",
    "jvm.gc.old_gen_size",
    "jvm.gc.survivor_size",
    "jvm.heap_memory",
    "jvm.heap_memory_committed",
    "jvm.heap_memory_init",
    "jvm.heap_memory_max",
    "jvm.loaded_classes",
    "jvm.non_heap_memory",
    "jvm.non_heap_memory_committed",
    "jvm.non_heap_memory_init",
    "jvm.non_heap_memory_max",
    "jvm.os.open_file_descriptors",
    "jvm.thread_count",
]
