# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
from __future__ import annotations

import re
from datetime import datetime, timezone

VALID_INTEGRATION_NAME = re.compile(r'^[A-Z0-9](?:[A-Z0-9._\- ]*[A-Z0-9])?$', re.IGNORECASE)


def is_valid_integration_name(name: str) -> bool:
    """Return True iff `name` is acceptable to `normalize_project_name` / scaffold path templating.

    Must contain only ASCII letters/digits, dots, hyphens, underscores, or spaces, and must
    begin and end with an alphanumeric character.
    """
    return bool(VALID_INTEGRATION_NAME.match(name))


def normalize_package_name(name: str) -> str:
    """Lowercase and collapse separators to underscore (used for directory and Python package names)."""
    return re.sub(r'[-_. ]+', '_', name).lower()


def normalize_project_name(name: str) -> str:
    """Normalize per PEP 503 for use as a distribution name."""
    if not re.search(r'^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$', name, re.IGNORECASE):
        raise ValueError('Project name must only contain ASCII letters/digits, underscores, hyphens, and periods.')
    return re.sub(r'[-_.]+', '-', name).lower()


def kebab_case_name(name: str) -> str:
    """Lowercase and replace separators with hyphens."""
    return re.sub(r'[_ ]', '-', name.lower())


def normalize_display_name(display_name: str) -> str:
    """Lower-case, collapse runs of non-alphanumeric characters to underscores, strip leading/trailing underscores."""
    normalized = re.sub(r'[^0-9A-Za-z-]', '_', display_name)
    normalized = re.sub(r'_+', '_', normalized).strip('_')
    return normalized.lower()


def get_license_header() -> str:
    year = datetime.now(timezone.utc).year
    return (
        f'# (C) Datadog, Inc. {year}-present\n'
        '# All rights reserved\n'
        '# Licensed under a 3-clause BSD style license (see LICENSE)'
    )


def get_config_models_documentation() -> str:
    return (
        '# This file is autogenerated.\n'
        '# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:\n'
        '#     ddev -x validate config -s <INTEGRATION_NAME>\n'
        '#     ddev -x validate models -s <INTEGRATION_NAME>\n'
    )
