# (C) Datadog, Inc. 2023-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def shared_collect_device_metadata():
    return True


def shared_ignore_nonincreasing_oid():
    return False


def shared_loader():
    return 'python'


def shared_min_collection_interval():
    return 15


def shared_oid_batch_size():
    return 10


def shared_optimize_mib_memory_usage():
    return False


def shared_refresh_oids_cache_interval():
    return 0


def shared_use_device_id_as_hostname():
    return False


def instance_bulk_threshold():
    return 0


def instance_collect_device_metadata():
    return True


def instance_disable_generic_tags():
    return False


def instance_discovery_allowed_failures():
    return 3


def instance_discovery_interval():
    return 3600


def instance_discovery_workers():
    return 5


def instance_empty_default_hostname():
    return False


def instance_enforce_mib_constraints():
    return True


def instance_loader():
    return 'python'


def instance_min_collection_interval():
    return 15


def instance_oid_batch_size():
    return 5


def instance_port():
    return 161


def instance_refresh_oids_cache_interval():
    return 0


def instance_retries():
    return 3


def instance_snmp_version():
    return 2


def instance_timeout():
    return 2


def instance_use_device_id_as_hostname():
    return False


def instance_use_global_metrics():
    return True


def instance_workers():
    return 5
