# (C) Datadog, Inc. 2023-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from __future__ import annotations

from types import MappingProxyType
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from datadog_checks.base.utils.functions import identity
from datadog_checks.base.utils.models import validation

from . import defaults, validators


class SharedConfig(BaseModel):
    model_config = ConfigDict(
        validate_default=True,
        arbitrary_types_allowed=True,
        frozen=True,
    )
    collect_device_metadata: Optional[bool] = None
    global_metrics: Optional[tuple[MappingProxyType[str, Any], ...]] = None
    ignore_nonincreasing_oid: Optional[bool] = None
    loader: Optional[str] = None
    mibs_folder: Optional[str] = None
    min_collection_interval: Optional[float] = None
    oid_batch_size: Optional[int] = None
    optimize_mib_memory_usage: Optional[bool] = None
    profiles: Optional[MappingProxyType[str, Any]] = None
    refresh_oids_cache_interval: Optional[int] = None
    service: Optional[str] = None
    use_device_id_as_hostname: Optional[bool] = None

    @model_validator(mode='before')
    def _initial_validation(cls, values):
        return validation.core.initialize_config(getattr(validators, 'initialize_shared', identity)(values))

    @field_validator('*', mode='before')
    def _validate(cls, value, info):
        field = cls.model_fields[info.field_name]
        field_name = field.alias or info.field_name
        if field_name in info.context['configured_fields']:
            value = getattr(validators, f'shared_{info.field_name}', identity)(value, field=field)
        else:
            value = getattr(defaults, f'shared_{info.field_name}', lambda: value)()

        return validation.utils.make_immutable(value)

    @model_validator(mode='after')
    def _final_validation(cls, model):
        return validation.core.check_model(getattr(validators, 'check_shared', identity)(model))
