# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

METRICS_LIST = [
    'ci_docker_machines_provider_machine_creation_duration_seconds',
    'ci_docker_machines_provider_machine_states',
    'ci_runner_builds',
    'ci_runner_errors',
    'ci_ssh_docker_machines_provider_machine_creation_duration_seconds',
    'ci_ssh_docker_machines_provider_machine_states',
    'gitlab_runner_api_request_duration_seconds',
    'gitlab_runner_autoscaling_machine_creation_duration_seconds',
    'gitlab_runner_autoscaling_machine_states',
    'gitlab_runner_errors_total',
    'gitlab_runner_job_queue_duration_seconds',
    'gitlab_runner_jobs',
    'gitlab_runner_version_info',
    'go_gc_duration_seconds',
    'go_goroutines',
    'go_memstats_alloc_bytes',
    'go_memstats_alloc_bytes_total',
    'go_memstats_buck_hash_sys_bytes',
    'go_memstats_frees_total',
    'go_memstats_gc_sys_bytes',
    'go_memstats_heap_alloc_bytes',
    'go_memstats_heap_idle_bytes',
    'go_memstats_heap_inuse_bytes',
    'go_memstats_heap_objects',
    'go_memstats_heap_released_bytes_total',
    'go_memstats_heap_sys_bytes',
    'go_memstats_last_gc_time_seconds',
    'go_memstats_lookups_total',
    'go_memstats_mallocs_total',
    'go_memstats_mcache_inuse_bytes',
    'go_memstats_mcache_sys_bytes',
    'go_memstats_mspan_inuse_bytes',
    'go_memstats_mspan_sys_bytes',
    'go_memstats_next_gc_bytes',
    'go_memstats_other_sys_bytes',
    'go_memstats_stack_inuse_bytes',
    'go_memstats_stack_sys_bytes',
    'go_memstats_sys_bytes',
    'process_cpu_seconds_total',
    'process_max_fds',
    'process_open_fds',
    'process_resident_memory_bytes',
    'process_start_time_seconds',
    'process_virtual_memory_bytes',
]
