# Dockerfile_custom
ARG VERTICA_VERSION="latest"
FROM opentext/vertica-k8s:${VERTICA_VERSION}

# Install tzdata (pick the one that matches your base OS)
# RUN microdnf install -y tzdata && microdnf clean all || true
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/* || true
# RUN apk add --no-cache tzdata || true


ADD ./custom-entrypoint.sh ${VERTICA_HOME_DIR}/custom-entrypoint.sh
RUN chmod +x ${VERTICA_HOME_DIR}/custom-entrypoint.sh \
 && rm -rf "${VERTICA_OPT_DIR}/packages"

ENTRYPOINT ["/bin/bash","-lc","${VERTICA_HOME_DIR}/custom-entrypoint.sh"]