FROM gcr.io/istio-testing/go-control-plane-ci:08-20-2019

RUN go get github.com/envoyproxy/go-control-plane/envoy/api/v2

COPY controlplane.go /go-control-plane/controlplane.go
RUN go build 

ENTRYPOINT /go-control-plane/go-control-plane
