# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

MACHINES_API_UP_METRIC = "machines_api.up"

MACHINE_UP_STATE = "started"
VOLUME_CREATED_STATE = "created"

MACHINE_METRIC_PREFIX = "machine"
MACHINE_COUNT_METRIC = f"{MACHINE_METRIC_PREFIX}.count"
MACHINE_CPUS_METRIC = f"{MACHINE_METRIC_PREFIX}.cpus.count"
MACHINE_GPUS_METRIC = f"{MACHINE_METRIC_PREFIX}.gpus.count"
MACHINE_MEM_METRIC = f"{MACHINE_METRIC_PREFIX}.memory"
MACHINE_SWAP_SIZE_METRIC = f"{MACHINE_METRIC_PREFIX}.swap_size"

VOLUME_METRIC_PREFIX = "volume"
VOLUME_CREATED_METRIC = f"{VOLUME_METRIC_PREFIX}.created"
VOLUME_SIZE_METRIC = f"{VOLUME_METRIC_PREFIX}.size"
VOLUME_ENCRYPTED_METRIC = f"{VOLUME_METRIC_PREFIX}.encrypted"
VOLUME_BLOCKS_METRIC = f"{VOLUME_METRIC_PREFIX}.blocks.count"
VOLUME_BLOCK_SIZE_METRIC = f"{VOLUME_METRIC_PREFIX}.block_size"
VOLUME_BLOCKS_FREE_METRIC = f"{VOLUME_METRIC_PREFIX}.blocks_free"
VOLUME_BLOCKS_AVAIL_METRIC = f"{VOLUME_METRIC_PREFIX}.blocks_avail"

APP_METRIC_PREFIX = "app"
APP_COUNT_METRIC = f"{APP_METRIC_PREFIX}.count"
