# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
from datadog_checks.dev.jmx import JVM_E2E_METRICS_NEW

METRICS = [
    "weblogic.server_runtime.open_sockets_count",
    "weblogic.server.accept_backlog",
    "weblogic.server.threadpool_socket_readers_percent",
    "weblogic.server.max_open_sock_count",
    "weblogic.threadpool_runtime.completed_request_count",
    "weblogic.threadpool_runtime.execute_thread_idle_count",
    "eblogic.threadpool_runtime.execute_thread_total_count",
    "weblogic.threadpool_runtime.pending_user_request_count",
    "weblogic.threadpool_runtime.hogging_thread_count",
    "weblogic.threadpool_runtime.min_threads_constraints_completed",
    "weblogic.threadpool_runtime.min_threads_constraints_pending",
    "weblogic.threadpool_runtime.overload_rejected_requests_count",
    "weblogic.threadpool_runtime.queue_length",
    "weblogic.threadpool_runtime.shared_capacity_for_work_managers",
    "weblogic.threadpool_runtime.standby_thread_count",
    "weblogic.threadpool_runtime.stuck_thread_count",
    "weblogic.threadpool_runtime.throughput",
    "weblogic.jvm_runtime.heap_size",
    "weblogic.jvm_runtime.heap_free",
    "weblogic.jvm_runtime.heap_free_percent",
    "weblogic.jvm_runtime.heap_size_max",
    "weblogic.connector_connection_pool_runtime.active_connections_count",
    "weblogic.connector_connection_pool_runtime.active_connections_high_count",
    "weblogic.connector_connection_pool_runtime.free_connections_count",
    "weblogic.connector_connection_pool_runtime.average_active_usage",
    "weblogic.connector_connection_pool_runtime.connections_created_total",
    "weblogic.jms_runtime.connections_current_count",
    "weblogic.jms_runtime.connections_high_count",
    "weblogic.jms_runtime.connections_total",
    "weblogic.jms_runtime.jms_servers_count",
    "weblogic.jms_runtime.jms_servers_high_count",
    "weblogic.jms_runtime.jms_servers_total",
    "weblogic.work_manager_runtime.completed_requests",
    "weblogic.work_manager_runtime.pending_requests",
    "weblogic.work_manager_runtime.stuck_thread_count",
    "weblogic.server_channel_runtime.accept_count",
    "weblogic.server_channel_runtime.connections_count",
    "weblogic.server_channel_runtime.bytes_received_count",
    "weblogic.server_channel_runtime.bytes_sent_count",
    "weblogic.server_channel_runtime.messages_received_count",
    "weblogic.server_channel_runtime.messages_sent_count",
] + JVM_E2E_METRICS_NEW
