# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
from datadog_checks.dev.jmx import JVM_E2E_METRICS_NEW

METRICS = [
    "weblogic.connector_connection_pool_runtime.active_connections",
    "weblogic.connector_connection_pool_runtime.active_connections_high",
    "weblogic.connector_connection_pool_runtime.free_connections",
    "weblogic.connector_connection_pool_runtime.average_active_usage",
    "weblogic.connector_connection_pool_runtime.connections_created_total",
    "weblogic.jms_runtime.connections_current",
    "weblogic.jms_runtime.connections_high_count",
    "weblogic.jms_runtime.connections_total",
    "weblogic.jms_runtime.jms_servers",
    "weblogic.jms_runtime.jms_servers_high_count",
    "weblogic.jms_runtime.jms_servers_total",
    "weblogic.jvm_runtime.heap_size",
    "weblogic.jvm_runtime.heap_free",
    "weblogic.jvm_runtime.heap_free_percent",
    "weblogic.jvm_runtime.heap_size_max",
    "weblogic.server_runtime.open_sockets",
    "weblogic.server.accept_backlog",
    "weblogic.server.threadpool_socket_readers_percent",
    "weblogic.server.max_open_sock",
    "weblogic.server_channel_runtime.accept",
    "weblogic.server_channel_runtime.connections",
    "weblogic.server_channel_runtime.bytes_received",
    "weblogic.server_channel_runtime.bytes_sent",
    "weblogic.server_channel_runtime.messages_received",
    "weblogic.server_channel_runtime.messages_sent",
    "weblogic.threadpool_runtime.completed_request",
    "weblogic.threadpool_runtime.execute_thread_idle",
    "weblogic.threadpool_runtime.execute_thread_total",
    "weblogic.threadpool_runtime.pending_user_request",
    "weblogic.threadpool_runtime.hogging_thread",
    "weblogic.threadpool_runtime.min_threads_constraints_completed",
    "weblogic.threadpool_runtime.min_threads_constraints_pending",
    "weblogic.threadpool_runtime.overload_rejected_requests",
    "weblogic.threadpool_runtime.queue_length",
    "weblogic.threadpool_runtime.shared_capacity_for_work_managers",
    "weblogic.threadpool_runtime.standby_thread",
    "weblogic.threadpool_runtime.stuck_thread",
    "weblogic.threadpool_runtime.throughput",
    "weblogic.work_manager_runtime.completed_requests",
    "weblogic.work_manager_runtime.pending_requests",
    "weblogic.work_manager_runtime.stuck_thread",
] + JVM_E2E_METRICS_NEW
