# (C) Datadog, Inc. 2010-2017
# All rights reserved
# Licensed under Simplified BSD License (see LICENSE)
from __future__ import print_function, unicode_literals

import os

# the root of the repo
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The requirements file used by the agent
AGENT_REQ_FILE = 'requirements-agent-release.txt'

# Note: these are the names of the folder containing the check
AGENT_BASED_INTEGRATIONS = [
    'active_directory',
    'apache',
    'aspdotnet',
    'btrfs',
    'ceph',
    'cisco_aci',
    'consul',
    'couch',
    'couchbase',
    'datadog_checks_base',
    'directory',
    'disk',
    'dotnetclr',
    'elastic',
    'envoy',
    'exchange_server',
    'haproxy',
    'hdfs_datanode',
    'hdfs_namenode',
    'http_check',
    'iis',
    'istio',
    'kafka_consumer',
    'kube_proxy',
    'kubelet',
    'kyototycoon',
    'lighttpd',
    'linkerd',
    'mapreduce',
    'marathon',
    'mcache',
    'mysql',
    'network',
    'nfsstat',
    'nginx',
    'openstack',
    'oracle',
    'pdh_check',
    'pgbouncer',
    'postgres',
    'powerdns_recursor',
    'prometheus',
    'redisdb',
    'riak',
    'spark',
    'ssh_check',
    'squid',
    'system_core',
    'teamcity',
    'varnish',
    'vsphere',
    'yarn',
]

# These are the integrations that aren't ported to the new pytest format
AGENT_INTEGRATIONS_PRE_PYTEST = [
    'activemq',
    'activemq_xml',
    'amazon_eks',
    'cacti',
    'cassandra',
    'cassandra_nodetool',
    'datadog_checks_tests_helper',
    'dns_check',
    'ecs_fargate',
    'etcd',
    'fluentd',
    'gearmand',
    'gitlab',
    'gitlab_runner',
    'go_expvar',
    'gunicorn',
    'kong',
    'kube_dns',
    'kubernetes',
    'kubernetes_state',
    'linux_proc_extras',
    'mesos_master',
    'mesos_slave',
    'mongo',
    'nagios',
    'ntp',
    'php_fm',
    'postfix',
    'process',
    'rabbitmq',
    'riakcs',
    'snmp',
    'solr',
    'sqlserver',
    'statsd',
    'supervisord',
    'system_swap',
    'tcp_check',
    'tokumx',
    'tomcat',
    'twemproxy',
    'win32_event_log',
    'windows_service',
    'wmi_check',
    'zk',
]

AGENT_V5_ONLY = [
    'agent_metrics',
    'docker_daemon',
    'kubernetes',
    'ntp',
]
