METRIC_MAP = {
    "felix_active_local_endpoints": "felix.active.local_endpoints",
    "felix_active_local_policies": "felix.active.local_policies",
    "felix_active_local_selectors": "felix.active.local_selectors",
    "felix_active_local_tags": "felix.active.local_tags",
    "felix_cluster_num_host_endpoints": "felix.cluster.num_host_endpoints",
    "felix_cluster_num_hosts": "felix.cluster.num_hosts",
    "felix_cluster_num_workload_endpoints": "felix.cluster.num_workload_endpoints",
    "felix_ipset_calls": "felix.ipset.calls",
    "felix_ipset_errors": "felix.ipset.errors",
    "felix_ipsets_calico": "felix.ipsets.calico",
    "felix_ipsets_total": "felix.ipsets.total",
    "felix_iptables_chains": "felix.iptables.chains",
    "felix_iptables_rules": "felix.iptables.rules",
    "felix_iptables_restore_calls": "felix.iptables.restore_calls",
    "felix_iptables_restore_errors": "felix.iptables.restore_errors",
    "felix_iptables_save_calls": "felix.iptables.save_calls",
    "felix_iptables_save_errors": "felix.iptables.save_errors",
    "felix_int_dataplane_failures": "felix.int_dataplane_failures",
}
