# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_collect_cf_metrics():
    return False


def instance_collect_connection_metrics():
    return False


def instance_collect_container_metrics():
    return False


def instance_collect_fcm_connection_metrics():
    return False


def instance_collect_fcm_metrics():
    return False


def instance_collect_group_bufferpool_metrics():
    return False


def instance_collect_index_metrics():
    return False


def instance_collect_table_metrics():
    return False


def instance_collect_wlm_service_class_metrics():
    return False


def instance_connection_metrics_limit():
    return 300


def instance_connection_timeout():
    return 10


def instance_database_instance_collection_interval():
    return 300


def instance_dbm():
    return False


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_exclude_hostname():
    return False


def instance_index_metrics_limit():
    return 1000


def instance_log_unobfuscated_queries():
    return False


def instance_min_collection_interval():
    return 15


def instance_only_custom_queries():
    return False


def instance_port():
    return 50000


def instance_security():
    return 'none'


def instance_table_metrics_limit():
    return 300


def instance_use_global_custom_queries():
    return 'true'
