# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_kafka_cluster_id():
    return 'MkU3OEVBNTcwNTJENDM2Qk'


def instance_min_collection_interval():
    return 15


def instance_sasl_mechanism():
    return 'PLAIN'


def instance_security_protocol():
    return 'PLAINTEXT'
