# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_kafka_cluster_id():
    return 'MkU3OEVBNTcwNTJENDM2Qk'


def instance_min_collection_interval():
    return 15


def instance_sasl_kerberos_principal():
    return 'kafkaclient'


def instance_sasl_kerberos_service_name():
    return 'kafka'


def instance_schema_registry_tls_ca_cert():
    return '/path/to/ca_cert.pem'


def instance_schema_registry_tls_cert():
    return '/path/to/client_cert.pem'


def instance_schema_registry_tls_key():
    return '/path/to/client_key.pem'


def instance_schema_registry_tls_verify():
    return True


def instance_schema_registry_url():
    return 'http://localhost:8081'


def instance_security_protocol():
    return 'PLAINTEXT'


def instance_tls_validate_hostname():
    return True


def instance_tls_verify():
    return True
