# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# Metrics mapping without prefix - use raw_metric_prefix config to strip prefixes like 'n8n_', 'n8n_my_team_', etc.
# Namespace will be applied by the check
METRIC_MAP = {
    'active_workflow_count': 'active.workflow.count',
    'api_request_duration_seconds': 'api.request.duration.seconds',
    'api_requests_total': 'api.requests.total',
    'cache_errors_total': 'cache.errors.total',
    'cache_hits_total': 'cache.hits.total',
    'cache_latency_seconds': 'cache.latency.seconds',
    'cache_misses_total': 'cache.misses.total',
    'cache_operations_total': 'cache.operations.total',
    'eventbus_connections_total': 'eventbus.connections.total',
    'eventbus_events_failed_total': 'eventbus.events.failed.total',
    'eventbus_events_processed_total': 'eventbus.events.processed.total',
    'eventbus_events_total': 'eventbus.events.total',
    'eventbus_queue_size': 'eventbus.queue.size',
    'http_request_duration_seconds': 'http.request.duration.seconds',
    'instance_role_leader': 'instance.role.leader',
    'last_activity': 'last.activity',
    'nodejs_active_handles': 'nodejs.active.handles',
    'nodejs_active_handles_total': 'nodejs.active.handles.total',
    'nodejs_active_requests': 'nodejs.active.requests',
    'nodejs_active_requests_total': 'nodejs.active.requests.total',
    'nodejs_active_resources': 'nodejs.active.resources',
    'nodejs_active_resources_total': 'nodejs.active.resources.total',
    'nodejs_event_loop_lag_seconds': 'nodejs.event.loop.lag.seconds',
    'nodejs_eventloop_lag_max_seconds': 'nodejs.eventloop.lag.max.seconds',
    'nodejs_eventloop_lag_mean_seconds': 'nodejs.eventloop.lag.mean.seconds',
    'nodejs_eventloop_lag_min_seconds': 'nodejs.eventloop.lag.min.seconds',
    'nodejs_eventloop_lag_p50_seconds': 'nodejs.eventloop.lag.p50.seconds',
    'nodejs_eventloop_lag_p90_seconds': 'nodejs.eventloop.lag.p90.seconds',
    'nodejs_eventloop_lag_p99_seconds': 'nodejs.eventloop.lag.p99.seconds',
    'nodejs_eventloop_lag_seconds': 'nodejs.eventloop.lag.seconds',
    'nodejs_eventloop_lag_stddev_seconds': 'nodejs.eventloop.lag.stddev.seconds',
    'nodejs_external_memory_bytes': 'nodejs.external.memory.bytes',
    'nodejs_gc_duration_seconds': 'nodejs.gc.duration.seconds',
    'nodejs_heap_size_total_bytes': 'nodejs.heap.size.total.bytes',
    'nodejs_heap_size_used_bytes': 'nodejs.heap.size.used.bytes',
    'nodejs_heap_space_size_available_bytes': 'nodejs.heap.space.size.available.bytes',
    'nodejs_heap_space_size_total_bytes': 'nodejs.heap.space.size.total.bytes',
    'nodejs_heap_space_size_used_bytes': 'nodejs.heap.space.size.used.bytes',
    'nodejs_heap_total_bytes': 'nodejs.heap.total.bytes',
    'nodejs_heap_used_bytes': 'nodejs.heap.used.bytes',
    'nodejs_version_info': 'nodejs.version.info',
    'process_cpu_system_seconds_total': 'process.cpu.system.seconds.total',
    'process_cpu_user_seconds_total': 'process.cpu.user.seconds.total',
    'process_heap_bytes': 'process.heap.bytes',
    'process_max_fds': 'process.max.fds',
    'process_open_fds': 'process.open.fds',
    'process_resident_memory_bytes': 'process.resident.memory.bytes',
    'process_start_time_seconds': 'process.start.time.seconds',
    'process_virtual_memory_bytes': 'process.virtual.memory.bytes',
    'queue_job_attempts_total': 'queue.job.attempts.total',
    'queue_jobs_duration_seconds': 'queue.jobs.duration.seconds',
    'queue_jobs_total': 'queue.jobs.total',
    'workflow_executions_active': 'workflow.executions.active',
    'workflow_executions_duration_seconds': 'workflow.executions.duration.seconds',
    'workflow_executions_total': 'workflow.executions.total',
    'process_cpu_seconds_total': 'process.cpu.seconds.total',
    'version_info': 'version.info',
}