# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from __future__ import annotations

from types import MappingProxyType
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from datadog_checks.base.utils.functions import identity
from datadog_checks.base.utils.models import validation

from . import defaults, validators


class CompletedQuerySamples(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        frozen=True,
    )
    collection_interval: Optional[float]
    enabled: Optional[bool]
    max_samples_per_collection: Optional[float]
    run_sync: Optional[bool]
    samples_per_hour_per_query: Optional[float]
    seen_samples_cache_maxsize: Optional[float]


class CustomQuery(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        frozen=True,
    )
    collection_interval: Optional[int]
    columns: Optional[tuple[MappingProxyType[str, Any], ...]]
    metric_prefix: Optional[str]
    query: Optional[str]
    tags: Optional[tuple[str, ...]]


class MetricPatterns(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        frozen=True,
    )
    exclude: Optional[tuple[str, ...]]
    include: Optional[tuple[str, ...]]


class QueryActivity(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        frozen=True,
    )
    collection_interval: Optional[float]
    enabled: Optional[bool]
    payload_row_limit: Optional[int]
    run_sync: Optional[bool]


class QueryMetrics(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        frozen=True,
    )
    collection_interval: Optional[float]
    enabled: Optional[bool]
    full_statement_text_cache_max_size: Optional[float]
    full_statement_text_samples_per_hour_per_query: Optional[float]
    run_sync: Optional[bool]


class InstanceConfig(BaseModel):
    model_config = ConfigDict(
        validate_default=True,
        arbitrary_types_allowed=True,
        frozen=True,
    )
    completed_query_samples: Optional[CompletedQuerySamples] = None
    compression: Optional[str] = None
    connect_timeout: Optional[int] = None
    custom_queries: Optional[tuple[CustomQuery, ...]] = None
    database_instance_collection_interval: Optional[float] = None
    db: Optional[str] = None
    dbm: Optional[bool] = None
    disable_generic_tags: Optional[bool] = None
    empty_default_hostname: Optional[bool] = None
    enable_legacy_tags_normalization: Optional[bool] = None
    metric_patterns: Optional[MetricPatterns] = None
    min_collection_interval: Optional[float] = None
    only_custom_queries: Optional[bool] = None
    password: Optional[str] = None
    port: Optional[int] = None
    query_activity: Optional[QueryActivity] = None
    query_metrics: Optional[QueryMetrics] = None
    read_timeout: Optional[int] = None
    server: str
    service: Optional[str]
    single_endpoint_mode: Optional[bool]
    tags: Optional[tuple[str, ...]]
    tls_ca_cert: Optional[str]
    tls_verify: Optional[bool]
    use_global_custom_queries: Optional[str]
    username: Optional[str]
    verify: Optional[bool]

    @model_validator(mode='before')
    def _initial_validation(cls, values):
        return validation.core.initialize_config(getattr(validators, 'initialize_instance', identity)(values))

    @field_validator('*', mode='before')
    def _validate(cls, value, info):
        field = cls.model_fields[info.field_name]
        field_name = field.alias or info.field_name
        if field_name in info.context['configured_fields']:
            value = getattr(validators, f'instance_{info.field_name}', identity)(value, field=field)
        else:
            value = getattr(defaults, f'instance_{info.field_name}', lambda: value)()

        return validation.utils.make_immutable(value)

    @model_validator(mode='after')
    def _final_validation(cls, model):
        return validation.core.check_model(getattr(validators, 'check_instance', identity)(model))
