name: Traefik Mesh
fleet_configurable: true
files:
  - name: traefik_mesh.yaml
    discovery:
      strategies:
      - strategy: local:from_traefik_mesh_kube_daemon_set
        provides:
        - endpoints
        inputs: {}
        candidates:
        - openmetrics_endpoint: "{endpoints.openmetrics_endpoint}"
          traefik_proxy_api_endpoint: "{endpoints.traefik_proxy_api_endpoint}"
    options:
    - template: init_config
      options:
      - template: init_config/openmetrics
    - template: instances
      options:
      - template: instances/openmetrics
        overrides:
          openmetrics_endpoint.required: true
          openmetrics_endpoint.value.example: http://<PROXY_ENDPOINT>:<METRICS_PORT>
          openmetrics_endpoint.description: |
            Endpoint exposing the Traefic Proxy Prometheus metrics. For more information refer to:
            https://doc.traefik.io/traefik/observability/metrics/prometheus/
      - name: traefik_proxy_api_endpoint
        fleet_configurable: true
        formats: ["url"]
        required: false
        description: URL of the Traefik Mesh proxy to query.
        value:
          example: HTTP://<PROXY_ENDPOINT>:<API_PORT>
          pattern: \w+
          type: string
      - name: traefik_controller_api_endpoint
        fleet_configurable: true
        formats: ["url"]
        required: false
        description: URL of the Traefik Mesh controller to query.
        value:
          example: HTTP://<CONTROLLER_ENDPOINT>:<API_PORT>
          pattern: \w+
          type: string
  - name: auto_conf.yaml
    options:
    - template: ad_identifiers
      overrides:
        value.example:
        - traefik
    - template: auto_conf/discovery
