# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

METRIC_MAP = {
    'podVolume_data_download_cancel': 'pod_volume.data.download.cancel',
    'podVolume_data_download_failure': 'pod_volume.data.download.failure',
    'podVolume_data_download_success': 'pod_volume.data.download.success',
    'podVolume_data_upload_cancel': 'pod_volume.data.upload.cancel',
    'podVolume_data_upload_failure': 'pod_volume.data.upload.failure',
    'podVolume_data_upload_success': 'pod_volume.data.upload.success',
    'podVolume_pod_volume_backup_dequeue_count': 'pod_volume.backup.dequeue',
    'podVolume_pod_volume_backup_enqueue_count': 'pod_volume.backup.enqueue',
    'podVolume_pod_volume_operation_latency_seconds': 'pod_volume.operation_latency.seconds',
    'podVolume_pod_volume_operation_latency_seconds_gauge': 'pod_volume.operation_latency.seconds.gauge',
    'velero_backup_attempt': 'backup.attempt',
    'velero_backup_deletion_attempt': 'backup.deletion.attempt',
    'velero_backup_deletion_failure': 'backup.deletion.failure',
    'velero_backup_deletion_success': 'backup.deletion.success',
    'velero_backup_duration_seconds': 'backup.duration.seconds',
    'velero_backup_failure': 'backup.failure',
    'velero_backup_items_errors': 'backup.items.errors',
    'velero_backup_items_total': 'backup.items',
    'velero_backup_last_status': 'backup.last_status',
    'velero_backup_last_successful_timestamp': 'backup.last_successful_timestamp',
    'velero_backup_partial_failure': 'backup.partial_failure',
    'velero_backup_success': 'backup.success',
    'velero_backup_tarball_size_bytes': 'backup.tarball_size_bytes',
    'velero_backup_total': 'backup.amount',
    'velero_backup_validation_failure': 'backup.validation_failure',
    'velero_backup_warning': 'backup.warning',
    'velero_csi_snapshot_attempt': 'csi_snapshot.attempt',
    'velero_csi_snapshot_failure': 'csi_snapshot.failure',
    'velero_csi_snapshot_success': 'csi_snapshot.success',
    'velero_restore_attempt': 'restore.attempt',
    'velero_restore_failed': 'restore.failed',
    'velero_restore_partial_failure': 'restore.partial_failure',
    'velero_restore_success': 'restore.success',
    'velero_restore_total': 'restore.amount',
    'velero_restore_validation_failed': 'restore.validation_failed',
    'velero_volume_snapshot_attempt': 'volume_snapshot.attempt',
    'velero_volume_snapshot_failure': 'volume_snapshot.failure',
    'velero_volume_snapshot_success': 'volume_snapshot.success',
}
