# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_collect_client_metrics(_field, _value):
    return False


def instance_command_stats(_field, _value):
    return False


def instance_db(_field, _value):
    return 0


def instance_disable_connection_cache(_field, _value):
    return False


def instance_disable_generic_tags(_field, _value):
    return False


def instance_empty_default_hostname(_field, _value):
    return False


def instance_keys(field, value):
    return get_default_field_value(field, value)


def instance_metric_patterns(field, value):
    return get_default_field_value(field, value)


def instance_min_collection_interval(_field, _value):
    return 15


def instance_password(field, value):
    return get_default_field_value(field, value)


def instance_service(field, value):
    return get_default_field_value(field, value)


def instance_slowlog_max_len(_field, _value):
    return 128


def instance_socket_timeout(_field, _value):
    return 5


def instance_ssl(_field, _value):
    return False


def instance_ssl_ca_certs(field, value):
    return get_default_field_value(field, value)


def instance_ssl_cert_reqs(_field, _value):
    return 2


def instance_ssl_certfile(field, value):
    return get_default_field_value(field, value)


def instance_ssl_keyfile(field, value):
    return get_default_field_value(field, value)


def instance_tags(field, value):
    return get_default_field_value(field, value)


def instance_unix_socket_path(field, value):
    return get_default_field_value(field, value)


def instance_username(field, value):
    return get_default_field_value(field, value)


def instance_warn_on_missing_keys(_field, _value):
    return True
