# (C) Datadog, Inc. 2023-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# E501: line too long (XXX > 120 characters)
# flake8: noqa: E501
# Source for metric names: https://github.com/temporalio/temporal/blob/17e06952d471f86d106af0158419d9e288371585/common/metrics/metric_defs.go
METRIC_MAP = {
    # General
    'service_requests': 'service.requests',
    'service_pending_requests': 'service.pending_requests',
    'service_errors': 'service.errors',
    'service_error_with_type': 'service.error_with_type',
    'service_errors_resource_exhausted': 'service.errors.resource_exhausted',
    'service_panics': 'service.panics',
    'service_errors_invalid_argument': 'service.errors.invalid_argument',
    'service_errors_namespace_not_active': 'service.errors.namespace_not_active',
    'service_errors_entity_not_found': 'service.errors.entity_not_found',
    'service_errors_execution_already_started': 'service.errors.execution_already_started',
    'service_errors_context_timeout': 'service.errors.context_timeout',
    'service_errors_retry_task': 'service.errors.retry_task',
    'service_errors_incomplete_history': 'service.errors.incomplete_history',
    'service_errors_nondeterministic': 'service.errors.nondeterministic',
    'service_errors_unauthorized': 'service.errors.unauthorized',
    'service_errors_authorize_failed': 'service.errors.authorize_failed',
    'service_latency': 'service.latency',
    'service_latency_nouserlatency': 'service.latency.nouserlatency',
    'service_latency_userlatency': 'service.latency.userlatency',
    'action': 'action',
    'certificates_expired': 'certificates.expired',
    'certificates_expiring': 'certificates.expiring',
    'service_authorization_latency': 'service.authorization_latency',
    'event_blob_size': 'event.blob_size',
    'lock_requests': 'lock.requests',
    'lock_latency': 'lock.latency',
    'client_requests': 'client.requests',
    'client_errors': 'client.errors',
    'client_latency': 'client.latency',
    'client_redirection_requests': 'client.redirection.requests',
    'client_redirection_errors': 'client.redirection.errors',
    'client_redirection_latency': 'client.redirection.latency',
    'state_transition_count': 'state_transition',
    'history_size': 'history.size',
    'history_count': 'history',
    'search_attributes_size': 'search_attributes_size',
    'memo_size': 'memo_size',
    'wf_too_many_pending_child_workflows': 'wf_too_many_pending.child_workflows',
    'wf_too_many_pending_activities': 'wf_too_many_pending.activities',
    'wf_too_many_pending_cancel_requests': 'wf_too_many_pending.cancel_requests',
    'wf_too_many_pending_external_workflow_signals': 'wf_too_many_pending.external_workflow_signals',
    # Frontend
    'add_search_attributes_workflow_success': 'add_search_attributes.workflow_success',
    'add_search_attributes_workflow_failure': {
        'name': 'add_search_attributes.workflow_failure',
        'type': 'native_dynamic',
    },
    'version_check_success': 'version_check.success',
    'version_check_failed': 'version_check.failed',
    'version_check_request_failed': 'version_check.request_failed',
    'version_check_latency': 'version_check.latency',
    # History
    'cache_requests': 'cache.requests',
    'cache_errors': 'cache.errors',
    'cache_latency': 'cache.latency',
    'cache_miss': 'cache.miss',
    'cache_size': 'cache.size',
    'cache_usage': 'cache.usage',
    'cache_pinned_usage': 'cache.pinned_usage',
    'cache_ttl': 'cache.ttl',
    'cache_entry_age_on_get': 'cache.entry_age_on_get',
    'cache_entry_age_on_eviction': 'cache.entry_age_on_eviction',
    'history_event_notification_queueing_latency': 'history.event_notification.queueing_latency',
    'history_event_notification_fanout_latency': 'history.event_notification.fanout_latency',
    'history_event_notification_inflight_message_gauge': 'history.event_notification.inflight_message',
    'history_event_notification_fail_delivery_count': 'history.event_notification.fail_delivery',
    'archival_task_invalid_uri': 'archival.task_invalid_uri',
    'archiver_archive_latency': 'archiver.archive.latency',
    'archiver_archive_target_latency': 'archiver.archive.target_latency',
    'shard_closed_count': 'shard_closed',
    'sharditem_created_count': 'sharditem.created',
    'sharditem_removed_count': 'sharditem.removed',
    'sharditem_acquisition_latency': 'sharditem.acquisition_latency',
    'syncshard_remote_count': 'syncshard.remote',
    'syncshard_remote_failed': 'syncshard.remote.failed',
    'task_requests': 'task.requests',
    'task_latency_load': 'task.latency.load',
    'task_latency_schedule': 'task.latency.schedule',
    'task_latency_processing': 'task.latency.processing',
    'task_latency': 'task.latency',
    'task_latency_queue': 'task.latency.queue',
    'task_attempt': 'task.attempt',
    'task_errors': 'task.errors',
    'task_errors_discarded': 'task.errors.discarded',
    'task_skipped': 'task.skipped',
    'task_errors_version_mismatch': 'task.errors.version_mismatch',
    'task_dependency_task_not_completed': 'task.dependency_task_not_completed',
    'task_errors_standby_retry_counter': 'task.errors.standby_retry_counter',
    'task_errors_workflow_busy': 'task.errors.workflow_busy',
    'task_errors_not_active_counter': 'task.errors.not_active_counter',
    'task_errors_namespace_handover': 'task.errors.namespace_handover',
    'task_errors_throttled': 'task.errors.throttled',
    'task_errors_corruption': 'task.errors.corruption',
    'task_terminal_failures': 'task.terminal_failures',
    'task_dlq_failures': 'task.dlq_failures',
    'task_dlq_latency': 'task.dlq_latency',
    'task_schedule_to_start_latency': 'task.schedule_to_start_latency',
    'task_batch_complete_counter': 'task.batch_complete_counter',
    'task_rescheduler_pending_tasks': 'task_rescheduler.pending_tasks',
    'pending_tasks': 'pending_tasks',
    'task_scheduler_throttled': 'task_scheduler.throttled',
    'queue_latency_schedule': 'queue.latency_schedule',
    'queue_reader_count': 'queue.reader',
    'queue_slice_count': 'queue.slice',
    'queue_actions': 'queue.actions',
    'activity_end_to_end_latency': 'activity.end_to_end_latency',
    'ack_level_update': 'ack_level.update',
    'ack_level_update_failed': 'ack_level.update.failed',
    'accept_workflow_update_message': 'accept_workflow_update_message',
    'reject_workflow_update_message': 'reject_workflow_update_message',
    'activity_eager_execution': 'activity.eager_execution',
    'workflow_eager_execution': 'workflow.eager_execution',
    'workflow_eager_execution_denied': 'workflow.eager_execution.denied',
    'empty_completion_commands': 'empty_completion_commands',
    'multiple_completion_commands': 'multiple_completion_commands',
    'failed_workflow_tasks': 'failed_workflow_tasks',
    'workflow_task_attempt': 'workflow.task.attempt',
    'stale_mutable_state': 'stale_mutable_state',
    'auto_reset_points_exceed_limit': 'auto_reset_points.exceed_limit',
    'auto_reset_point_corruption': 'auto_reset_point.corruption',
    'concurrency_update_failure': 'concurrency_update_failure',
    'service_errors_shard_ownership_lost': 'service.errors.shard_ownership_lost',
    'heartbeat_timeout': 'heartbeat.timeout',
    'schedule_to_start_timeout': 'schedule_to_start.timeout',
    'start_to_close_timeout': 'start_to_close.timeout',
    'schedule_to_close_timeout': 'schedule_to_close.timeout',
    'new_timer_notifications': 'new_timer_notifications',
    'acquire_shards_count': 'acquire_shards',
    'acquire_shards_latency': 'acquire_shards.latency',
    'membership_changed_count': 'membership_changed',
    'numshards_gauge': 'numshards',
    'get_engine_for_shard_errors': 'get_engine_for_shard.errors',
    'get_engine_for_shard_latency': 'get_engine_for_shard.latency',
    'remove_engine_for_shard_latency': 'remove_engine_for_shard.latency',
    'complete_workflow_task_sticky_enabled_count': 'complete_workflow_task_sticky.enabled',
    'complete_workflow_task_sticky_disabled_count': 'complete_workflow_task_sticky.disabled',
    'workflow_task_heartbeat_timeout_count': 'workflow.task.heartbeat_timeout',
    'duplicate_replication_events': 'duplicate_replication_events',
    'replication_tasks_applied': 'replication.tasks.applied',
    'replication_tasks_failed': 'replication.tasks.failed',
    'replication_tasks_lag': 'replication.tasks.lag',
    'replication_latency': 'replication.latency',
    'replication_tasks_fetched': 'replication.tasks.fetched',
    'replication_dlq_enqueue_failed': 'replication.dlq.enqueue_failed',
    'replication_dlq_max_level': 'replication.dlq.max_level',
    'replication_dlq_ack_level': 'replication.dlq.ack_level',
    'event_reapply_skipped_count': 'event.reapply_skipped',
    'direct_query_dispatch_latency': 'direct_query_dispatch.latency',
    'direct_query_dispatch_sticky_latency': 'direct_query_dispatch.sticky.latency',
    'direct_query_dispatch_non_sticky_latency': 'direct_query_dispatch.non_sticky.latency',
    'direct_query_dispatch_sticky_success': 'direct_query_dispatch.sticky.success',
    'direct_query_dispatch_non_sticky_success': 'direct_query_dispatch.non_sticky.success',
    'direct_query_dispatch_clear_stickiness_latency': 'direct_query_dispatch.clear_stickiness.latency',
    'direct_query_dispatch_clear_stickiness_success': 'direct_query_dispatch.clear_stickiness.success',
    'direct_query_dispatch_timeout_before_non_sticky': 'direct_query_dispatch.timeout_before_non_sticky',
    'workflow_task_query_latency': 'workflow.task.query_latency',
    'consistent_query_timeout': 'consistent_query_timeout',
    'query_buffer_exceeded': 'query_buffer_exceeded',
    'query_registry_invalid_state': 'query_registry_invalid_state',
    'workflow_task_timeout_overrides': 'workflow.task.timeout_overrides',
    'workflow_run_timeout_overrides': 'workflow.run_timeout_overrides',
    'replication_task_cleanup_count': 'replication.task_cleanup',
    'replication_task_cleanup_failed': 'replication.task_cleanup.failed',
    'mutable_state_checksum_mismatch': 'mutable_state_checksum.mismatch',
    'mutable_state_checksum_invalidated': 'mutable_state_checksum.invalidated',
    'closed_workflow_buffer_event_counter': 'closed_workflow_buffer_event_counter',
    # Matching
    'forwarded': 'forwarded',
    'invalid_task_queue_name': 'invalid_task_queue_name',
    'syncmatch_latency': 'syncmatch.latency',
    'asyncmatch_latency': 'asyncmatch.latency',
    'poll_success': 'poll.success',
    'poll_timeouts': 'poll.timeouts',
    'poll_success_sync': 'poll.success_sync',
    'lease_requests': 'lease.requests',
    'lease_failures': 'lease.failures',
    'condition_failed_errors': 'condition_failed_errors',
    'respond_query_failed': 'respond_query_failed',
    'sync_throttle_count': 'sync_throttle',
    'buffer_throttle_count': 'buffer_throttle',
    'tasks_expired': 'tasks_expired',
    'forwarded_per_tl': 'forwarded_per_tl',
    'local_to_local_matches': 'local_to_local.matches',
    'local_to_remote_matches': 'local_to_remote.matches',
    'remote_to_local_matches': 'remote_to_local.matches',
    'remote_to_remote_matches': 'remote_to_remote.matches',
    'loaded_task_queue_count': 'loaded_task_queue_count',
    'task_queue_started': 'task_queue.started',
    'task_queue_stopped': 'task_queue.stopped',
    'task_write_throttle_count': 'task.write.throttle',
    'task_write_latency': 'task.write.latency',
    'task_lag_per_tl': 'task.lag_per_tl',
    'no_poller_tasks': 'no_poller_tasks',
    # Worker
    'executor_done': 'executor.done',
    'executor_err': 'executor.err',
    'executor_deferred': 'executor.deferred',
    'executor_dropped': 'executor.dropped',
    'started': 'started',
    'stopped': 'stopped',
    'task_processed': 'task.processed',
    'task_deleted': 'task.deleted',
    'taskqueue_processed': 'taskqueue.processed',
    'taskqueue_deleted': 'taskqueue.deleted',
    'taskqueue_outstanding': 'taskqueue.outstanding',
    'history_archiver_archive_non_retryable_error': 'history.archiver.archive.non_retryable_error',
    'history_archiver_archive_transient_error': 'history.archiver.archive.transient_error',
    'history_archiver_archive_success': 'history.archiver.archive.success',
    'history_archiver_total_upload_size': 'history.archiver.total_upload_size',
    'history_archiver_history_size': 'history.archiver.history_size',
    'history_archiver_duplicate_archivals': 'history.archiver.duplicate_archivals',
    'history_archiver_blob_exists': 'history.archiver.blob_exists',
    'history_archiver_blob_size': 'history.archiver.blob_size',
    'history_workflow_execution_cache_latency': 'history.workflow_execution_cache_latency',
    'visibility_archiver_archive_non_retryable_error': 'visibility.archiver.archive.non_retryable_error',
    'visibility_archiver_archive_transient_error': 'visibility.archiver.archive.transient_error',
    'visibility_archiver_archive_success': 'visibility.archiver.archive.success',
    'scavenger_success': 'scavenger.success',
    'scavenger_errors': 'scavenger.errors',
    'scavenger_skips': 'scavenger.skips',
    'executions_outstanding': 'executions_outstanding',
    'scavenger_validation_requests': 'scavenger.validation.requests',
    'scavenger_validation_failures': 'scavenger.validation.failures',
    'scavenger_validation_skips': 'scavenger.validation.skips',
    'add_search_attributes_failures': 'add_search_attributes.failures',
    'delete_executions_success': 'delete_executions.success',
    'batcher_processor_requests': 'batcher.processor_requests',
    'batcher_processor_errors': 'batcher.processor_errors',
    'batcher_operation_errors': 'batcher.operation_errors',
    'elasticsearch_bulk_processor_requests': 'elasticsearch.bulk_processor.requests',
    'elasticsearch_bulk_processor_queued_requests': 'elasticsearch.bulk_processor.queued_requests',
    'elasticsearch_bulk_processor_errors': 'elasticsearch.bulk_processor.errors',
    'elasticsearch_bulk_processor_corrupted_data': 'elasticsearch.bulk_processor.corrupted_data',
    'elasticsearch_bulk_processor_duplicate_request': 'elasticsearch.bulk_processor.duplicate_request',
    'elasticsearch_bulk_processor_request_latency': 'elasticsearch.bulk_processor.request.latency',
    'elasticsearch_bulk_processor_commit_latency': 'elasticsearch.bulk_processor.commit.latency',
    'elasticsearch_bulk_processor_wait_add_latency': 'elasticsearch.bulk_processor.wait_add.latency',
    'elasticsearch_bulk_processor_wait_start_latency': 'elasticsearch.bulk_processor.wait_start.latency',
    'elasticsearch_bulk_processor_bulk_size': 'elasticsearch.bulk_processor.bulk_size',
    'elasticsearch_document_parse_failures_counter': 'elasticsearch.document.parse_failures_counter',
    'elasticsearch_document_generate_failures_counter': 'elasticsearch.document.generate_failures_counter',
    'catchup_ready_shard_count': 'catchup.ready_shard_count',
    'handover_ready_shard_count': 'handover.ready_shard_count',
    'replicator_messages': 'replicator.messages',
    'replicator_errors': 'replicator.errors',
    'replicator_latency': 'replicator.latency',
    'replicator_dlq_enqueue_fails': 'replicator.dlq_enqueue_fails',
    'namespace_replication_dlq_enqueue_requests': 'namespace_replication.dlq_enqueue_requests',
    'parent_close_policy_processor_requests': 'parent_close_policy_processor.requests',
    'parent_close_policy_processor_errors': 'parent_close_policy_processor.errors',
    'schedule_missed_catchup_window': 'schedule.missed_catchup_window',
    'schedule_rate_limited': 'schedule.rate_limited',
    'schedule_buffer_overruns': 'schedule.buffer_overruns',
    'schedule_action_success': 'schedule.action.success',
    'schedule_action_errors': 'schedule.action.errors',
    'schedule_cancel_workflow_errors': 'schedule.cancel_workflow.errors',
    'schedule_terminate_workflow_errors': 'schedule.terminate_workflow.errors',
    # Replication
    'namespace_replication_task_ack_level': 'namespace_replication.task_ack_level',
    'namespace_dlq_ack_level': 'namespace_dlq.ack_level',
    'namespace_dlq_max_level': 'namespace_dlq.max_level',
    # Persistence
    'persistence_requests': 'persistence.requests',
    'persistence_errors': 'persistence.errors',
    'persistence_error_with_type': 'persistence.error_with_type',
    'persistence_latency': 'persistence.latency',
    'persistence_errors_resource_exhausted': 'persistence.errors.resource_exhausted',
    'visibility_persistence_requests': 'visibility.persistence.requests',
    'visibility_persistence_error_with_type': 'visibility.persistence.error_with_type',
    'visibility_persistence_errors': 'visibility.persistence.errors',
    'visibility_persistence_resource_exhausted': 'visibility.persistence.resource_exhausted',
    'visibility_persistence_latency': 'visibility.persistence.latency',
    # HTTP/Nexus
    'http_service_requests': 'http.service_requests',
    'nexus_request_preprocess_errors': 'nexus.request_preprocess_errors',
    'nexus_completion_request_preprocess_errors': 'nexus.completion_request_preprocess_errors',
    # Dynamic Worker Pool
    'dynamic_worker_pool_scheduler_dequeued_tasks': 'dynamic_worker_pool.scheduler_dequeued_tasks',
    'dynamic_worker_pool_scheduler_rejected_tasks': 'dynamic_worker_pool.scheduler_rejected_tasks',
    # Host/Rate Limit
    'host_rps_limit': 'host.rps_limit',
    'namespace_host_rps_limit': 'namespace_host.rps_limit',
    'handover_wait_latency': 'handover_wait_latency',
    # Deadlock detector metrics
    'dd_cluster_metadata_lock_latency': 'dd.cluster_metadata.lock_latency',
    'dd_cluster_metadata_callback_lock_latency': 'dd.cluster_metadata.callback.lock_latency',
    'dd_shard_controller_lock_latency': 'dd.shard_controller.lock_latency',
    'dd_shard_lock_latency': 'dd.shard.lock_latency',
    'dd_shard_io_semaphore_latency': 'dd.shard.io_semaphore_latency',
    'dd_namespace_registry_lock_latency': 'dd.namespace_registry.lock_latency',
    # Task metrics
    'task_errors_internal': 'task.errors.internal',
    'task_dispatch_latency': 'task.dispatch_latency',
    'task_rewrites': 'task.rewrites',
    'batchable_task_batch_count': 'batchable_task.batch_count',
    # Workflow metrics
    'speculative_workflow_task_commits': 'workflow.speculative_task.commits',
    'speculative_workflow_task_rollbacks': 'workflow.speculative_task.rollbacks',
    'workflow_update_registry_size': 'workflow.update.registry_size',
    'workflow_update_registry_size_limited': 'workflow.update.registry_size_limited',
    'workflow_update_request_rate_limited': 'workflow.update.request_rate_limited',
    'workflow_update_request_too_many': 'workflow.update.request_too_many',
    'workflow_update_aborted': 'workflow.update.aborted',
    'workflow_update_continue_as_new_suggestions': 'workflow.update.continue_as_new_suggestions',
    'workflow_update_sent_to_worker': 'workflow.update.sent_to_worker',
    'workflow_update_sent_to_worker_again': 'workflow.update.sent_to_worker_again',
    'workflow_update_wait_stage_accepted': 'workflow.update.wait_stage_accepted',
    'workflow_update_wait_stage_completed': 'workflow.update.wait_stage_completed',
    'workflow_update_client_timeout': 'workflow.update.client_timeout',
    'workflow_update_server_timeout': 'workflow.update.server_timeout',
    'workflow_delayed_start_backoff_timer': 'workflow.delayed_start_backoff.timer',
    'workflow_backoff_timer': 'workflow.backoff.timer',
    # Replication metrics
    'replication_task_transmission_latency': 'replication.task.transmission_latency',
    'replication_task_send_attempt': 'replication.task.send_attempt',
    'replication_task_send_backlog': 'replication.task.send_backlog',
    'replication_task_send_error': 'replication.task.send_error',
    'replication_task_send_latency': 'replication.task.send_latency',
    'replication_task_processing_latency': 'replication.task.processing_latency',
    'replication_task_generation_latency': 'replication.task.generation_latency',
    'replication_task_load_latency': 'replication.task.load_latency',
    'replication_task_load_size': 'replication.task.load_size',
    'replication_tasks_send': 'replication.tasks.send',
    'replication_tasks_recv': 'replication.tasks.recv',
    'replication_tasks_recv_backlog': 'replication.tasks.recv_backlog',
    'replication_tasks_skipped': 'replication.tasks.skipped',
    'replication_dlq_non_empty': 'replication.dlq.non_empty',
    'replication_service_error': 'replication.service_error',
    'replication_stream_error': 'replication.stream_error',
    'replication_stream_panic': 'replication.stream_panic',
    'replication_stream_stuck': 'replication.stream_stuck',
    'replication_duplicated_task': 'replication.duplicated_task',
    'replication_outlier_namespace': 'replication.outlier_namespace',
    # Verification metrics
    'verify_replication_task_success': 'verify.replication_task.success',
    'verify_replication_task_not_found': 'verify.replication_task.not_found',
    'verify_replication_task_failed': 'verify.replication_task.failed',
    'verify_replication_tasks_latency': 'verify.replication_tasks.latency',
    'verify_describe_mutable_state_latency': 'verify.describe_mutable_state.latency',
    'generate_replication_tasks_latency': 'generate.replication_tasks.latency',
    # Encounter metrics
    'encounter_zombie_workflow_count': 'encounter.zombie_workflow',
    'encounter_not_found_workflow_count': 'encounter.not_found_workflow',
    'encounter_pass_retention_workflow_count': 'encounter.pass_retention_workflow',
    # Matching metrics
    'invalid_task_queue_partition': 'invalid_task_queue_partition',
    'loaded_task_queue_family_count': 'loaded_task_queue_family',
    'loaded_task_queue_partition_count': 'loaded_task_queue_partition',
    'force_loaded_task_queue_partitions_count': 'force_loaded_task_queue_partitions',
    'force_loaded_task_queue_partition_unnecessarily_count': 'force_loaded_task_queue_partition_unnecessarily',
    'unknown_build_polls': 'unknown_build_polls',
    'unknown_build_tasks': 'unknown_build_tasks',
    'poll_latency': 'poll.latency',
    'respond_nexus_failed': 'respond_nexus.failed',
    # State metrics
    'state_machine_timer_processing_failures': 'state_machine.timer_processing_failures',
    'state_machine_timer_skips': 'state_machine.timer_skips',
    # Shard metrics
    'shard_linger_success': 'shard.linger_success',
    'shard_linger_timeouts': 'shard.linger_timeouts',
    # Command metrics
    'command': 'command',
    # Circuit breaker metrics
    'circuit_breaker_executable_blocked': 'circuit_breaker.executable_blocked',
    # Rate limiter metrics
    'rate_limited_task_runnable_wait_time': 'rate_limited_task.runnable_wait_time',
    # Dynamic worker pool metrics
    'dynamic_worker_pool_scheduler_buffer_size': 'dynamic_worker_pool.scheduler_buffer_size',
    'dynamic_worker_pool_scheduler_active_workers': 'dynamic_worker_pool.scheduler_active_workers',
    'dynamic_worker_pool_scheduler_enqueued_tasks': 'dynamic_worker_pool.scheduler_enqueued_tasks',
    # Persistence metrics
    'persistence_shard_rps': 'persistence.shard_rps',
    'persistence_session_refresh_failures': 'persistence.session_refresh_failures',
    'persistence_session_refresh_attempts': 'persistence.session_refresh_attempts',
    # Memory metrics
    'memory_allocated': 'memory.allocated',
    'memory_heap': 'memory.heap',
    'memory_heap_objects': 'memory.heap_objects',
    'memory_heapidle': 'memory.heapidle',
    'memory_heapinuse': 'memory.heapinuse',
    'memory_stack': 'memory.stack',
    'memory_mallocs': 'memory.mallocs',
    'memory_frees': 'memory.frees',
    'memory_num_gc': 'memory.num_gc',
    'memory_gc_pause_ms': 'memory.gc_pause_ms',
    'memory_num_gc_last': 'memory.num_gc_last',
    'memory_pause_total_ns_last': 'memory.pause_total_ns_last',
    # Process metrics
    'restarts': 'restarts',
    'num_goroutines': 'num_goroutines',
    'gomaxprocs': 'gomaxprocs',
    # Finalizer metrics
    'finalizer_items_completed': 'finalizer.items_completed',
    'finalizer_items_unfinished': 'finalizer.items_unfinished',
    'finalizer_latency': 'finalizer.latency',
    # Activity metrics
    'paused_activities': 'paused_activities',
    # Signal metrics
    'signal_request_id_size': 'signal_request_id.size',
    'signal_request_id_count': 'signal_request_id',
    # Total metrics
    'total_activity_count': 'total.activity',
    'total_user_timer_count': 'total.user_timer',
    'total_signal_count': 'total.signal',
    'total_signal_external_count': 'total.signal_external',
    'total_request_cancel_external_count': 'total.request_cancel_external',
    'total_child_execution_count': 'total.child_execution',
    # Chasm metrics
    'chasm_total_size': 'chasm.total_size',
    # Reachability metrics
    'reachability_exit_point_count': 'reachability.exit_point',
    # Start workflow metrics
    'start_workflow_request_deduped': 'start_workflow.request_deduped',
    # Out of order metrics
    'out_of_order_buffered_events': 'out_of_order.buffered_events',
    # Approximate metrics
    'approximate_backlog_count': 'approximate.backlog_count',
    'approximate_backlog_age_seconds': 'approximate.backlog_age_seconds',
    # Time metrics
    'time_between_shardinfo_update': 'time_between_shardinfo.update',
    'tasks_per_shardinfo_update': 'tasks_per_shardinfo.update',
    # Elasticsearch metrics
    'elasticsearch_custom_order_by_clause_counter': 'elasticsearch.custom_order_by_clause',
    'elasticsearch_bulk_processor_bulk_request_took_latency': 'elasticsearch.bulk_processor.bulk_request_took.latency',
    # Workflow update metrics
    'request_workflow_update_message': 'request_workflow.update_message',
    'respond_workflow_update_message': 'respond_workflow.update_message',
    'invalid_state_transition_workflow_update_message': 'invalid_state_transition_workflow.update_message',
    # Signal metrics
    'signal_with_start_skip_delay_count': 'signal_with_start.skip_delay',
    # Cassandra metrics
    'cassandra_session_refresh_failures': 'cassandra.session_refresh_failures',
    'cassandra_init_session_latency': 'cassandra.init_session_latency',
    # Replication metrics
    'replication_tasks_back_fill': 'replication.tasks.back_fill',
    'replication_tasks_back_fill_latency': 'replication.tasks.back_fill_latency',
    # Semaphore metrics
    'semaphore_latency': 'semaphore.latency',
    'semaphore_requests': 'semaphore.requests',
    'semaphore_failures': 'semaphore.failures',
    # Task queue metrics
    'loaded_physical_task_queue_count': 'loaded_physical_task_queue',
    # Rate limit metrics
    'dynamic_rate_limit_multiplier': 'dynamic_rate_limit.multiplier',
    # Namespace metrics
    'read_namespace_errors': 'read_namespace.errors',
    # Mutable state metrics
    'mutable_state_dirty': 'mutable_state.dirty',
    # History metrics
    'history_workflow_execution_cache_lock_hold_duration': 'history.workflow_execution_cache_lock_hold_duration',
    # New metrics
    'activity_info_size': 'activity_info.size',
    'nexus_requests': 'nexus.requests',
    'workflow_cancel': 'workflow.cancel',
    'dlq_writes': 'dlq.writes',
    'signal_info_count': 'signal_info.count',
    'reclaim_resources_delete_executions_success': 'reclaim_resources.delete_executions.success',
    'request_cancel_info_count': 'request_cancel_info.count',
    'delete_executions_failure': 'delete_executions.failure',
    'workflow_failed': 'workflow.failed',
    'child_info_size': 'child_info.size',
    'activity_info_count': 'activity_info.count',
    'delete_executions_not_found': 'delete_executions.not_found',
    'task_count': 'task.count',
    'schedule_action_delay': 'schedule.action.delay',
    'workflow_cron_backoff_timer': 'workflow.cron_backoff.timer',
    'signal_info_size': 'signal_info.size',
    'buffered_events_size': 'buffered_events.size',
    'workflow_continued_as_new': 'workflow.continued_as_new',
    'nexus_completion_requests': 'nexus.completion.requests',
    'persisted_mutable_state_size': 'persisted_mutable_state.size',
    'workflow_retry_backoff_timer': 'workflow.retry_backoff.timer',
    'non_retryable_tasks': 'non_retryable.tasks',
    'shardinfo_scheduled_queue_lag': 'shardinfo.scheduled_queue.lag',
    'workflow_success': 'workflow.success',
    'acquire_lock_failed': 'acquire_lock.failed',
    'mutable_state_size': 'mutable_state.size',
    'nexus_completion_latency': 'nexus.completion.latency',
    'timer_info_size': 'timer_info.size',
    'child_info_count': 'child_info.count',
    'execution_state_size': 'execution_state.size',
    'workflow_timeout': 'workflow.timeout',
    'schedule_action_attempt': 'schedule.action.attempt',
    'execution_info_size': 'execution_info.size',
    'forward_task_errors': 'forward_task.errors',
    'buffered_events_count': 'buffered_events.count',
    'timer_info_count': 'timer_info.count',
    'request_cancel_info_size': 'request_cancel_info.size',
    'workflow_context_cleared': 'workflow.context_cleared',
    'dlq_message_count': 'dlq.message.count',
    'reclaim_resources_namespace_delete_success': 'reclaim_resources.namespace_delete.success',
    'reclaim_resources_namespace_delete_failure': 'reclaim_resources.namespace_delete.failure',
    'nexus_latency': 'nexus.latency',
    'workflow_cleanup_delete': 'workflow.cleanup.delete',
    'reclaim_resources_delete_executions_failure': 'reclaim_resources.delete_executions.failure',
    'workflow_terminate': 'workflow.terminate',
    'shardinfo_immediate_queue_lag': 'shardinfo.immediate_queue.lag',
}
