# (C) Datadog, Inc. 2023-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def shared_exclude_network_ids():
    return []


def shared_exclude_server_ids():
    return []


def shared_nova_api_version():
    return 'v2.1'


def shared_ssl_verify():
    return True


def shared_use_agent_proxy():
    return True


def instance_append_tenant_id():
    return False


def instance_collect_all_projects():
    return True


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_min_collection_interval():
    return 15
