# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from collections.abc import Iterator
from typing import Any

from datadog_checks.base.utils.discovery import Service, from_ports


def candidates(service: Service) -> Iterator[dict[str, Any]]:
    # discovery[0]: from_ports
    for ctx in from_ports(service, port_hints=[9000]):
        yield {
            'init_config': {},
            'instances': [
                {
                    'status_url': 'http://{service.host}:{port.number}/status'.format(service=service, **ctx),
                    'ping_url': 'http://{service.host}:{port.number}/ping'.format(service=service, **ctx),
                    'use_fastcgi': 'true'.format(service=service, **ctx),
                }
            ],
        }
