# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under Simplified BSD License (see LICENSE)
from pyVmomi import vim

# https://code.vmware.com/apis/358/vsphere/doc/cpu_counters.html

# Set of metrics that are emitted as percentages between 0 and 100. For those metrics, we divide the value by 100
# to get a float between 0 and 1.
PERCENT_METRICS = {
    'cpu.capacity.contention.avg',
    'cpu.coreUtilization.avg',
    'cpu.coreUtilization.max',
    'cpu.coreUtilization.min',
    'cpu.coreUtilization.raw',
    'cpu.corecount.contention.avg',
    'cpu.demandEntitlementRatio.latest',
    'cpu.latency.avg',
    'cpu.readiness.avg',
    'cpu.usage.avg',
    'cpu.usage.max',
    'cpu.usage.min',
    'cpu.usage.raw',
    'cpu.utilization.avg',
    'cpu.utilization.max',
    'cpu.utilization.min',
    'cpu.utilization.raw',
    'datastore.siocActiveTimePercentage.avg',
    'disk.capacity.contention.avg',
    'disk.scsiReservationCnflctsPct.avg',
    'gpu.mem.usage.avg',
    'gpu.mem.usage.max',
    'gpu.mem.usage.min',
    'gpu.mem.usage.raw',
    'gpu.utilization.avg',
    'gpu.utilization.max',
    'gpu.utilization.min',
    'gpu.utilization.raw',
    'mem.capacity.contention.avg',
    'mem.latency.avg',
    'mem.reservedCapacityPct.avg',
    'mem.usage.avg',
    'mem.usage.max',
    'mem.usage.min',
    'mem.usage.raw',
    'mem.vmfs.pbc.capMissRatio.latest',
    'power.capacity.usagePct.avg',
    'rescpu.actav1.latest',
    'rescpu.actav15.latest',
    'rescpu.actav5.latest',
    'rescpu.actpk1.latest',
    'rescpu.actpk15.latest',
    'rescpu.actpk5.latest',
    'rescpu.maxLimited1.latest',
    'rescpu.maxLimited15.latest',
    'rescpu.maxLimited5.latest',
    'rescpu.runav1.latest',
    'rescpu.runav15.latest',
    'rescpu.runav5.latest',
    'rescpu.runpk1.latest',
    'rescpu.runpk15.latest',
    'rescpu.runpk5.latest',
    'storageAdapter.OIOsPct.avg',
    'sys.diskUsage.latest',
    'sys.resourceCpuAct1.latest',
    'sys.resourceCpuAct5.latest',
    'sys.resourceCpuMaxLimited1.latest',
    'sys.resourceCpuMaxLimited5.latest',
    'sys.resourceCpuRun1.latest',
    'sys.resourceCpuRun5.latest',
    'vcResources.priviledgedcpuusage.avg',
    'vcResources.processcpuusage.avg',
    'vcResources.systemcpuusage.avg',
    'vcResources.systemnetusage.avg',
    'vcResources.usercpuusage.avg',
    'vsanDomObj.readCacheHitRate.latest',
}

# All metrics that can be collected from VirtualMachines.
# The table maps a dd-formatted metric_name to a tuple containing:
# (collection_level, per_instance_collection_level, is_available_per_instance)
# Note: Only the keys of the dict are used, but the values can be useful later
# to decide how and when to collect per-instance level metrics.
VM_METRICS = {
    'cpu.costop.sum': (2, 3, False),
    'cpu.demand.avg': (2, 3, False),
    'cpu.demandEntitlementRatio.latest': (4, 4, False),
    'cpu.entitlement.latest': (2, 3, False),
    'cpu.idle.sum': (2, 3, True),
    'cpu.latency.avg': (2, 3, False),
    'cpu.maxlimited.sum': (2, 3, True),
    'cpu.overlap.sum': (3, 3, True),
    'cpu.readiness.avg': (4, 4, False),
    'cpu.ready.sum': (1, 3, False),
    'cpu.run.sum': (2, 3, True),
    'cpu.swapwait.sum': (3, 3, False),
    'cpu.system.sum': (3, 3, True),
    'cpu.usage.avg': (1, 3, True),
    'cpu.usage.max': (4, 4, True),
    'cpu.usage.min': (4, 4, True),
    'cpu.usage.raw': (4, 4, True),
    'cpu.usagemhz.avg': (1, 3, False),
    'cpu.usagemhz.max': (4, 4, False),
    'cpu.usagemhz.min': (4, 4, False),
    'cpu.usagemhz.raw': (4, 4, False),
    'cpu.used.sum': (3, 3, True),
    'cpu.wait.sum': (3, 3, False),
    'datastore.maxTotalLatency.latest': (3, 3, False),
    'datastore.numberReadAveraged.avg': (1, 3, False),
    'datastore.numberWriteAveraged.avg': (1, 3, False),
    'datastore.read.avg': (2, 2, True),
    'datastore.totalReadLatency.avg': (1, 3, True),
    'datastore.totalWriteLatency.avg': (1, 3, True),
    'datastore.write.avg': (2, 2, True),
    'disk.busResets.sum': (2, 3, True),
    'disk.commands.sum': (2, 3, True),
    'disk.commandsAborted.sum': (2, 3, True),
    'disk.commandsAveraged.avg': (2, 3, True),
    'disk.maxTotalLatency.latest': (1, 3, False),
    'disk.numberRead.sum': (3, 3, True),
    'disk.numberReadAveraged.avg': (1, 3, False),
    'disk.numberWrite.sum': (3, 3, True),
    'disk.numberWriteAveraged.avg': (1, 3, False),
    'disk.read.avg': (2, 3, True),
    'disk.usage.avg': (1, 3, False),
    'disk.usage.max': (4, 4, False),
    'disk.usage.min': (4, 4, False),
    'disk.usage.raw': (4, 4, False),
    'disk.write.avg': (2, 3, True),
    'hbr.hbrNetRx.avg': (4, 4, False),
    'hbr.hbrNetTx.avg': (4, 4, False),
    'mem.active.avg': (2, 3, False),
    'mem.active.max': (4, 4, False),
    'mem.active.min': (4, 4, False),
    'mem.active.raw': (4, 4, False),
    'mem.activewrite.avg': (2, 3, False),
    'mem.compressed.avg': (2, 3, False),
    'mem.compressionRate.avg': (2, 3, False),
    'mem.consumed.avg': (1, 3, False),
    'mem.consumed.max': (4, 4, False),
    'mem.consumed.min': (4, 4, False),
    'mem.consumed.raw': (4, 4, False),
    'mem.decompressionRate.avg': (2, 3, False),
    'mem.entitlement.avg': (2, 3, False),
    'mem.granted.avg': (2, 3, False),
    'mem.granted.max': (4, 4, False),
    'mem.granted.min': (4, 4, False),
    'mem.granted.raw': (4, 4, False),
    'mem.latency.avg': (2, 3, False),
    'mem.llSwapInRate.avg': (2, 3, False),
    'mem.llSwapOutRate.avg': (2, 3, False),
    'mem.llSwapUsed.avg': (4, 4, False),
    'mem.llSwapUsed.max': (4, 4, False),
    'mem.llSwapUsed.min': (4, 4, False),
    'mem.llSwapUsed.raw': (4, 4, False),
    'mem.overhead.avg': (1, 1, False),
    'mem.overhead.max': (4, 4, False),
    'mem.overhead.min': (4, 4, False),
    'mem.overhead.raw': (4, 4, False),
    'mem.overheadMax.avg': (2, 3, False),
    'mem.overheadTouched.avg': (4, 4, False),
    'mem.shared.avg': (2, 3, False),
    'mem.shared.max': (4, 4, False),
    'mem.shared.min': (4, 4, False),
    'mem.shared.raw': (4, 4, False),
    'mem.swapin.avg': (2, 3, False),
    'mem.swapin.max': (4, 4, False),
    'mem.swapin.min': (4, 4, False),
    'mem.swapin.raw': (4, 4, False),
    'mem.swapinRate.avg': (1, 3, False),
    'mem.swapout.avg': (2, 3, False),
    'mem.swapout.max': (4, 4, False),
    'mem.swapout.min': (4, 4, False),
    'mem.swapout.raw': (4, 4, False),
    'mem.swapoutRate.avg': (1, 3, False),
    'mem.swapped.avg': (2, 3, False),
    'mem.swapped.max': (4, 4, False),
    'mem.swapped.min': (4, 4, False),
    'mem.swapped.raw': (4, 4, False),
    'mem.swaptarget.avg': (2, 3, False),
    'mem.swaptarget.max': (4, 4, False),
    'mem.swaptarget.min': (4, 4, False),
    'mem.swaptarget.raw': (4, 4, False),
    'mem.usage.avg': (1, 3, False),
    'mem.usage.max': (4, 4, False),
    'mem.usage.min': (4, 4, False),
    'mem.usage.raw': (4, 4, False),
    'mem.vmmemctl.avg': (1, 3, False),
    'mem.vmmemctl.max': (4, 4, False),
    'mem.vmmemctl.min': (4, 4, False),
    'mem.vmmemctl.raw': (4, 4, False),
    'mem.vmmemctltarget.avg': (2, 3, False),
    'mem.vmmemctltarget.max': (4, 4, False),
    'mem.vmmemctltarget.min': (4, 4, False),
    'mem.vmmemctltarget.raw': (4, 4, False),
    'mem.zero.avg': (2, 3, False),
    'mem.zero.max': (4, 4, False),
    'mem.zero.min': (4, 4, False),
    'mem.zero.raw': (4, 4, False),
    'mem.zipSaved.latest': (2, 3, False),
    'mem.zipped.latest': (2, 3, False),
    'net.broadcastRx.sum': (2, 3, True),
    'net.broadcastTx.sum': (2, 3, True),
    'net.bytesRx.avg': (2, 3, True),
    'net.bytesTx.avg': (2, 3, True),
    'net.droppedRx.sum': (2, 3, True),
    'net.droppedTx.sum': (2, 3, True),
    'net.multicastRx.sum': (2, 3, True),
    'net.multicastTx.sum': (2, 3, True),
    'net.packetsRx.sum': (2, 3, True),
    'net.packetsTx.sum': (2, 3, True),
    'net.pnicBytesRx.avg': (4, 4, True),
    'net.pnicBytesTx.avg': (4, 4, True),
    'net.received.avg': (2, 3, True),
    'net.transmitted.avg': (2, 3, True),
    'net.usage.avg': (1, 3, True),
    'net.usage.max': (4, 4, True),
    'net.usage.min': (4, 4, True),
    'net.usage.raw': (4, 4, True),
    'power.energy.sum': (3, 3, False),
    'power.power.avg': (2, 3, False),
    'rescpu.actav1.latest': (3, 3, False),
    'rescpu.actav15.latest': (3, 3, False),
    'rescpu.actav5.latest': (3, 3, False),
    'rescpu.actpk1.latest': (3, 3, False),
    'rescpu.actpk15.latest': (3, 3, False),
    'rescpu.actpk5.latest': (3, 3, False),
    'rescpu.maxLimited1.latest': (3, 3, False),
    'rescpu.maxLimited15.latest': (3, 3, False),
    'rescpu.maxLimited5.latest': (3, 3, False),
    'rescpu.runav1.latest': (3, 3, False),
    'rescpu.runav15.latest': (3, 3, False),
    'rescpu.runav5.latest': (3, 3, False),
    'rescpu.runpk1.latest': (3, 3, False),
    'rescpu.runpk15.latest': (3, 3, False),
    'rescpu.runpk5.latest': (3, 3, False),
    'rescpu.sampleCount.latest': (3, 3, False),
    'rescpu.samplePeriod.latest': (3, 3, False),
    'sys.heartbeat.latest': (4, 4, False),
    'sys.heartbeat.sum': (1, 3, False),
    'sys.osUptime.latest': (4, 4, False),
    'sys.uptime.latest': (1, 3, False),
    'virtualDisk.busResets.sum': (2, 4, True),
    'virtualDisk.commandsAborted.sum': (2, 4, True),
    'virtualDisk.largeSeeks.latest': (4, 4, True),
    'virtualDisk.mediumSeeks.latest': (4, 4, True),
    'virtualDisk.numberReadAveraged.avg': (1, 3, True),
    'virtualDisk.numberWriteAveraged.avg': (1, 3, True),
    'virtualDisk.read.avg': (2, 2, True),
    'virtualDisk.readIOSize.latest': (4, 4, True),
    'virtualDisk.readLatencyUS.latest': (4, 4, True),
    'virtualDisk.readLoadMetric.latest': (2, 2, True),
    'virtualDisk.readOIO.latest': (2, 2, True),
    'virtualDisk.smallSeeks.latest': (4, 4, True),
    'virtualDisk.totalReadLatency.avg': (1, 3, True),
    'virtualDisk.totalWriteLatency.avg': (1, 3, True),
    'virtualDisk.write.avg': (2, 2, True),
    'virtualDisk.writeIOSize.latest': (4, 4, True),
    'virtualDisk.writeLatencyUS.latest': (4, 4, True),
    'virtualDisk.writeLoadMetric.latest': (2, 2, True),
    'virtualDisk.writeOIO.latest': (2, 2, True),
}

# All metrics that can be collected from ESXi Hosts.
# The table maps a dd-formatted metric_name to a tuple containing:
# (collection_level, per_instance_collection_level, (optional)is_available_per_instance)
HOST_METRICS = {
    'cpu.coreUtilization.avg': (2, 3, True),
    'cpu.coreUtilization.max': (4, 4, True),
    'cpu.coreUtilization.min': (4, 4, True),
    'cpu.coreUtilization.raw': (4, 4, True),
    'cpu.costop.sum': (2, 3, False),
    'cpu.demand.avg': (2, 3, False),
    'cpu.idle.sum': (2, 3, True),
    'cpu.latency.avg': (2, 3, False),
    'cpu.readiness.avg': (4, 4, False),
    'cpu.ready.sum': (1, 3, False),
    'cpu.reservedCapacity.avg': (2, 3, False),
    'cpu.swapwait.sum': (3, 3, False),
    'cpu.totalCapacity.avg': (2, 3, False),
    'cpu.usage.avg': (1, 3, True),
    'cpu.usage.max': (4, 4, True),
    'cpu.usage.min': (4, 4, True),
    'cpu.usage.raw': (4, 4, True),
    'cpu.usagemhz.avg': (1, 3, False),
    'cpu.usagemhz.max': (4, 4, False),
    'cpu.usagemhz.min': (4, 4, False),
    'cpu.usagemhz.raw': (4, 4, False),
    'cpu.used.sum': (3, 3, True),
    'cpu.utilization.avg': (2, 3, True),
    'cpu.utilization.max': (4, 4, True),
    'cpu.utilization.min': (4, 4, True),
    'cpu.utilization.raw': (4, 4, True),
    'cpu.wait.sum': (3, 3, False),
    'datastore.datastoreIops.avg': (1, 3, True),
    'datastore.datastoreMaxQueueDepth.latest': (1, 3, True),
    'datastore.datastoreNormalReadLatency.latest': (2, 2, True),
    'datastore.datastoreNormalWriteLatency.latest': (2, 2, True),
    'datastore.datastoreReadBytes.latest': (2, 2, True),
    'datastore.datastoreReadIops.latest': (1, 3, True),
    'datastore.datastoreReadLoadMetric.latest': (4, 4, True),
    'datastore.datastoreReadOIO.latest': (1, 3, True),
    'datastore.datastoreVMObservedLatency.latest': (1, 3, True),
    'datastore.datastoreWriteBytes.latest': (2, 2, True),
    'datastore.datastoreWriteIops.latest': (1, 3, True),
    'datastore.datastoreWriteLoadMetric.latest': (4, 4, True),
    'datastore.datastoreWriteOIO.latest': (1, 3, True),
    'datastore.maxTotalLatency.latest': (3, 3, False),
    'datastore.numberReadAveraged.avg': (1, 3, False),
    'datastore.numberWriteAveraged.avg': (1, 3, False),
    'datastore.read.avg': (2, 2, True),
    'datastore.siocActiveTimePercentage.avg': (1, 3, True),
    'datastore.sizeNormalizedDatastoreLatency.avg': (1, 3, True),
    'datastore.totalReadLatency.avg': (1, 3, True),
    'datastore.totalWriteLatency.avg': (1, 3, True),
    'datastore.write.avg': (2, 2, True),
    'disk.busResets.sum': (2, 3, True),
    'disk.commands.sum': (2, 3, True),
    'disk.commandsAborted.sum': (2, 3, True),
    'disk.commandsAveraged.avg': (2, 3, True),
    'disk.deviceLatency.avg': (1, 3, True),
    'disk.deviceReadLatency.avg': (2, 3, True),
    'disk.deviceWriteLatency.avg': (2, 3, True),
    'disk.kernelLatency.avg': (2, 3, True),
    'disk.kernelReadLatency.avg': (2, 3, True),
    'disk.kernelWriteLatency.avg': (2, 3, True),
    'disk.maxQueueDepth.avg': (1, 3, True),
    'disk.maxTotalLatency.latest': (1, 3, False),
    'disk.numberRead.sum': (3, 3, True),
    'disk.numberReadAveraged.avg': (1, 3, False),
    'disk.numberWrite.sum': (3, 3, True),
    'disk.numberWriteAveraged.avg': (1, 3, False),
    'disk.queueLatency.avg': (2, 3, True),
    'disk.queueReadLatency.avg': (2, 3, True),
    'disk.queueWriteLatency.avg': (2, 3, True),
    'disk.read.avg': (2, 3, True),
    'disk.scsiReservationCnflctsPct.avg': (4, 4, True),
    'disk.scsiReservationConflicts.sum': (2, 2, True),
    'disk.totalLatency.avg': (3, 3, True),
    'disk.totalReadLatency.avg': (2, 3, True),
    'disk.totalWriteLatency.avg': (2, 3, True),
    'disk.usage.avg': (1, 3, False),
    'disk.usage.max': (4, 4, False),
    'disk.usage.min': (4, 4, False),
    'disk.usage.raw': (4, 4, False),
    'disk.write.avg': (2, 3, True),
    'hbr.hbrNetRx.avg': (4, 4, False),
    'hbr.hbrNetTx.avg': (4, 4, False),
    'hbr.hbrNumVms.avg': (4, 4, False),
    'mem.active.avg': (2, 3, False),
    'mem.active.max': (4, 4, False),
    'mem.active.min': (4, 4, False),
    'mem.active.raw': (4, 4, False),
    'mem.activewrite.avg': (2, 3, False),
    'mem.compressed.avg': (2, 3, False),
    'mem.compressionRate.avg': (2, 3, False),
    'mem.consumed.avg': (1, 3, False),
    'mem.consumed.max': (4, 4, False),
    'mem.consumed.min': (4, 4, False),
    'mem.consumed.raw': (4, 4, False),
    'mem.consumed.userworlds.avg': (2, 4, False),
    'mem.consumed.vms.avg': (2, 4, False),
    'mem.decompressionRate.avg': (2, 3, False),
    'mem.granted.avg': (2, 3, False),
    'mem.granted.max': (4, 4, False),
    'mem.granted.min': (4, 4, False),
    'mem.granted.raw': (4, 4, False),
    'mem.heap.avg': (4, 4, False),
    'mem.heap.max': (4, 4, False),
    'mem.heap.min': (4, 4, False),
    'mem.heap.raw': (4, 4, False),
    'mem.heapfree.avg': (4, 4, False),
    'mem.heapfree.max': (4, 4, False),
    'mem.heapfree.min': (4, 4, False),
    'mem.heapfree.raw': (4, 4, False),
    'mem.latency.avg': (2, 3, False),
    'mem.llSwapIn.avg': (4, 4, False),
    'mem.llSwapIn.max': (4, 4, False),
    'mem.llSwapIn.min': (4, 4, False),
    'mem.llSwapIn.raw': (4, 4, False),
    'mem.llSwapInRate.avg': (2, 3, False),
    'mem.llSwapOut.avg': (4, 4, False),
    'mem.llSwapOut.max': (4, 4, False),
    'mem.llSwapOut.min': (4, 4, False),
    'mem.llSwapOut.raw': (4, 4, False),
    'mem.llSwapOutRate.avg': (2, 3, False),
    'mem.llSwapUsed.avg': (4, 4, False),
    'mem.llSwapUsed.max': (4, 4, False),
    'mem.llSwapUsed.min': (4, 4, False),
    'mem.llSwapUsed.raw': (4, 4, False),
    'mem.lowfreethreshold.avg': (2, 3, False),
    'mem.overhead.avg': (1, 1, False),
    'mem.overhead.max': (4, 4, False),
    'mem.overhead.min': (4, 4, False),
    'mem.overhead.raw': (4, 4, False),
    'mem.reservedCapacity.avg': (2, 3, False),
    'mem.shared.avg': (2, 3, False),
    'mem.shared.max': (4, 4, False),
    'mem.shared.min': (4, 4, False),
    'mem.shared.raw': (4, 4, False),
    'mem.sharedcommon.avg': (2, 3, False),
    'mem.sharedcommon.max': (4, 4, False),
    'mem.sharedcommon.min': (4, 4, False),
    'mem.sharedcommon.raw': (4, 4, False),
    'mem.state.latest': (2, 3, False),
    'mem.swapin.avg': (2, 3, False),
    'mem.swapin.max': (4, 4, False),
    'mem.swapin.min': (4, 4, False),
    'mem.swapin.raw': (4, 4, False),
    'mem.swapinRate.avg': (1, 3, False),
    'mem.swapout.avg': (2, 3, False),
    'mem.swapout.max': (4, 4, False),
    'mem.swapout.min': (4, 4, False),
    'mem.swapout.raw': (4, 4, False),
    'mem.swapoutRate.avg': (1, 3, False),
    'mem.swapused.avg': (2, 3, False),
    'mem.swapused.max': (4, 4, False),
    'mem.swapused.min': (4, 4, False),
    'mem.swapused.raw': (4, 4, False),
    'mem.sysUsage.avg': (2, 3, False),
    'mem.sysUsage.max': (4, 4, False),
    'mem.sysUsage.min': (4, 4, False),
    'mem.sysUsage.raw': (4, 4, False),
    'mem.totalCapacity.avg': (2, 3, False),
    'mem.unreserved.avg': (2, 3, False),
    'mem.unreserved.max': (4, 4, False),
    'mem.unreserved.min': (4, 4, False),
    'mem.unreserved.raw': (4, 4, False),
    'mem.usage.avg': (1, 3, False),
    'mem.usage.max': (4, 4, False),
    'mem.usage.min': (4, 4, False),
    'mem.usage.raw': (4, 4, False),
    'mem.vmfs.pbc.capMissRatio.latest': (4, 4, False),
    'mem.vmfs.pbc.overhead.latest': (4, 4, False),
    'mem.vmfs.pbc.size.latest': (4, 4, False),
    'mem.vmfs.pbc.sizeMax.latest': (4, 4, False),
    'mem.vmfs.pbc.workingSet.latest': (4, 4, False),
    'mem.vmfs.pbc.workingSetMax.latest': (4, 4, False),
    'mem.vmmemctl.avg': (1, 3, False),
    'mem.vmmemctl.max': (4, 4, False),
    'mem.vmmemctl.min': (4, 4, False),
    'mem.vmmemctl.raw': (4, 4, False),
    'mem.zero.avg': (2, 3, False),
    'mem.zero.max': (4, 4, False),
    'mem.zero.min': (4, 4, False),
    'mem.zero.raw': (4, 4, False),
    'net.broadcastRx.sum': (2, 3, True),
    'net.broadcastTx.sum': (2, 3, True),
    'net.bytesRx.avg': (2, 3, True),
    'net.bytesTx.avg': (2, 3, True),
    'net.droppedRx.sum': (2, 3, True),
    'net.droppedTx.sum': (2, 3, True),
    'net.errorsRx.sum': (2, 3, True),
    'net.errorsTx.sum': (2, 3, True),
    'net.multicastRx.sum': (2, 3, True),
    'net.multicastTx.sum': (2, 3, True),
    'net.packetsRx.sum': (2, 3, True),
    'net.packetsTx.sum': (2, 3, True),
    'net.received.avg': (2, 3, True),
    'net.transmitted.avg': (2, 3, True),
    'net.unknownProtos.sum': (2, 3, True),
    'net.usage.avg': (1, 3, True),
    'net.usage.max': (4, 4, True),
    'net.usage.min': (4, 4, True),
    'net.usage.raw': (4, 4, True),
    'power.energy.sum': (3, 3, False),
    'power.power.avg': (2, 3, False),
    'power.powerCap.avg': (3, 3, False),
    'rescpu.actav1.latest': (3, 3, False),
    'rescpu.actav15.latest': (3, 3, False),
    'rescpu.actav5.latest': (3, 3, False),
    'rescpu.actpk1.latest': (3, 3, False),
    'rescpu.actpk15.latest': (3, 3, False),
    'rescpu.actpk5.latest': (3, 3, False),
    'rescpu.maxLimited1.latest': (3, 3, False),
    'rescpu.maxLimited15.latest': (3, 3, False),
    'rescpu.maxLimited5.latest': (3, 3, False),
    'rescpu.runav1.latest': (3, 3, False),
    'rescpu.runav15.latest': (3, 3, False),
    'rescpu.runav5.latest': (3, 3, False),
    'rescpu.runpk1.latest': (3, 3, False),
    'rescpu.runpk15.latest': (3, 3, False),
    'rescpu.runpk5.latest': (3, 3, False),
    'rescpu.sampleCount.latest': (3, 3, False),
    'rescpu.samplePeriod.latest': (3, 3, False),
    'storageAdapter.commandsAveraged.avg': (2, 2, True),
    'storageAdapter.maxTotalLatency.latest': (3, 3, False),
    'storageAdapter.numberReadAveraged.avg': (2, 2, True),
    'storageAdapter.numberWriteAveraged.avg': (2, 2, True),
    'storageAdapter.outstandingIOs.avg': (2, 2, True),
    'storageAdapter.queueDepth.avg': (2, 2, True),
    'storageAdapter.queueLatency.avg': (2, 2, True),
    'storageAdapter.queued.avg': (2, 2, True),
    'storageAdapter.read.avg': (2, 2, True),
    'storageAdapter.totalReadLatency.avg': (2, 2, True),
    'storageAdapter.totalWriteLatency.avg': (2, 2, True),
    'storageAdapter.write.avg': (2, 2, True),
    'storagePath.busResets.sum': (2, 3, True),
    'storagePath.commandsAborted.sum': (2, 3, True),
    'storagePath.commandsAveraged.avg': (3, 3, True),
    'storagePath.maxTotalLatency.latest': (3, 3, False),
    'storagePath.numberReadAveraged.avg': (3, 3, True),
    'storagePath.numberWriteAveraged.avg': (3, 3, True),
    'storagePath.read.avg': (3, 3, True),
    'storagePath.totalReadLatency.avg': (3, 3, True),
    'storagePath.totalWriteLatency.avg': (3, 3, True),
    'storagePath.write.avg': (3, 3, True),
    'sys.resourceCpuAct1.latest': (3, 3, True),
    'sys.resourceCpuAct5.latest': (3, 3, True),
    'sys.resourceCpuAllocMax.latest': (3, 3, True),
    'sys.resourceCpuAllocMin.latest': (3, 3, True),
    'sys.resourceCpuAllocShares.latest': (3, 3, True),
    'sys.resourceCpuMaxLimited1.latest': (3, 3, True),
    'sys.resourceCpuMaxLimited5.latest': (3, 3, True),
    'sys.resourceCpuRun1.latest': (3, 3, True),
    'sys.resourceCpuRun5.latest': (3, 3, True),
    'sys.resourceCpuUsage.avg': (3, 3, True),
    'sys.resourceCpuUsage.max': (4, 4, True),
    'sys.resourceCpuUsage.min': (4, 4, True),
    'sys.resourceCpuUsage.raw': (4, 4, True),
    'sys.resourceFdUsage.latest': (4, 4, True),
    'sys.resourceMemAllocMax.latest': (3, 3, True),
    'sys.resourceMemAllocMin.latest': (3, 3, True),
    'sys.resourceMemAllocShares.latest': (3, 3, True),
    'sys.resourceMemConsumed.latest': (4, 4, True),
    'sys.resourceMemCow.latest': (3, 3, True),
    'sys.resourceMemMapped.latest': (3, 3, True),
    'sys.resourceMemOverhead.latest': (3, 3, True),
    'sys.resourceMemShared.latest': (3, 3, True),
    'sys.resourceMemSwapped.latest': (3, 3, True),
    'sys.resourceMemTouched.latest': (3, 3, True),
    'sys.resourceMemZero.latest': (3, 3, True),
    'sys.uptime.latest': (1, 3, False),
    'virtualDisk.busResets.sum': (2, 4, True),
    'virtualDisk.commandsAborted.sum': (2, 4, True),
}

# All metrics that can be collected from Datastores.
# The table maps a dd-formatted metric_name to a tuple containing:
# (collection_level, per_instance_collection_level, (optional)is_available_per_instance)
DATASTORE_METRICS = {
    'datastore.busResets.sum': (2, 2, True),
    'datastore.commandsAborted.sum': (2, 2, True),
    'datastore.numberReadAveraged.avg': (1, 3, False),
    'datastore.numberWriteAveraged.avg': (1, 3, False),
    'datastore.throughput.contention.avg': (4, 4, True),
    'datastore.throughput.usage.avg': (4, 4, True),
    'disk.busResets.sum': (2, 3, True),
    'disk.capacity.contention.avg': (4, 4, False),
    'disk.capacity.latest': (1, 3, False),
    'disk.capacity.provisioned.avg': (4, 4, False),
    'disk.capacity.usage.avg': (4, 4, True),
    'disk.numberReadAveraged.avg': (1, 3, False),
    'disk.numberWriteAveraged.avg': (1, 3, False),
    'disk.provisioned.latest': (1, 1, True),
    'disk.unshared.latest': (1, 1, True),
    'disk.used.latest': (1, 1, True),
}

# All metrics that can be collected from Datacenters.
# The table maps a dd-formatted metric_name to a tuple containing:
# (collection_level, per_instance_collection_level, (optional)is_available_per_instance)
DATACENTER_METRICS = {
    'vmop.numChangeDS.latest': (1, 3, False),
    'vmop.numChangeHost.latest': (1, 3, False),
    'vmop.numChangeHostDS.latest': (1, 3, False),
    'vmop.numClone.latest': (1, 3, False),
    'vmop.numCreate.latest': (1, 3, False),
    'vmop.numDeploy.latest': (1, 3, False),
    'vmop.numDestroy.latest': (1, 3, False),
    'vmop.numPoweroff.latest': (1, 3, False),
    'vmop.numPoweron.latest': (1, 3, False),
    'vmop.numRebootGuest.latest': (1, 3, False),
    'vmop.numReconfigure.latest': (1, 3, False),
    'vmop.numRegister.latest': (1, 3, False),
    'vmop.numReset.latest': (1, 3, False),
    'vmop.numSVMotion.latest': (1, 3, False),
    'vmop.numShutdownGuest.latest': (1, 3, False),
    'vmop.numStandbyGuest.latest': (1, 3, False),
    'vmop.numSuspend.latest': (1, 3, False),
    'vmop.numUnregister.latest': (1, 3, False),
    'vmop.numVMotion.latest': (1, 3, False),
    'vmop.numXVMotion.latest': (1, 3, False),
}

# All metrics that can be collected from Clusters.
# The table maps a dd-formatted metric_name to a tuple containing:
# (collection_level, per_instance_collection_level, (optional)is_available_per_instance)
CLUSTER_METRICS = {
    # clusterServices are only available for DRS and HA clusters, and are causing errors. Let's deactivate for now
    # but they were collected before so investigate why
    'clusterServices.cpufairness.latest': (1, 3, False),
    'clusterServices.effectivecpu.avg': (1, 3, False),
    'clusterServices.effectivemem.avg': (1, 3, False),
    'clusterServices.failover.latest': (1, 3, False),
    'clusterServices.memfairness.latest': (1, 3, False),
    'cpu.totalmhz.avg': (1, 3, False),
    'cpu.usage.avg': (1, 3, True),
    'cpu.usagemhz.avg': (1, 3, False),
    'mem.consumed.avg': (1, 3, False),
    'mem.overhead.avg': (1, 1, False),
    'mem.totalmb.avg': (1, 3, False),
    'mem.usage.avg': (1, 3, False),
    'mem.vmmemctl.avg': (1, 3, False),
    'vmop.numChangeDS.latest': (1, 3, False),
    'vmop.numChangeHost.latest': (1, 3, False),
    'vmop.numChangeHostDS.latest': (1, 3, False),
    'vmop.numClone.latest': (1, 3, False),
    'vmop.numCreate.latest': (1, 3, False),
    'vmop.numDeploy.latest': (1, 3, False),
    'vmop.numDestroy.latest': (1, 3, False),
    'vmop.numPoweroff.latest': (1, 3, False),
    'vmop.numPoweron.latest': (1, 3, False),
    'vmop.numRebootGuest.latest': (1, 3, False),
    'vmop.numReconfigure.latest': (1, 3, False),
    'vmop.numRegister.latest': (1, 3, False),
    'vmop.numReset.latest': (1, 3, False),
    'vmop.numSVMotion.latest': (1, 3, False),
    'vmop.numShutdownGuest.latest': (1, 3, False),
    'vmop.numStandbyGuest.latest': (1, 3, False),
    'vmop.numSuspend.latest': (1, 3, False),
    'vmop.numUnregister.latest': (1, 3, False),
    'vmop.numVMotion.latest': (1, 3, False),
    'vmop.numXVMotion.latest': (1, 3, False),
}

ALLOWED_METRICS_FOR_MOR = {
    vim.VirtualMachine: VM_METRICS,
    vim.HostSystem: HOST_METRICS,
    vim.Datacenter: DATACENTER_METRICS,
    vim.Datastore: DATASTORE_METRICS,
    vim.ClusterComputeResource: CLUSTER_METRICS,
}
