# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_disable_generic_tags(_field, _value):
    return False


def instance_empty_default_hostname(_field, _value):
    return False


def instance_filters(field, value):
    return get_default_field_value(field, value)


def instance_host(_field, _value):
    return 'localhost'


def instance_metric_patterns(field, value):
    return get_default_field_value(field, value)


def instance_min_collection_interval(_field, _value):
    return 15


def instance_namespace(_field, _value):
    return 'root\\cimv2'


def instance_password(field, value):
    return get_default_field_value(field, value)


def instance_provider(_field, _value):
    return 64


def instance_service(field, value):
    return get_default_field_value(field, value)


def instance_tag_by(field, value):
    return get_default_field_value(field, value)


def instance_tag_queries(field, value):
    return get_default_field_value(field, value)


def instance_tags(field, value):
    return get_default_field_value(field, value)


def instance_username(field, value):
    return get_default_field_value(field, value)
