import json
import os
import sys
import argparse

def main():
    """
    This is just a poc for a future worker script that takes the matrix generated by compute matrix and
    explodes it into a list of jobs.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('matrix', type=str, required=True)

    try:
        input_data = parser.parse_args()
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON input. {e}", file=sys.stderr)
        sys.exit(1)

    input_data = json.loads(input_data.matrix)


    include_list = []

    for job_definition in input_data:
        runner_list = job_definition.get('runner', [])

        for runner_item in runner_list:
            entry = job_definition.copy()

            entry['runner'] = runner_item

            include_list.append(entry)

    print(json.dumps({"include": include_list}))


if __name__ == "__main__":
    main()