'''
apn = appliance

ctr = Controller

gw = Gateway

ptl = Portal
'''

# these metrics are from Appgate v.6.3.3 as documented here: https://sdphelp.appgate.com/adminguide/v6.3/prometheus-metrics.html

METRIC_MAP = {
    'apn_active_connections': 'appliance.active.connections',
    'apn_active_connections_max': 'appliance.active.connections.max',
    'apn_audit_events': 'appliance.audit.events',
    'apn_audit_logs': 'appliance.audit.logs',
    'apn_certificate_days_remaining': 'appliance.certificate.days.remaining',
    'apn_cpu_usage_percent': 'appliance.cpu.usage.percent',
    'apn_disk': 'appliance.disk',
    'apn_disk_partition_statistic': 'appliance.disk.partition.statistic',
    'apn_function_sessions': 'appliance.function.sessions',
    'apn_function_status': 'appliance.function.status',
    'apn_image_size': 'appliance.image.size',
    'apn_memory': 'appliance.memory',
    'apn_network_interface_speed': 'appliance.network.interface.speed',
    'apn_network_interface_statistic': 'appliance.network.interface.statistic',
    'apn_proxy_protocol_messages': 'appliance.proxy.protocol.messages',
    'apn_snat': 'appliance.snat',
    'apn_spa_packet_authorization_time': 'appliance.spa.packet.authorization.time',
    'apn_spa_packets': 'appliance.spa.packets',
    'apn_spa_replay_attack_cache_entries': 'appliance.spa.replay.attack.cache.entries',
    'apn_status': 'appliance.status',
    'apn_volume_number': 'appliance.volume.number',
    'ctr_admin_authentication': 'controller.admin.authentication',
    'ctr_admin_authorization': 'controller.admin.authorization',
    'ctr_admin_mfa': 'controller.admin.mfa',
    'ctr_client_authentication': 'controller.client.authentication',
    'ctr_client_authorization': 'controller.client.authorization',
    'ctr_client_csr': 'controller.client.csr',
    'ctr_client_enter_password': 'controller.client.enter.password',
    'ctr_client_evaluate_all_policies': 'controller.client.evaluate.all.policies',
    'ctr_client_evaluate_auto_update_criteria_script': 'controller.client.evaluate.auto.update.criteria.script',
    'ctr_client_mfa': 'controller.client.mfa',
    'ctr_client_new_ip_allocation': 'controller.client.new.ip.allocation',
    'ctr_client_risk_engine_response': 'controller.client.risk.engine.response',
    'ctr_client_sign_in_with_mfa': 'controller.client.sign.in.with.mfa',
    'ctr_database_conflicts': 'controller.database.conflicts',
    'ctr_database_node_state': 'controller.database.node.state',
    'ctr_database_raft_state': 'controller.database.raft.state',
    'ctr_database_replication': 'controller.database.replication',
    'ctr_database_replication_slot_replay_lag': 'controller.database.replication.slot.replay.lag',
    'ctr_database_size': 'controller.database.size',
    'ctr_evaluate_user_claim_script': 'controller.evaluate.user.claim.script',
    'ctr_ip_pool': 'controller.ip.pool',
    'ctr_license': 'controller.license',
    'ctr_license_days_remaining': 'controller.license.days.remaining',
    'ctr_memory_heap': 'controller.memory.heap',
    'ctr_policy_evaluator': 'controller.policy.evaluator',
    'ctr_threads': 'controller.threads',
    'gw_dns_forwarder_cache': 'gateway.dns.forwarder.cache',
    'gw_dns_forwarder_domain': 'gateway.dns.forwarder.domain',
    'gw_dns_forwarder_query': 'gateway.dns.forwarder.query',
    'gw_dns_resolver_cache': 'gateway.dns.resolver.cache',
    'gw_dns_resolver_query': 'gateway.dns.resolver.query',
    'gw_event_queue_size': 'gateway.event.queue.size',
    'gw_fallback_site_usage': 'gateway.fallback.site.usage',
    'gw_ha_interface': 'gateway.ha.interface',
    'gw_http_action': 'gateway.http.action',
    'gw_http_connection': 'gateway.http.connection',
    'gw_http_open_connection': 'gateway.http.open.connection',
    'gw_http_requests': 'gateway.http.requests',
    'gw_name_resolver': 'gateway.name.resolver',
    'gw_name_resolver_cache_count': 'gateway.name.resolver.cache.count',
    'gw_name_resolver_cache_value': 'gateway.name.resolver.cache.value',
    'gw_name_resolver_names_missing_resolver': 'gateway.name.resolver.names.missing.resolver',
    'gw_name_resolver_value': 'gateway.name.resolver.value',
    'gw_policy_evaluator': 'gateway.policy.evaluator',
    'gw_session_dropped_signin': 'gateway.session.dropped.signin',
    'gw_session_event_count': 'gateway.session.event.count',
    'gw_session_event_timing': 'gateway.session.event.timing',
    'gw_session_js_exectime': 'gateway.session.js.exectime',
    'gw_sessiond_heap': 'gateway.sessiond.heap',
    'gw_sessiond_thread_count': 'gateway.sessiond.thread.count',
    'gw_token_size': 'gateway.token.size',
    'gw_vpn_memory_usage': 'gateway.vpn.memory.usage',
    'gw_vpn_resolved_actions': 'gateway.vpn.resolved.actions',
    'gw_vpn_resolved_actions_size': 'gateway.vpn.resolved.actions.size',
    'gw_vpn_rules': 'gateway.vpn.rules',
    'gw_vpn_rules_size': 'gateway.vpn.rules.size',
    'gw_vpn_sessions': 'gateway.vpn.sessions',
    'gw_vpn_states': 'gateway.vpn.states',
    'gw_vpn_states_size': 'gateway.vpn.states.size',
    'ptl_client': 'portal.client',
    'ptl_dns_proxy_query': 'portal.dns.proxy.query',
    'ptl_dns_proxy_top_domain': 'portal.dns.proxy.top.domain',
    'ptl_dns_proxy_top_server': 'portal.dns.proxy.top.server',
}
