# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_global_custom_queries(field, value):
    return get_default_field_value(field, value)


def shared_persist_db_connections(_field, _value):
    return True


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_batch_size(_field, _value):
    return 1000


def instance_connection_properties(field, value):
    return get_default_field_value(field, value)


def instance_custom_queries(field, value):
    return get_default_field_value(field, value)


def instance_disable_generic_tags(_field, _value):
    return False


def instance_empty_default_hostname(_field, _value):
    return False


def instance_metric_patterns(field, value):
    return get_default_field_value(field, value)


def instance_min_collection_interval(_field, _value):
    return 15


def instance_only_custom_queries(_field, _value):
    return False


def instance_persist_db_connections(_field, _value):
    return True


def instance_port(_field, _value):
    return 30015


def instance_schema_(_field, _value):
    return 'SYS_DATABASES'


def instance_service(field, value):
    return get_default_field_value(field, value)


def instance_tags(field, value):
    return get_default_field_value(field, value)


def instance_timeout(_field, _value):
    return 10


def instance_tls_ca_cert(field, value):
    return get_default_field_value(field, value)


def instance_tls_cert(field, value):
    return get_default_field_value(field, value)


def instance_tls_private_key(field, value):
    return get_default_field_value(field, value)


def instance_tls_private_key_password(field, value):
    return get_default_field_value(field, value)


def instance_tls_validate_hostname(_field, _value):
    return True


def instance_tls_verify(_field, _value):
    return True


def instance_use_global_custom_queries(_field, _value):
    return 'true'


def instance_use_hana_hostnames(_field, _value):
    return False


def instance_use_tls(_field, _value):
    return False
