# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

import datetime

from dateutil.tz import tzutc
from kubernetes.client.models import V1ObjectMeta, V1Pod

annotations = {
    "kubevirt.io/install-strategy-identifier": "96d0fd48fa88abe041085474347e87222b076258",
    "kubevirt.io/install-strategy-registry": "quay.io/kubevirt",
    "kubevirt.io/install-strategy-version": "v1.3.0",
}

labels = {
    "app.kubernetes.io/component": "kubevirt",
    "app.kubernetes.io/managed-by": "virt-operator",
    "app.kubernetes.io/version": "v1.3.0",
    "kubevirt.io": "virt-api",
    "pod-template-hash": "7976d99767",
    "prometheus.kubevirt.io": "true",
}

metadata = V1ObjectMeta(
    name="virt-api-7976d99767-cbj7g",
    namespace="kubevirt",
    annotations=annotations,
    labels=labels,
    uid="b2d68e35-47a1-43aa-a4fa-3b15d63e2a66",
)

GET_PODS_RESPONSE_VIRT_API_POD = [
    V1Pod(
        metadata=metadata,
        **{
            "api_version": None,
            "kind": None,
            "spec": {
                "active_deadline_seconds": None,
                "affinity": {
                    "node_affinity": {
                        "preferred_during_scheduling_ignored_during_execution": [
                            {
                                "preference": {
                                    "match_expressions": [
                                        {
                                            "key": "node-role.kubernetes.io/worker",
                                            "operator": "DoesNotExist",
                                            "values": None,
                                        }
                                    ],
                                    "match_fields": None,
                                },
                                "weight": 100,
                            }
                        ],
                        "required_during_scheduling_ignored_during_execution": {
                            "node_selector_terms": [
                                {
                                    "match_expressions": [
                                        {
                                            "key": "node-role.kubernetes.io/control-plane",
                                            "operator": "Exists",
                                            "values": None,
                                        }
                                    ],
                                    "match_fields": None,
                                },
                                {
                                    "match_expressions": [
                                        {"key": "node-role.kubernetes.io/master", "operator": "Exists", "values": None}
                                    ],
                                    "match_fields": None,
                                },
                            ]
                        },
                    },
                    "pod_affinity": None,
                    "pod_anti_affinity": {
                        "preferred_during_scheduling_ignored_during_execution": [
                            {
                                "pod_affinity_term": {
                                    "label_selector": {
                                        "match_expressions": [
                                            {"key": "kubevirt.io", "operator": "In", "values": ["virt-api"]}
                                        ],
                                        "match_labels": None,
                                    },
                                    "match_label_keys": None,
                                    "mismatch_label_keys": None,
                                    "namespace_selector": None,
                                    "namespaces": None,
                                    "topology_key": "kubernetes.io/hostname",
                                },
                                "weight": 1,
                            }
                        ],
                        "required_during_scheduling_ignored_during_execution": None,
                    },
                },
                "automount_service_account_token": None,
                "containers": [
                    {
                        "args": ["--port", "8443", "--console-server-port", "8186", "--subresources-only", "-v", "2"],
                        "command": ["virt-api"],
                        "env": None,
                        "env_from": None,
                        "image": "quay.io/kubevirt/virt-api:v1.3.0",
                        "image_pull_policy": "IfNotPresent",
                        "lifecycle": None,
                        "liveness_probe": None,
                        "name": "virt-api",
                        "ports": [
                            {
                                "container_port": 8443,
                                "host_ip": None,
                                "host_port": None,
                                "name": "virt-api",
                                "protocol": "TCP",
                            },
                            {
                                "container_port": 8443,
                                "host_ip": None,
                                "host_port": None,
                                "name": "metrics",
                                "protocol": "TCP",
                            },
                        ],
                        "readiness_probe": {
                            "_exec": None,
                            "failure_threshold": 3,
                            "grpc": None,
                            "http_get": {
                                "host": None,
                                "http_headers": None,
                                "path": "/apis/subresources.kubevirt.io/v1/healthz",
                                "port": 8443,
                                "scheme": "HTTPS",
                            },
                            "initial_delay_seconds": 15,
                            "period_seconds": 10,
                            "success_threshold": 1,
                            "tcp_socket": None,
                            "termination_grace_period_seconds": None,
                            "timeout_seconds": 1,
                        },
                        "resize_policy": None,
                        "resources": {"claims": None, "limits": None, "requests": {"cpu": "5m", "memory": "500Mi"}},
                        "restart_policy": None,
                        "security_context": {
                            "allow_privilege_escalation": False,
                            "app_armor_profile": None,
                            "capabilities": {"add": None, "drop": ["ALL"]},
                            "privileged": None,
                            "proc_mount": None,
                            "read_only_root_filesystem": None,
                            "run_as_group": None,
                            "run_as_non_root": None,
                            "run_as_user": None,
                            "se_linux_options": None,
                            "seccomp_profile": {"localhost_profile": None, "type": "RuntimeDefault"},
                            "windows_options": None,
                        },
                        "startup_probe": None,
                        "stdin": None,
                        "stdin_once": None,
                        "termination_message_path": "/dev/termination-log",
                        "termination_message_policy": "File",
                        "tty": None,
                        "volume_devices": None,
                        "volume_mounts": [
                            {
                                "mount_path": "/etc/virt-api/certificates",
                                "mount_propagation": None,
                                "name": "kubevirt-virt-api-certs",
                                "read_only": True,
                                "recursive_read_only": None,
                                "sub_path": None,
                                "sub_path_expr": None,
                            },
                            {
                                "mount_path": "/etc/virt-handler/clientcertificates",
                                "mount_propagation": None,
                                "name": "kubevirt-virt-handler-certs",
                                "read_only": True,
                                "recursive_read_only": None,
                                "sub_path": None,
                                "sub_path_expr": None,
                            },
                            {
                                "mount_path": "/profile-data",
                                "mount_propagation": None,
                                "name": "profile-data",
                                "read_only": None,
                                "recursive_read_only": None,
                                "sub_path": None,
                                "sub_path_expr": None,
                            },
                            {
                                "mount_path": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "mount_propagation": None,
                                "name": "kube-api-access-vht47",
                                "read_only": True,
                                "recursive_read_only": None,
                                "sub_path": None,
                                "sub_path_expr": None,
                            },
                        ],
                        "working_dir": None,
                    }
                ],
                "dns_config": None,
                "dns_policy": "ClusterFirst",
                "enable_service_links": True,
                "ephemeral_containers": None,
                "host_aliases": None,
                "host_ipc": None,
                "host_network": None,
                "host_pid": None,
                "host_users": None,
                "hostname": None,
                "image_pull_secrets": None,
                "init_containers": None,
                "node_name": "minikube",
                "node_selector": {"kubernetes.io/os": "linux"},
                "os": None,
                "overhead": None,
                "preemption_policy": "PreemptLowerPriority",
                "priority": 1000000000,
                "priority_class_name": "kubevirt-cluster-critical",
                "readiness_gates": None,
                "resource_claims": None,
                "restart_policy": "Always",
                "runtime_class_name": None,
                "scheduler_name": "default-scheduler",
                "scheduling_gates": None,
                "security_context": {
                    "app_armor_profile": None,
                    "fs_group": None,
                    "fs_group_change_policy": None,
                    "run_as_group": None,
                    "run_as_non_root": True,
                    "run_as_user": None,
                    "se_linux_options": None,
                    "seccomp_profile": {"localhost_profile": None, "type": "RuntimeDefault"},
                    "supplemental_groups": None,
                    "sysctls": None,
                    "windows_options": None,
                },
                "service_account": "kubevirt-apiserver",
                "service_account_name": "kubevirt-apiserver",
                "set_hostname_as_fqdn": None,
                "share_process_namespace": None,
                "subdomain": None,
                "termination_grace_period_seconds": 30,
                "tolerations": [
                    {
                        "effect": None,
                        "key": "CriticalAddonsOnly",
                        "operator": "Exists",
                        "toleration_seconds": None,
                        "value": None,
                    },
                    {
                        "effect": "NoSchedule",
                        "key": "node-role.kubernetes.io/control-plane",
                        "operator": "Exists",
                        "toleration_seconds": None,
                        "value": None,
                    },
                    {
                        "effect": "NoSchedule",
                        "key": "node-role.kubernetes.io/master",
                        "operator": "Exists",
                        "toleration_seconds": None,
                        "value": None,
                    },
                    {
                        "effect": "NoExecute",
                        "key": "node.kubernetes.io/not-ready",
                        "operator": "Exists",
                        "toleration_seconds": 300,
                        "value": None,
                    },
                    {
                        "effect": "NoExecute",
                        "key": "node.kubernetes.io/unreachable",
                        "operator": "Exists",
                        "toleration_seconds": 300,
                        "value": None,
                    },
                ],
                "topology_spread_constraints": None,
                "volumes": [
                    {
                        "aws_elastic_block_store": None,
                        "azure_disk": None,
                        "azure_file": None,
                        "cephfs": None,
                        "cinder": None,
                        "config_map": None,
                        "csi": None,
                        "downward_api": None,
                        "empty_dir": None,
                        "ephemeral": None,
                        "fc": None,
                        "flex_volume": None,
                        "flocker": None,
                        "gce_persistent_disk": None,
                        "git_repo": None,
                        "glusterfs": None,
                        "host_path": None,
                        "iscsi": None,
                        "name": "kubevirt-virt-api-certs",
                        "nfs": None,
                        "persistent_volume_claim": None,
                        "photon_persistent_disk": None,
                        "portworx_volume": None,
                        "projected": None,
                        "quobyte": None,
                        "rbd": None,
                        "scale_io": None,
                        "secret": {
                            "default_mode": 420,
                            "items": None,
                            "optional": True,
                            "secret_name": "kubevirt-virt-api-certs",
                        },
                        "storageos": None,
                        "vsphere_volume": None,
                    },
                    {
                        "aws_elastic_block_store": None,
                        "azure_disk": None,
                        "azure_file": None,
                        "cephfs": None,
                        "cinder": None,
                        "config_map": None,
                        "csi": None,
                        "downward_api": None,
                        "empty_dir": None,
                        "ephemeral": None,
                        "fc": None,
                        "flex_volume": None,
                        "flocker": None,
                        "gce_persistent_disk": None,
                        "git_repo": None,
                        "glusterfs": None,
                        "host_path": None,
                        "iscsi": None,
                        "name": "kubevirt-virt-handler-certs",
                        "nfs": None,
                        "persistent_volume_claim": None,
                        "photon_persistent_disk": None,
                        "portworx_volume": None,
                        "projected": None,
                        "quobyte": None,
                        "rbd": None,
                        "scale_io": None,
                        "secret": {
                            "default_mode": 420,
                            "items": None,
                            "optional": True,
                            "secret_name": "kubevirt-virt-handler-certs",
                        },
                        "storageos": None,
                        "vsphere_volume": None,
                    },
                    {
                        "aws_elastic_block_store": None,
                        "azure_disk": None,
                        "azure_file": None,
                        "cephfs": None,
                        "cinder": None,
                        "config_map": None,
                        "csi": None,
                        "downward_api": None,
                        "empty_dir": {"medium": None, "size_limit": None},
                        "ephemeral": None,
                        "fc": None,
                        "flex_volume": None,
                        "flocker": None,
                        "gce_persistent_disk": None,
                        "git_repo": None,
                        "glusterfs": None,
                        "host_path": None,
                        "iscsi": None,
                        "name": "profile-data",
                        "nfs": None,
                        "persistent_volume_claim": None,
                        "photon_persistent_disk": None,
                        "portworx_volume": None,
                        "projected": None,
                        "quobyte": None,
                        "rbd": None,
                        "scale_io": None,
                        "secret": None,
                        "storageos": None,
                        "vsphere_volume": None,
                    },
                    {
                        "aws_elastic_block_store": None,
                        "azure_disk": None,
                        "azure_file": None,
                        "cephfs": None,
                        "cinder": None,
                        "config_map": None,
                        "csi": None,
                        "downward_api": None,
                        "empty_dir": None,
                        "ephemeral": None,
                        "fc": None,
                        "flex_volume": None,
                        "flocker": None,
                        "gce_persistent_disk": None,
                        "git_repo": None,
                        "glusterfs": None,
                        "host_path": None,
                        "iscsi": None,
                        "name": "kube-api-access-vht47",
                        "nfs": None,
                        "persistent_volume_claim": None,
                        "photon_persistent_disk": None,
                        "portworx_volume": None,
                        "projected": {
                            "default_mode": 420,
                            "sources": [
                                {
                                    "cluster_trust_bundle": None,
                                    "config_map": None,
                                    "downward_api": None,
                                    "secret": None,
                                    "service_account_token": {
                                        "audience": None,
                                        "expiration_seconds": 3607,
                                        "path": "token",
                                    },
                                },
                                {
                                    "cluster_trust_bundle": None,
                                    "config_map": {
                                        "items": [{"key": "ca.crt", "mode": None, "path": "ca.crt"}],
                                        "name": "kube-root-ca.crt",
                                        "optional": None,
                                    },
                                    "downward_api": None,
                                    "secret": None,
                                    "service_account_token": None,
                                },
                                {
                                    "cluster_trust_bundle": None,
                                    "config_map": None,
                                    "downward_api": {
                                        "items": [
                                            {
                                                "field_ref": {"api_version": "v1", "field_path": "metadata.namespace"},
                                                "mode": None,
                                                "path": "namespace",
                                                "resource_field_ref": None,
                                            }
                                        ]
                                    },
                                    "secret": None,
                                    "service_account_token": None,
                                },
                            ],
                        },
                        "quobyte": None,
                        "rbd": None,
                        "scale_io": None,
                        "secret": None,
                        "storageos": None,
                        "vsphere_volume": None,
                    },
                ],
            },
            "status": {
                "conditions": [
                    {
                        "last_probe_time": None,
                        "last_transition_time": datetime.datetime(2024, 7, 25, 15, 16, 47, tzinfo=tzutc()),
                        "message": None,
                        "reason": None,
                        "status": "True",
                        "type": "PodReadyToStartContainers",
                    },
                    {
                        "last_probe_time": None,
                        "last_transition_time": datetime.datetime(2024, 7, 24, 22, 15, 4, tzinfo=tzutc()),
                        "message": None,
                        "reason": None,
                        "status": "True",
                        "type": "Initialized",
                    },
                    {
                        "last_probe_time": None,
                        "last_transition_time": datetime.datetime(2024, 7, 25, 15, 17, 6, tzinfo=tzutc()),
                        "message": None,
                        "reason": None,
                        "status": "True",
                        "type": "Ready",
                    },
                    {
                        "last_probe_time": None,
                        "last_transition_time": datetime.datetime(2024, 7, 25, 15, 17, 6, tzinfo=tzutc()),
                        "message": None,
                        "reason": None,
                        "status": "True",
                        "type": "ContainersReady",
                    },
                    {
                        "last_probe_time": None,
                        "last_transition_time": datetime.datetime(2024, 7, 24, 22, 15, 4, tzinfo=tzutc()),
                        "message": None,
                        "reason": None,
                        "status": "True",
                        "type": "PodScheduled",
                    },
                ],
                "container_statuses": [
                    {
                        "allocated_resources": None,
                        "container_id": "docker://8ad97c811573006c67ad0aee2734feef886ac99db89b1be0cca4c7ce588b7806",
                        "image": "quay.io/kubevirt/virt-api:v1.3.0",
                        "image_id": "docker-pullable://quay.io/kubevirt/virt-api@sha256:3f1e97424b7563fbab544b128fb06d0b84efea1a209be09178722309f34b215e",
                        "last_state": {
                            "running": None,
                            "terminated": {
                                "container_id": "docker://8160bb0b4f3c0fa947151d958e931d009dd915f3c402ba877fd02ae93e996e9c",
                                "exit_code": 0,
                                "finished_at": datetime.datetime(2024, 7, 25, 14, 32, 13, tzinfo=tzutc()),
                                "message": None,
                                "reason": "Completed",
                                "signal": None,
                                "started_at": datetime.datetime(2024, 7, 24, 22, 15, 9, tzinfo=tzutc()),
                            },
                            "waiting": None,
                        },
                        "name": "virt-api",
                        "ready": True,
                        "resources": None,
                        "restart_count": 1,
                        "started": True,
                        "state": {
                            "running": {"started_at": datetime.datetime(2024, 7, 25, 15, 16, 47, tzinfo=tzutc())},
                            "terminated": None,
                            "waiting": None,
                        },
                        "volume_mounts": None,
                    }
                ],
                "ephemeral_container_statuses": None,
                "host_i_ps": [{"ip": "192.168.49.2"}],
                "host_ip": "192.168.49.2",
                "init_container_statuses": None,
                "message": None,
                "nominated_node_name": None,
                "phase": "Running",
                "pod_i_ps": [{"ip": "10.244.0.38"}],
                "pod_ip": "10.244.0.38",
                "qos_class": "Burstable",
                "reason": None,
                "resize": None,
                "resource_claim_statuses": None,
                "start_time": datetime.datetime(2024, 7, 24, 22, 15, 4, tzinfo=tzutc()),
            },
        },
    )
]
