# (C) Datadog, Inc. 2022-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CHECK_NAME = 'teradata'

E2E_METADATA = {
    'use_jmx': True,
    'docker_volumes': [
        '{}/setup/odbc/odbc.ini:/opt/datadog-agent/embedded/etc/odbc.ini'.format(HERE),
        '{}/setup/odbc/odbcinst.ini:/opt/datadog-agent/embedded/etc/odbcinst.ini'.format(HERE),
        '{}/setup/start_commands.sh:/tmp/start_commands.sh'.format(HERE),
    ],
    'env_vars': {'CLASSPATH': '/terajdbc4.jar'},
    'start_commands': ['bash /tmp/start_commands.sh'],
}

EXPECTED_METRICS = [
    "teradata.disk_space.max_perm",
    "teradata.disk_space.max_spool",
    "teradata.disk_space.max_temp",
    "teradata.disk_space.curr_perm",
    "teradata.disk_space.curr_spool",
    "teradata.disk_space.curr_persist_spool",
    "teradata.disk_space.curr_temp",
    "teradata.disk_space.peak_perm",
    "teradata.disk_space.peak_spool",
    "teradata.disk_space.peak_persist_spool",
    "teradata.disk_space.peak_temp",
    "teradata.disk_space.max_prof_spool",
    "teradata.disk_space.max_prof_temp",
    "teradata.disk_space.alloc_perm",
    "teradata.disk_space.alloc_spool",
    "teradata.disk_space.alloc_temp",
    "teradata.disk_space.perm_skew",
    "teradata.disk_space.spool_skew",
    "teradata.disk_space.temp_skew",
    "teradata.amp.cpu_time",
    "teradata.amp.disk_io",
    "teradata.amp.cpu_time_norm",
    "teradata.file_lock.blocks",
    "teradata.file_lock.deadlocks",
    "teradata.file_lock.enters",
    "teradata.db_lock.blocks",
    "teradata.db_lock.deadlocks",
    "teradata.io.throttle_count",
    "teradata.io.throttle_time",
    "teradata.io.throttle_time_max",
    "teradata.mem.ctxt_page_reads",
    "teradata.mem.ctxt_page_writes",
    "teradata.mem.txt_page_reads",
    "teradata.mem.vh_cache_size",
    "teradata.mem.kernel_inuse_size",
    "teradata.mem.seg_mdl.inuse_size",
    "teradata.mem.seg_max_avail_size",
    "teradata.mem.seg_in_use_size",
    "teradata.mem.seg_cache_size",
    "teradata.mem.seg_mdl.alloc",
    "teradata.mem.seg_mdl.free",
    "teradata.mem.seg_mdl.release",
    "teradata.mem.seg_mdl.recycle",
    "teradata.mem.seg_mdl.alloc_size",
    "teradata.mem.seg_mdl.free_size",
    "teradata.mem.seg_mdl.release_size",
    "teradata.mem.seg_mdl.recycle_size",
    "teradata.mem.fsg.cache_size",
    "teradata.mem.page_faults_major",
    "teradata.mem.page_faults_minor",
    "teradata.process.blocked",
    "teradata.process.ready",
    "teradata.process.ready_max",
    "teradata.process.cpu_idle",
    "teradata.process.cpu_io_wait",
    "teradata.process.cpu_serv",
    "teradata.process.cpu_exec",
    "teradata.process.cpu_throttle",
    "teradata.process.cpu_throttle_time",
]
