# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

E2E_METRICS = [
    "sonatype_nexus.status.available_cpus_health",
    "sonatype_nexus.status.blob_store.quota_health",
    "sonatype_nexus.status.blob_store.ready_health",
    "sonatype_nexus.status.coordinate_content_selectors_health",
    "sonatype_nexus.status.default_admin_credentials_health",
    "sonatype_nexus.status.default_secret_encryption_key_health",
    "sonatype_nexus.status.default_role_realm_health",
    "sonatype_nexus.status.blob_store.file_path_health",
    "sonatype_nexus.status.file_descriptors_health",
    "sonatype_nexus.status.lifecycle_phase_health",
    "sonatype_nexus.status.NuGet_V2_repositories_health",
    "sonatype_nexus.status.re_encryption_required_health",
    "sonatype_nexus.status.read_only_detector_health",
    "sonatype_nexus.status.scheduler_health",
    "sonatype_nexus.status.scripting_health",
    "sonatype_nexus.status.thread_deadlock_detector",
    "sonatype_nexus.analytics.gc.g1_old_generation_count",
    "sonatype_nexus.analytics.gc.g1_young_generation_count",
    "sonatype_nexus.analytics.gc.g1_old_generation_time",
    "sonatype_nexus.analytics.gc.g1_young_generation_time",
    "sonatype_nexus.analytics.jvm.heap_memory_max",
    "sonatype_nexus.analytics.jvm.heap_memory_used",
    "sonatype_nexus.analytics.repository_total_count",
    "sonatype_nexus.analytics.component_total_count",
    "sonatype_nexus.analytics.log4j_visualizer_non_vulnerable_daily_download_count",
    "sonatype_nexus.analytics.log4j_visualizer_vulnerable_daily_download_count",
    "sonatype_nexus.analytics.cleanup_dry_run_count",
    "sonatype_nexus.analytics.cleanup_dry_run_avg_execution_time",
    "sonatype_nexus.analytics.uptime",
    "sonatype_nexus.analytics.blob_store.blobcount_by_type",
    "sonatype_nexus.analytics.blob_store.size_by_type",
    "sonatype_nexus.analytics.repository_asset_count_by_format_type",
    "sonatype_nexus.analytics.repository_count_by_format_type",
    "sonatype_nexus.analytics.malicious_risk_on_disk",
    "sonatype_nexus.analytics.failed_unique_user_authentication_count",
    "sonatype_nexus.analytics.successful_unique_user_authentication_count",
    "sonatype_nexus.analytics.total_memory",
    "sonatype_nexus.analytics.available_cpus",
]
