# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_disable_generic_tags():
    return False


def instance_driver():
    return 'iSeries Access ODBC Driver'


def instance_empty_default_hostname():
    return False


def instance_job_query_timeout():
    return 240


def instance_min_collection_interval():
    return 15


def instance_queries():
    return [
        {'name': 'disk_usage'},
        {'name': 'cpu_usage'},
        {'name': 'jobq_job_status'},
        {'name': 'active_job_status'},
        {'name': 'job_memory_usage'},
        {'name': 'memory_info'},
        {'name': 'subsystem'},
        {'name': 'job_queue'},
        {'name': 'message_queue_info'},
    ]


def instance_query_timeout():
    return 30


def instance_severity_threshold():
    return 50


def instance_system_mq_query_timeout():
    return 80
