# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_connection_string(field, value):
    return get_default_field_value(field, value)


def instance_disable_generic_tags(field, value):
    return False


def instance_driver(field, value):
    return 'iSeries Access ODBC Driver'


def instance_empty_default_hostname(field, value):
    return False


def instance_hostname(field, value):
    return get_default_field_value(field, value)


def instance_job_query_timeout(field, value):
    return 240


def instance_message_queue_info(field, value):
    return get_default_field_value(field, value)


def instance_metric_patterns(field, value):
    return get_default_field_value(field, value)


def instance_min_collection_interval(field, value):
    return 15


def instance_password(field, value):
    return get_default_field_value(field, value)


def instance_queries(field, value):
    return [
        {'name': 'disk_usage'},
        {'name': 'cpu_usage'},
        {'name': 'jobq_job_status'},
        {'name': 'active_job_status'},
        {'name': 'job_memory_usage'},
        {'name': 'memory_info'},
        {'name': 'subsystem'},
        {'name': 'job_queue'},
        {'name': 'message_queue_info'},
    ]


def instance_query_timeout(field, value):
    return 30


def instance_service(field, value):
    return get_default_field_value(field, value)


def instance_severity_threshold(field, value):
    return 50


def instance_system(field, value):
    return get_default_field_value(field, value)


def instance_system_mq_query_timeout(field, value):
    return 80


def instance_tags(field, value):
    return get_default_field_value(field, value)


def instance_username(field, value):
    return get_default_field_value(field, value)
