# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_activity_metrics_excluded_aggregations(_field, _value):
    return []


def instance_application_name(_field, _value):
    return 'datadog-agent'


def instance_aws(field, value):
    return get_default_field_value(field, value)


def instance_azure(field, value):
    return get_default_field_value(field, value)


def instance_collect_activity_metrics(_field, _value):
    return False


def instance_collect_bloat_metrics(_field, _value):
    return False


def instance_collect_count_metrics(_field, _value):
    return True


def instance_collect_database_size_metrics(_field, _value):
    return True


def instance_collect_default_database(_field, _value):
    return True


def instance_collect_function_metrics(_field, _value):
    return False


def instance_collect_wal_metrics(_field, _value):
    return False


def instance_custom_queries(field, value):
    return get_default_field_value(field, value)


def instance_data_directory(_field, _value):
    return '/usr/local/pgsql/data'


def instance_dbm(_field, _value):
    return False


def instance_dbname(_field, _value):
    return 'postgres'


def instance_dbstrict(_field, _value):
    return False


def instance_disable_generic_tags(_field, _value):
    return False


def instance_empty_default_hostname(_field, _value):
    return False


def instance_gcp(field, value):
    return get_default_field_value(field, value)


def instance_ignore_databases(_field, _value):
    return ['template%', 'rdsadmin', 'azure_maintenance']


def instance_log_unobfuscated_plans(_field, _value):
    return False


def instance_log_unobfuscated_queries(_field, _value):
    return False


def instance_max_relations(_field, _value):
    return 300


def instance_metric_patterns(field, value):
    return get_default_field_value(field, value)


def instance_min_collection_interval(_field, _value):
    return 15


def instance_obfuscator_options(field, value):
    return get_default_field_value(field, value)


def instance_password(field, value):
    return get_default_field_value(field, value)


def instance_pg_stat_statements_view(_field, _value):
    return 'show_pg_stat_statements()'


def instance_port(_field, _value):
    return 5432


def instance_query_activity(field, value):
    return get_default_field_value(field, value)


def instance_query_metrics(field, value):
    return get_default_field_value(field, value)


def instance_query_samples(field, value):
    return get_default_field_value(field, value)


def instance_query_timeout(_field, _value):
    return 5000


def instance_relations(field, value):
    return get_default_field_value(field, value)


def instance_reported_hostname(field, value):
    return get_default_field_value(field, value)


def instance_service(field, value):
    return get_default_field_value(field, value)


def instance_ssl(_field, _value):
    return False


def instance_ssl_cert(_field, _value):
    return False


def instance_ssl_key(_field, _value):
    return False


def instance_ssl_password(_field, _value):
    return False


def instance_ssl_root_cert(_field, _value):
    return False


def instance_table_count_limit(_field, _value):
    return 200


def instance_tag_replication_role(_field, _value):
    return False


def instance_tags(field, value):
    return get_default_field_value(field, value)
