[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["11.1"]

[envs.default.env-vars]
DB2_VERSION = "{matrix:version:11.1}"
IBM_DB_INSTALLER_URL = "https://agent-integrations-ci-fixtures.s3.us-east-1.amazonaws.com/fixtures/ibm-db2/"

[envs.default]
dependencies = [
  "ibm_db==3.0.1; python_version < '3.0'",
  "ibm_db==3.2.6; python_version > '3.0'",
]

[envs.bench]
