[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]
version = ["11.5.5.1", "12.1.5.0"]

[envs.default.env-vars]
IBM_DB_INSTALLER_URL = "https://ddintegrations.blob.core.windows.net/ibm-db2/"

[envs.default.overrides]
matrix.version.env-vars = "DB2_VERSION"

[envs.default]
dependencies = [
  "ibm_db==3.0.1; python_version < '3.0'",
  "ibm_db==3.2.6; python_version > '3.0'",
]

[envs.bench]
