"""Content-hash builder image inputs and resolution inputs for change detection.

The `Resolve Dependencies and Build Wheels` workflow uses these hashes to
decide whether to rebuild a builder image from scratch or pull the existing
one by digest, and whether to run the full resolution pipeline at all.

A "target" is one of the builder image names we maintain — one per
(OS, CPU architecture) pair that the Agent ships Python wheels for.
The names match the subdirectories of .builders/images/, for example:
`linux-x86_64`, `linux-aarch64`, `windows-x86_64`.

SHARED_INPUTS and RESOLUTION_INPUTS are the source of truth for what counts
as a resolution input. See test_inputs_hash.py::test_no_uncovered_files for
enforcement that no file is accidentally excluded from coverage.
"""
from __future__ import annotations

import argparse
import json
import sys
import tomllib
from collections.abc import Iterator
from hashlib import sha256
from pathlib import Path

HERE = Path(__file__).parent
REPO_ROOT = HERE.parent
PINNED_FILE = REPO_ROOT / '.deps' / 'builder_inputs.toml'

# Glob patterns relative to .builders/ for inputs shared across all builder
# target images.
SHARED_INPUTS = [
    'build.py',
    'deps/build_dependencies.txt',
    'scripts/**/*',
    'patches/**/*',
    'images/helpers.ps1',
    'images/install-from-source.sh',
    'images/runner_dependencies.txt',
]

# Glob patterns relative to the repo root for inputs that affect resolution
# output (uv pip compile, builder images, wheels, lockfiles, published
# artifacts). Note: per-target image files are included wholesale, so a
# change to any single Dockerfile invalidates resolution for all targets.
# This is intentional — image contents determine what the resolved wheels
# can link against, so resolution is conservatively rerun on any image change.
RESOLUTION_INPUTS = [
    'agent_requirements.in',
    '.github/workflows/resolve-build-deps.yaml',
    '.builders/build.py',
    '.builders/upload.py',
    '.builders/inputs_hash.py',
    '.builders/deps/*.txt',
    '.builders/scripts/**/*',
    '.builders/patches/**/*',
    '.builders/images/**/*',
]


def is_ignored(name: str) -> bool:
    if name == '.gitkeep':
        return False
    return name.startswith('.') or name == '__pycache__'


def _iter_files(root: Path) -> Iterator[Path]:
    if root.is_file():
        yield root
    elif root.is_dir():
        for path in root.rglob('*'):
            rel_parts = path.relative_to(root).parts
            if path.is_file() and not any(is_ignored(part) for part in rel_parts):
                yield path


def hash_paths(base: Path, patterns: list[str]) -> str:
    """Hash all files matched by `patterns` (glob-expanded relative to `base`).

    Raises RuntimeError if any pattern matches no files. The pattern lists are
    static and author-curated, so an empty match means a list entry has gone
    stale — failing loud prevents the hash from silently narrowing.

    Sorting by relative POSIX path before hashing preserves cross-OS stability:
    WindowsPath sorting is case-insensitive and uses backslashes, which would
    produce a different hash than on POSIX systems for the same input set.
    """
    paths: set[Path] = set()
    for pattern in patterns:
        matched = list(base.glob(pattern))
        if not matched:
            raise RuntimeError(
                f'pattern {pattern!r} matched no files under {base}; '
                f'a SHARED_INPUTS/RESOLUTION_INPUTS entry has gone stale'
            )
        for p in matched:
            paths.update(_iter_files(p))

    sorted_paths = sorted(paths, key=lambda p: p.relative_to(base).as_posix())
    digest = sha256()
    for path in sorted_paths:
        rel_path = path.relative_to(base).as_posix().encode('utf-8')
        digest.update(rel_path + b'\0')
        digest.update(path.read_bytes())
        digest.update(b'\0')
    return digest.hexdigest()


def compute_target(target: str) -> str:
    """Hash the working-tree inputs for `target` and return hex sha256."""
    target_dir = HERE / 'images' / target
    if not target_dir.is_dir():
        raise FileNotFoundError(f'Unknown builder target: {target} (expected {target_dir})')
    return hash_paths(HERE, SHARED_INPUTS + [f'images/{target}/**/*'])


def compute_resolution() -> str:
    """Hash all resolution inputs relative to the repo root and return hex sha256."""
    return hash_paths(REPO_ROOT, RESOLUTION_INPUTS)


def _load_pinned() -> dict:
    """Load the pinned TOML file, returning {} when the file is missing."""
    if not PINNED_FILE.is_file():
        print(f'{PINNED_FILE} not found; treating as unpinned', file=sys.stderr)
        return {}
    try:
        with PINNED_FILE.open('rb') as f:
            return tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        raise RuntimeError(
            f'{PINNED_FILE} is malformed; it is regenerated by .builders/upload.py, '
            f'rerun resolve-build-deps if it is corrupted: {e}'
        ) from e


def pinned_target(target: str) -> str:
    """Return the hash pinned for `target` in builder_inputs.toml, or empty if absent."""
    images = _load_pinned().get('images', {})
    if target not in images:
        print(f'{PINNED_FILE}: no entry for {target}; treating as unpinned', file=sys.stderr)
        return ''
    return images[target]


def pinned_resolution() -> str:
    """Return the resolution hash pinned in builder_inputs.toml, or empty if absent."""
    resolution = _load_pinned().get('resolution', {})
    if 'hash' not in resolution:
        print(f'{PINNED_FILE}: no [resolution] hash; treating as unpinned', file=sys.stderr)
        return ''
    return resolution['hash']


def _check(label: str, current: str, pinned: str) -> bool:
    """Print current/pinned/fresh-or-STALE status to stderr and return whether they match."""
    fresh = current == pinned
    print(f'{label}: current={current}', file=sys.stderr)
    print(f'{label}: pinned ={pinned}', file=sys.stderr)
    print(f'{label}: {"fresh" if fresh else "STALE"}', file=sys.stderr)
    return fresh


def verify_resolution() -> bool:
    """Return True if the working-tree resolution hash matches the pinned hash."""
    current = compute_resolution()
    pinned = pinned_resolution()
    if not pinned:
        print(
            f'{PINNED_FILE}: no [resolution] hash found; dependency resolution has '
            'not yet published a pin. Expected during the initial rollout; once '
            'resolve-build-deps publishes once on master, this check starts working '
            'normally.',
            file=sys.stderr,
        )
        return False
    return _check('resolution', current, pinned)


def status(targets: list[str]) -> dict[str, str]:
    """Compute gate outputs for `targets` and return them as $GITHUB_OUTPUT key=value pairs.

    Side effect: prints human-readable current/pinned/fresh-or-STALE lines for
    each hash to stderr.

    Output keys: `needs_resolution` (bool string), `rebuild_<target>` (bool
    string per target), `hashes` (JSON blob mapping target → current hash,
    consumed by downstream jobs that need the hash value itself).
    """
    needs_resolution = not verify_resolution()
    outputs: dict[str, str] = {'needs_resolution': str(needs_resolution).lower()}
    hashes: dict[str, str] = {}
    for target in targets:
        current = compute_target(target)
        hashes[target] = current
        fresh = _check(target, current, pinned_target(target))
        outputs['rebuild_' + target.replace('-', '_')] = str(not fresh).lower()
    outputs['hashes'] = json.dumps(hashes, sort_keys=True)
    return outputs


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            'Hash the inputs that determine builder images and resolution output. '
            'Used by resolve-build-deps.yaml to gate the full pipeline and by '
            'verify-deps-pin.yaml to validate merged trees on queue refs.'
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest='command', required=True)

    status_parser = subparsers.add_parser(
        'status',
        help='Emit needs_resolution, rebuild_<target>, and hashes (JSON) to $GITHUB_OUTPUT.',
    )
    status_parser.add_argument('--targets', nargs='+', required=True, metavar='TARGET')

    subparsers.add_parser(
        'verify-resolution',
        help='Exit 0 if resolution hash matches pinned; exit 1 on mismatch.',
    )
    return parser


def main() -> None:
    args = _build_parser().parse_args()
    try:
        if args.command == 'status':
            for key, value in status(args.targets).items():
                sys.stdout.write(f'{key}={value}\n')
        elif args.command == 'verify-resolution':
            if not verify_resolution():
                print(
                    'Resolution pin is stale. Rebase your branch onto master to re-trigger '
                    'dependency resolution and update the pin.',
                    file=sys.stderr,
                )
                sys.exit(1)
    except RuntimeError as e:
        print(f'error: {e}', file=sys.stderr)
        sys.exit(2)


if __name__ == '__main__':
    main()
