# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# Some metrics mapping are too long. This turns off the 120 line limit for this file:
# ruff: noqa: E501

RESOURCE_METRIC_MAP = {
    'kueue_cluster_queue_borrowing_limit': 'cluster_queue.borrowing_limit',
    'kueue_cluster_queue_lending_limit': 'cluster_queue.lending_limit',
    'kueue_cluster_queue_nominal_quota': 'cluster_queue.nominal_quota',
    'kueue_cluster_queue_resource_pending': 'cluster_queue.resource_pending',
    'kueue_cluster_queue_resource_reservation': 'cluster_queue.resource_reservation',
    'kueue_cluster_queue_resource_usage': 'cluster_queue.resource_usage',
    'kueue_cohort_subtree_quota': 'cohort_subtree.quota',
    'kueue_cohort_subtree_resource_reservations': 'cohort_subtree.resource_reservations',
    'kueue_local_queue_resource_reservation': 'local_queue.resource_reservation',
    'kueue_local_queue_resource_usage': 'local_queue.resource_usage',
}

LOCAL_QUEUE_METRIC_MAP = {
    'kueue_local_queue_admission_checks_wait_time_seconds': 'local_queue.admission_checks.wait_time.seconds',
    'kueue_local_queue_admission_wait_time_seconds': 'local_queue.admission.wait_time.seconds',
    'kueue_local_queue_admitted_until_ready_wait_time_seconds': 'local_queue.admitted_until_ready.wait_time.seconds',
    'kueue_local_queue_admitted_active_workloads': 'local_queue.admitted.active_workloads',
    'kueue_local_queue_admitted_workloads': 'local_queue.admitted.workloads',
    'kueue_local_queue_evicted_workloads': 'local_queue.evicted_workloads',
    'kueue_local_queue_finished_workloads': 'local_queue.finished_workloads',
    'kueue_local_queue_finished_workloads_total': 'local_queue.finished_workloads',
    'kueue_local_queue_pending_workloads': 'local_queue.pending_workloads',
    'kueue_local_queue_quota_reserved_wait_time_seconds': 'local_queue.quota_reserved.wait_time.seconds',
    'kueue_local_queue_quota_reserved_workloads': 'local_queue.quota_reserved.workloads',
    'kueue_local_queue_ready_wait_time_seconds': 'local_queue.ready_wait_time.seconds',
    'kueue_local_queue_reserving_active_workloads': 'local_queue.reserving.active_workloads',
    'kueue_local_queue_status': 'local_queue.status',
}

METRIC_MAP = {
    'certwatcher_read_certificate': 'certwatcher.read_certificate',
    'certwatcher_read_certificate_errors': 'certwatcher.read_certificate_errors',
    'controller_runtime_active_workers': 'controller.runtime.active_workers',
    'controller_runtime_conversion_webhook_panics': 'controller.runtime.conversion_webhook_panics',
    'controller_runtime_max_concurrent_reconciles': 'controller.runtime.max_concurrent_reconciles',
    'controller_runtime_reconcile': 'controller.runtime.reconcile',
    'controller_runtime_reconcile_errors': 'controller.runtime.reconcile_errors',
    'controller_runtime_reconcile_panics': 'controller.runtime.reconcile_panics',
    'controller_runtime_reconcile_time_seconds': 'controller.runtime.reconcile_time.seconds',
    'controller_runtime_reconcile_timeouts': 'controller.runtime.reconcile_timeouts',
    'controller_runtime_terminal_reconcile_errors': 'controller.runtime.terminal_reconcile_errors',
    'controller_runtime_webhook_latency_seconds': 'controller.runtime.webhook_latency.seconds',
    'controller_runtime_webhook_panics': 'controller.runtime.webhook_panics',
    'controller_runtime_webhook_requests': 'controller.runtime.webhook_requests',
    'controller_runtime_webhook_requests_in_flight': 'controller.runtime.webhook_requests_in_flight',
    'go_gc_duration_seconds': 'go.gc.duration.seconds',
    'go_gc_gogc_percent': 'go.gc.gogc.percent',
    'go_gc_gomemlimit_bytes': 'go.gc.gomemlimit.bytes',
    'go_goroutines': 'go.goroutines',
    'go_info': 'go.info',
    'go_memstats_alloc_bytes': {'name': 'go.memstats.alloc_bytes', 'type': 'native_dynamic'},
    'go_memstats_buck_hash_sys_bytes': 'go.memstats.buck_hash.sys_bytes',
    'go_memstats_frees': 'go.memstats.frees',
    'go_memstats_gc_sys_bytes': 'go.memstats.gc.sys_bytes',
    'go_memstats_heap_alloc_bytes': 'go.memstats.heap_alloc.bytes',
    'go_memstats_heap_idle_bytes': 'go.memstats.heap_idle.bytes',
    'go_memstats_heap_inuse_bytes': 'go.memstats.heap_inuse.bytes',
    'go_memstats_heap_objects': 'go.memstats.heap_objects',
    'go_memstats_heap_released_bytes': 'go.memstats.heap_released.bytes',
    'go_memstats_heap_sys_bytes': 'go.memstats.heap_sys.bytes',
    'go_memstats_last_gc_time_seconds': {
        'name': 'go.memstats.time_since_last_gc.seconds',
        'type': 'time_elapsed',
    },
    'go_memstats_mallocs': 'go.memstats.mallocs',
    'go_memstats_mcache_inuse_bytes': 'go.memstats.mcache_inuse.bytes',
    'go_memstats_mcache_sys_bytes': 'go.memstats.mcache_sys.bytes',
    'go_memstats_mspan_inuse_bytes': 'go.memstats.mspan_inuse.bytes',
    'go_memstats_mspan_sys_bytes': 'go.memstats.mspan_sys.bytes',
    'go_memstats_next_gc_bytes': 'go.memstats.next_gc.bytes',
    'go_memstats_other_sys_bytes': 'go.memstats.other_sys.bytes',
    'go_memstats_stack_inuse_bytes': 'go.memstats.stack_inuse.bytes',
    'go_memstats_stack_sys_bytes': 'go.memstats.stack_sys.bytes',
    'go_memstats_sys_bytes': 'go.memstats.sys.bytes',
    'go_threads': 'go.threads',
    'kueue_admission_attempt_duration_seconds': 'admission_attempt.duration.seconds',
    'kueue_admission_attempts': 'admission.attempts',
    'kueue_admission_checks_wait_time_seconds': 'admission_checks.wait_time.seconds',
    'kueue_admission_cycle_preemption_skips': 'admission_cycle.preemption_skips',
    'kueue_admission_wait_time_seconds': 'admission.wait_time.seconds',
    'kueue_admitted_until_ready_wait_time_seconds': 'admitted_until_ready.wait_time.seconds',
    'kueue_admitted_active_workloads': 'admitted.active_workloads',
    'kueue_admitted_workloads': 'admitted.workloads',
    'kueue_build_info': 'build_info',
    'kueue_cluster_queue_info': 'cluster_queue.info',
    'kueue_cluster_queue_status': 'cluster_queue.status',
    'kueue_cluster_queue_weighted_share': 'cluster_queue.weighted_share',
    'kueue_cohort_info': 'cohort.info',
    'kueue_cohort_subtree_admitted_active_workloads': 'cohort_subtree.admitted.active_workloads',
    'kueue_cohort_subtree_admitted_workloads': 'cohort_subtree.admitted.workloads',
    'kueue_cohort_weighted_share': 'cohort.weighted_share',
    'kueue_evicted_workloads': 'evicted_workloads',
    'kueue_evicted_workloads_once': 'evicted_workloads_once',
    'kueue_finished_workloads': 'finished_workloads',
    'kueue_finished_workloads_total': 'finished_workloads',
    'kueue_pending_workloads': 'pending_workloads',
    'kueue_pods_ready_to_evicted_time_seconds': 'pods_ready_to_evicted_time.seconds',
    'kueue_preempted_workloads': 'preempted_workloads',
    'kueue_quota_reserved_wait_time_seconds': 'quota_reserved.wait_time.seconds',
    'kueue_quota_reserved_workloads': 'quota_reserved.workloads',
    'kueue_ready_wait_time_seconds': 'ready_wait_time.seconds',
    'kueue_replaced_workload_slices': 'replaced_workload_slices',
    'kueue_resource_flavor_quota_reserved_workloads': 'resource_flavor.quota_reserved_workloads',
    'kueue_reserving_active_workloads': 'reserving.active_workloads',
    'kueue_workload_creation_latency_seconds': 'workload.creation_latency.seconds',
    'kueue_workload_eviction_latency_seconds': 'workload.eviction_latency.seconds',
    'leader_election_master_status': 'leader_election.master_status',
    'process_cpu_seconds': 'process.cpu.seconds',
    'process_max_fds': 'process.max_fds',
    'process_network_receive_bytes': 'process.network_receive.bytes',
    'process_network_transmit_bytes': 'process.network_transmit.bytes',
    'process_open_fds': 'process.open_fds',
    'process_resident_memory_bytes': 'process.resident_memory.bytes',
    'process_start_time_seconds': {
        'name': 'process.uptime.seconds',
        'type': 'time_elapsed',
    },
    'process_virtual_memory_bytes': 'process.virtual_memory.bytes',
    'process_virtual_memory_max_bytes': 'process.virtual_memory.max_bytes',
    'workqueue_adds': 'workqueue.adds',
    'workqueue_depth': 'workqueue.depth',
    'workqueue_longest_running_processor_seconds': 'workqueue.longest_running_processor.seconds',
    'workqueue_queue_duration_seconds': 'workqueue.queue_duration.seconds',
    'workqueue_retries': 'workqueue.retries',
    'workqueue_unfinished_work_seconds': 'workqueue.unfinished_work.seconds',
    'workqueue_work_duration_seconds': 'workqueue.work_duration.seconds',
}
