FROM envoyproxy/envoy:v1.29.0
RUN apt-get update && apt-get install -y python3 bash python3-pip
RUN python3 --version && pip3 --version
RUN pip3 install -q Flask==2.1.2 requests==2.28.1
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
