# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit scripts/templates/system_metrics.py and then run the following command:
#     hatch run data:generate

# https://clickhouse.com/docs/operations/system-tables/errors
SystemErrors = {{
    'name': 'system.errors',
    'query': 'SELECT name, value FROM system.errors',
    'columns': [
        {{
            'name': 'value',
            'type': 'source'
        }},
        {{
            'name': 'metric',
            'type': 'match',
            'source': 'value',
            'items': {{
{items}
            }},
        }},
    ],
}}
