# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit scripts/templates/system_metrics.py and then run the following command:
#     hatch run py3.12-<VERSION>:python ./scripts/generate_metrics.py

# https://clickhouse.com/docs/operations/system-tables/metrics
SystemMetrics = {{
    'name': 'system.metrics',
    'query': 'SELECT value, metric FROM system.metrics',
    'columns': [
        {{
            'name': 'value',
            'type': 'source'
        }},
        {{
            'name': 'metric',
            'type': 'match',
            'source': 'value',
            'items': {{
{items}
            }},
        }},
    ],
}}
