# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit scripts/templates/system_events.tpl and then run the following command:
#     hatch run data:generate

# https://clickhouse.com/docs/operations/system-tables/events
SystemEvents = {{
    'name': 'system_events',
    'query': 'SELECT value, event FROM system.events',
    'columns': [
        {{
            'name': 'metric_value',
            'type': 'source'
        }},
        {{
            'name': 'metric_name',
            'type': 'match',
            'source': 'metric_value',
            'items': {{
{items}
            }},
        }},
    ],
}}
