# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)


METRICS_MAP = {
    "aggregateHypervisorMemoryUsagePpm": "aggregate_hypervisor.memory.usage_ppm",
    "aggregateHypervisorMemoryUsagePpmLowerBuf": "aggregate_hypervisor.memory.usage_ppm.lower_buf",
    "aggregateHypervisorMemoryUsagePpmUpperBuf": "aggregate_hypervisor.memory.usage_ppm.upper_buf",
    "controllerAvgIoLatencyUsecs": "controller.avg.io.latency.usecs",
    "controllerAvgIoLatencyUsecsLowerBuf": "controller.avg.io.latency.usecs.lower_buf",
    "controllerAvgIoLatencyUsecsUpperBuf": "controller.avg.io.latency.usecs.upper_buf",
    "controllerAvgReadIoLatencyUsecs": "controller.avg.read.io.latency.usecs",
    "controllerAvgReadIoLatencyUsecsLowerBuf": "controller.avg.read.io.latency.usecs.lower_buf",
    "controllerAvgReadIoLatencyUsecsUpperBuf": "controller.avg.read.io.latency.usecs.upper_buf",
    "controllerAvgWriteIoLatencyUsecs": "controller.avg.write.io.latency.usecs",
    "controllerAvgWriteIoLatencyUsecsLowerBuf": "controller.avg.write.io.latency.usecs.lower_buf",
    "controllerAvgWriteIoLatencyUsecsUpperBuf": "controller.avg.write.io.latency.usecs.upper_buf",
    "controllerNumIops": "controller.num.iops",
    "controllerNumIopsLowerBuf": "controller.num.iops.lower_buf",
    "controllerNumIopsUpperBuf": "controller.num.iops.upper_buf",
    "controllerNumReadIops": "controller.num.read.iops",
    "controllerNumReadIopsLowerBuf": "controller.num.read.iops.lower_buf",
    "controllerNumReadIopsUpperBuf": "controller.num.read.iops.upper_buf",
    "controllerNumWriteIops": "controller.num.write.iops",
    "controllerNumWriteIopsLowerBuf": "controller.num.write.iops.lower_buf",
    "controllerNumWriteIopsUpperBuf": "controller.num.write.iops.upper_buf",
    "controllerReadIoBandwidthKbps": "controller.read.io.bandwidth.kbps",
    "controllerReadIoBandwidthKbpsLowerBuf": "controller.read.io.bandwidth.kbps.lower_buf",
    "controllerReadIoBandwidthKbpsUpperBuf": "controller.read.io.bandwidth.kbps.upper_buf",
    "controllerWriteIoBandwidthKbps": "controller.write.io.bandwidth.kbps",
    "controllerWriteIoBandwidthKbpsLowerBuf": "controller.write.io.bandwidth.kbps.lower_buf",
    "controllerWriteIoBandwidthKbpsUpperBuf": "controller.write.io.bandwidth.kbps.upper_buf",
    "cpuCapacityHz": "cpu.capacity_hz",
    "cpuUsageHz": "cpu.usage_hz",
    "freePhysicalStorageBytes": "free.physical.storage_bytes",
    "healthCheckScore": "health.check_score",
    "hypervisorCpuUsagePpm": "hypervisor.cpu.usage_ppm",
    "hypervisorCpuUsagePpmLowerBuf": "hypervisor.cpu.usage_ppm.lower_buf",
    "hypervisorCpuUsagePpmUpperBuf": "hypervisor.cpu.usage_ppm.upper_buf",
    "ioBandwidthKbps": "io.bandwidth.kbps",
    "ioBandwidthKbpsLowerBuf": "io.bandwidth.kbps.lower_buf",
    "ioBandwidthKbpsUpperBuf": "io.bandwidth.kbps.upper_buf",
    "logicalStorageUsageBytes": "logical.storage.usage_bytes",
    "memoryCapacityBytes": "memory.capacity_bytes",
    "overallMemoryUsageBytes": "overall.memory.usage_bytes",
    "overallSavingsBytes": "overall.savings_bytes",
    "overallSavingsRatio": "overall.savings_ratio",
    "powerConsumptionInstantWatt": "power.consumption.instant_watt",
    "recycleBinUsageBytes": "recycle.bin.usage_bytes",
    "snapshotCapacityBytes": "snapshot.capacity_bytes",
    "storageCapacityBytes": "storage.capacity_bytes",
    "storageUsageBytes": "storage.usage_bytes",
}
