# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)


CLUSTER_STATS_METRICS = {
    "aggregateHypervisorMemoryUsagePpm": "aggregate_hypervisor.memory.usage_ppm",
    "controllerAvgIoLatencyUsecs": "controller.avg.io.latency.usecs",
    "controllerAvgReadIoLatencyUsecs": "controller.avg.read.io.latency.usecs",
    "controllerAvgWriteIoLatencyUsecs": "controller.avg.write.io.latency.usecs",
    "controllerNumIops": "controller.num.iops",
    "controllerNumReadIops": "controller.num.read.iops",
    "controllerNumWriteIops": "controller.num.write.iops",
    "controllerReadIoBandwidthKbps": "controller.read.io.bandwidth.kbps",
    "controllerWriteIoBandwidthKbps": "controller.write.io.bandwidth.kbps",
    "cpuCapacityHz": "cpu.capacity_hz",
    "cpuUsageHz": "cpu.usage_hz",
    "freePhysicalStorageBytes": "free.physical.storage_bytes",
    "healthCheckScore": "health.check_score",
    "hypervisorCpuUsagePpm": "hypervisor.cpu.usage_ppm",
    "ioBandwidthKbps": "io.bandwidth.kbps",
    "logicalStorageUsageBytes": "logical.storage.usage_bytes",
    "memoryCapacityBytes": "memory.capacity_bytes",
    "overallMemoryUsageBytes": "overall.memory.usage_bytes",
    "overallSavingsBytes": "overall.savings_bytes",
    "overallSavingsRatio": "overall.savings_ratio",
    "powerConsumptionInstantWatt": "power.consumption.instant_watt",
    "recycleBinUsageBytes": "recycle.bin.usage_bytes",
    "snapshotCapacityBytes": "snapshot.capacity_bytes",
    "storageCapacityBytes": "storage.capacity_bytes",
    "storageUsageBytes": "storage.usage_bytes",
}

HOST_STATS_METRICS = {
    "aggregateHypervisorMemoryUsagePpm": "host.aggregate_hypervisor.memory.usage_ppm",
    "controllerAvgIoLatencyUsecs": "host.controller.avg.io.latency.usecs",
    "controllerAvgReadIoLatencyUsecs": "host.controller.avg.read.io.latency.usecs",
    "controllerAvgWriteIoLatencyUsecs": "host.controller.avg.write.io.latency.usecs",
    "controllerNumIops": "host.controller.num.iops",
    "controllerNumReadIops": "host.controller.num.read.iops",
    "controllerNumWriteIops": "host.controller.num.write.iops",
    "controllerReadIoBandwidthKbps": "host.controller.read.io.bandwidth.kbps",
    "controllerWriteIoBandwidthKbps": "host.controller.write.io.bandwidth.kbps",
    "cpuCapacityHz": "host.cpu.capacity_hz",
    "cpuUsageHz": "host.cpu.usage_hz",
    "freePhysicalStorageBytes": "host.free.physical.storage_bytes",
    "healthCheckScore": "host.health.check_score",
    "hypervisorCpuUsagePpm": "host.hypervisor.cpu.usage_ppm",
    "ioBandwidthKbps": "host.io.bandwidth.kbps",
    "logicalStorageUsageBytes": "host.logical.storage.usage_bytes",
    "memoryCapacityBytes": "host.memory.capacity_bytes",
    "overallMemoryUsageBytes": "host.overall.memory.usage_bytes",
    "overallMemoryUsagePpm": "host.overall.memory.usage_ppm",
    "powerConsumptionInstantWatt": "host.power.consumption.instant_watt",
    "storageCapacityBytes": "host.storage.capacity_bytes",
    "storageUsageBytes": "host.storage.usage_bytes",
}
