# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def shared_collect_default_metrics():
    return False


def shared_is_jmx():
    return False


def shared_new_gc_metrics():
    return False


def shared_skip_proxy():
    return False


def shared_timeout():
    return 10


def instance_allow_redirects():
    return True


def instance_auth_type():
    return 'basic'


def instance_collect_default_jvm_metrics():
    return True


def instance_empty_default_hostname():
    return False


def instance_is_jmx():
    return False


def instance_kerberos_auth():
    return 'disabled'


def instance_kerberos_delegate():
    return False


def instance_kerberos_force_initiate():
    return False


def instance_log_requests():
    return False


def instance_min_collection_interval():
    return 15


def instance_persist_connections():
    return False


def instance_port():
    return 1099


def instance_request_size():
    return 16


def instance_rmi_client_timeout():
    return 15000


def instance_rmi_connection_timeout():
    return 20000


def instance_rmi_registry_ssl():
    return False


def instance_skip_proxy():
    return False


def instance_timeout():
    return 10


def instance_tls_ignore_warning():
    return False


def instance_tls_use_host_header():
    return False


def instance_tls_verify():
    return True


def instance_use_legacy_auth_encoding():
    return True
