# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)


class AgentEnvVars:
    API_KEY = 'DD_API_KEY'
    APM_ENABLED = 'DD_APM_ENABLED'
    APP_KEY = 'DD_APP_KEY'
    CMD_PORT = 'DD_CMD_PORT'
    DOGSTATSD_METRICS_STATS = 'DD_DOGSTATSD_METRICS_STATS_ENABLE'
    DOGSTATSD_NON_LOCAL_TRAFFIC = 'DD_DOGSTATSD_NON_LOCAL_TRAFFIC'
    DOGSTATSD_PORT = 'DD_DOGSTATSD_PORT'
    EXPVAR_PORT = 'DD_EXPVAR_PORT'
    HOSTNAME = 'DD_HOSTNAME'
    LOGS_ENABLED = 'DD_LOGS_ENABLED'
    LOGS_URL = 'DD_LOGS_CONFIG_LOGS_DD_URL'
    PROXY_HTTP = 'DD_PROXY_HTTP'
    PROXY_HTTPS = 'DD_PROXY_HTTPS'
    SITE = 'DD_SITE'
    TELEMETRY_ENABLED = 'DD_TELEMETRY_ENABLED'
    URL = 'DD_DD_URL'
