# (C) Datadog, Inc. 2019
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
STANDARD = [
    'ibm_db2.application.active',
    'ibm_db2.application.executing',
    'ibm_db2.connection.active',
    'ibm_db2.connection.max',
    'ibm_db2.connection.total',
    'ibm_db2.lock.dead',
    'ibm_db2.lock.waiting',
    'ibm_db2.lock.active',
    'ibm_db2.lock.wait',
    'ibm_db2.lock.pages',
    'ibm_db2.lock.timeouts',
    'ibm_db2.backup.latest',
    'ibm_db2.row.modified.total',
    'ibm_db2.row.reads.total',
    'ibm_db2.row.returned.total',
    'ibm_db2.bufferpool.column.reads.physical',
    'ibm_db2.bufferpool.column.reads.logical',
    'ibm_db2.bufferpool.column.reads.total',
    'ibm_db2.bufferpool.column.hit_percent',
    'ibm_db2.bufferpool.data.reads.physical',
    'ibm_db2.bufferpool.data.reads.logical',
    'ibm_db2.bufferpool.data.reads.total',
    'ibm_db2.bufferpool.data.hit_percent',
    'ibm_db2.bufferpool.index.reads.physical',
    'ibm_db2.bufferpool.index.reads.logical',
    'ibm_db2.bufferpool.index.reads.total',
    'ibm_db2.bufferpool.index.hit_percent',
    'ibm_db2.bufferpool.xda.reads.physical',
    'ibm_db2.bufferpool.xda.reads.logical',
    'ibm_db2.bufferpool.xda.reads.total',
    'ibm_db2.bufferpool.xda.hit_percent',
    'ibm_db2.bufferpool.reads.physical',
    'ibm_db2.bufferpool.reads.logical',
    'ibm_db2.bufferpool.reads.total',
    'ibm_db2.bufferpool.hit_percent',
    'ibm_db2.tablespace.size',
    'ibm_db2.tablespace.usable',
    'ibm_db2.tablespace.used',
    'ibm_db2.tablespace.utilized',
    'ibm_db2.log.used',
    'ibm_db2.log.available',
    'ibm_db2.log.utilized',
    'ibm_db2.log.reads',
    'ibm_db2.log.writes',
]

BUFFERPOOL = [
    'ibm_db2.bufferpool.column.reads.physical',
    'ibm_db2.bufferpool.column.reads.logical',
    'ibm_db2.bufferpool.column.reads.total',
    'ibm_db2.bufferpool.column.hit_percent',
    'ibm_db2.bufferpool.data.reads.physical',
    'ibm_db2.bufferpool.data.reads.logical',
    'ibm_db2.bufferpool.data.reads.total',
    'ibm_db2.bufferpool.data.hit_percent',
    'ibm_db2.bufferpool.index.reads.physical',
    'ibm_db2.bufferpool.index.reads.logical',
    'ibm_db2.bufferpool.index.reads.total',
    'ibm_db2.bufferpool.index.hit_percent',
    'ibm_db2.bufferpool.xda.reads.physical',
    'ibm_db2.bufferpool.xda.reads.logical',
    'ibm_db2.bufferpool.xda.reads.total',
    'ibm_db2.bufferpool.xda.hit_percent',
    'ibm_db2.bufferpool.reads.physical',
    'ibm_db2.bufferpool.reads.logical',
    'ibm_db2.bufferpool.reads.total',
    'ibm_db2.bufferpool.hit_percent',
]

TABLESPACE = [
    'ibm_db2.tablespace.size',
    'ibm_db2.tablespace.usable',
    'ibm_db2.tablespace.used',
    'ibm_db2.tablespace.utilized',
]
