# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

SYSTEM_MDM_CLUSTER_METRICS = [
    {'name': 'dell_powerflex.system.mdm_cluster.good_nodes', 'value': 3},
    {'name': 'dell_powerflex.system.mdm_cluster.good_replicas', 'value': 2},
    {
        'name': 'dell_powerflex.system.mdm_cluster.cluster_state',
        'value': 1,
        'extra_tags': ['cluster_state:ClusteredNormal'],
    },
    {'name': 'dell_powerflex.system.mdm_mode', 'value': 1, 'extra_tags': ['mdm_mode:ThreeNodes']},
]

SYSTEM_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.system.capacity.in_use_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.system.max_capacity.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.system.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.system.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.system.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.system.unused_capacity.in_kb', 'value': 179488768},
    {'name': 'dell_powerflex.system.spare_capacity.in_kb', 'value': 130733056},
    {'name': 'dell_powerflex.system.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.system.rmcache.size_in_kb', 'value': 393216},
    {'name': 'dell_powerflex.system.rmcache.size_in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.system.num_of_unmapped_volumes', 'value': 2},
    {'name': 'dell_powerflex.system.num_of_mapped_to_all_volumes', 'value': 0},
    {'name': 'dell_powerflex.system.num_of_snapshots', 'value': 2},
    {'name': 'dell_powerflex.system.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.system.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.system.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.system.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.system.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.system.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.system.user_data.capacity_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.system.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.system.overall_usage_ratio', 'value': 96.0},
    {'name': 'dell_powerflex.system.num_sds_reconnections', 'value': 8},
    {'name': 'dell_powerflex.system.num_dev_errors', 'value': 0},
    {'name': 'dell_powerflex.system.num_sds_sdr_disconnections', 'value': 0},
    {'name': 'dell_powerflex.system.num_sdr_sdc_disconnections', 'value': 0},
]

VOLUME_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.volume.num_of_child_volumes', 'value': 1},
    {'name': 'dell_powerflex.volume.num_of_mapped_sdcs', 'value': 1},
    {'name': 'dell_powerflex.volume.rpl_total_journal_cap', 'value': 0},
    {'name': 'dell_powerflex.volume.rpl_used_journal_cap', 'value': 0},
]

VOLUME_STATS_BWC_METRICS = [
    'dell_powerflex.volume.user_data_read_bwc',
    'dell_powerflex.volume.user_data_write_bwc',
    'dell_powerflex.volume.user_data_trim_bwc',
    'dell_powerflex.volume.user_data_sdc_read_latency',
    'dell_powerflex.volume.user_data_sdc_write_latency',
    'dell_powerflex.volume.user_data_sdc_trim_latency',
]

STORAGE_POOL_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.storage_pool.capacity_limit.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.storage_pool.max_capacity.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.storage_pool.capacity.in_use_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.storage_pool.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.unreachable_unused_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.unused_capacity.in_kb', 'value': 179488768},
    {'name': 'dell_powerflex.storage_pool.spare_capacity.in_kb', 'value': 130733056},
    {'name': 'dell_powerflex.storage_pool.capacity_available_for_volume_allocation.in_kb', 'value': 75497472},
    {'name': 'dell_powerflex.storage_pool.protected_capacity.in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.storage_pool.failed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.in_use_vac.in_kb', 'value': 67108864},
    {'name': 'dell_powerflex.storage_pool.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.num_of_unmapped_volumes', 'value': 2},
    {'name': 'dell_powerflex.storage_pool.num_of_snapshots', 'value': 2},
    {'name': 'dell_powerflex.storage_pool.num_of_volumes', 'value': 4},
    {'name': 'dell_powerflex.storage_pool.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.user_data.capacity_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.storage_pool.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.overall_usage_ratio', 'value': 96.0},
    {'name': 'dell_powerflex.storage_pool.exposed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.storage_pool.actual_net_capacity.in_use_in_kb', 'value': 0},
]

STORAGE_POOL_STATS_BWC_METRICS = [
    'dell_powerflex.storage_pool.user_data_read_bwc',
    'dell_powerflex.storage_pool.user_data_write_bwc',
    'dell_powerflex.storage_pool.user_data_trim_bwc',
    'dell_powerflex.storage_pool.user_data_sdc_read_latency',
    'dell_powerflex.storage_pool.user_data_sdc_write_latency',
    'dell_powerflex.storage_pool.user_data_sdc_trim_latency',
    'dell_powerflex.storage_pool.primary_read_bwc',
    'dell_powerflex.storage_pool.primary_write_bwc',
    'dell_powerflex.storage_pool.secondary_read_bwc',
    'dell_powerflex.storage_pool.secondary_write_bwc',
    'dell_powerflex.storage_pool.rebalance_read_bwc',
    'dell_powerflex.storage_pool.rebalance_write_bwc',
    'dell_powerflex.storage_pool.total_read_bwc',
    'dell_powerflex.storage_pool.total_write_bwc',
    'dell_powerflex.storage_pool.target_read_latency',
    'dell_powerflex.storage_pool.target_write_latency',
    'dell_powerflex.storage_pool.fwd_rebuild_read_bwc',
    'dell_powerflex.storage_pool.bck_rebuild_read_bwc',
    'dell_powerflex.storage_pool.norm_rebuild_read_bwc',
]

PROTECTION_DOMAIN_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.protection_domain.capacity_limit.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.protection_domain.max_capacity.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.protection_domain.capacity.in_use_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.protection_domain.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.unreachable_unused_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.unused_capacity.in_kb', 'value': 179488768},
    {'name': 'dell_powerflex.protection_domain.spare_capacity.in_kb', 'value': 130733056},
    {'name': 'dell_powerflex.protection_domain.capacity_available_for_volume_allocation.in_kb', 'value': 75497472},
    {'name': 'dell_powerflex.protection_domain.volume_allocation_limit.in_kb', 'value': 864026624},
    {'name': 'dell_powerflex.protection_domain.protected_capacity.in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.protection_domain.failed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.in_use_vac.in_kb', 'value': 67108864},
    {'name': 'dell_powerflex.protection_domain.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.num_of_unmapped_volumes', 'value': 2},
    {'name': 'dell_powerflex.protection_domain.num_of_snapshots', 'value': 2},
    {'name': 'dell_powerflex.protection_domain.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.net_user_data_capacity.in_kb', 'value': 524288},
    {'name': 'dell_powerflex.protection_domain.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.overall_usage_ratio', 'value': 96.0},
    {'name': 'dell_powerflex.protection_domain.net_capacity.in_use_in_kb', 'value': 524288},
    {'name': 'dell_powerflex.protection_domain.rebuild_wait_send_q_length', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rebalance_wait_send_q_length', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.rmcache.size_in_kb', 'value': 393216},
    {'name': 'dell_powerflex.protection_domain.rmcache.size_in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.num_of_thick_base_volumes', 'value': 0},
    {'name': 'dell_powerflex.protection_domain.num_of_thin_base_volumes', 'value': 2},
    {'name': 'dell_powerflex.protection_domain.num_of_sds', 'value': 3},
    {'name': 'dell_powerflex.protection_domain.num_of_storage_pools', 'value': 2},
    {'name': 'dell_powerflex.protection_domain.num_of_fault_sets', 'value': 0},
]

PROTECTION_DOMAIN_STATS_BWC_METRICS = [
    'dell_powerflex.protection_domain.user_data_read_bwc',
    'dell_powerflex.protection_domain.user_data_write_bwc',
    'dell_powerflex.protection_domain.user_data_trim_bwc',
    'dell_powerflex.protection_domain.user_data_sdc_read_latency',
    'dell_powerflex.protection_domain.user_data_sdc_write_latency',
    'dell_powerflex.protection_domain.user_data_sdc_trim_latency',
    'dell_powerflex.protection_domain.primary_read_bwc',
    'dell_powerflex.protection_domain.primary_write_bwc',
    'dell_powerflex.protection_domain.secondary_read_bwc',
    'dell_powerflex.protection_domain.secondary_write_bwc',
    'dell_powerflex.protection_domain.rebalance_read_bwc',
    'dell_powerflex.protection_domain.rebalance_write_bwc',
    'dell_powerflex.protection_domain.total_read_bwc',
    'dell_powerflex.protection_domain.total_write_bwc',
    'dell_powerflex.protection_domain.target_read_latency',
    'dell_powerflex.protection_domain.target_write_latency',
    'dell_powerflex.protection_domain.fwd_rebuild_read_bwc',
    'dell_powerflex.protection_domain.fwd_rebuild_write_bwc',
    'dell_powerflex.protection_domain.bck_rebuild_read_bwc',
    'dell_powerflex.protection_domain.bck_rebuild_write_bwc',
    'dell_powerflex.protection_domain.norm_rebuild_read_bwc',
    'dell_powerflex.protection_domain.norm_rebuild_write_bwc',
    'dell_powerflex.protection_domain.vol_migration_read_bwc',
    'dell_powerflex.protection_domain.vol_migration_write_bwc',
]

SDS_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.sds.capacity_limit.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.sds.max_capacity.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.sds.capacity.in_use_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.sds.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.sds.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.sds.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.sds.unreachable_unused_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.sds.unused_capacity.in_kb', 'value': 103407616},
    {'name': 'dell_powerflex.sds.failed_vac.in_kb', 'value': 0},
    {'name': 'dell_powerflex.sds.in_use_vac.in_kb', 'value': 22380544},
    {'name': 'dell_powerflex.sds.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.sds.num_of_devices', 'value': 1},
    {'name': 'dell_powerflex.sds.compression_ratio', 'value': 1.0},
    {'name': 'dell_powerflex.sds.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.reads_pending', 'value': 0},
    {'name': 'dell_powerflex.sds.rfcache.io_errors', 'value': 0},
    {'name': 'dell_powerflex.sds.user_data.capacity_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.sds.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.sds.rmcache.size_in_kb', 'value': 131072},
    {'name': 'dell_powerflex.sds.rmcache.size_in_use_in_kb', 'value': 0},
]

SDS_STATS_BWC_METRICS = [
    'dell_powerflex.sds.primary_read_bwc',
    'dell_powerflex.sds.primary_write_bwc',
    'dell_powerflex.sds.secondary_read_bwc',
    'dell_powerflex.sds.secondary_write_bwc',
    'dell_powerflex.sds.total_read_bwc',
    'dell_powerflex.sds.total_write_bwc',
    'dell_powerflex.sds.vol_migration_read_bwc',
    'dell_powerflex.sds.vol_migration_write_bwc',
    'dell_powerflex.sds.target_read_latency',
    'dell_powerflex.sds.target_write_latency',
    'dell_powerflex.sds.user_data_read_bwc',
    'dell_powerflex.sds.user_data_write_bwc',
    'dell_powerflex.sds.user_data_sdc_read_latency',
    'dell_powerflex.sds.user_data_sdc_write_latency',
]

DEVICE_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.device.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.device.avg_read_size_in_bytes', 'value': 353621},
    {'name': 'dell_powerflex.device.avg_write_size_in_bytes', 'value': 0},
    {'name': 'dell_powerflex.device.avg_read_latency_in_microsec', 'value': 9596},
    {'name': 'dell_powerflex.device.avg_write_latency_in_microsec', 'value': 0},
    {'name': 'dell_powerflex.device.capacity_limit.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.device.max_capacity.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.device.capacity.in_use_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.device.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.device.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.device.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.device.failed_vac.in_kb', 'value': 0},
    {'name': 'dell_powerflex.device.in_use_vac.in_kb', 'value': 22380544},
    {'name': 'dell_powerflex.device.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.device.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.device.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.device.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.device.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.device.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.device.user_data.capacity_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.device.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.device.compression_ratio', 'value': 1.0},
    {'name': 'dell_powerflex.device.inaccessible_capacity.in_kb', 'value': 0},
]

DEVICE_STATS_BWC_METRICS = [
    'dell_powerflex.device.primary_read_bwc',
    'dell_powerflex.device.primary_write_bwc',
    'dell_powerflex.device.secondary_read_bwc',
    'dell_powerflex.device.secondary_write_bwc',
    'dell_powerflex.device.total_read_bwc',
    'dell_powerflex.device.total_write_bwc',
    'dell_powerflex.device.target_read_latency',
    'dell_powerflex.device.target_write_latency',
]

SDC_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.sdc.num_of_mapped_volumes', 'value': 2},
]

SDC_STATS_BWC_METRICS = [
    'dell_powerflex.sdc.user_data_read_bwc',
    'dell_powerflex.sdc.user_data_write_bwc',
    'dell_powerflex.sdc.user_data_trim_bwc',
    'dell_powerflex.sdc.user_data_sdc_read_latency',
    'dell_powerflex.sdc.user_data_sdc_write_latency',
    'dell_powerflex.sdc.user_data_sdc_trim_latency',
]

SYSTEM_STATS_BWC_METRICS = [
    'dell_powerflex.system.user_data_read_bwc',
    'dell_powerflex.system.user_data_write_bwc',
    'dell_powerflex.system.user_data_trim_bwc',
    'dell_powerflex.system.user_data_sdc_read_latency',
    'dell_powerflex.system.user_data_sdc_write_latency',
    'dell_powerflex.system.user_data_sdc_trim_latency',
    'dell_powerflex.system.journaler_read_latency',
    'dell_powerflex.system.journaler_write_latency',
    'dell_powerflex.system.target_write_latency',
]
