# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

SYSTEM_MDM_CLUSTER_METRICS = [
    {'name': 'dell_powerflex.mdm_cluster.good_nodes', 'value': 3},
    {'name': 'dell_powerflex.mdm_cluster.good_replicas', 'value': 2},
    {
        'name': 'dell_powerflex.mdm_cluster.cluster_state',
        'value': 1,
        'extra_tags': ['cluster_state:ClusteredNormal'],
    },
    {'name': 'dell_powerflex.mdm_mode', 'value': 1, 'extra_tags': ['mdm_mode:ThreeNodes']},
]

SYSTEM_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.capacity.in_use_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.max_capacity.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.unused_capacity.in_kb', 'value': 179488768},
    {'name': 'dell_powerflex.spare_capacity.in_kb', 'value': 130733056},
    {'name': 'dell_powerflex.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.rmcache.size_in_kb', 'value': 393216},
    {'name': 'dell_powerflex.rmcache.size_in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.num_of_unmapped_volumes', 'value': 2},
    {'name': 'dell_powerflex.num_of_mapped_to_all_volumes', 'value': 0},
    {'name': 'dell_powerflex.num_of_snapshots', 'value': 2},
    {'name': 'dell_powerflex.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.user_data.capacity_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.overall_usage_ratio', 'value': 96.0},
    {'name': 'dell_powerflex.num_sds_reconnections', 'value': 8},
    {'name': 'dell_powerflex.num_dev_errors', 'value': 0},
    {'name': 'dell_powerflex.num_sds_sdr_disconnections', 'value': 0},
    {'name': 'dell_powerflex.num_sdr_sdc_disconnections', 'value': 0},
]

VOLUME_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.num_of_child_volumes', 'value': 1},
    {'name': 'dell_powerflex.num_of_mapped_sdcs', 'value': 1},
    {'name': 'dell_powerflex.rpl_total_journal_cap', 'value': 0},
    {'name': 'dell_powerflex.rpl_used_journal_cap', 'value': 0},
]

VOLUME_STATS_BWC_METRICS = [
    'dell_powerflex.user_data_read_bwc',
    'dell_powerflex.user_data_write_bwc',
    'dell_powerflex.user_data_trim_bwc',
    'dell_powerflex.user_data_sdc_read_latency',
    'dell_powerflex.user_data_sdc_write_latency',
    'dell_powerflex.user_data_sdc_trim_latency',
]

STORAGE_POOL_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.capacity_limit.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.max_capacity.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.capacity.in_use_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.unreachable_unused_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.unused_capacity.in_kb', 'value': 179488768},
    {'name': 'dell_powerflex.spare_capacity.in_kb', 'value': 130733056},
    {'name': 'dell_powerflex.capacity_available_for_volume_allocation.in_kb', 'value': 75497472},
    {'name': 'dell_powerflex.protected_capacity.in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.failed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.in_use_vac.in_kb', 'value': 67108864},
    {'name': 'dell_powerflex.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.num_of_unmapped_volumes', 'value': 2},
    {'name': 'dell_powerflex.num_of_snapshots', 'value': 2},
    {'name': 'dell_powerflex.num_of_volumes', 'value': 4},
    {'name': 'dell_powerflex.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.user_data.capacity_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.overall_usage_ratio', 'value': 96.0},
    {'name': 'dell_powerflex.exposed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.actual_net_capacity.in_use_in_kb', 'value': 0},
]

STORAGE_POOL_STATS_BWC_METRICS = [
    'dell_powerflex.user_data_read_bwc',
    'dell_powerflex.user_data_write_bwc',
    'dell_powerflex.user_data_trim_bwc',
    'dell_powerflex.user_data_sdc_read_latency',
    'dell_powerflex.user_data_sdc_write_latency',
    'dell_powerflex.user_data_sdc_trim_latency',
    'dell_powerflex.primary_read_bwc',
    'dell_powerflex.primary_write_bwc',
    'dell_powerflex.secondary_read_bwc',
    'dell_powerflex.secondary_write_bwc',
    'dell_powerflex.rebalance_read_bwc',
    'dell_powerflex.rebalance_write_bwc',
    'dell_powerflex.total_read_bwc',
    'dell_powerflex.total_write_bwc',
    'dell_powerflex.target_read_latency',
    'dell_powerflex.target_write_latency',
    'dell_powerflex.fwd_rebuild_read_bwc',
    'dell_powerflex.bck_rebuild_read_bwc',
    'dell_powerflex.norm_rebuild_read_bwc',
]

PROTECTION_DOMAIN_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.capacity_limit.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.max_capacity.in_kb', 'value': 311270400},
    {'name': 'dell_powerflex.capacity.in_use_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.unreachable_unused_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.unused_capacity.in_kb', 'value': 179488768},
    {'name': 'dell_powerflex.spare_capacity.in_kb', 'value': 130733056},
    {'name': 'dell_powerflex.capacity_available_for_volume_allocation.in_kb', 'value': 75497472},
    {'name': 'dell_powerflex.volume_allocation_limit.in_kb', 'value': 864026624},
    {'name': 'dell_powerflex.protected_capacity.in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.failed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.in_use_vac.in_kb', 'value': 67108864},
    {'name': 'dell_powerflex.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.num_of_unmapped_volumes', 'value': 2},
    {'name': 'dell_powerflex.num_of_snapshots', 'value': 2},
    {'name': 'dell_powerflex.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.net_user_data_capacity.in_kb', 'value': 524288},
    {'name': 'dell_powerflex.user_data.capacity_in_kb', 'value': 1048576},
    {'name': 'dell_powerflex.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.overall_usage_ratio', 'value': 96.0},
    {'name': 'dell_powerflex.net_capacity.in_use_in_kb', 'value': 524288},
    {'name': 'dell_powerflex.rebuild_wait_send_q_length', 'value': 0},
    {'name': 'dell_powerflex.rebalance_wait_send_q_length', 'value': 0},
    {'name': 'dell_powerflex.rmcache.size_in_kb', 'value': 393216},
    {'name': 'dell_powerflex.rmcache.size_in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.num_of_thick_base_volumes', 'value': 0},
    {'name': 'dell_powerflex.num_of_thin_base_volumes', 'value': 2},
    {'name': 'dell_powerflex.num_of_sds', 'value': 3},
    {'name': 'dell_powerflex.num_of_storage_pools', 'value': 2},
    {'name': 'dell_powerflex.num_of_fault_sets', 'value': 0},
    {'name': 'dell_powerflex.exposed_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.actual_net_capacity.in_use_in_kb', 'value': 0},
]

PROTECTION_DOMAIN_STATS_BWC_METRICS = [
    'dell_powerflex.user_data_read_bwc',
    'dell_powerflex.user_data_write_bwc',
    'dell_powerflex.user_data_trim_bwc',
    'dell_powerflex.user_data_sdc_read_latency',
    'dell_powerflex.user_data_sdc_write_latency',
    'dell_powerflex.user_data_sdc_trim_latency',
    'dell_powerflex.primary_read_bwc',
    'dell_powerflex.primary_write_bwc',
    'dell_powerflex.secondary_read_bwc',
    'dell_powerflex.secondary_write_bwc',
    'dell_powerflex.rebalance_read_bwc',
    'dell_powerflex.rebalance_write_bwc',
    'dell_powerflex.total_read_bwc',
    'dell_powerflex.total_write_bwc',
    'dell_powerflex.target_read_latency',
    'dell_powerflex.target_write_latency',
    'dell_powerflex.fwd_rebuild_read_bwc',
    'dell_powerflex.fwd_rebuild_write_bwc',
    'dell_powerflex.bck_rebuild_read_bwc',
    'dell_powerflex.bck_rebuild_write_bwc',
    'dell_powerflex.norm_rebuild_read_bwc',
    'dell_powerflex.norm_rebuild_write_bwc',
    'dell_powerflex.vol_migration_read_bwc',
    'dell_powerflex.vol_migration_write_bwc',
]

SDS_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.capacity_limit.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.max_capacity.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.capacity.in_use_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.unreachable_unused_capacity.in_kb', 'value': 0},
    {'name': 'dell_powerflex.unused_capacity.in_kb', 'value': 103407616},
    {'name': 'dell_powerflex.failed_vac.in_kb', 'value': 0},
    {'name': 'dell_powerflex.in_use_vac.in_kb', 'value': 22380544},
    {'name': 'dell_powerflex.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.num_of_devices', 'value': 1},
    {'name': 'dell_powerflex.compression_ratio', 'value': 1.0},
    {'name': 'dell_powerflex.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.rfcache.reads_pending', 'value': 0},
    {'name': 'dell_powerflex.rfcache.io_errors', 'value': 0},
    {'name': 'dell_powerflex.user_data.capacity_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.rmcache.size_in_kb', 'value': 131072},
    {'name': 'dell_powerflex.rmcache.size_in_use_in_kb', 'value': 0},
]

SDS_STATS_BWC_METRICS = [
    'dell_powerflex.primary_read_bwc',
    'dell_powerflex.primary_write_bwc',
    'dell_powerflex.secondary_read_bwc',
    'dell_powerflex.secondary_write_bwc',
    'dell_powerflex.total_read_bwc',
    'dell_powerflex.total_write_bwc',
    'dell_powerflex.vol_migration_read_bwc',
    'dell_powerflex.vol_migration_write_bwc',
    'dell_powerflex.target_read_latency',
    'dell_powerflex.target_write_latency',
    'dell_powerflex.user_data_read_bwc',
    'dell_powerflex.user_data_write_bwc',
    'dell_powerflex.user_data_sdc_read_latency',
    'dell_powerflex.user_data_sdc_write_latency',
]

DEVICE_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.fixed_read_error_count', 'value': 0},
    {'name': 'dell_powerflex.avg_read_size_in_bytes', 'value': 353621},
    {'name': 'dell_powerflex.avg_write_size_in_bytes', 'value': 0},
    {'name': 'dell_powerflex.avg_read_latency_in_microsec', 'value': 9596},
    {'name': 'dell_powerflex.avg_write_latency_in_microsec', 'value': 0},
    {'name': 'dell_powerflex.capacity_limit.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.max_capacity.in_kb', 'value': 103756800},
    {'name': 'dell_powerflex.capacity.in_use_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.thick_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.thin_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.snap_capacity.in_use_in_kb', 'value': 0},
    {'name': 'dell_powerflex.failed_vac.in_kb', 'value': 0},
    {'name': 'dell_powerflex.in_use_vac.in_kb', 'value': 22380544},
    {'name': 'dell_powerflex.rfcache.reads_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.writes_received', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.read_miss', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_hit', 'value': 0},
    {'name': 'dell_powerflex.rfcache.write_miss', 'value': 0},
    {'name': 'dell_powerflex.user_data.capacity_in_kb', 'value': 349184},
    {'name': 'dell_powerflex.snapshot.capacity_in_kb', 'value': 0},
    {'name': 'dell_powerflex.compression_ratio', 'value': 1.0},
    {'name': 'dell_powerflex.inaccessible_capacity.in_kb', 'value': 0},
]

DEVICE_STATS_BWC_METRICS = [
    'dell_powerflex.primary_read_bwc',
    'dell_powerflex.primary_write_bwc',
    'dell_powerflex.secondary_read_bwc',
    'dell_powerflex.secondary_write_bwc',
    'dell_powerflex.total_read_bwc',
    'dell_powerflex.total_write_bwc',
    'dell_powerflex.target_read_latency',
    'dell_powerflex.target_write_latency',
]

SDC_STATS_SIMPLE_METRICS = [
    {'name': 'dell_powerflex.num_of_mapped_volumes', 'value': 2},
]

SDC_STATS_BWC_METRICS = [
    'dell_powerflex.user_data_read_bwc',
    'dell_powerflex.user_data_write_bwc',
    'dell_powerflex.user_data_trim_bwc',
    'dell_powerflex.user_data_sdc_read_latency',
    'dell_powerflex.user_data_sdc_write_latency',
    'dell_powerflex.user_data_sdc_trim_latency',
]

SYSTEM_STATS_BWC_METRICS = [
    'dell_powerflex.user_data_read_bwc',
    'dell_powerflex.user_data_write_bwc',
    'dell_powerflex.user_data_trim_bwc',
    'dell_powerflex.user_data_sdc_read_latency',
    'dell_powerflex.user_data_sdc_write_latency',
    'dell_powerflex.user_data_sdc_trim_latency',
    'dell_powerflex.journaler_read_latency',
    'dell_powerflex.journaler_write_latency',
    'dell_powerflex.target_write_latency',
]
