# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from __future__ import annotations

from typing import Any, Mapping, Optional, Sequence

from pydantic import BaseModel, root_validator, validator

from datadog_checks.base.utils.functions import identity
from datadog_checks.base.utils.models import validation

from . import defaults, validators


class Aws(BaseModel):
    class Config:
        allow_mutation = False

    instance_endpoint: Optional[str]


class Azure(BaseModel):
    class Config:
        allow_mutation = False

    deployment_type: Optional[str]
    name: Optional[str]


class CustomQuery(BaseModel):
    class Config:
        allow_mutation = False

    columns: Optional[Sequence[Mapping[str, Any]]]
    query: Optional[str]
    tags: Optional[Sequence[str]]


class Gcp(BaseModel):
    class Config:
        allow_mutation = False

    instance_id: Optional[str]
    project_id: Optional[str]


class MetricPatterns(BaseModel):
    class Config:
        allow_mutation = False

    exclude: Optional[Sequence[str]]
    include: Optional[Sequence[str]]


class ObfuscatorOptions(BaseModel):
    class Config:
        allow_mutation = False

    collect_commands: Optional[bool]
    collect_comments: Optional[bool]
    collect_metadata: Optional[bool]
    collect_tables: Optional[bool]
    keep_sql_alias: Optional[bool]
    replace_digits: Optional[bool]


class QueryActivity(BaseModel):
    class Config:
        allow_mutation = False

    collection_interval: Optional[float]
    enabled: Optional[bool]


class QueryMetrics(BaseModel):
    class Config:
        allow_mutation = False

    collection_interval: Optional[float]
    disable_secondary_tags: Optional[bool]
    dm_exec_query_stats_row_limit: Optional[int]
    enabled: Optional[bool]
    enforce_collection_interval_deadline: Optional[bool]
    samples_per_hour_per_query: Optional[int]


class InstanceConfig(BaseModel):
    class Config:
        allow_mutation = False

    adoprovider: Optional[str]
    ao_database: Optional[str]
    autodiscovery_db_service_check: Optional[bool]
    autodiscovery_exclude: Optional[Sequence[str]]
    autodiscovery_include: Optional[Sequence[str]]
    availability_group: Optional[str]
    aws: Optional[Aws]
    azure: Optional[Azure]
    command_timeout: Optional[int]
    connection_string: Optional[str]
    connector: Optional[str]
    custom_queries: Optional[Sequence[CustomQuery]]
    database: Optional[str]
    database_autodiscovery: Optional[bool]
    database_autodiscovery_interval: Optional[int]
    db_fragmentation_object_names: Optional[Sequence[str]]
    dbm: Optional[bool]
    disable_generic_tags: Optional[bool]
    driver: Optional[str]
    dsn: Optional[str]
    empty_default_hostname: Optional[bool]
    gcp: Optional[Gcp]
    host: str
    ignore_missing_database: Optional[bool]
    include_ao_metrics: Optional[bool]
    include_db_fragmentation_metrics: Optional[bool]
    include_fci_metrics: Optional[bool]
    include_instance_metrics: Optional[bool]
    include_master_files_metrics: Optional[bool]
    include_task_scheduler_metrics: Optional[bool]
    log_unobfuscated_plans: Optional[bool]
    log_unobfuscated_queries: Optional[bool]
    metric_patterns: Optional[MetricPatterns]
    min_collection_interval: Optional[float]
    obfuscator_options: Optional[ObfuscatorOptions]
    only_custom_queries: Optional[bool]
    only_emit_local: Optional[bool]
    password: Optional[str]
    proc_only_if: Optional[str]
    proc_only_if_database: Optional[str]
    query_activity: Optional[QueryActivity]
    query_metrics: Optional[QueryMetrics]
    reported_hostname: Optional[str]
    server_version: Optional[str]
    service: Optional[str]
    stored_procedure: Optional[str]
    tags: Optional[Sequence[str]]
    use_global_custom_queries: Optional[str]
    username: Optional[str]

    @root_validator(pre=True)
    def _initial_validation(cls, values):
        return validation.core.initialize_config(getattr(validators, 'initialize_instance', identity)(values))

    @validator('*', pre=True, always=True)
    def _ensure_defaults(cls, v, field):
        if v is not None or field.required:
            return v

        return getattr(defaults, f'instance_{field.name}')(field, v)

    @validator('*')
    def _run_validations(cls, v, field):
        if not v:
            return v

        return getattr(validators, f'instance_{field.name}', identity)(v, field=field)

    @root_validator(pre=False)
    def _final_validation(cls, values):
        return validation.core.finalize_config(getattr(validators, 'finalize_instance', identity)(values))
