# (C) Datadog, Inc. 2023-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
METRICS_MAP = {
    'nv_cache_insertion_duration': 'cache.insertion.duration',
    'nv_cache_lookup_duration': 'cache.lookup.duration',
    'nv_cache_num_entries': 'cache.num.entries',
    'nv_cache_num_evictions': 'cache.num.evictions',
    'nv_cache_num_hits': 'cache.num.hits',
    'nv_cache_num_lookups': 'cache.num.lookups',
    'nv_cache_num_misses': 'cache.num.misses',
    'nv_cache_util': 'cache.util',
    'nv_cpu_memory_total_bytes': 'cpu.memory.total_bytes',
    'nv_cpu_memory_used_bytes': 'cpu.memory.used_bytes',
    'nv_cpu_utilization': 'cpu.utilization',
    'nv_energy_consumption': 'energy.consumption',
    'nv_gpu_memory_total_bytes': 'gpu.memory.total_bytes',
    'nv_gpu_memory_used_bytes': 'gpu.memory.used_bytes',
    'nv_gpu_power_limit': 'gpu.power.limit',
    'nv_gpu_power_usage': 'gpu.power.usage',
    'nv_gpu_utilization': 'gpu.utilization',
    'nv_inference_compute_infer_duration_us': 'inference.compute.infer.duration_us',
    'nv_inference_compute_infer_summary_us': 'inference.compute.infer.summary_us',
    'nv_inference_compute_input_duration_us': 'inference.compute.input.duration_us',
    'nv_inference_compute_input_summary_us': 'inference.compute.input.summary_us',
    'nv_inference_compute_output_duration_us': 'inference.compute.output.duration_us',
    'nv_inference_compute_output_summary_us': 'inference.compute.output.summary_us',
    'nv_inference_count': 'inference.count',
    'nv_inference_exec_count': 'inference.exec.count',
    'nv_inference_pending_request_count': 'inference.pending.request.count',
    'nv_inference_queue_duration_us': 'inference.queue.duration_us',
    'nv_inference_queue_summary_us': 'inference.queue.summary_us',
    'nv_inference_request_duration_us': 'inference.request.duration_us',
    'nv_inference_request_summary_us': 'inference.request.summary_us',
    'nv_inference_request_failure': 'inference.request_failure',
    'nv_inference_request_success': 'inference.request_success',
}
