# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This is not actually every metric, but rather the metrics that are
# immediately available upon the start up of our environment. Some
# metrics take a while to show up and others we cannot trigger.
ALL_METRICS = [
    'clickhouse.background_pool.processing.memory',
    'clickhouse.background_pool.processing.task.active',
    'clickhouse.background_pool.schedule.memory',
    'clickhouse.background_pool.schedule.task.active',
    'clickhouse.connection.http',
    'clickhouse.connection.interserver',
    'clickhouse.connection.send.external',
    'clickhouse.connection.tcp',
    'clickhouse.dictionary.item.current',
    'clickhouse.dictionary.load',
    'clickhouse.dictionary.memory.used',
    'clickhouse.dictionary.request.cache',
    'clickhouse.file.open.read',
    'clickhouse.file.open.total',
    'clickhouse.file.open.write',
    'clickhouse.file.read.size.total',
    'clickhouse.file.read.total',
    'clickhouse.file.write.size.total',
    'clickhouse.file.write.total',
    'clickhouse.lock.context.acquisition.total',
    'clickhouse.merge.active',
    'clickhouse.merge.disk.reserved',
    'clickhouse.merge.memory',
    'clickhouse.query.active',
    'clickhouse.query.insert.delayed',
    'clickhouse.query.memory',
    'clickhouse.query.mutation',
    'clickhouse.query.select.total',
    'clickhouse.query.total',
    'clickhouse.query.waiting',
    'clickhouse.replica.leader.election',
    'clickhouse.syscall.read',
    'clickhouse.syscall.write',
    'clickhouse.table.buffer.row',
    'clickhouse.table.buffer.size',
    'clickhouse.table.distributed.connection.inserted',
    'clickhouse.table.mergetree.part.current',
    'clickhouse.table.mergetree.row.current',
    'clickhouse.table.mergetree.size',
    'clickhouse.table.replicated.active',
    'clickhouse.table.replicated.leader',
    'clickhouse.table.replicated.log.max',
    'clickhouse.table.replicated.log.pointer',
    'clickhouse.table.replicated.part.check',
    'clickhouse.table.replicated.part.fetch',
    'clickhouse.table.replicated.part.future',
    'clickhouse.table.replicated.part.send',
    'clickhouse.table.replicated.part.suspect',
    'clickhouse.table.replicated.queue.insert',
    'clickhouse.table.replicated.queue.merge',
    'clickhouse.table.replicated.queue.size',
    'clickhouse.table.replicated.readonly',
    'clickhouse.table.replicated.total',
    'clickhouse.table.replicated.version',
    'clickhouse.thread.lock.context.waiting',
    'clickhouse.thread.lock.rw.active.read',
    'clickhouse.thread.lock.rw.active.write',
    'clickhouse.thread.lock.rw.waiting.read',
    'clickhouse.thread.lock.rw.waiting.write',
    'clickhouse.thread.query',
    'clickhouse.zk.connection',
    'clickhouse.zk.node.ephemeral',
    'clickhouse.zk.request',
    'clickhouse.zk.watch',
]
