# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
"""Advanced ClickHouse query definitions.

This package exposes four ``QueryManager`` query dicts:

- ``SystemEvents``, ``SystemMetrics``, and ``SystemAsynchronousMetrics`` are
  *bulk match queries*. Each one runs a single SQL that returns
  ``(value, metric_name)`` rows, then routes the metric-name column through a
  per-name lookup table to emit hundreds of Datadog metrics from one statement.
  Their lookup tables are large (over 1,000 entries for ``SystemEvents``), so
  the data ships as compact JSON under ``data/system_*.json`` and is
  reassembled into the ``QueryManager`` shape at load time.

- ``SystemErrors`` does not follow the bulk-match pattern. It runs a SQL that
  emits one ``errors.raised`` metric tagged by name/code/remote, with no
  per-row metric lookup. It lives below as a plain Python literal because the
  compression that justifies JSON has nothing to compress for a one-metric,
  three-tag query.

The compact JSON schema for a bulk match query is::

    {
      "name": "<query identifier passed to QueryManager>",
      "query": "<SQL>",
      "value_column": "<source-column name; becomes columns[0].name>",
      "match_column": "<dispatching-column name; becomes columns[1].name>",
      "prefix": "<Datadog metric-name prefix>",
      "items": {
        "<datadog metric type>": ["<key>", ...],          # gauge / monotonic_gauge
        "temporal_percent": {"<key>": "<scale>", ...}     # carries scale
      }
    }

At load time, ``load_match_query`` synthesises the two-column scaffold
(``[{value_column source}, {match_column match}]``) and expands ``items`` into
the per-entry shape ``QueryManager`` consumes::

    items["<key>"] = {"name": f"{prefix}.{key}", "type": "<datadog metric type>"
                      [, "scale": "<scale>"]}

The three ``data/system_*.json`` files are autogenerated from ClickHouse's C++
source by ``clickhouse/scripts/generate_metrics.py``. To update them (typically
when supporting a new ClickHouse version), run from the ``clickhouse``
directory::

    VERSIONS=24.8,25.3,25.8 hatch run metrics:generate

Don't edit those JSON files by hand; the generator overwrites them on the next
run. If you need a new metric type or a schema change, edit
``generate_metrics.py`` (the ``generate_queries`` function and the
``QUERY_SPECS`` table).
"""

from __future__ import annotations

import json
import os
from typing import Any

__all__ = ['SystemAsynchronousMetrics', 'SystemErrors', 'SystemEvents', 'SystemMetrics']

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data')

MATCH_QUERIES = {
    'SystemEvents': 'system_events',
    'SystemMetrics': 'system_metrics',
    'SystemAsynchronousMetrics': 'system_async_metrics',
}

_match_query_cache: dict[str, dict[str, Any]] = {}

SystemErrors: dict[str, Any] = {
    'name': 'system.errors',
    'query': 'SELECT value, name, code, remote FROM system.errors WHERE value > 0',
    'columns': [
        {'name': 'errors.raised', 'type': 'monotonic_count'},
        {'name': 'error_name', 'type': 'tag'},
        {'name': 'error_code', 'type': 'tag'},
        {'name': 'remote', 'type': 'tag', 'boolean': True},
    ],
}


def load_match_query(name: str) -> dict[str, Any]:
    """Read ``data/<name>.json`` and reconstitute the QueryManager-shaped dict."""
    try:
        with open(os.path.join(DATA_DIR, f'{name}.json'), encoding='utf-8') as f:
            spec = json.load(f)
        items = _expand_match_items(spec['items'], spec['prefix'])
        return {
            'name': spec['name'],
            'query': spec['query'],
            'columns': [
                {'name': spec['value_column'], 'type': 'source'},
                {
                    'name': spec['match_column'],
                    'type': 'match',
                    'source': spec['value_column'],
                    'items': items,
                },
            ],
        }
    except (OSError, json.JSONDecodeError, KeyError, TypeError, AttributeError) as exc:
        raise RuntimeError(f'failed to load advanced query {name!r}') from exc


def _expand_match_items(
    compact: dict[str, list[str] | dict[str, str]], prefix: str
) -> dict[str, dict[str, Any]]:
    """Expand the compact ``{type: keys | {key: scale}}`` map to the per-entry dict shape."""
    merged: dict[str, dict[str, Any]] = {}
    for type_name, group in compact.items():
        if isinstance(group, dict):
            for key, scale in group.items():
                merged[key] = {'name': f'{prefix}.{key}', 'type': type_name, 'scale': scale}
        else:
            for key in group:
                merged[key] = {'name': f'{prefix}.{key}', 'type': type_name}
    return dict(sorted(merged.items()))


def warm_cache() -> None:
    """Populate the match-query cache for every known name. Idempotent."""
    for attr, file in MATCH_QUERIES.items():
        if attr not in _match_query_cache:
            _match_query_cache[attr] = load_match_query(file)


def __getattr__(name: str) -> dict[str, Any]:
    if name not in MATCH_QUERIES:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    if name not in _match_query_cache:
        _match_query_cache[name] = load_match_query(MATCH_QUERIES[name])
    return _match_query_cache[name]
