# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

import os

from datadog_checks.dev import get_docker_hostname, get_here

HERE = get_here()
HOST = get_docker_hostname()
PORT = 8080


def get_fixture_path(filename):
    return os.path.join(HERE, 'fixtures', filename)


MOCKED_INSTANCE = {
    "openmetrics_endpoint": f"http://{HOST}:{PORT}/metrics",
    'tags': ['test:tag'],
}

COMPOSE_FILE = os.path.join(HERE, 'docker', 'docker-compose.yaml')

TEST_METRICS = [
    'keda.aggregator_discovery_aggregation.count',
    'keda.apiserver_audit_event.count',
    'keda.apiserver_audit_requests_rejected.count',
    'keda.apiserver_client_certificate_expiration_seconds.bucket',
    'keda.apiserver_client_certificate_expiration_seconds.count',
    'keda.apiserver_client_certificate_expiration_seconds.sum',
    'keda.apiserver_current_inflight_requests',
    'keda.apiserver_delegated_authz_request.count',
    'keda.apiserver_delegated_authz_request_duration_seconds.bucket',
    'keda.apiserver_delegated_authz_request_duration_seconds.count',
    'keda.apiserver_delegated_authz_request_duration_seconds.sum',
    'keda.apiserver_envelope_encryption_dek_cache_fill_percent',
    'keda.apiserver_flowcontrol_read_vs_write_current_requests.bucket',
    'keda.apiserver_flowcontrol_read_vs_write_current_requests.count',
    'keda.apiserver_flowcontrol_read_vs_write_current_requests.sum',
    'keda.apiserver_flowcontrol_seat_fair_frac',
    'keda.apiserver_request.count',
    'keda.apiserver_request_duration_seconds.bucket',
    'keda.apiserver_request_duration_seconds.count',
    'keda.apiserver_request_duration_seconds.sum',
    'keda.apiserver_request_filter_duration_seconds.bucket',
    'keda.apiserver_request_filter_duration_seconds.count',
    'keda.apiserver_request_filter_duration_seconds.sum',
    'keda.apiserver_request_sli_duration_seconds.bucket',
    'keda.apiserver_request_sli_duration_seconds.count',
    'keda.apiserver_request_sli_duration_seconds.sum',
    'keda.apiserver_request_slo_duration_seconds.bucket',
    'keda.apiserver_request_slo_duration_seconds.count',
    'keda.apiserver_request_slo_duration_seconds.sum',
    'keda.apiserver_response_sizes.bucket',
    'keda.apiserver_response_sizes.count',
    'keda.apiserver_response_sizes.sum',
    'keda.apiserver_storage_data_key_generation_duration_seconds.bucket',
    'keda.apiserver_storage_data_key_generation_duration_seconds.count',
    'keda.apiserver_storage_data_key_generation_duration_seconds.sum',
    'keda.apiserver_storage_data_key_generation_failures.count',
    'keda.apiserver_storage_envelope_transformation_cache_misses.count',
    'keda.apiserver_tls_handshake_errors.count',
    'keda.apiserver_webhooks_x509_insecure_sha1.count',
    'keda.apiserver_webhooks_x509_missing_san.count',
    'keda.authenticated_user_requests.count',
    'keda.authentication_attempts.count',
    'keda.authentication_duration_seconds.bucket',
    'keda.authentication_duration_seconds.count',
    'keda.authentication_duration_seconds.sum',
    'keda.authorization_attempts.count',
    'keda.authorization_duration_seconds.bucket',
    'keda.authorization_duration_seconds.count',
    'keda.authorization_duration_seconds.sum',
    'keda.build_info',
    'keda.cardinality_enforcement_unexpected_categorizations.count',
    'keda.certwatcher.read_certificate.count',
    'keda.certwatcher.read_certificate_errors.count',
    'keda.controller.runtime.active_workers',
    'keda.controller.runtime.max_concurrent_reconciles',
    'keda.controller.runtime.reconcile.count',
    'keda.controller.runtime.reconcile_errors.count',
    'keda.controller.runtime.reconcile_panics.count',
    'keda.controller.runtime.reconcile_time.seconds.bucket',
    'keda.controller.runtime.reconcile_time.seconds.count',
    'keda.controller.runtime.reconcile_time.seconds.sum',
    'keda.controller.runtime.terminal_reconcile_errors.count',
    'keda.controller.runtime.webhook_panics.count',
    'keda.controller.runtime.webhook_requests.count',
    'keda.controller.runtime.webhook_requests_in_flight',
    'keda.disabled_metrics.count',
    'keda.field_validation_request_duration_seconds.bucket',
    'keda.field_validation_request_duration_seconds.count',
    'keda.field_validation_request_duration_seconds.sum',
    'keda.go.gc.duration.seconds.count',
    'keda.go.gc.duration.seconds.quantile',
    'keda.go.gc.duration.seconds.sum',
    'keda.go.goroutines',
    'keda.go.info',
    'keda.go.memstats.alloc_bytes',
    'keda.go.memstats.alloc_bytes.count',
    'keda.go.memstats.buck_hash.sys_bytes',
    'keda.go.memstats.frees.count',
    'keda.go.memstats.gc.sys_bytes',
    'keda.go.memstats.heap.alloc_bytes',
    'keda.go.memstats.heap.idle_bytes',
    'keda.go.memstats.heap.inuse_bytes',
    'keda.go.memstats.heap.objects',
    'keda.go.memstats.heap.released_bytes',
    'keda.go.memstats.heap.sys_bytes',
    'keda.go.memstats.time_since_last_gc.seconds',
    'keda.go.memstats.lookups.count',
    'keda.go.memstats.mallocs.count',
    'keda.go.memstats.mcache.inuse_bytes',
    'keda.go.memstats.mcache.sys_bytes',
    'keda.go.memstats.mspan.inuse_bytes',
    'keda.go.memstats.mspan.sys_bytes',
    'keda.go.memstats.next.gc_bytes',
    'keda.go.memstats.other.sys_bytes',
    'keda.go.memstats.stack.inuse_bytes',
    'keda.go.memstats.stack.sys_bytes',
    'keda.go.memstats.sys_bytes',
    'keda.go.threads',
    'keda.hidden_metrics.count',
    'keda.internal_scale.loop_latency',
    'keda.internal_scale.loop_latency_seconds',
    'keda.leader_election.master_status',
    'keda.process.cpu.seconds.count',
    'keda.process.max_fds',
    'keda.process.open_fds',
    'keda.process.resident_memory.bytes',
    'keda.process.uptime.seconds',
    'keda.process.virtual_memory.bytes',
    'keda.process.virtual_memory.max_bytes',
    'keda.registered_metrics.count',
    'keda.resource_totals',
    'keda.rest.client.requests.count',
    'keda.scaled_job.errors.count',
    'keda.scaler.active',
    'keda.scaler.detail_errors.count',
    'keda.scaler.errors.count',
    'keda.scaler.metrics_latency',
    'keda.scaler.metrics_latency_seconds',
    'keda.scaler.metrics_value',
    'keda.trigger_totals',
    'keda.workqueue.adds.count',
    'keda.workqueue.depth',
    'keda.workqueue.longest.running_processor.seconds',
    'keda.workqueue.queue.duration.seconds.bucket',
    'keda.workqueue.queue.duration.seconds.count',
    'keda.workqueue.queue.duration.seconds.sum',
    'keda.workqueue.retries.count',
    'keda.workqueue.unfinished_work.seconds',
    'keda.workqueue.work.duration.seconds.bucket',
    'keda.workqueue.work.duration.seconds.count',
    'keda.workqueue.work.duration.seconds.sum',
]
