# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_allocations_per_worker():
    return 256


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_hold_ms():
    return 0


def instance_max_alloc_bytes():
    return 4194304


def instance_max_retained_bytes():
    return 268435456


def instance_max_total_bytes():
    return 1073741824


def instance_min_alloc_bytes():
    return 512


def instance_min_collection_interval():
    return 15


def instance_num_workers():
    return 48


def instance_retained_fraction():
    return 0.1


def instance_run_budget_seconds():
    return 5


def instance_thread_churn_per_run():
    return 8


def instance_touch_pages():
    return True
