excluded_paths = [
  # --- Type annotation ---
  "krb5/**/*.pyi",
  "krb5/**/py.typed",

  "Cryptodome/**/*.pyi",
  "Cryptodome/**/py.typed",

  "ddtrace/**/*.pyi",
  "ddtrace/**/py.typed",

  "pyVmomi/**/*.pyi",
  "pyVmomi/**/py.typed",

  "gssapi/**/*.pyi",
  "gssapi/**/py.typed",

  # --- Tests ---

  "tests/",
  "/test/",
  "idlelib/idle_test/",
  "Cryptodome/SelfTest/",
  "securesystemslib/_vendor/ed25519/test_data/",
  "win32com/test/",

  # --- Botocore ---
  "botocore/data/*",
  # Top-level JSON files (endpoints.json, partitions.json, _retry.json, etc.)
  # are required by botocore to resolve AWS endpoints and handle retries.
  "!botocore/data/*.json",
  # We use sts in several integrations for assuming roles:
  # - amazon_msk
  # - postres
  # - mysql
  "!botocore/data/sts",
  # amazon_msk also needs the kafka client.
  "!botocore/data/kafka",
  # postgres and mysql also need the rds.
  "!botocore/data/rds",
  # Riakcs integration monitors s3.
  "!botocore/data/s3",
]
