# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
import os

from datadog_checks.dev import get_docker_hostname, get_here

HERE = get_here()
HOST = get_docker_hostname()
PORT = 9091


def get_fixture_path(filename):
    return os.path.join(HERE, 'fixtures', filename)


MOCKED_INSTANCE = {
    "openmetrics_endpoint": f"http://{HOST}:{PORT}/metrics",
    'tags': ['test:tag'],
}

COMPOSE_FILE = os.path.join(HERE, 'docker', 'docker-compose.yaml')

TEST_METRICS = {
    'milvus.build_info': 'gauge',
    'milvus.cgo.active_future_total': 'gauge',
    'milvus.cgo.cgo_duration_seconds': 'gauge',
    'milvus.cgo.cgo_queue_duration_seconds': 'gauge',
    'milvus.cgo.running_cgo_call_total': 'gauge',
    'milvus.datacoord.channel_checkpoint_unix_seconds': 'gauge',
    'milvus.datacoord.collection_num': 'gauge',
    'milvus.datacoord.consume_datanode_tt_lag_ms': 'gauge',
    'milvus.datacoord.datanode_num': 'gauge',
    'milvus.datacoord.import_tasks': 'gauge',
    'milvus.datacoord.index.node_num': 'gauge',
    'milvus.datacoord.index.req_count': 'count',
    'milvus.datacoord.index.task_count': 'gauge',
    'milvus.datacoord.segment_num': 'gauge',
    'milvus.datacoord.stored.binlog_size': 'gauge',
    'milvus.datacoord.stored.index_files_size': 'gauge',
    'milvus.datacoord.stored.rows_num': 'gauge',
    'milvus.datacoord.task_execute_max_latency': 'gauge',
    'milvus.datacoord.watched_dml_chanel_num': 'gauge',
    'milvus.datanode.autoflush_buffer_op_count': 'count',
    'milvus.datanode.consume.bytes_count': 'count',
    'milvus.datanode.consume.msg_count': 'count',
    'milvus.datanode.consume.tt_lag_ms': 'gauge',
    'milvus.datanode.encode_buffer_latency': 'gauge',
    'milvus.datanode.flowgraph_num': 'gauge',
    'milvus.datanode.flush.buffer_op_count': 'count',
    'milvus.datanode.flush.req_count': 'count',
    'milvus.datanode.flushed_data.rows': 'count',
    'milvus.datanode.flushed_data.size': 'count',
    'milvus.datanode.msg.dispatcher_tt_lag_ms': 'gauge',
    'milvus.datanode.msg.rows_count': 'count',
    'milvus.datanode.save_latency': 'gauge',
    'milvus.flushed_segment_file_num': 'gauge',
    'milvus.indexnode.build_index_latency': 'gauge',
    'milvus.indexnode.encode_index_latency': 'gauge',
    'milvus.indexnode.index.task_count': 'count',
    'milvus.indexnode.index.task_latency_in_queue': 'gauge',
    'milvus.indexnode.knowhere_build_index_latency': 'gauge',
    'milvus.indexnode.save_index_latency': 'gauge',
    'milvus.meta.kv_size': 'gauge',
    'milvus.meta.op_count': 'count',
    'milvus.meta.request_latency': 'gauge',
    'milvus.msg_queue_consumer_num': 'gauge',
    'milvus.msgstream.op_count': 'count',
    'milvus.msgstream.request_latency': 'gauge',
    'milvus.num_node': 'gauge',
    'milvus.proxy.apply.pk_latency': 'gauge',
    'milvus.proxy.apply.timestamp_latency': 'gauge',
    'milvus.proxy.assign_segmentID_latency': 'gauge',
    'milvus.proxy.cache.hit_count': 'count',
    'milvus.proxy.cache.update_latency': 'gauge',
    'milvus.proxy.delete_vectors_count': 'count',
    'milvus.proxy.msgstream_obj_num': 'gauge',
    'milvus.proxy.mutation_send_latency': 'gauge',
    'milvus.proxy.rate_limit_req_count': 'count',
    'milvus.proxy.report_value': 'count',
    'milvus.proxy.req.count': 'count',
    'milvus.proxy.req.in_queue_latency': 'gauge',
    'milvus.proxy.req.latency': 'gauge',
    'milvus.proxy.send_bytes_count': 'count',
    'milvus.proxy.sq.decode_result_latency': 'gauge',
    'milvus.proxy.sq.reduce_result_latency': 'gauge',
    'milvus.proxy.sq.wait_result_latency': 'gauge',
    'milvus.proxy.sync_segment_request_length': 'gauge',
    'milvus.proxy.tt_lag_ms': 'gauge',
    'milvus.querycoord.collection_num': 'gauge',
    'milvus.querycoord.current_target_checkpoint_unix_seconds': 'gauge',
    'milvus.querycoord.load.latency': 'gauge',
    'milvus.querycoord.load.req_count': 'count',
    'milvus.querycoord.partition_num': 'gauge',
    'milvus.querycoord.querynode_num': 'gauge',
    'milvus.querycoord.release.latency': 'gauge',
    'milvus.querycoord.release.req_count': 'count',
    'milvus.querycoord_task_num': 'gauge',
    'milvus.querynode.apply_bf_latency': 'gauge',
    'milvus.querynode.collection_num': 'gauge',
    'milvus.querynode.consume.bytes_counter': 'count',
    'milvus.querynode.consume.msg_count': 'count',
    'milvus.querynode.consume.tt_lag_ms': 'gauge',
    'milvus.querynode.disk.cache.evict.bytes': 'count',
    'milvus.querynode.disk.cache.evict.duration': 'count',
    'milvus.querynode.disk.cache.evict.global_duration': 'gauge',
    'milvus.querynode.disk.cache.evict.total': 'count',
    'milvus.querynode.disk.cache.load.bytes': 'count',
    'milvus.querynode.disk.cache.load.duration': 'count',
    'milvus.querynode.disk.cache.load.global_duration': 'gauge',
    'milvus.querynode.disk.cache.load.total': 'count',
    'milvus.querynode.disk.used_size': 'gauge',
    'milvus.querynode.dml_vchannel_num': 'gauge',
    'milvus.querynode.entity.num': 'gauge',
    'milvus.querynode.entity.size': 'gauge',
    'milvus.querynode.execute_bytes_counter': 'count',
    'milvus.querynode.flowgraph_num': 'gauge',
    'milvus.querynode.forward_delete_latency': 'gauge',
    'milvus.querynode.load.index_latency': 'gauge',
    'milvus.querynode.load.segment.concurrency': 'gauge',
    'milvus.querynode.load.segment.latency': 'gauge',
    'milvus.querynode.msg_dispatcher_tt_lag_ms': 'gauge',
    'milvus.querynode.partition_num': 'gauge',
    'milvus.querynode.process_insert_or_delete_latency': 'gauge',
    'milvus.querynode.read_task.concurrency': 'gauge',
    'milvus.querynode.read_task.ready_len': 'gauge',
    'milvus.querynode.read_task.unsolved_len': 'gauge',
    'milvus.querynode.search.group.nq': 'gauge',
    'milvus.querynode.search.group.size': 'gauge',
    'milvus.querynode.search.group.topk': 'gauge',
    'milvus.querynode.search.nq': 'gauge',
    'milvus.querynode.search.topk': 'gauge',
    'milvus.querynode.segment.access.duration': 'count',
    'milvus.querynode.segment.access.global_duration': 'gauge',
    'milvus.querynode.segment.access.total': 'count',
    'milvus.querynode.segment.access.wait_cache.duration': 'count',
    'milvus.querynode.segment.access.wait_cache.global_duration': 'gauge',
    'milvus.querynode.segment.access.wait_cache.total': 'count',
    'milvus.querynode.segment.latency_per_vector': 'gauge',
    'milvus.querynode.segment.num': 'gauge',
    'milvus.querynode.sq.core_latency': 'gauge',
    'milvus.querynode.sq.queue.latency': 'gauge',
    'milvus.querynode.sq.queue.user_latency': 'gauge',
    'milvus.querynode.sq.reduce_latency': 'gauge',
    'milvus.querynode.sq.req.count': 'count',
    'milvus.querynode.sq.req.latency': 'gauge',
    'milvus.querynode.sq.segment_latency': 'gauge',
    'milvus.querynode.sq.wait_tsafe_latency': 'gauge',
    'milvus.querynode.wait_processing_msg_count': 'gauge',
    'milvus.querynode.watch_dml_channel_latency': 'gauge',
    'milvus.rootcoord.collection_num': 'gauge',
    'milvus.rootcoord.credential_num': 'gauge',
    'milvus.rootcoord.ddl_req.count': 'count',
    'milvus.rootcoord.ddl_req.latency': 'gauge',
    'milvus.rootcoord.ddl_req.latency_in_queue': 'gauge',
    'milvus.rootcoord.dml_channel_num': 'gauge',
    'milvus.rootcoord.entity_num': 'gauge',
    'milvus.rootcoord.force_deny_writing_counter': 'count',
    'milvus.rootcoord.id_alloc_count': 'count',
    'milvus.rootcoord.indexed_entity_num': 'gauge',
    'milvus.rootcoord.msgstream_obj_num': 'gauge',
    'milvus.rootcoord.num_of_roles': 'gauge',
    'milvus.rootcoord.partition_num': 'gauge',
    'milvus.rootcoord.produce_tt_lag_ms': 'gauge',
    'milvus.rootcoord.proxy_num': 'gauge',
    'milvus.rootcoord.qn_mem_high_water_level': 'gauge',
    'milvus.rootcoord.sync_timetick_latency': 'gauge',
    'milvus.rootcoord.timestamp': 'gauge',
    'milvus.rootcoord.timestamp_saved': 'gauge',
    'milvus.runtime_info': 'gauge',
    'milvus.storage.kv_size': 'gauge',
    'milvus.storage.op_count': 'count',
    'milvus.storage.request_latency': 'gauge',
}

RENAMED_LABELS = {
    "milvus.build_info": 'milvus_version:v2.3.15',
}
