# (C) Datadog, Inc. 2010-2018
# All rights reserved
# Licensed under Simplified BSD License (see LICENSE)

GAUGE_METRICS = [
    'cache-entries',
    'concurrent-queries',
    'failed-host-entries',
    'negcache-entries',
    'packetcache-entries',
    'throttle-entries',
]
RATE_METRICS = [
    'all-outqueries',
    'answers-slow',
    'answers0-1',
    'answers1-10',
    'answers10-100',
    'answers100-1000',
    'cache-hits',
    'cache-misses',
    'chain-resends',
    'case-mismatches',
    'client-parse-errors',
    'dont-outqueries',
    'ipv6-outqueries',
    'ipv6-questions',
    'malloc-bytes',
    'noerror-answers',
    'nxdomain-answers',
    'max-mthread-stack',
    'outgoing-timeouts',
    'over-capacity-drops',
    'packetcache-hits',
    'packetcache-misses',
    'policy-drops',
    'qa-latency',
    'questions',
    'server-parse-errors',
    'servfail-answers',
    'spoof-prevents',
    'sys-msec',
    'tcp-client-overflow',
    'tcp-clients',
    'tcp-outqueries',
    'tcp-questions',
    'throttled-out',
    'throttled-outqueries',
    'unauthorized-tcp',
    'unauthorized-udp',
    'unexpected-packets',
    'unreachables',
]
GAUGE_METRICS_V4 = [
    'fd-usage',
]
RATE_METRICS_V4 = [
    'auth4-answers-slow',
    'auth4-answers0-1',
    'auth4-answers1-10',
    'auth4-answers10-100',
    'auth4-answers100-1000',
    'auth6-answers-slow',
    'auth6-answers0-1',
    'auth6-answers1-10',
    'auth6-answers10-100',
    'auth6-answers100-1000',
    'dlg-only-drops',
    'dnssec-queries',
    'dnssec-result-bogus',
    'dnssec-result-indeterminate',
    'dnssec-result-insecure',
    'dnssec-result-nta',
    'dnssec-result-secure',
    'dnssec-validations',
    'edns-ping-matches',
    'edns-ping-mismatches',
    'ignored-packets',
    'no-packet-error',
    'noedns-outqueries',
    'noping-outqueries',
    'nsset-invalidations',
    'nsspeeds-entries',
    'outgoing4-timeouts',
    'outgoing6-timeouts',
    'policy-result-custom',
    'policy-result-drop',
    'policy-result-noaction',
    'policy-result-nodata',
    'policy-result-nxdomain',
    'policy-result-truncate',
    'real-memory-usage',
    'resource-limits',
    'too-old-drops',
    'udp-in-errors',
    'udp-noport-errors',
    'udp-recvbuf-errors',
    'udp-sndbuf-errors',
    'uptime',
    'user-msec',
]

METRIC_FORMAT = 'powerdns.recursor.{}'
