# (C) Datadog, Inc. 2026-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_hypervisor():
    return True


def instance_memory_entitlements():
    return True


def instance_memory_stats():
    return True


def instance_min_collection_interval():
    return 15


def instance_name():
    return 'lparstats'


def instance_page_stats():
    return True


def instance_spurr_utilization():
    return True


def instance_sudo():
    return False
