# (C) Datadog, Inc. 2021-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_blacklist_conntrack_metrics():
    return []


def instance_collect_aws_ena_metrics():
    return False


def instance_collect_connection_queues():
    return False


def instance_collect_connection_state():
    return False


def instance_collect_count_metrics():
    return False


def instance_collect_ethtool_metrics():
    return False


def instance_collect_rate_metrics():
    return True


def instance_combine_connection_states():
    return True


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_min_collection_interval():
    return 15


def instance_use_sudo_conntrack():
    return True


def instance_whitelist_conntrack_metrics():
    return ['max', 'count']
