[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.13"]

[[envs.default.matrix]]
python = ["3.13"]
setup = ["lab"]

[envs.default.overrides]
name."^py3\\.13$".e2e-env = { value = true }
matrix.setup.env-vars = [
  { key = "USE_EDGECONNECT_LAB", value = "True", if = ["lab"] },
]

[envs.default]
e2e-env = false
