# (C) Datadog, Inc. 2022-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_global_custom_queries(field, value):
    return get_default_field_value(field, value)


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_account(field, value):
    return get_default_field_value(field, value)


def instance_connection_string(field, value):
    return get_default_field_value(field, value)


def instance_database(field, value):
    return 'system'


def instance_driver(field, value):
    return 'Teradata Database ODBC Driver 17.10'


def instance_dsn(field, value):
    return get_default_field_value(field, value)


def instance_https_port(field, value):
    return 443


def instance_mechanism_key(field, value):
    return get_default_field_value(field, value)


def instance_mechanism_name(field, value):
    return get_default_field_value(field, value)


def instance_partition(field, value):
    return 'DBC/SQL'


def instance_port(field, value):
    return 1025


def instance_ssl_ca(field, value):
    return '/path/to/ssl_ca_dir'


def instance_ssl_ca_path(field, value):
    return '/path/to/ssl_ca_file/ca.pem'


def instance_ssl_mode(field, value):
    return 'Prefer'


def instance_ssl_protocol(field, value):
    return 'TLSv1.2'


def instance_use_odbc(field, value):
    return True


def instance_use_tls(field, value):
    return False
