name: release-dev

on:
  push:
    tags:
      - datadog_checks_dev-*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment: pypi-datadog-checks-dev

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.13'

    - name: Upgrade Python packaging tools
      run: pip install --disable-pip-version-check --upgrade pip setuptools wheel

    - name: Install ddev
      uses: ./.github/actions/setup-ddev
      with:
        install-mode: local
        cache-profile: local-ddev-base

    - name: Configure ddev
      run: |
        ddev config set upgrade_check false
        ddev config set repos.core .
        ddev config set repo core

    - name: Build dev package
      run: ddev release build datadog_checks_dev

    # Publish wheels to PyPI using Trusted Publishers.
    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    # This job needs to run from within the pypi-datadog-checks-dev environment. PyPi
    # validates the workflow file name, environment and repository the request is
    # comming from to provide the valid JWT token.
    - name: Release dev package to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
      with:
        skip-existing: true
        packages-dir: datadog_checks_dev/dist
