name: release-hash-check

on:
  pull_request:
    branches:
      - master
      - '7.[0-9]+.x'
    paths:
      - .in-toto/*.link
      - .github/workflows/release-hash-check.yml

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.13'

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      with:
        files: .in-toto/*.link

    - if: steps.changed-files.outputs.any_changed == 'true'
      run: python .github/workflows/release-hash-check.py ${{ steps.changed-files.outputs.all_changed_files }}
