# https://github.com/DataDog/slapr

name: Slack emoji PR updates
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

jobs:
  run_slapr_agent_integrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slack_channel_variable:
          - SLACK_CHANNEL_ID
          - SLACK_CHANNEL_ID_AGENT_INTEGRATIONS_REVIEWS
          - SLACK_CHANNEL_ID_INFRA_INTEGRATIONS
    steps:
    - uses: DataDog/slapr@4b5efe2ce585e45898bb88c4fa303e226e8199e4 # Not versioned, latest commit in master as of 2025-05-08
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        SLACK_CHANNEL_ID: "${{ secrets[matrix.slack_channel_variable] }}"
        SLACK_API_TOKEN: "${{ secrets.SLACK_API_TOKEN }}"
        SLAPR_BOT_USER_ID: "${{ secrets.SLAPR_BOT_USER_ID }}"
        SLAPR_EMOJI_REVIEW_STARTED: "review_started"
        SLAPR_EMOJI_APPROVED: "approved2"
        SLAPR_EMOJI_CHANGES_REQUESTED: "changes_requested"
        SLAPR_EMOJI_MERGED: "merged"
        SLAPR_EMOJI_CLOSED: "closed"