name: Test all

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

      python-version:
        required: false
        default: ""
        type: string
      standard:
        required: false
        default: false
        type: boolean
      latest:
        required: false
        default: false
        type: boolean
      minimum-base-package:
        required: false
        default: false
        type: boolean
      test-py2:
        required: false
        default: false
        type: boolean
      test-py3:
        required: false
        default: true
        type: boolean
      agent-image:
        required: false
        default: ""
        type: string
      agent-image-py2:
        required: false
        default: ""
        type: string
      agent-image-windows:
        required: false
        default: ""
        type: string
      agent-image-windows-py2:
        required: false
        default: ""
        type: string
      pytest-args:
        description: "Arguments to pass to pytest"
        required: false
        type: string
        default: ""
      skip-ddev-tests:
        required: false
        default: false
        type: boolean

jobs:
  j73baea9:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Confluent Platform (py3.12-6.2)
      target: confluent_platform
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j74904dc:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Consul (py3.12-1.6)
      target: consul
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j14a5407:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Consul (py3.12-1.9)
      target: consul
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j1809ed5:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: CoreDNS (py3.12-1.2)
      target: coredns
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j589c6d9:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: CoreDNS (py3.12-1.8)
      target: coredns
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jdb447c4:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: CouchDB (py3.12-1.6)
      target: couch
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j54a97ce:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: CouchDB (py3.12-2.3)
      target: couch
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j57ae19a:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: CouchDB (py3.12-3.1)
      target: couch
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j6dcc445:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Couchbase (py3.12-6.6)
      target: couchbase
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jf0f3726:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Couchbase (py3.12-7.0)
      target: couchbase
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j34c3f45:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Couchbase (py3.12-7.1)
      target: couchbase
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j0682cef:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: DNS on Linux (py3.12)
      target: dns_check
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j5073ed5:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: DNS on Windows (py3.12)
      target: dns_check
      platform: windows
      runner: '["windows-2022"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j927846e:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Checks Base on Linux (py3.12)
      target: datadog_checks_base
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j357f6e2:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Checks Base on Windows (py3.12)
      target: datadog_checks_base
      platform: windows
      runner: '["windows-2022"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jbd5bb76:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Checks Dev on Linux (py3.12)
      target: datadog_checks_dev
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j37c1734:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Checks Dev on Windows (py3.12)
      target: datadog_checks_dev
      platform: windows
      runner: '["windows-2022"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jdc24315:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Checks Downloader on Linux (py3.12)
      target: datadog_checks_downloader
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jdeb2407:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Checks Downloader on Windows (py3.12)
      target: datadog_checks_downloader
      platform: windows
      runner: '["windows-2022"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jfb6cc5b:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Datadog Cluster Agent (py3.12)
      target: datadog_cluster_agent
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jfcd8340:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Directory (py3.12)
      target: directory
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j749e896:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Disk on Linux (py3.12)
      target: disk
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j0365d8d:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Disk on Windows (py3.12)
      target: disk
      platform: windows
      runner: '["windows-2022"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j1129e3e:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Druid (py3.12)
      target: druid
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j33436b0:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: DuckDB (py3.12-1.1.1)
      target: duckdb
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j4ab56ba:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: EKS Fargate (py3.12)
      target: eks_fargate
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jcd0613f:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: ESXi (py3.12-lab)
      target: esxi
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jda6bcb8:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: ESXi (py3.12-vcsim-6.5)
      target: esxi
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  ja38c5ea:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: ESXi (py3.12-vcsim-7.0)
      target: esxi
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j1971cb2:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Elasticsearch (py3.12-elasticsearch-7.10)
      target: elastic
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j24b0f2e:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Elasticsearch (py3.12-elasticsearch-7.2)
      target: elastic
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j5fa4b70:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Elasticsearch (py3.12-elasticsearch-7.7)
      target: elastic
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j2d85767:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Elasticsearch (py3.12-elasticsearch-7.9)
      target: elastic
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j76dada0:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Elasticsearch (py3.12-elasticsearch-8.8)
      target: elastic
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jb5c983d:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Elasticsearch (py3.12-opensearch-1.1)
      target: elastic
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jeeaa455:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Envoy (py3.12-2)
      target: envoy
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j560114e:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Envoy (py3.12-3)
      target: envoy
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jb6f10b7:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Exchange Server (py3.12)
      target: exchange_server
      platform: windows
      runner: '["windows-2022"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j8151fb5:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: External DNS (py3.12)
      target: external_dns
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  je046ce0:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Falco (py3.12)
      target: falco
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j6e516b2:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Fluentd (py3.12-1.17)
      target: fluentd
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j98a8bbe:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Fly.io (py3.12-caddy)
      target: fly_io
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j56e878d:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Fly.io (py3.12-lab)
      target: fly_io
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jb241af5:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: FoundationDB (py3.12)
      target: foundationdb
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jf41dddd:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: FoundationDB (py3.12-tls)
      target: foundationdb
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jec8fda1:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Gearman (py3.12-1.0)
      target: gearmand
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j988c002:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Gearman (py3.12-1.1)
      target: gearmand
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jbde23f7:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Gitlab (py3.12-13.12)
      target: gitlab
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  jd8754a0:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Gitlab (py3.12-14.10)
      target: gitlab
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
  j8601f1e:
    uses: ./.github/workflows/test-target.yml
    with:
      job-name: Gitlab (py3.12-15.10)
      target: gitlab
      platform: linux
      runner: '["ubuntu-22.04"]'
      repo: "${{ inputs.repo }}"
      python-version: "${{ inputs.python-version }}"
      standard: ${{ inputs.standard }}
      latest: ${{ inputs.latest }}
      agent-image: "${{ inputs.agent-image }}"
      agent-image-py2: "${{ inputs.agent-image-py2 }}"
      agent-image-windows: "${{ inputs.agent-image-windows }}"
      agent-image-windows-py2: "${{ inputs.agent-image-windows-py2 }}"
      test-py2: ${{ inputs.test-py2 }}
      test-py3: ${{ inputs.test-py3 }}
      minimum-base-package: ${{ inputs.minimum-base-package }}
      pytest-args: ${{ inputs.pytest-args }}
    secrets: inherit
