name: 'Validate skip QA label'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  validate-skip-qa:
    if: '!github.event.pull_request.draft'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PYTHON_VERSION: "3.13"

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Get token via dd-octo-sts
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/integrations-core
          policy: self.validate-skip-qa.pull-request

      - name: Get files changed
        id: changed_files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          json: true
          escape_json: false
          safe_output: false
          files: |
            **/datadog_checks/**
            **/changelog.d/**
            **/pyproject.toml
            **/hatch.toml
          files_ignore: |
            ddev/**
            datadog_checks_dev/**
            datadog_checks_tests_helper/**
  
      - name: Find comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find_comment
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "<!-- validate-skip-qa-comment -->"

      - name: Write comment body - Add skip qa label
        if: steps.changed_files.outputs.any_changed == 'false' && !contains(github.event.pull_request.labels.*.name, 'qa/skip-qa')
        uses: ./.github/actions/render-skip-qa-comment
        with:
          mode: add-label
          output: comment-body.md

      - name: Post message - Add skip qa label
        if: steps.changed_files.outputs.any_changed == 'false' && !contains(github.event.pull_request.labels.*.name, 'qa/skip-qa')
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment-body.md
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: "replace"

      - name: Write comment body - Remove skip qa label
        if: steps.changed_files.outputs.any_changed == 'true' && contains(github.event.pull_request.labels.*.name, 'qa/skip-qa')
        uses: ./.github/actions/render-skip-qa-comment
        with:
          mode: remove-label
          changed-files-json: ${{ steps.changed_files.outputs.all_changed_files }}
          output: comment-body.md

      - name: Post comment - Remove skip qa label
        if: steps.changed_files.outputs.any_changed == 'true' && contains(github.event.pull_request.labels.*.name, 'qa/skip-qa')
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment-body.md
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: "replace"
