# (C) Datadog, Inc. 2024-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)
import datetime
import os

from datadog_checks.base.utils.time import ensure_aware_datetime
from datadog_checks.dev.fs import get_here

COMPOSE_FILE = os.path.join(get_here(), 'docker', 'docker-compose.yaml')
INSTANCE = {'octopus_endpoint': 'http://localhost:80/api', 'space': 'Default'}


BASE_TIME = ensure_aware_datetime(datetime.datetime.strptime("2024-09-23 14:45:58.888492", '%Y-%m-%d %H:%M:%S.%f'))
MOCKED_TIMESTAMPS = [BASE_TIME] * 20


ALL_METRICS = [
    "octopus_deploy.project_group.count",
    "octopus_deploy.project.count",
    "octopus_deploy.deployment.count",
    "octopus_deploy.deployment.duration",
    "octopus_deploy.deployment.has_warnings_or_errors",
    "octopus_deploy.deployment.queue_time",
    "octopus_deploy.deployment.succeeded",
    "octopus_deploy.deployment.can_rerun",
    "octopus_deploy.server_node.count",
    "octopus_deploy.server_node.in_maintenance_mode",
    "octopus_deploy.server_node.max_concurrent_tasks",
]

PROJECT_GROUP_ALL_METRICS = [
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:Default Project Group", "project_group_id:ProjectGroups-1", "space_name:Default"],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:hello", "project_group_id:ProjectGroups-3", "space_name:Default"],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:test-group", "project_group_id:ProjectGroups-2", "space_name:Default"],
        'count': 1,
    },
]

PROJECT_GROUP_ONLY_TEST_GROUP_METRICS = [
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:Default Project Group", "project_group_id:ProjectGroups-1", "space_name:Default"],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:hello", "project_group_id:ProjectGroups-3", "space_name:Default"],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:test-group", "project_group_id:ProjectGroups-2", "space_name:Default"],
        'count': 1,
    },
]

PROJECT_GROUP_NO_METRICS = [
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:Default Project Group", "project_group_id:ProjectGroups-1", "space_name:Default"],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:hello", "project_group_id:ProjectGroups-3", "space_name:Default"],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:test-group", "project_group_id:ProjectGroups-2", "space_name:Default"],
        'count': 0,
    },
]
PROJECT_GROUP_NO_TEST_GROUP_METRICS = [
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:Default Project Group", "project_group_id:ProjectGroups-1", "space_name:Default"],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:hello", "project_group_id:ProjectGroups-3", "space_name:Default"],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project_group.count',
        'tags': ["project_group_name:test-group", "project_group_id:ProjectGroups-2", "space_name:Default"],
        'count': 0,
    },
]

PROJECT_ALL_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 1,
    },
]

PROJECT_ONLY_TEST_GROUP_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 0,
    },
]

PROJECT_ONLY_DEFAULT_GROUP_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 1,
    },
]

PROJECT_ONLY_TEST_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 1,
    },
]

PROJECT_ONLY_HI_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 0,
    },
]

PROJECT_ONLY_HI_MY_PROJECT_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 0,
    },
]

PROJECT_EXCLUDE_TEST_API_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 0,
    },
]

PROJECT_NO_METRICS = [
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:test-group",
            "project_group_id:ProjectGroups-2",
            "space_name:Default",
            "project_name:hi",
            "project_id:Projects-4",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:my-project",
            "project_id:Projects-2",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
        ],
        'count': 0,
    },
    {
        'name': 'octopus_deploy.project.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
        ],
        'count': 0,
    },
]


DEPLOYMENT_METRICS = [
    {
        'name': 'octopus_deploy.deployment.duration',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 2.073,
    },
    {
        'name': 'octopus_deploy.deployment.queue_time',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 0.639,
    },
    {
        'name': 'octopus_deploy.deployment.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.deployment.succeeded',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.deployment.can_rerun',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.deployment.has_warnings_or_errors',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.deployment.duration',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 2.134,
    },
    {
        'name': 'octopus_deploy.deployment.queue_time',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 0.67,
    },
    {
        'name': 'octopus_deploy.deployment.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.deployment.succeeded',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.deployment.can_rerun',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.deployment.has_warnings_or_errors',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.deployment.duration',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
        'value': 6.267,
    },
    {
        'name': 'octopus_deploy.deployment.queue_time',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
        'value': 0.631,
    },
    {
        'name': 'octopus_deploy.deployment.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.deployment.succeeded',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.deployment.can_rerun',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.deployment.has_warnings_or_errors',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.deployment.duration',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 3.192,
    },
    {
        'name': 'octopus_deploy.deployment.queue_time',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test-api",
            "project_id:Projects-1",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 1,
        'value': 0.613,
    },
]


DEPLOYMENT_METRICS_NO_PROJECT_1 = [
    {
        'name': 'octopus_deploy.deployment.duration',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
    },
    {
        'name': 'octopus_deploy.deployment.queue_time',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
    },
    {
        'name': 'octopus_deploy.deployment.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
    },
    {
        'name': 'octopus_deploy.deployment.succeeded',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Success",
        ],
        'count': 2,
    },
    {
        'name': 'octopus_deploy.deployment.count',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.deployment.succeeded',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.deployment.can_rerun',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.deployment.has_warnings_or_errors',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.deployment.duration',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
    },
    {
        'name': 'octopus_deploy.deployment.queue_time',
        'tags': [
            "project_group_name:Default Project Group",
            "project_group_id:ProjectGroups-1",
            "space_name:Default",
            "project_name:test",
            "project_id:Projects-3",
            "task_name:Deploy",
            "task_state:Failed",
        ],
        'count': 1,
    },
]

SERVER_NODES_METRICS = [
    {
        'name': 'octopus_deploy.server_node.count',
        'tags': [
            "space_name:Default",
            "server_node_name:octopus-i8932-79236734bc234-09h234n",
            "server_node_id:OctopusServerNodes-octopus-i8932-79236734bc234-09h234n",
        ],
        'count': 1,
        'value': 1,
    },
    {
        'name': 'octopus_deploy.server_node.in_maintenance_mode',
        'tags': [
            "space_name:Default",
            "server_node_name:octopus-i8932-79236734bc234-09h234n",
            "server_node_id:OctopusServerNodes-octopus-i8932-79236734bc234-09h234n",
        ],
        'count': 1,
        'value': 0,
    },
    {
        'name': 'octopus_deploy.server_node.max_concurrent_tasks',
        'tags': [
            "space_name:Default",
            "server_node_name:octopus-i8932-79236734bc234-09h234n",
            "server_node_id:OctopusServerNodes-octopus-i8932-79236734bc234-09h234n",
        ],
        'count': 1,
        'value': 5,
    },
]

ALL_DEPLOYMENT_LOGS = [
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The deployment failed because one or more steps failed. '
        'Please see the deployment log for details.',
        'timestamp': 1727104203218,
        'status': 'Fatal',
        'stage_name': 'Deploy test release 0.0.2 to Development',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'hello',
        'timestamp': 1727104198525,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': "The step failed: Activity Run a Script on the Octopus Server failed "
        "with error 'The remote script failed with exit code 1'.",
        'timestamp': 1727104202767,
        'status': 'Fatal',
        'stage_name': 'Step 2: Run a Script',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'ParserError: At /home/octopus/.octopus/OctopusServer/Server'
        '/Work/09234928998123-1847-68/Script.ps1:1 char:6',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+ echo "stop',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+      ~~~~~',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The string is missing the terminator: ".',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'At /home/octopus/.octopus/OctopusServer/Server' '/Work/09234928998123-1847-68/Script.ps1:1 char:6',
        'timestamp': 1727104202605,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+ echo "stop',
        'timestamp': 1727104202605,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+      ~~~~~',
        'timestamp': 1727104202605,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, <No file>: line 1',
        'timestamp': 1727104202606,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, /home/octopus/.octopus/OctopusServer/Server'
        '/Work/09234928998123-1847-68/Octopus.FunctionAppenderContext.ps1: line 258',
        'timestamp': 1727104202606,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, /home/octopus/.octopus/OctopusServer/Server/'
        'Work/09234928998123-1847-68/Bootstrap.Octopus.FunctionAppenderContext.ps1: line 1505',
        'timestamp': 1727104202607,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, <No file>: line 1',
        'timestamp': 1727104202607,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, <No file>: line 1',
        'timestamp': 1727104202607,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The remote script failed with exit code 1',
        'timestamp': 1727104202733,
        'status': 'Fatal',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The action Run a Script on the Octopus Server failed',
        'timestamp': 1727104202758,
        'status': 'Fatal',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'The deployment completed successfully.',
        'timestamp': 1727103628255,
        'status': 'Info',
        'stage_name': 'Deploy test release 0.0.1 to Staging',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'hello',
        'timestamp': 1727103627639,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'The deployment completed successfully.',
        'timestamp': 1727103621669,
        'status': 'Info',
        'stage_name': 'Deploy test release 0.0.1 to Development',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'hello',
        'timestamp': 1727103621208,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-1',
            'project_name:test-api',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'The deployment completed successfully.',
        'timestamp': 1727103442532,
        'status': 'Info',
        'stage_name': 'Deploy test-api release 0.1.5 to Development',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-1',
            'project_name:test-api',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'Testing',
        'timestamp': 1727103440967,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-1',
            'project_name:test-api',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'test',
        'timestamp': 1727103442029,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
]

ONLY_TEST_LOGS = [
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The deployment failed because one or more steps failed. '
        'Please see the deployment log for details.',
        'timestamp': 1727104203218,
        'status': 'Fatal',
        'stage_name': 'Deploy test release 0.0.2 to Development',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'hello',
        'timestamp': 1727104198525,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': "The step failed: Activity Run a Script on the Octopus Server failed "
        "with error 'The remote script failed with exit code 1'.",
        'timestamp': 1727104202767,
        'status': 'Fatal',
        'stage_name': 'Step 2: Run a Script',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'ParserError: At /home/octopus/.octopus/OctopusServer/Server'
        '/Work/09234928998123-1847-68/Script.ps1:1 char:6',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+ echo "stop',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+      ~~~~~',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The string is missing the terminator: ".',
        'timestamp': 1727104202599,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'At /home/octopus/.octopus/OctopusServer/Server' '/Work/09234928998123-1847-68/Script.ps1:1 char:6',
        'timestamp': 1727104202605,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+ echo "stop',
        'timestamp': 1727104202605,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': '+      ~~~~~',
        'timestamp': 1727104202605,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, <No file>: line 1',
        'timestamp': 1727104202606,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, /home/octopus/.octopus/OctopusServer/Server'
        '/Work/09234928998123-1847-68/Octopus.FunctionAppenderContext.ps1: line 258',
        'timestamp': 1727104202606,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, /home/octopus/.octopus/OctopusServer/Server/'
        'Work/09234928998123-1847-68/Bootstrap.Octopus.FunctionAppenderContext.ps1: line 1505',
        'timestamp': 1727104202607,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, <No file>: line 1',
        'timestamp': 1727104202607,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'at <ScriptBlock>, <No file>: line 1',
        'timestamp': 1727104202607,
        'status': 'Error',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The remote script failed with exit code 1',
        'timestamp': 1727104202733,
        'status': 'Fatal',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Failed',
        ],
        'message': 'The action Run a Script on the Octopus Server failed',
        'timestamp': 1727104202758,
        'status': 'Fatal',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'The deployment completed successfully.',
        'timestamp': 1727103628255,
        'status': 'Info',
        'stage_name': 'Deploy test release 0.0.1 to Staging',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'hello',
        'timestamp': 1727103627639,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'The deployment completed successfully.',
        'timestamp': 1727103621669,
        'status': 'Info',
        'stage_name': 'Deploy test release 0.0.1 to Development',
    },
    {
        'ddtags': [
            'space_name:Default',
            'project_id:Projects-3',
            'project_name:test',
            'project_group_id:ProjectGroups-1',
            'project_group_name:Default Project Group',
            'task_name:Deploy',
            'task_state:Success',
        ],
        'message': 'hello',
        'timestamp': 1727103621208,
        'status': 'Info',
        'stage_name': 'Octopus Server',
    },
]
